### ISSUE TITLE
sigmap seems not to be creation operator

### ISSUE THREAD

**Issue by JiahaoYao** [qutip/qutip#1001]
Hi, 
    I find that the `sigmap` is not the creation operator but the annihilation operator. Could you check that for me? Similar to #957. 

![image](https://user-images.githubusercontent.com/20907377/58288423-64a33880-7d68-11e9-9570-36bbc3311eae.png)

**Comment by nonhermitian** [comment]
Sure. This is because we originally targeted compatibility with the qotoolbox that does the same thing. You can just do destroy(2).

**Comment by JiahaoYao** [comment]
Thanks @nonhermitian
