### ISSUE TITLE
How to obtain the thermal equilibrium density operator?

### ISSUE THREAD

**Issue by liwt31** [qutip/qutip#1002]
Hi all, I'm learning to use this great package and I've found it very helpful, but I'm having trouble looking for thermal equilibrium density operator, $e^{-\beta H}$. There is a thermal density matrix constructor `thermal_dm` in this package but it seems to be too simple for my purpose. Any advice on how to calculate this value? Thank you all in advance.

**Comment by nwlambert** [comment]
Hi! An easy way to do this for arbitrary Hamiltonian is using the expm() method for a quantum object.

E.g., assuming you have a predefined H and beta  

 (-beta * H).expm().unit()

unit() is necessary to re-normalize the state (i.e. it is equivalent to dividing by the partition function).
You can check it works by comparing to thermal_dm() for a harmonic oscillator.

**Comment by liwt31** [comment]
I get it now. Exactly the elegant solution I'm looking for!
