### ISSUE TITLE
ENH: add `store_final_state` to `mcsolve`

### ISSUE THREAD

**Issue by fminga** [qutip/qutip#1006]
In Qutip 4.3.1, `mcsolve` does not take the option `store_final_state`, which is a possible instance for the `Option` class which can be fed to the solvers. Other solvers, e.g., `mesolve()`, accept this option.
One could thus implement this feature also for `mcsolve`. 

Two possibilities can be envisioned: store the wavefunction of each trajectory or the density matrix obtained by averaging over all the trajectories.
This feature could be implemented using `average_states`, which is already a existing instance of the `Option` class.

**Comment by Ericgig** [comment]
PR #991 (in review) add/repair this feature.
