### ISSUE TITLE
Compiled cython files (such as `rhs77052.pyx`) generated in user root on Mac

### ISSUE THREAD

**Issue by nathanshammah** [qutip/qutip#1009]
The following files get generated in the user's root when installing QuTiP: 
rhs77050.pyx
rhs77051.pyx
rhs77052.pyx
rhs77053.pyx
rhs77054.pyx
rhs77055.pyx
rhs77056.pyx
rhs77057.pyx
rhs77058.pyx
An example of the content is here https://gist.github.com/nathanshammah/7054fd9954d0e5abe17db1d1981903d4.

**Comment by AronisGod** [comment]
This happens to me as well, except that I'm running Ubuntu.

**Comment by nathanshammah** [comment]
Solved in 4.4.0.
