### ISSUE TITLE
plot different groups of vector with different color

### ISSUE THREAD

**Issue by JiahaoYao** [qutip/qutip#1011]
Hi, I want to give different groups of vectors with different colors. How could I manage to do that? I use `b.vector_color = ['b']` then everything becomes *blue*. 
![image](https://user-images.githubusercontent.com/20907377/59135994-fe0c4600-8935-11e9-8e03-d16ce8de3fdd.png)

**Comment by Ericgig** [comment]
vector_color should be able to take a list of colors: `b.vector_color = ['b', 'r', 'g']`

Could you tell me which version of python you are using? I want to check if it is just me or `Bloch()` is not compatible with python3.7.

**Comment by JiahaoYao** [comment]
Thanks @Ericgig. I use python 3.5. I think it might be some issue with jupyter notebook. If you do not use jupyter notebook, `Bloch()` is good for me.

**Comment by nathanshammah** [comment]
@Ericgig `b=Bloch()` QuTiP 4.3.1 and 4.4.0.dev0+5af8c1c5 on python 3.7.3 works on Mac, both from shell and Jupyter notebook. Also plotting is fine.

Simply running `Bloch()` in Jupyter notebook gives the error
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/miniconda3/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

/miniconda3/lib/python3.7/site-packages/qutip/bloch.py in _repr_svg_(self)
    298         from IPython.core.pylabtools import print_figure
    299         self.render()
--> 300         fig_data = print_figure(self.fig, 'svg').decode('utf-8')
    301         plt.close(self.fig)
    302         return fig_data

AttributeError: 'str' object has no attribute 'decode'
```
but then plots the Bloch sphere, I don't know if it's a problem though or the correct functioning of the class. In shell it gives the object reference.
