### ISSUE TITLE
AttributeError: module 'qutip' has no attribute 'settings'

### ISSUE THREAD

**Issue by c-zou** [qutip/qutip#1018]
I followed instruction on http://qutip.org/docs/4.1/installation.html and used pip to install qutip in my python3.5.2 virtualenv directory.  All required packages listed under "General Requirements" were also installed.  pip commands completed fine.

I then cd into a directory peer to "python3.5.2 virtualenv directory" and launched jupyter notebook.  Ran two import commands.  Both failed.

Any suggestions on how to debug these failures?  I restarted firefox and jupyter notebook several times.

1. "import qutip.testing as qt" to verify installation
lib/python3.5/site-packages/qutip/__init__.py
    169 
    170 # core
--> 171 from qutip.qobj import *
    172 from qutip.states import *
    173 from qutip.operators import *

lib/python3.5/site-packages/qutip/qobj.py
     58 import qutip.settings as settings
     59 from qutip import __version__
---> 60 from qutip.fastsparse import fast_csr_matrix, fast_identity
     61 from qutip.cy.ptrace import _ptrace
     62 from qutip.permute import _permute

lib/python3.5/site-packages/qutip/fastsparse.py
     35 from scipy.sparse import (_sparsetools, isspmatrix, isspmatrix_csr,
     36                           csr_matrix, coo_matrix, csc_matrix, dia_matrix)
---> 37 from scipy.sparse.sputils import (upcast, upcast_char, to_native, isdense, isshape,
     38                       getdtype, isscalarlike, IndexMixin, get_index_dtype)
     39 from scipy.sparse.base import spmatrix, isspmatrix, SparseEfficiencyWarning

ImportError: cannot import name 'IndexMixin'

2. "from qutip import *"
lib/python3.5/site-packages/qutip/__init__.py in <module>
     46     __IPYTHON__
---> 47     qutip.settings.ipython = True
     48 except:

AttributeError: module 'qutip' has no attribute 'settings'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-2-82c62ef8635d> in <module>
----> 1 from qutip import *

lib/python3.5/site-packages/qutip/__init__.py in <module>
     47     qutip.settings.ipython = True
     48 except:
---> 49     qutip.settings.ipython = False
     50 

AttributeError: module 'qutip' has no attribute 'settings'

**Comment by nathanshammah** [comment]
The bug in 1) seems to refer to Issue #1008 due to #999, the incopatibility of current version releases with SciPy 1.3. Try to pinpoint in your virtual environment the version of SciPy to 1.2.1.
Something like `pip install scipy==1.2.1` should work.

Also, this is a minor thing but please refer to the current documentation, http://qutip.org/docs/latest/installation.html (QuTiP 4.3, not 4.1). 

In a conda environment everything should work properly with these specifications:
```
QuTiP Version:      4.3.1
Numpy Version:      1.15.4
Scipy Version:      1.2.1
Cython Version:     0.29.8
Matplotlib Version: 3.1.0
Python Version:     3.7.3
Number of CPUs:     2
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Darwin (x86_64)
Installation path:  /miniconda3/lib/python3.7/site-packages/qutip
```
Also, consider upgrading to python 3.6 or 3.7.

**Comment by nathanshammah** [comment]
Also, let me add that the development version of qutip is compatible with scipy 1.3 #1000.

**Comment by c-zou** [comment]
Thanks Nathan.  Once I install your versions of the packages and Python 3.7, these errors are gone.
