### ISSUE TITLE
Python version of qutip source code

### ISSUE THREAD

**Issue by TejasAvinashShetty** [qutip/qutip#1020]
In what version of python are qutip source code files written in? For example [progressbar.py](https://github.com/qutip/qutip/blob/master/qutip/ui/progressbar.py) has this line after the license "from __future__ import print_function" . 
This line is generally written in python 2.7 scripts which wish to use the print function from python 3.x.

**Comment by quantshah** [comment]
Hi, back in 2011 when QuTiP started, it must have been written in Python 2.
But now all development happens in Python 3. Also we have dropped support
for python 2 as even scipy/numpy etc are doing so and supporting python 3+
only

**Comment by TejasAvinashShetty** [comment]
So, this particular [file](https://github.com/qutip/qutip/blob/master/qutip/ui/progressbar.py) is in python 2 right?

**Comment by quantshah** [comment]
Maybe, but the print statements are still written as functions there. Thank you for the PR, I will help you out and try to merge it asap. But I do not think you need to put the extensive description of the port to python 3 syntax. Just updating the syntax to python 3 with a comment linking to some discussion should be fine.

Btw, there is a cool progress bar called tqdm if you are not already aware, [tqdm](https://github.com/tqdm/tqdm). I have seen it work out nice with some qutip functions.

**Comment by TejasAvinashShetty** [comment]
Honestly speaking, I didn't submit any PR. I just was surprised as to how .py files with two different versions were present in the source code. 
Thank you for pointing out  [tqdm](https://github.com/tqdm/tqdm).

**Comment by TejasAvinashShetty** [comment]
> Maybe, but the print statements are still written as functions there. 

this is because of the line ""from future import print_function"

**Comment by jakelishman** [comment]
Technically `from __future__ import print_function` should never be harmful, because `__future__` import statements are permanent for backwards compatibility.  Still, they can be removed next time someone touches those files, because we don't support Python 2 any more.
