### ISSUE TITLE
Cython error with time dependent Hamiltonian on Win10

### ISSUE THREAD

**Issue by zqedwardchou** [qutip/qutip#1026]
I am using anaconda and qutip on Win10 system with VS2015 (community version). When solving Hamiltonian with time dependent coefficients, I get an "ImportError" that caused by cython which does not occur on linux. I've re-installed VS2015 and qutip many times, but this problem still exists. Is there any way to solve it? Here is my error message.

**ImportError: Building module rhs22280 failed: ["distutils.errors.CompileError: command 'C:\\\\Program Files (x86)\\\\Microsoft Visual Studio 14.0\\\\VC\\\\bin\\\\cl.exe' failed with exit status 2\n"]**

[error_message.txt](https://github.com/qutip/qutip/files/3317876/error_message.txt)

**Comment by taw181** [comment]
I solved this by adding C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\ to the PATH variable

**Comment by zqedwardchou** [comment]
> I solved this by adding C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\ to the PATH variable

I don't know why, but setting the PATH variable does not work for me :(
I was using VS2017 before installing qutip. It was recommended that qutip should work with VS2015 on windows. So I uninstalled VS2017 and reinstalled VS2015. I guess something went wrong in this process, but I haven't figured out what it is.

**Comment by tehruhn** [comment]
I have two possible solutions for this, one is legit, and the other's a little hacky.

1. (legit) You might want to try installing Visual Studio Build Tools for C/C++, which you can do by going to Control Panel and modifying your VS install.
2. (hacky) Try pip installing the right WHL package from here for your Python version (basically Wisows binaries for certain Python libs): [https://www.lfd.uci.edu/~gohlke/pythonlibs/#cython](url). Navigate to the specific download path and run `pip -m install <path-to-whl-file>`.

**Comment by hodgestar** [comment]
We run tests on Windows in CI now and they pass, so I'm going to close this now. Feel free to comment if needed.
