### ISSUE TITLE
Qobj.permute() falsely affects the isherm-property

### ISSUE THREAD

**Issue by llorz1207** [qutip/qutip#1051]
When using the Qobj.permute function for a specific state and specific permutation we encounter the isherm-property to be set to False, while the state is Hermitian nevertheless. 
I attached the most minimalistic example I could built. 

There we calculate a permutation of a small compound state that sets isherm=False, another one that works properly and a transformation (double transpose) that "repairs" the Qobj and sets isherm=True again.

A double transpose of the state is our current work-around. With isherm=False you cannot calculate the partial trace of the density operator describing the state.

[qutip_permute_isherm_bug.txt](https://github.com/qutip/qutip/files/3406839/qutip_permute_isherm_bug.txt)

**Comment by Ericgig** [comment]
Hi llorz1207,
Thank you for raising this issue.
Instead of doing the double transpose you can do `permuted_Qobj.data.sort_indices()`.

Issue: Qobj.permute does not sort csr_matrix indice.
