### ISSUE TITLE
_check_ket_dims fails

### ISSUE THREAD

**Issue by yarrriv** [qutip/qutip#1057]
The dimension check [here](https://github.com/qutip/qutip/blob/181a98e910a1f34bb29be31b91d61f765d6c5a37/qutip/random_objects.py#L672) should be
`if np.prod(dims[0]) != N1 or np.prod(dims[1]) != 1`

(alternately the whole function could just call _check_dims(dims, N1, 1) )

In particular this makes rand_ket_haar fail if dims is specified, presumably other ket creators as well.

**Comment by yarrriv** [comment]
Actually looking at it again I think all of _check_ket_dims should be revised, and should look like a specialized copy of _check_dims with N2 replaced by 1, something like this:

def _check_ket_dims(dims, N1):
    if len(dims) != 2:
        raise Exception("Qobj dimensions must be list of length 2.")
    if (not isinstance(dims[0], list)) or (not isinstance(dims[1], list)):
        raise TypeError(
            "Qobj dimension components must be lists. i.e. dims=[[N],[N]]")
    if np.prod(dims[0]) != N1 or np.prod(dims[1]) != 1:
        raise ValueError("Qobj dimensions must match matrix shape.")
    if len(dims[0]) != len(dims[1]):
        raise TypeError("Qobj dimension components must have same length.")

**Comment by Ericgig** [comment]
Hi yarrriv,
Your new version of the check seems better. 
Do you want to make a pull request?
We could also make improve `rand_ket_haar` further so that when `dims` is given, `N` is determined from it.
