### ISSUE TITLE
mesolve/sesolve options have a mutable default value

### ISSUE THREAD

**Issue by goerz** [qutip/qutip#1061]
There is a problem with `mesolve` and `sesolve`'s default `options`, which determine whether the propagated states are stored in the `result` object:

~~~
>>> import qutip
>>> import numpy as np
>>> qutip.__version__
'4.5.0.dev0+19f172cb'
>>> H = qutip.sigmaz() + qutip.sigmax()
>>> psi = qutip.ket('0')
>>> tlist = np.linspace(0,10, 200)
>>> p0 = qutip.ket2dm(psi)
>>> res1 = qutip.mesolve(H, psi, tlist, e_ops=[p0])
>>> len(res1.states)  # should be 0
0
>>> len(res1.expect)  # should be 1
1
>>>
>>> len(res2.states)  # should be 200
200
>>> len(res2.expect)  # should be 0
0
>>> res3 = qutip.mesolve(H, psi, tlist, e_ops=[p0])
>>> len(res3.states)  # should be 0 (same as res1)
200
>>> len(res3.expect)  # should be 1
1
~~~
In `res3`, there should be no stored `states`, as I'm requesting expectation values. The problem is due to the common gotcha of [mutable default arguments](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments) in the definition of of e.g. `mesolve`:
~~~
def mesolve(H, rho0, tlist, c_ops=[], e_ops=[], args={}, options=Options(),
    progress_bar=BaseProgressBar(), _safe_mode=True)
~~~
What happens is that the default `options` get instantiated once when `qutip` is imported. In the example above `res2 = qutip.mesolve(H, psi, tlist)` will then internally set `options.store_states = True`, and this value will still be there for `res3 = qutip.mesolve(H, psi, tlist, e_ops=[p0])`.

Also, `c_ops`, `e_ops`, `args`, and `progress_bar` are all mutable in this definition, which could cause more problems. The correct thing to do is to initialize with `None` and set the mutable defaults in the body of the function.

I can prepare a pull request for this.

**Comment by Ericgig** [comment]
Thank you, 
I was not aware of that and put the Options as default value to clean the code.
