### ISSUE TITLE
qutip.simdiag throws TypeError

### ISSUE THREAD

**Issue by Croydon-Brixton** [qutip/qutip#1067]
Hi, thank you for the amazing work that you do.

When using qutip to diagonalise two simultaneously diagonalizible, hermitian operators it continues to throw this error:

![Screen Shot 2019-08-08 at 11 29 59](https://user-images.githubusercontent.com/19754061/62691897-e0a83680-b9cf-11e9-8a92-a88a3716ae99.png)

Which comes from `qutip.simdiag.py` in `simdiag(ops, evals)`:

![Screen Shot 2019-08-08 at 11 27 34](https://user-images.githubusercontent.com/19754061/62691786-a76fc680-b9cf-11e9-8f99-7a9ba78db518.png)

My installed packages:
QuTiP Version:      4.4.0
Numpy Version:      1.16.4
Scipy Version:      1.3.0
Cython Version:     0.29.12
Matplotlib Version: 3.1.0
Python Version:     3.7.3

**Comment by Croydon-Brixton** [comment]
Here's a code that reproduces the error for me (taken from an earlier GitHub issue for qutip):
import qutip as q

```
#consider two coupled spin L and S
Lval = 1
Sval = 0.5

[Lx,Ly,Lz] = map(lambda x: q.tensor(x, q.qeye(2*Sval+1)),q.jmat(Lval))
[Sx,Sy,Sz] = map(lambda x: q.tensor(q.qeye(2*Lval+1), x),q.jmat(Sval))

Jx = Lx + Sx
Jy = Ly + Sy
Jz = Lz + Sz

Lsq = Lx*Lx + Ly*Ly + Lz*Lz
Ssq = Sx*Sx + Sy*Sy + Sz*Sz
Jsq = Jx*Jx + Jy*Jy + Jz*Jz

q.simdiag([Lsq,Ssq,Jsq,Jz])
```

**Comment by Ericgig** [comment]
Thank you for reporting, should work in 4.4.1 
https://github.com/qutip/qutip/tree/qutip-4.4.1 (Should be released next week).

**Comment by nathanshammah** [comment]
I tested that this snippet now runs on qutip 4.4.1.
