### ISSUE TITLE
Restructuring QIP module - `device`, `circuit`, `operations`, `measurement` ... 

### ISSUE THREAD

**Issue by quantshah** [qutip/qutip#1072]
With the Google Summer of Code 2019 project by @BoxiLi on noise models, we are making some big changes to update the QIP module. One of the things that came up is having a `DeviceProcessor` or `Device`` class which interfaces with hardware implementations directly and runs quantum circuits on models such as SpinChain, cQED. We will also work towards linking the OptPulseProcessor to find optimal pulses to implement a circuit and add a `noise` module.

I am opening this issue to discuss the restructuring of the QIP module and also adding a `measure` function/module (later) to get samples and expectation values from a circuit. We c can use this thread to discuss other issues too regarding the QIP module and how we can interface it better to QuTiP core functionalities. 

- qip
    - device/
        - processor (which has DeviceProcessor (base class for spinchain, cqed), OptPulseProcessor etc)
        - spinchain
        - cqed
    - circuit.py
    - operations.py (gates.py + qft.py)
    - noise.py
    - measurement

@ajgpitch @nathanshammah @qutip/owners 
@BoxiLi please feel free to suggest, change or discuss more on this issue as you continue working on it. Thanks.

**Comment by BoxiLi** [comment]
It seems more natural for me to put gates, qft, measurement all under a module called operations. From the view of quantum information theory, measurement no different than a non-unitary operation.

- operations/
     - gates.py
     - qft.py
     - measurement.py

On the other hand, functions in gate.py seem to be used quite a lot (also inside qutip, like `swap`). I'm not sure if `from qutip.qip.operations import swap` is too cumbersome?

**Comment by nathanshammah** [comment]
I think this has been addressed by #1042 (GSoC project on noise in quantum circuit). Feel free to reopen if this is not the case or it only partially addresses this.
