### ISSUE TITLE
entropy vonnumen

### ISSUE THREAD

**Issue by Hosseinyeganeh** [qutip/qutip#1078]
Hi
RT=1/sqrt(2)*(tensor(ket0,ket0)+tensor(ket1,ket1))
RR=ket2dm(RT)
print(entropy_vn(RR, base=2, sparse=False))

in above program I want calculate the entropy 
We know that it is 1 for bell state
But output is 3.2034265038149176e-16!!!!
can you help me?

**Comment by nwlambert** [comment]
Hi, you need to take a partial trace of one of the subsystems first, and
then calculate the entropy.  You can use the ptrace() function for that.

**Comment by Hosseinyeganeh** [comment]
it not work 
I want to obtain  entropy of 4*4 density matrix

**Comment by nwlambert** [comment]
The state you defined is a pure state, so even if you write it as a density matrix it has zero entropy.
So that output is correct.

The entropy being 1 for a Bell state is true when you trace out one of the two systems, so that the reduced state is now mixed,
e.g., 
```
RR2=ptrace(RR,0)
print(entropy_vn(RR2, base=2, sparse=False))

```
