### ISSUE TITLE
population should stay constant but drifts linearly (spin 1, H=Sz^2)

### ISSUE THREAD

**Issue by JossBern** [qutip/qutip#1085]
Hello

I'm working on a qutrit system (spin 1). Eventually need to do some pulse optimization but for testing I tried to propagate using a very simple Hamiltonian, namely just Sz^2 with D=2000. 
Units are µs for time (so MHz for frequency). 

versions used:
```python
matplotlib.pylab 1.16.4
qutip            4.4.1
matplotlib       3.1.1
numpy            1.16.4
scipy            1.3.1
CPython 3.7.3
IPython 7.5.0
```

I solve with sesolve or mesolve with  (|+

1> + |0>)/sqrt(2) as initial state.
**expected:** quite trivially, population should stay 1/2 for any t for |+1> and |0>, 0 for |-1>
**result:** population of  |+1> goes down linearly and |0> goes up 
a few observations: 
- if I make the coefficient of Sz^2 smaller, the population diverges less 
- with less time steps but same overall propagation time, I see the divergence less obviously because I see the beginning of it
- I am aware one can somehow optimize the number of time steps but this is about the convenient settings for the next steps for me
- I was thinking of increasing floating point precision or something like that but wasn't able to find a simple way to do that in the docs.

it does not seem like having a coefficient on the order of 10000 or 10^5 time steps is that unreasonable, does it ?
anyway, this is about the right, convenient choice of unit for us here.

any idea what's wrong ?

```python
%load_ext watermark
import numpy as np
import scipy
import matplotlib
import matplotlib.pylab as plt
import qutip
%watermark -v --iversions
%matplotlib qt

#Spin 1 operators
S1_x = 1/np.sqrt(2)*qutip.Qobj([[0,1.,0],
                      [1.,0,1.],
                      [0,1.,0]])

S1_y = 1.j/np.sqrt(2)*qutip.Qobj([[0,-1.,0],
                      [1.,0,-1.],
                      [0,1.,0]])

S1_z = qutip.qdiags([1.,0,-1.], 0)

#canonical basis with corresponding projectors
canon_100 = qutip.basis(3,0) #ket |+1>
canon_010 = qutip.basis(3,1) #ket |0>
canon_001 = qutip.basis(3,2)  #ket |-1>

proj100 = qutip.ket2dm(canon_100)
proj010 = qutip.ket2dm(canon_010)
proj001 = qutip.ket2dm(canon_001)

#Hamiltonian parameters
f_0FS = 2000. # (Zero field splitting) in MHz
D = 2*np.pi*f_0FS
# Constant Hamiltonian
H_0 = D * S1_z * S1_z

# time limits
start_time = 0. # in µs
stop_time = 0.5 # in µs

#inital state  (|+1> + |0>)/sqrt(2) 
plusket = (canon_100 + canon_010).unit()

#time steps
Nsteps = 100000
tlist = np.linspace(start_time, stop_time, Nsteps)

labels = ['100', '010', '001']
def plot_exp_val(result):
    fig, ax = plt.subplots(figsize=(9, 3))
    for i in range(0,len(result.expect)):
        ax.plot(result.times, result.expect[i], label=labels[i])
    ax.legend()
    ax.set_xlabel('time')
    ax.set_ylabel('population')
    plt.show(fig)

output_SE = qutip.sesolve(H_0, plusket, tlist, e_ops = [proj100,proj010,proj001])

plot_exp_val(output_SE)
```
here's the result I get:

![populations_qutrit](https://user-images.githubusercontent.com/55277602/64865793-715edb80-d63a-11e9-80b2-f6557f6f6a58.png)

**Comment by Ericgig** [comment]
Hi,
This seems to ba accumulation of numerical error.
You can increase the solver precision (atol, rtol, max_step) in options:
`sesolve(..., options=qutip.Options(atol=1e-9)`.
You could also remove the normalization of the state `Options(normalize_output=False)`, then the error will not spread to the "010" state.

**Comment by JossBern** [comment]
ah great the rtol set to 1e-9 solved it.
thanks a lot !

out of a curiosity I need to ask though: why is the bias so constantly driving the population exclusively downwards (or upwards) ? I have no idea where the numerical error actually comes into play but I would have expected the error to be a lil' more all over the place...

**Comment by Ericgig** [comment]
This error comes from the integration algorithm.
Take a differential equation like dy/dt = -i*y.
With a simple method like euler: 
y(t+dt) = y(t) + f' dt = y(1-i*dt)
So the norm increase exponentially *(1+dt**2) at each iteration, not somewhat randomly.
The default method we use is "adams" from scipy's solver, which is a lot better than euler, but still have a bias. We also stop the solver for re-normalization of the state from time to time, introducing another bias.

**Comment by JossBern** [comment]
I see. thanks a lot!
