### ISSUE TITLE
BUG: Qutip fails to install on Ubuntu 18.04 via pip

### ISSUE THREAD

**Issue by jakobjakobson13** [qutip/qutip#1086]
Dear developers,

I'm failing to install qutip on Ubuntu 18.04 via pip. The error output says:
```bash
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for qutip
```

How can I solve this issue?

Regards

PS: The relevant software versions are
python3 3.6.8
python3-venv 3.6.7
qutip 4.4.1 (The version I tried to install.)

**Comment by nathanshammah** [comment]
Thank you for reporting it. Hope we can assess this. It is not a solution, but just in case it can help you, maybe with conda things work more smoothly, if that is a suitable option for you.

**Comment by jakobjakobson13** [comment]
I filed the bug report even though there is no bug. My apologies.
