### ISSUE TITLE
Parallel Computing With qutip

### ISSUE THREAD

**Issue by bulmust** [qutip/qutip#1101]
Does qutip use multiprocessor packages? (like MPI etc.)

I have large, non linear, stiffly oscillated Hamiltonian system that needs to be accelerated. I am really curious about the difference between dif. eqn. solvers of qutip and ordinary numpy odeint ('LSODA') solver.

**Comment by Ericgig** [comment]
Qutip use Scipy's Ode solvers. The interface of scipy solvers chaged in recent version, but we are still using [ode](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.ode.html#scipy.integrate.ode). We are using zvode integrator and adams method per default. Most of qutip's solver accept an options arguments which can change the method to 'bdf' but cannot be changed to Isoda or dopri.

Mpi is not supported but multiprocessing is used by mcsolve and the stochastic solvers. If you [compile qutip](http://qutip.org/docs/latest/installation.html?highlight=openmp) yourself, we have a openmp parallelized matrix-vector product which can be used to speed up problem with large Hamiltonian.

**Comment by nathanshammah** [comment]
Just to mention, another issue with references to parallel computing, mainly showing how it can work in practice https://github.com/qutip/qutip/issues/438

**Comment by nathanshammah** [comment]
See also https://github.com/qutip/qutip/pull/1092

**Comment by bulmust** [comment]
Thank you for your detailed answer.
