### ISSUE TITLE
Possible solution to automating changelog/release notes, and adding PR templates

### ISSUE THREAD

**Issue by tehruhn** [qutip/qutip#1108]
Referencing this : https://github.com/qutip/qutip-doc/pull/70

1. Having manually compiled the changelog for v4.4.1 and v4.5.x today, I think that maybe we should try automating the release notes/changelogs with something like this : https://github.com/github-tools/github-release-notes
I'm attaching release notes generated by this for QuTiP.
[RELEASE_NOTES.txt](https://github.com/qutip/qutip/files/3728179/RELEASE_NOTES.txt)

2. We could also, in pursuit of having an automated release notes/changelog system start with making commits in more of a standard format, using some pre-decided keywords like [bugfix] or [improvement] in the commit message. I understand that this is a rather ambitious thing to say, but we can then use `grep` and `git log` itself to generate these in markdown. As a first step, I am proposing to use **Pull request /Issue** templates, something like this for instance : https://github.com/angular-translate/angular-translate/blob/master/.github/ISSUE_TEMPLATE.md
This way, all our Pull Requests and Issues will be homogeneously formatted.

**Comment by hodgestar** [comment]
Superseded by #1894.
