### ISSUE TITLE
confusing scaling in wigner() and plot_wigner()

### ISSUE THREAD

**Issue by gsteele13** [qutip/qutip#1112]
The default scaling factor of \sqrt(2) used by wigner() and plot_wigner() is confusing

```
alpha = 3
psi = coherent(N,alpha)
plot_wigner(psi)
```

produced a plot with coherent state that is NOT centered at alpha = 3 (mega confusing)

Does anyone know where this default scaling of $\sqrt{2}$ comes from? 

In particular, I would suggest that the default be changed to g = 1  to make the above code segment not internally self-inconsisitent

I can easily submit a patch if needed

**Comment by gsteele13** [comment]
(also, although wigner() allow you to override the scaling factor, plot_wigner() does not...)

**Comment by gsteele13** [comment]
minor correction: the parameter g in the function call should actually be set to g=2 to get the correct scaling

(also confusing...)

**Comment by nonhermitian** [comment]
It was originally for compatibility with the qotoolbox.

**Comment by KosukeMizuno** [comment]
Hi, since it've been intended for compatibility, just changing the default could cause compatibility issues.
I also frequently use `plot_wigner` but g=2 is proper for me, so if it can be changed, I'm happy.
Thus I added argumens for plotter functions to specify a desired `g` value instead of changing the default.

**Comment by BeateAsenbeck** [comment]
I have come across the same problem. If you set g=2 you will have a different normalization for the Wigner function. W(0,0)=-0.63661977 is the 0,0 point of the single photon, which usually should be -1/pi so here we multiplied it by two. Same goes for g=1 where you divide it by 2 as far as I see. This does not change the normalization of the marginal distributions so all of those Wigner functions with different g are valid phase-space quasi-probabilities. What does change in fact with the factor g is the commutator relation [x,p]=a*i, where if g!=sqrt(2) a!=1. This will in fact change how we connect annihilation, creation, position and momentum operators together. 
In the case g=sqrt(2) we have the definition x=1/sqrt(2)(a^\dagger + a) and p = i/sqrt(2)(a^\dagger - a).
If we now consider the question at hand concerning the coherent state amplitude we easily understand what is happening. A coherent state is defined by the displacement operator D(\alpha) which is defined as D(\alpha)=Exp[\alpha a^\dagger  - Conj[\alpha]a], where we can rewrite the exponential argument as Re(\alpha)(a^\dagger - a) + i Im(\alpha) (a^\dagger + a) which is Re(\alpha) p sqrt(2) + Im(\alpha) x sqrt(2). You can see that with this definition there is a scaling factor alpha/sqrt(2) if we want to plot it in x,p phase space. So all you need to do is rescale your amplitude.
If you instead want to have g=2 then there is no rescaling needed, but your commutator relation and therefore your Heisenberg uncertainty minimum will change.

**Comment by Ericgig** [comment]
An option was added to `plot_wigner` to accept an optional `g` input.
