### ISSUE TITLE
Inconsistent output multiplying Qobjs

### ISSUE THREAD

**Issue by wouterkesselsap** [qutip/qutip#1114]
Say I have the operator `b = tensor(destroy(3), qeye(3))`. When I want to calculate the fourth power of `(b + b.dag())` I have several possibilities to do that, but they give different answers.
Let's define:
`B1 = (b + b.dag())**4`;
`B2 = (b + b.dag()) * (b + b.dag()) * (b + b.dag()) * (b + b.dag())`, and
`B3 = b*b*b*b`
`B3 += b.dag()*b*b*b + b*b.dag()*b*b + b*b*b.dag()*b + b*b*b*b.dag()`
`B3 += b.dag()*b.dag()*b*b + b.dag()*b*b.dag()*b + b.dag()*b*b*b.dag()`
`B3 += b*b.dag()*b.dag()*b + b*b.dag()*b*b.dag() + b*b*b.dag()*b.dag()`
`B3 += b.dag()*b.dag()*b.dag()*b + b.dag()*b.dag()*b*b.dag() + b.dag()*b*b.dag()*b.dag() + b*b.dag()*b.dag()*b.dag()`
`B3 += b.dag()+b.dag()+b.dag()+b.dag()`

B1 and B2 give the same output, but that is different from B3. How can this possibly be? And which one should I trust?

**Comment by tehruhn** [comment]
Hi @wouterkesselsap ,

In the last line of B3, you have written 
`B3 += b.dag()+b.dag()+b.dag()+b.dag()`

but it should be 

`B3 += b.dag()*b.dag()*b.dag()*b.dag()`

**Comment by tehruhn** [comment]
Also, please close the issue if it's resolved. Thank!
