### ISSUE TITLE
Husimi Q and Wigner spin functions don't give correct results

### ISSUE THREAD

**Issue by maij** [qutip/qutip#1128]
The Husimi Q function for spins gives incorrect output for the states |J, -J>, for all J.
Generating a spin-coherent state with some theta and phi, and then calculating the Husimi Q function for the same theta and phi should always give 1/pi, but this value tends toward 0 the closer to the bottom of the Bloch sphere you go.

A similar problem exists for the spin wigner function, where a the spin-coherent state |J, -J> has some negativity in the wigner function.

**Comment by quantshah** [comment]
Could you please post a code snippet to reproduce this? I am working with the Husimi Q and Wigner functions now and could look into it more.

**Comment by maij** [comment]
`theta, phi = pi, 0`
`psi = spin_coherent(1/2, theta, phi)`
`husimi, _, _ = spin_q_function(psi, theta, phi) # should evaluate to 1/pi but = 0`

This shows the main problem, if you also calculate the Husimi Q function for all theta and phi, it will be equal to 0 at every point.

A similar problem occurs for the spin_wigner function.

**Comment by gharib85** [comment]
See 
A Group-Theoretical Approach to Quantum Optics           book equation   (10.25)
Different implementation from Qutip 
|θ,φ>=exp(−iϕSz)exp(−iθSy)|S,S>

**Comment by maij** [comment]
I discovered the issue originated from this commit da642a3539cbf1d3d8c391576eedd3a3f6bdc50e

This prevented the Husimi Q function being correctly calculated for non-integer spin systems. There is a remaining factor of 1/pi to be included as well, which I might treat as an option when I update the code.
