### ISSUE TITLE
Travis deprecated the container infrastructure last year

### ISSUE THREAD

**Issue by tehruhn** [qutip/qutip#1133]
Running `travis lint` gives a bunch of warning. Like for instance, `sudo : required` is no longer needed, and Travis migrated to a new architecture. So the `travis.yml` file needs to be updated.

https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures

**Comment by nathanshammah** [comment]
@tehruhn can you open a PR just for this?

**Comment by jakelishman** [comment]
At least as of #1347 this is fixed, but I think the true fix date is much earlier than that.
