### ISSUE TITLE
`TestPulseOptim` fails

### ISSUE THREAD

**Issue by nathanshammah** [qutip/qutip#1134]
While trying to migrate to pytest from nose , #1131, there is only one failed test arising on all platforms. 
The problem seems to be a test in the `control` module, exactly it is `qutip.tests.test_control_pulseoptim.TestPulseOptim` called by     `test_03_dumping(self):` on line 340. 

```
AttributeError: 'TestPulseOptim' object has no attribute 'tmp_dirs'
```
Indeed, TestPulseOptim seems to have this attribute where `tmp_dirs`
are defined, 
```
    def setUp(self):
        # list of file paths to be removed after test
        self.tmp_files = []
        # list of folder paths to be removed after test
        self.tmp_dirs = []
```
Any help @tehruhn and @ajgpitch would be great. I think one should call `setUp`.

**Comment by tehruhn** [comment]
This can be close, #1131 fixes this.

**Comment by nathanshammah** [comment]
Maybe we can try remove pytest-cov?

**Comment by tehruhn** [comment]
We only use it for Travis, the end user only needs to install pytest.
I don't think removing it should change the output, but we can try it if you think it might work.

**Comment by nathanshammah** [comment]
ah ok no fine. I meant to comment the other PR.
