### ISSUE TITLE
Basis

### ISSUE THREAD

**Issue by gharib85** [qutip/qutip#1146]
Why 
return Qobj(fast_csr_matrix((data,ind,ptr), shape=(N,1)), isherm=False)
.,................
Can use csr_matrix directy
..........
return Qobj(
Scipy.lil.csr_matrix( (data,(row,col)), shape=(N,1) ,)isherm=False)

**Comment by Ericgig** [comment]
Without any context, we can't understand what you are asking...
But you should use which ever you what when using qutip.
fast_csr_matrix is mostly an internal representation of csr_matrix which disable type checks to make it faster.
