### ISSUE TITLE
Error in the log_handler setting and missing documentation

### ISSUE THREAD

**Issue by mgunyho** [qutip/qutip#1156]
Hello,

I'm using qutip alongside another library, which does something like this:
```py
import logging
logger = logging.getLogger()
logger.setLevel(logging.DEBUG)
```
Im not entirely sure why it does so, but nevertheless debug messages don't show up anywhere, since the root logger doesn't print anything without it being configured. If you run the above code in Ipython but add `import qutip` before it, `logging.debug("foo")` prints to the stderr (without qutip it doesn't). So when I started using the library with qutip, suddenly all debug messages started getting printed to stderr.

Apparently, this is somewhat on purpose, by looking at the code [here](https://github.com/qutip/qutip/blob/eff1c3a606cad64b8d16f3232181b0463d65d746/qutip/logging_utils.py#L99). I'm not entirely sure what tho think about that, because as shown above this causes something unexpected. Nevertheless, I thought I could work around this by setting `log_handler = "null"` in my settings file, but that in turn causes qutip to crash, because the rc loader [expects](https://github.com/qutip/qutip/blob/eff1c3a606cad64b8d16f3232181b0463d65d746/qutip/configrc.py#L97) `log_handler` to be a boolean for some reason. Also, it took me a while to find this, since the `log_handler` option is [not documented](http://qutip.org/docs/latest/guide/guide-settings.html?highlight=log).

I'm using python 3.7.4 and QuTiP 4.4.1 installed with pip.

**Comment by BoxiLi** [comment]
It seems that the library you are using turns off the logging stream. Maybe you can try `logging.disable(logging.DEBUG)`

**Comment by mgunyho** [comment]
I worked around this by doing
```py
import qutip
import the_library  # this sets the log level to DEBUG
import logging
logging.getLogger().setLevel(logging.WARNING)
```
I supposes that it's a bit weird/wrong that the library sets the log level like that, and maybe it's understandable that qutip has somewhat automatic logging for IPython. The real issue is that the config for `log_handler` is broken. I could possibly submit a PR for that at some point.

**Comment by Ericgig** [comment]
Qutip use the logging library anymore.
