### ISSUE TITLE
Documentation of photocurrent_mesolve

### ISSUE THREAD

**Issue by rporotti** [qutip/qutip#1163]
Hi all,
I am trying to reproduce the results of the photocurrent solver for open systems with my own methods, but I see some differences in the dynamics.

In the [documentation webpage](http://qutip.org/docs/latest/guide/dynamics/dynamics-photocurrent.html#open-system) to what L_sys is, and why it should be corrected with that effective term. Can someone please give provide a reference for that statement?

Furthermore, are C_n in that equation equivalent to the sc_ops in Qutip?

Thank you for your help!

**Comment by nathanshammah** [comment]
It refers to the system's Liouvillian, I'd say. The user guide is partly out of date there, @Ericgig and others have considerably extended the functionalities of the stochastic solvers. Looking at the [API documentation](http://qutip.org/docs/latest/apidoc/functions.html#module-qutip.stochastic) is safer, and the [source code](http://qutip.org/docs/latest/modules/qutip/stochastic.html) is even more complete. 

Meanwhile, you can also have a look at these development notebooks [here](https://nbviewer.jupyter.org/github/qutip/qutip-notebooks/blob/master/development/development-smesolve-milstein-speed-test.ipynb) [here](https://nbviewer.jupyter.org/github/qutip/qutip-notebooks/blob/master/development/development-smesolve-tests.ipynb), and [here](https://nbviewer.jupyter.org/github/qutip/qutip-notebooks/blob/master/development/development-smesolver-new-methods.ipynb) the new methods (you can find them all, a bit hidden, at the bottom of the http://qutip.org/tutorials.html list). Technically this issue could be raised under [`qutip/qutip-doc`](https://github.com/qutip/qutip-doc).

**Comment by rporotti** [comment]
Thank you very much! The development notebooks were very useful, especially the last one.

> It refers to the system's Liouvillian, I'd say. I think all the `C_n` there are stochastic jumps, `sc_ops `, while the system Liouvillian is the constant part, `c_ops`. But I am not 100% sure.

Everything's correct.
