### ISSUE TITLE
Qutip propagator does not work for Hamiltonians that are QobjEvo objects

### ISSUE THREAD

**Issue by Wikstahl** [qutip/qutip#1166]
Trying to run the Qutip `propagator` for a Hamiltonian that is a `QobjEvo` object does not work and will result in _Invalid time-dependent format_ error.

Example of a piece of code.

```
N = 3
a = destroy(N)
t_total = 10
tlist = np.linspace(0, t_total, 1000)
H = a.dag()**2 * a**2
H1 = a.dag()*a
H_tot = QobjEvo([H,[H1,np.cos(tlist)]],tlist=tlist)
prop = propagator(H_tot, tlist, [])
```

**Comment by BoxiLi** [comment]
`propagator` does not support `QobjEvo` yet.
If you are looking for solution for the problem `prop = propagator([H,[H1,np.cos(tlist)]], tlist, [])` will work. You can get `[H,[H1,np.cos(tlist)]]` using `H_tot.to_list()` if you already have a `QobjEvo` from somewhere else.
