### ISSUE TITLE
clebsch function not working with non-int j values

### ISSUE THREAD

**Issue by taw181** [qutip/qutip#1176]
I'm getting the following error when the first three arguments for the clebsch function aren't all ints:    
```
c_factor = np.zeros((j1 + j2 + j3 + 1), np.int32)
TypeError: 'float' object cannot be interpreted as an integer
```
Fixed by changing 
`c_factor = np.zeros((j1 + j2 + j3 + 1), np.int32) `
to 
`c_factor = np.zeros((int(j1 + j2 + j3 + 1)), np.int32)`
and same for _factorial_prod() etc. It's now giving expected results. This shouldn't break anything as j1 +/- j2 +/- j3 should always give an integer.

Seems to have been caused by #1142 in response to #1141.

**Comment by nathanshammah** [comment]
Thanks for the details and tracking it down. Could you open a Pull Request and add a test for that?

**Comment by taw181** [comment]
#1177
