### ISSUE TITLE
More detailed information for GSoC 2020 project

### ISSUE THREAD

**Issue by BoxiLi** [qutip/qutip#1184]
I have some detail information for the GSoC 2020  project "Error mitigation in QuTiP". Unfortunately, I don't have writing access to the QuTiP GitHub Wiki page. I post it here so if anyone finding it nice could copy it to the Wiki page.

I add some details based on the original description:

-----------------------------------
## 1. Error mitigation in QuTiP
From the QuTiP 4.5 release, the qutip.qip module now contains the noisy quantum circuit simulator (which was a GSoC project) providing enhanced features for a pulse-level description of quantum circuits and noise models. A new class `Processor` and several subclasses are added to represent different platforms for quantum computing. They can transfer a quantum circuit into the corresponding control sequence and simulate the dynamics with QuTiP solvers. Different noise models can be added to `qutip.qip.noise` to simulate noise in a quantum device. 

This module is still young and many features can be improved, including new device models, new noise models and integration with the existing general framework for quantum circuits (`qutip.qip.circuit`). There are also possible applications such as error mitigation techniques [1-3].

The tutorial notebooks can be found at http://qutip.org/tutorials.html#nisq. A recent presentation on the FOSDEM conference may help you get an overview (https://fosdem.org/2020/schedule/event/quantum_qutip/). See also the Github Project page for a collection of related issues and ongoing Pull Requests.

### Expected outcomes
 - More devices defined in the `qutip.qip.device` module. At the moment, we have two models: spin chain and cavity QED. We would like to include some other commonly used planform such as Superconducting system, Ion trap system or silicon system. Each model will need a new set of control hamiltonian and a compiler that find the control pulse of a quantum gate. This part is gonna involve some physics and study of commonly used hardware platforms. The related code can be found in `qutip.qip.device` and `qutip.qip.compiler`
- Refactoring the circuit compiler to allow simple pulse scheduling, e.g. Restriction one pulses that can be turned on at the same time.
- Features to perform error mitigation techniques in QuTiP, such as zero-error extrapolation.
- APIs to allow import quantum circuits from other software packages or commonly used language e.g. through quantum assembly language (qasm)
----------------------------------------------------------------

Also, the last outcomes have some overlap with the last project. Although I also find this circuit importation very important, I guess two projects should not have overlap if they are both selected.

**Comment by nathanshammah** [comment]
Hi Boxi,

Can you please modify the projects of the Wiki page as you deem best?
All: we can also think of changing the order of them. It may be that
project #3 is deemed the most important.

Best wishes,

Nathan

Dr. Nathan Shammah
Postdoctoral Research Scientist
Theoretical Quantum Physics Laboratory
RIKEN, Wako, Saitama, Japan
www.nathanshammah.com

**Comment by BoxiLi** [comment]
Hi Nathan,

I can't modify the Wiki page because I'm not a maintainer of QuTiP. And it seems that there is no way to make a PR to Wiki. I can also send you the markdown source code per email like this, but I’m not sure if it works as I expected.

The following is the markdown source code:

-----------------------------------
## 1. Error mitigation in QuTiP
From the QuTiP 4.5 release, the qutip.qip module now contains the noisy quantum circuit simulator (which was a GSoC project) providing enhanced features for a pulse-level description of quantum circuits and noise models. A new class `Processor` and several subclasses are added to represent different platforms for quantum computing. They can transfer a quantum circuit into the corresponding control sequence and simulate the dynamics with QuTiP solvers. Different noise models can be added to `qutip.qip.noise` to simulate noise in a quantum device.

This module is still young and many features can be improved, including new device models, new noise models and integration with the existing general framework for quantum circuits (`qutip.qip.circuit`). There are also possible applications such as error mitigation techniques [1-3].

The tutorial notebooks can be found at http://qutip.org/tutorials.html#nisq. A recent presentation on the FOSDEM conference may help you get an overview (https://fosdem.org/2020/schedule/event/quantum_qutip/). See also the Github Project page for a collection of related issues and ongoing Pull Requests.

### Expected outcomes
- More devices defined in the `qutip.qip.device` module. At the moment, we have two models: spin chain and cavity QED. We would like to include some other commonly used planform such as Superconducting system, Ion trap system or silicon system. Each model will need a new set of control hamiltonian and a compiler that find the control pulse of a quantum gate. This part is gonna involve some physics and study of commonly used hardware platforms. The related code can be found in `qutip.qip.device` and `qutip.qip.compiler`
- Refactoring the circuit compiler to allow simple pulse scheduling, e.g. Restriction one pulses that can be turned on at the same time.
- Features to perform error mitigation techniques in QuTiP, such as zero-error extrapolation.
- APIs to allow import quantum circuits from other software packages or commonly used language e.g. through quantum assembly language (qasm)
----------------------------------------------------------------

Best
Boxi

**Comment by nathanshammah** [comment]
Hi,

Yes, I know, that's why I added the md file. I updated it now, thanks,
adding more info on general resources to learn about QuTiP and more
references to the #3 project, i.e. your blog and the talk.
https://github.com/qutip/qutip/wiki/Google-Summer-of-Code-2020

Neill, Alex, if you have a lead, please add a HEOM project.

Bests,

Nathan

Dr. Nathan Shammah
Postdoctoral Research Scientist
Theoretical Quantum Physics Laboratory
RIKEN, Wako, Saitama, Japan
www.nathanshammah.com

**Comment by nathanshammah** [comment]
updated on the Wiki GSoC 2020 page. https://github.com/qutip/qutip/wiki/Google-Summer-of-Code-2020
