### ISSUE TITLE
Mcsolve with row and column matrix rather than vector matrix.

### ISSUE THREAD

**Issue by vini199** [qutip/qutip#1189]
I need mcsolve result in row and column matrix as mentioned below. How can i got this because this code is showing error.
```python
fieldfield_list = []
atomfield_list = []
tlist = np.linspace(0,20,2000)
gM_list = np.linspace(0,3,200)
for g_M in gM_list:
    H = omega_M*b.dag()*b + Y*(a + a.dag())+ g*((a*sig_plus) + (a.dag()*sig_plus.dag()))
    + g_M*a.dag()*a*(b + b.dag())
    evalues = mcsolve(H, psi0, tlist, c_ops=[], e_ops=[], ntraj=None, args={}, options=None, progress_bar=True, map_func=None, map_kwargs=None, _safe_mode=True)
    fieldfield_list.append(evalues[0][-1]/(evalues[2][-1]**2))
    atomfield_list.append(evalues[1][-1]/(evalues[2][-1]*evalues[3][-1]))
```

**Comment by jakelishman** [comment]
I'm not entirely sure what's being asked here.  `mcsolve` evolves the state `psi0` by the given Hamiltonian for the given times, and returns a `qutip.solver.Result` object that contains various quantities, such as how the state evolved for each of the trajectories at a given time, and values of expectation operators at those times if `e_ops` is given.

This looks like a question that's best answered by [reading the user guide on solving system dynamics](http://qutip.org/docs/latest/guide/dynamics/dynamics-monte.html).
