### ISSUE TITLE
installation issue: `src/zspmv_openmp.hpp`

### ISSUE THREAD

**Issue by JiahaoYao** [qutip/qutip#1205]
I want to install qutip on the linux (ubuntu 18.04 LTS), but I got the following issue. I wonder whether anyone has encountered this problem before. 

```
/home/abc/.pyxbld/temp.linux-x86_64-3.7/pyrex/qutip/cy/openmp/parfuncs.cpp:614:10: fatal error: src/zspmv_openmp.hpp: No such file or directory
 #include "src/zspmv_openmp.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by Ericgig** [comment]
No, we usually have no problem on linux. How did you install it? `pip`, `python setup.py install`? Did you have a prior installation? Some time, if you install qutip without openmp but installed it previously with openmp there are errors.

**Comment by JiahaoYao** [comment]
Thanks, i think that is an openmp issue.

**Comment by JiahaoYao** [comment]
Finally, here is the temporal solution for those who might have the same issue.

My bug report is 
```
/home/abc/.pyxbld/temp.linux-x86_64-3.7/pyrex/qutip/cy/openmp/parfuncs.cpp:614:10: fatal error: src/zspmv_openmp.hpp: No such file or directory
 #include "src/zspmv_openmp.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

There is no `src/zspmv_openmp.hpp` in that folder, i.e. `/home/abc/.pyxbld/temp.linux-x86_64-3.7/pyrex/qutip/cy/openmp/`.

One can download [this folder](https://github.com/qutip/qutip/tree/master/qutip/cy/openmp/src) and put this `src` folder into the target folder `/home/abc/.pyxbld/temp.linux-x86_64-3.7/pyrex/qutip/cy/openmp/`.

**Comment by jakelishman** [comment]
This file is now correctly distributed in the `4.6` sdist release (see #1449), though do note that people who want to use OpenMP will probably have an easier time of it if they are installing from the latest `git` source.
