### ISSUE TITLE
Add more single-qubit gates to QubitCircuit

### ISSUE THREAD

**Issue by BoxiLi** [qutip/qutip#1208]
QuTiP `qip` module currently supports six different single-qubits gate, including rx, ry, yz, http://qutip.org/docs/latest/guide/guide-qip.html. However, the commonly used Pauli X, Y, Z  gates, T gate and S gate are not there. Although in principle they can all be realized by the existing gate set. It would still be good to have them supported in `qutip.qip.QubitCircuit`.

- Define those gates in `qutip.qip.operation`. If they already exist in `qutip.operators`, import them as functions such as `x_gate`, `y_gate`, `z_gate`, `s_gate`, `t_gate`
- Add the gates to `quip.qip.QubitCircuit`
- Add them also to the LaTeX code if applicable.

**Comment by sarsid** [comment]
Hello, 

I am trying to work on this feature. Do you think it's also a good idea to add the controller version of the above gates? This can be done by defining a custom gate as well as given in the example (for rx) in the docs.  Also, is it better if we name the gates "X" or "XGATE". I am not sure what convention the naming follows, if any. I can issue a pull request as soon as this is clarified. 

Best, 
Sidhant.

**Comment by BoxiLi** [comment]
Hi @sarsid, Thanks for working on this.

In `qutip.qip.QubitCircuit`, I think "X" "Y" "Z" "S", "T" is good enough as a gate name. No need to let the user repeat GATE every time. In `qutip.qip.operations`, I find it's better to name the function `x_gate `because `x` seems too short and unclear. Feel free to argue if you are of a different mind.

Sure you can add the controlled version like "CZ" etc if you'd like to. There is a function called `controlled_gate` in `qutip.qip.operations.gates`, might be useful.

**Comment by BoxiLi** [comment]
Solved by #1209 and #1224.
