### ISSUE TITLE
QubitCircuit.add_1q_gate missing last qubit

### ISSUE THREAD

**Issue by white-cold** [qutip/qutip#1210]
Expected behavior: add_1q_gate applies the specified gate to the whole register.
Actual behavior: add_1q_gate sets end to N-1, and iterates with range(start, end) to apply the single qubit rotations. Since range() does not include the stop, the last qubit is not affected.

**Comment by sarsid** [comment]
You are correct, also this does not comply with user behavior in the sense that it does not apply the qubit on the end gate specified by the "end" argument.
