### ISSUE TITLE
Density matrix becomes nonhermitian after sufficient time in `mesolve`

### ISSUE THREAD

**Issue by Krastanov** [qutip/qutip#122]
Frequently while I am using `mesolve` for some long protracted evolution the density matrix at some point becomes nonhermitian (`isherm` and `checkherm()` return false). I am guessing that this is just because of numeric noise, as there is nothing physically that can cause that (and it is happening even when the evolution is purely unitary).

Is this actually because of numerical noise?

If yes, I was wondering whether this can be addressed from within `qutip` or whether the burden on addressing numerical noise should be on the user?

Is there a "canonical qutip way" to remove the nonhermitian numerical noise from matrices that should be hermitian?

Edit: the nonhermiticity is indeed very small (10**-11), so it is just noise. I am just wondering whether it is `qutip` that should address the problem or the user.

**Comment by mmensing** [comment]
I was wondering if this is still an issue? If so I could try to spend some thinking on possible ways to correct the errors.

**Comment by nonhermitian** [comment]
Whether it is an issue likely depends on you school of thought.  The error comes from the finite accuracy of the solvers. By default, the solutions are found using a method that is accurate 12-order in the step size and looks for absolute and relative errors at the 1e-8 and 1e-6 levels, respectively.  If you evolve for long enough then inevitably there is going to be some error, and you will not get perfectly Hermitian matrices.  One can accept this, and possibly lower the tolerance levels for more accuracy, or you can take 0.5*(A+A.dag()) to force the Hermicity.  What method you use likely depends on your question and taste.  Either way, I do not think that I would call this an issue.  It is more of a fact of life when doing numerics.

Paul

**Comment by nonhermitian** [comment]
Closing this question as it is answered.
