### ISSUE TITLE
Discussion about Qutip's Options and settings

### ISSUE THREAD

**Issue by Ericgig** [qutip/qutip#1234]
@ajgpitch @jakelishman,
Moving the discussion we had last week here.

#### The `Options` object.
It contains the options used by the solvers:
-  Scipy's solver options (`atol`, `method`, ...)
-  Output (`store_states`, `average_states`, ...)
-  To deprecate (`rhs_reuse`, `ntraj`, ...)

But making the solver objects, I added new base solver (`solve_ivp`, `dop853`) which require new options. Eventually, using `dense` vs `sparse` matrix should also be added somewhere.
So I have a few issues about it:
1. Increasing number of options being confusing.
2. Some options are no longer used, or used only in specific solver. `seeds` is used by mcsolve, but the stochastic solver use a `noise` keyword arguments, not the options' value.
3. No way to change the default.

#### `qutip.settings`
It has some installation settings: `has_mkl`, `has_openmp` and some Qobj options, `auto_herm`, `auto_tidyup_atol`.
I am adding a new value: `path`, which set the path to where the compiled string code are saved. Here also there is no easy way to change the default. If it was possible, I would have the default matrix data type set here.

#### `qutiprc`
File saved in the users home "~/.qutip/qutiprc". If qutip is installed with openmp, it contains the matrix size over which it is worth to use the openmp version of spmv.
Under used.

I would propose:
- A function in settings that save a new default to qutiprc.
- Something similar for options.
- Splitting the options object into a few ones: output options, solver options, mcsolver options?

**Comment by jakelishman** [comment]
Implemented in #1289 (partial for `master`) and in #1337 (for `dev.major`).
