### ISSUE TITLE
ptrace called on non-composite object fails

### ISSUE THREAD

**Issue by liorella** [qutip/qutip#1239]
**Describe the bug**
calling ptrace(0) should simply return the object. Instead it fails with an error

**To Reproduce**
import qutip as qp
qp.sigmax().ptrace(0)

**Expected behavior**
expect it to return the existing object

**Your Environment**
QuTiP Version:      4.5.0
Numpy Version:      1.18.1
Scipy Version:      1.4.1
Cython Version:     0.29.16
Matplotlib Version: 3.2.1
Python Version:     3.7.6
Number of CPUs:     8
BLAS Info:          Generic
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Windows (AMD64)
Installation path:  C:\Users\Lior Ella\scoop\apps\miniconda3\4.5.12\envs\tfenv\lib\site-packages\qutip

**Comment by nathanshammah** [comment]
`qutip.ptrace()` takes the partial trace. It is defined only on composite Hilbert spaces. You are applying it on a single Hilbert space, hence it gives an error. If you want to take the trace, you could call it with `qp.sigmax().tr()`.
