### ISSUE TITLE
UnboundLocalError:local variable 'e' referenced before assignment

### ISSUE THREAD

**Issue by TakumiAizawa** [qutip/qutip#1244]
**Describe the issue**
I tried to Execute the code "Time-dependent master equation: Landau-Zener transitions" in QuTiP HP's Example notebooks(http://nbviewer.ipython.org/github/qutip/qutip-notebooks/blob/master/examples/landau-zener.ipynb) ,and I get the following error message. 
Could someone help please?

Error message:
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-7-f9c1fc837f05> in <module>
      1 start_time = time.time()
----> 2 p_ex = qubit_integrate(delta, eps0, A, omega, gamma1, gamma2, psi0, tlist, "dynamics")
      3 print('dynamics: time elapsed = ' + str(time.time() - start_time))

<ipython-input-5-8172adafcb2d> in qubit_integrate(delta, eps0, A, omega, gamma1, gamma2, psi0, tlist, option)
     33     if option == "dynamics":
     34         # evolve and calculate expectation values
---> 35         output = mesolve(H, psi0, tlist, c_op_list, [sm.dag() * sm], H_args)
     36 
     37         return output.expect[0]

~\Anaconda3\lib\site-packages\qutip\mesolve.py in mesolve(H, rho0, tlist, c_ops, e_ops, args, options, progress_bar, _safe_mode)
    252         ss = H
    253     elif isinstance(H, (list, Qobj, QobjEvo)):
--> 254         ss = _mesolve_QobjEvo(H, c_ops, tlist, args, options)
    255     elif callable(H):
    256         ss = _mesolve_func_td(H, c_ops, rho0, tlist, args, options)

~\Anaconda3\lib\site-packages\qutip\mesolve.py in _mesolve_QobjEvo(H, c_ops, tlist, args, opt)
    298 
    299     nthread = opt.openmp_threads if opt.use_openmp else 0
--> 300     L_td.compile(omp=nthread)
    301 
    302     ss = SolverSystem()

~\Anaconda3\lib\site-packages\qutip\qobjevo.py in compile(self, code, matched, dense, omp)
   1557                                                         self.args,
   1558                                                         self.dynamics_args,
-> 1559                                                         self.tlist)
   1560                     coeff_files.add(file_)
   1561                     self.coeff_files.append(file_)

~\Anaconda3\lib\site-packages\qutip\qobjevo_codegen.py in _compiled_coeffs(ops, args, dyn_args, tlist)
    122     code = _make_code_4_cimport(ops, args, dyn_args, tlist)
    123     coeff_obj, filename = _import_str(code, "cqobjevo_compiled_coeff_",
--> 124                                       "CompiledStrCoeff", True)
    125     return coeff_obj(ops, args, tlist, dyn_args), code, filename
    126 

~\Anaconda3\lib\site-packages\qutip\qobjevo_codegen.py in _import_str(code, basefilename, obj_name, cythonfile)
     80     if not import_list:
     81         raise Exception("Could not convert string to importable function, "
---> 82                         "tmpfile:" + try_file + ext) from e
     83     coeff_obj = import_list[0]
     84     return coeff_obj, try_file + ext

UnboundLocalError: local variable 'e' referenced before assignment

------------------------------------------------------
Software	Version:
QuTiP	4.5.0
Numpy	1.18.1
SciPy	1.4.1
matplotlib	3.1.3
Cython	0.29.15
Number of CPUs	4
BLAS Info	INTEL MKL
IPython	7.12.0
Python	3.7.6 (default, Jan 8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
OS	nt [win32]
Sat May 02 19:27:58 2020 ???? (?W???)
-------------------------------------------------------

**Comment by jakelishman** [comment]
Hi!

This was a bug in the main library and has been fixed in #1199, which will make its way into a new version of QuTiP in the near future.

**Comment by TakumiAizawa** [comment]
Thank you so much!

Does it mean that the bug is fixed in a new version of QuTiP ?

**Comment by BoxiLi** [comment]
Hi @TakumiAizawa, yes in a future QuTiP release this will be fixed. If you need to use this right now, I would recommend downloading the code from GitHub and install from source code. http://qutip.org/docs/latest/installation.html#installing-from-source

**Comment by TakumiAizawa** [comment]
Thank you!
I'm going to do it the way you taught me to do it!
