### ISSUE TITLE
solver c_ops callback function

### ISSUE THREAD

**Issue by lfry512** [qutip/qutip#1254]
Dear qutip developers,

In the documentation of version 4.5 the c_ops argument is said to support callback functions, however they are not implemented in that version and as far as I can tell neither in the current branch. It would be nice to have this feature added to allow for arbitrary time-dependent Lindbladians to be implemented. There are cases where Lindbladians cannot simply be described as the product of a time-dependent scalar and a time-independent Lindbladian, this is where the callback becomes useful.

I envisage a single callback passed to c_ops as being useful, where the user has to manually add multiple decoherence channels. This way, arbitrary data can be passed through the args parameter of the callback to build the operators at a given time step. I believe this would also allow channel cross-correlations to be implemented too.

I have hacked my local copy of qutip 4.5 to check this can in principle be done with mesolve, and it has worked. Here is a link to a patch file that shows the changes I made to get this working:
https://pastebin.com/iZCgBbNQ

I am happy to add this functionality properly to a clone and make a pull request.

**Comment by Ericgig** [comment]
The recently released v5 support callback for `c_ops`.
