### ISSUE TITLE
specifying a folder for temporary pyx files

### ISSUE THREAD

**Issue by petergthatsme** [qutip/qutip#1259]
It would be great if it were possible to specify where the temporary pyx (and other?) files are stored during a cython build. At the moment when one runs mesolve, the pyx files (and maybe others?) get written in the current working folder. Therefore running mesolve with some parameter scan (say with multiprocessing), results in *many* temp files that something like dropbox has to struggle in the background to process. 

I can tell from those around me this happens to be an extremely common use case; i.e. most people are using dropbox or the like to backup their files.

I would think the easiest thing to do might be to have an ENV variable, like, say QUTIP_BUILD_FOLDER that could dictate where this happens. Alternatively setting the default to system's tmp folder would be a good alternative. 

I've looked in docs, and can't see anything like that; please let me know if i missed it.

**Comment by Ericgig** [comment]
The options is in development ( #1231 ) , the options will be set in the qutiprc file. However it will probably not be released before end of fall if not winter.

**Comment by petergthatsme** [comment]
Good to know this is on your radar. Thanks.

**Comment by jakelishman** [comment]
This is implemented in the development branch for the next major release of QuTiP, but likely won't appear in the 4.x branch.
