### ISSUE TITLE
Result.states in essolve

### ISSUE THREAD

**Issue by cphenicie** [qutip/qutip#1262]
I am unable to find the list of states returned by the essolve function

For example:

```python
import qutip as qt
test = qt.essolve(qt.qeye(2), qt.ket2dm(qt.basis(2, 0)), [1,2,3], c_op_list=[], e_ops=[])
```
Returns the message
```
Result object with essolve data.
--------------------------------
states = True, expect = True
num_expect = 0, num_collapse = 0
```
but if I try to access the states
```
test.states
>>> []
```
Should this contain a list of states like mesolve()? It seems a similar issue has been raised before: https://groups.google.com/forum/#!topic/qutip/st3i6STPrQY

Here's my environment details:

```
QuTiP: Quantum Toolbox in Python
================================
QuTiP Version:      4.5.0
Numpy Version:      1.16.4
Scipy Version:      1.1.0
Cython Version:     0.27.3
Matplotlib Version: 2.1.2
Python Version:     3.6.4
Number of CPUs:     4
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Windows (AMD64)
Installation path:  C:\Users\chris\Anaconda3\lib\site-packages\qutip
============================================
```

**Comment by jakelishman** [comment]
Yeah, looking at it, this functionality still does not exist.  The `essolve` function is pretty out-of-date (its last real activity was back in 2013), and may well be completely deprecated in an upcoming version of QuTiP.

Hopefully `qutip.mesolve` should be a near drop-in replacement for you (`c_ops_list` is now called `c_ops`, but other than that you're fine), and it may well be a lot faster as well.

@Ericgig, @ajgpitch: shall we commit to maintaining `essolve` and/or the `eseries` class, or issue a deprecation warning as soon as possible?  They're pretty unloved, and `QobjEvo` really is a far far more general way of specifying time-dependence.  My vote (should I have one) is for deprecation.

I'm always in favour of slimming down codebases if it doesn't remove useful functionality!

**Comment by jakelishman** [comment]
Come to think of it, neither `eseries` nor `essolve` have significant tests, and a quick `grep` through shows that `eseries` is completely untested, and `essolve` has only one very basic test.

**Comment by jakelishman** [comment]
Closing now as `essolve` and `eseries` will be removed in 5.0, and we'll issue deprecation warnings soon.  We're unlikely to backport a fix to the 4.x branch since it would require developer time that we unfortunately just don't have to support a very old, little-used function.  Sorry about that!
