### ISSUE TITLE
Mesolve function returns wrong result using default Ode method

### ISSUE THREAD

**Issue by ZhiwenZong** [qutip/qutip#1265]
**Describe the bug**

In single qubit simulation, we are trying to apply the same gate sequence as experimentation.
Seq1: pi/2 pulse (20ns) -> pi/2 pulse (20ns)
Seq2: pi/2 pulse (20ns) -> wait(50ns) -> pi/2 pulse (20 ns)
The result of excited state probability is wrong for the seq2, with only Pe = 0.5, but we expect Pe=1.0.

I assume there are something imperfect with the original ODE algorithm.
If I use a self-written **fast propagation** method descriped by a master or liouville equation, I can get the expected vaule. 

**To Reproduce**
```
# Qutip simulation
import numpy as np
import matplotlib.pyplot as plt
import qutip as qu

T1, T2 = float('inf'), float('inf')  # coherence time
piLen = 20
piAmp = np.pi*1.0/20
psi0 = qu.basis(2, 0)

# basic Hamiltonian
Hsys = {}
Hsys['Hq'] =  qu.Qobj(np.diag([0, 0]), dims=[[2], [2]])
Hsys['Hc_x'] = qu.sigmax()
# dissipation
Hsys['Hlbld'] = [np.sqrt(1./T1)*qu.destroy(2),
                 np.sqrt(2./T2)*qu.num(2)]

# Control pulse
def cosine_pulse(t, t0=piLen/2.0, amp=piAmp, w=piLen, phase=0, df=0):
    x = t - t0
    return amp * 0.5 * (1+np.cos(2*np.pi*x/w)) * ((x+w/2.)>0) * ((-x+w/2.)>0) * \
        np.exp(1j*phase- 2j*np.pi*df*x)

c_x = lambda t, arg: cosine_pulse(t, t0=piLen/2.0, amp=0.5*piAmp)+\
    cosine_pulse(t, t0=1.0*piLen+piLen/2.0, amp=0.5*piAmp)


c_x_bug = lambda t, arg: cosine_pulse(t, t0=piLen/2.0, amp=0.5*piAmp)+\
    cosine_pulse(t, t0=3.0*piLen+piLen/2.0, amp=0.5*piAmp)

pulse_set = [c_x, c_x_bug]
bloch_set = []

def test_mesolve(time_test=np.arange(0,100,0.5), show_seq=True, bloch=True):
    if show_seq:
        plt.figure(figsize=(10,5))
        for idx, name in zip(range(len(pulse_set)), ['c_x', 'c_x_bug']):
            plt.subplot(len(pulse_set),1,idx+1)
            plt.plot(time_test,pulse_set[idx](time_test,None),label=name)
            plt.legend(loc=1)
        plt.xlabel('time')
        plt.show()

    for idx, name in zip(range(len(pulse_set)), ['c_x', 'c_x_bug']):
        H = [Hsys['Hq'],[Hsys['Hc_x'], pulse_set[idx]]]
        result = qu.mesolve(H, psi0, time_test, Hsys['Hlbld'],
                        [qu.sigmax(), qu.sigmay(), qu.sigmaz()],
                        progress_bar=None, options=None)
        b = qu.Bloch()
        b.clear()
        Pg, Pe = [], []
        qu_blochs = result.expect
        plt.title('probability of excited state')
        for i,j,k in zip(qu_blochs[0],qu_blochs[1],qu_blochs[2]):
            points = [i,j,k]
            b.add_points(points)
            P0, P1 = (1+k)/2.0, (1-k)/2.0
            Pg.append(P0)
            Pe.append(P1)
        plt.subplot(len(pulse_set),1,idx+1)
        plt.plot(time_test, Pe, label=name)
        plt.legend(loc=1)
        bloch_set.append(b)
    plt.xlabel('time')
    plt.show()
    if bloch:
        bloch_set[0].show()
        bloch_set[1].show()
    return result

# to run the test:
test_mesolve(time_test=np.arange(0,100,0.5), show_seq=True, bloch=False)
```

The terminal out put is
```
![sequence](https://user-images.githubusercontent.com/41005903/82047831-11976380-96e6-11ea-869d-7278ba1cbeaa.png)
![probability](https://user-images.githubusercontent.com/41005903/82047837-12c89080-96e6-11ea-98d6-0ba6528a50ad.png)
```

**Expected behavior**
As discussed above.

**Your Environment**

QuTiP: Quantum Toolbox in Python
Copyright (c) 2011 and later.
A. J. Pitchford, P. D. Nation, R. J. Johansson, A. Grimsmo, and C. Granade

QuTiP Version:      4.3.1
Numpy Version:      1.15.2
Scipy Version:      1.1.0
Cython Version:     0.28.4
Matplotlib Version: 3.0.3
Python Version:     3.5.5
Number of CPUs:     8
BLAS Info:          INTEL MKL
OPENMP Installed:   False
INTEL MKL Ext:      True
Platform Info:      Windows (AMD64)
Installation path:  D:\anaconda\envs\py3.5\lib\site-packages\qutip

**Additional context**
This issue is the same bug mention by @xlelephant at #1038 , but after trying the tweaking option mentioned by @nwlambert , we still get the same error.

**Comment by xlelephant** [comment]
![image](https://user-images.githubusercontent.com/50734064/82048475-57086080-96e7-11ea-89e4-6fe3be0be787.png)

![image](https://user-images.githubusercontent.com/50734064/82048499-62f42280-96e7-11ea-9c69-0e03c8a9f54c.png)

**Comment by BoxiLi** [comment]
Maybe this will help, when I run the code, I get the following warning:
```
ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
```

**Comment by BoxiLi** [comment]
I find this error appears when the two pulses are separated by a distance d > 23.0017... Have no idea why...
```
c_x_bug = lambda t, arg: cosine_pulse(t, t0=piLen/2.0, amp=0.5*piAmp)+\
    cosine_pulse(t, t0=23.0018 + 1.0*piLen+piLen/2.0, amp=0.5*piAmp)
```
The generated `QuobjEvo` seems to be correct. 

If I change the `[Qobj, func]` representation to `[Qobj, np.array]`, the same thing appears but with a different threshold. 

The bug disappears if I give an epsilon small value to the pulse, like 0.000001, instead of 0.

```
def cosine_pulse(t, t0=piLen/2.0, amp=piAmp, w=piLen, phase=0, df=0):
    ...
    return ... + 0.000001
```

Does this somehow ring a bell @Ericgig? Is this possible that the algorithm terminates if the coefficients are all zero for a while?

**Comment by Ericgig** [comment]
We had an issue like this in the past. If it is what I believe, the ODE use variable step, when nothing happens, these step can become very long and skip over the pulse. The option max_step can limit this step, so it should be set to be shorter than the shortest pulse.
Here I beleive that using `options=qu.Options(max_step=5)` in the solver call would fix it.
If it does not work, I can look in more details next week.

**Comment by xlelephant** [comment]
Thanks for your replies @BoxiLi @Ericgig , very helpful!

The output seems right after adding the `max_step` option to mesolve().
We changed the width of the cosine shaped pulse, here are some simple observations.
```
if width = 20, then setting max_step < 27 can produce the correct answer.
if width = 50, then setting max_step < 70 can produce the correct answer.
if width = 100, then setting max_step < 130 can produce the correct answer.
```

But as we are most caring about how to use the solvers correctly, we still have some doubts:
1. We only observed two results, one is 'perfectly correct', and another is 'totally wrong' (Like @Ericgig said, the second pulse has been completely skipped over). Would some fault result in the middle happen? Some wrong result very similar to the correct would be even worse.

2. The Ode version of mesolve function is very fast, which is one of the reasons we love it. But we did not find document about other solvers (raw propagator, flatten to Liouville space?) for the master equation. Could you explain why the ODE method is the best over others, in aspect of accuracy and speed?

**Comment by nonhermitian** [comment]
When doing pulse type simulations, it is best to set the max_step size to be half the width of the smallest pulse in the simulation.  This makes sure that pulses do not get over stepped.

Propagators are unitaries.  To compute them you need to evolve all basis vectors.  In addition, it is normal to get a dense matrix for the resulting unitary.  In contrast, canonical Hamiltonians are usually quite sparse, and the computing the evolution is quick sparse matrix - dense vector multiplication.

**Comment by jakelishman** [comment]
Closing for now as the fix is not something QuTiP can detect - we need to have `max_step` to a suitable value to know how stiff the input is.  If there's further discussion we need to have, let's talk about it more in other issues / the Google groups discussion boards.
