### ISSUE TITLE
Consider changing issue / PR template

### ISSUE THREAD

**Issue by nathanshammah** [qutip/qutip#1266]
Currently, the issue template reads (for fearure requests):

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Similarly, for bug reports, one finds:

**Describe the bug**

**To Reproduce**
Please provide a minimal working example. For instance:

```python
from qutip import identity
print(identity(2))
```
The terminal out put is
```
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]
```

**Expected behavior**

**Your Environment**
Please use `qutip.about()` to get the information about your environment and paste it here.

**Additional context**

-------------
The slight hiccup I find with these great templates introduced by @BoxiLi, especially in the first case above, is that many sub-titles  need to be deleted by the user and are not uniform in the end. Something more standard could be achieved by clearly stating what lines should be removed by the user and are just explanations, and what are to be kept in the structure. Sometimes simply rewording the titles could help. For example:
From
```
**Describe the solution you'd like**
A clear and concise description of what you want to happen.
```
To something like
```
**Feature Request Description**
+++ remove this line and the text example below
**Describe the solution you'd like**
A clear and concise description of what you want to happen.
+++ remove this line and the text example above
```
or something like that. Similarly, 
```
**Describe the bug** 
```
could become
```
**Bug description** 
```
and so on.

**Comment by nathanshammah** [comment]
Maybe I am interpreting the template wrong, and the subtitles are meant to be kept as they are.

**Comment by Ericgig** [comment]
Maybe use comment that are seen only when writing:
`<!--` This would be invisible if not the code blocks `-->`

**Comment by BoxiLi** [comment]
Indeed, all subtitles are meant to be kept. But I agree that rewording the titles could help. I also like the idea to make the comment only visible when writing. What about
```
**Feature Request Description**
<!-- A clear and concise description of what you want to happen.-->
```

**Comment by Chasmiccoder** [comment]
Hi there!    @nathanshammah @BoxiLi 

Can I work on this?  
Hope these changes are okay...
