### ISSUE TITLE
Consider using pytest xdist in continuous integration

### ISSUE THREAD

**Issue by nathanshammah** [qutip/qutip#1267]
**Testing fails on several platforms**
In QuTiP 4.5.1, several `skipif`have been introduced to avoid build fail on Mac. Similarly, there are other issues related to robust random objects testing. 

**Describe the solution you'd like**
An option could be using [`xdist`](https://docs.pytest.org/en/3.0.1/xdist.html) to allow specifics of certain tests, as it seems to have, beyond parallelization, some potentially interesting multi-platform coverage.

**Comment by jakelishman** [comment]
I think `xdist` is about self-managing a distributed cluster for testing?  The little line at the bottom about "it effectively `rsync`s the code to the remote locations" certainly sounds like it, and those descriptions seem to match too.

I think the current `pytest.mark.skipif(...)` is fine - skipping based on the platform in use is actually one of the main examples in the documentation for that.

**Comment by jakelishman** [comment]
I'll close this for now, unless anyone wants to discuss it further.  I believe `xdist` is more if we were managing distributing testing runs manually on our own test runners.  The `skipif` would still be important even with `xdist` to decide which tests should run on which system.
