### ISSUE TITLE
Consider deprecation of eseries and essolve

### ISSUE THREAD

**Issue by jakelishman** [qutip/qutip#1281]
As part of the creation of the `core` package and the data layer, I'm hitting basically every single part of QuTiP, so I'm flagging parts we might want to consider for removal.

`eseries` is completely eclipsed by `QobjEvo`, so I think we can definitely get rid of that.  `essolve` is rather specific and not very used, I suspect.  We _could_ keep `essolve` without too much effort, but we should change the internals to use `QobjEvo` (though I also wouldn't be averse to removing it too).

@ajgpitch, @Ericgig, @nathanshammah.

**Comment by nathanshammah** [comment]
I agree that on top level, these may seldom be used. It is not straightforwardly clear what is the added value of removing them, if no one is complaining or they are not hard to maintain. It may make things cleaner, but I am not aware of the implications. `eseries` seems used in the correlation module, possibly (marginally) also in `expect`. 

If QobjEvo is a more modern way of applying`essolve`, that is fine with me, it would be nice to restructure it that way. My advice before switching to QobjEvo, is that its use is first well documented in the documentation's Users guide, which could be done by copy-pasting chuncks from the notebook.

**Comment by jakelishman** [comment]
`eseries` isn't really used by `correlation`, it's just a possible solver, and `expect` doesn't use it, it just currently has to support it.  Removing `eseries` would involve just removing that part of the solver.

`essolve` only functions with time-independent Hamiltonians anyway, and `QobjEvo` can represent a full superset of `eseries` operations, and is an awful lot faster at it too.  I agree that the documentation can definitely be improved - I'll be working on that later on in the project.

No-one's complaining about the difficult of maintaining them, because nobody _is_ maintaining them.  `eseries` hasn't been meaningfully touched since 2014, and there's been an issue recently (#1262) where somebody pointed out that `essolve` doesn't do really simple parts of its spec.

**Comment by jakelishman** [comment]
Removed in `dev.major` already.  We'll issue deprecation warnings in an upcoming 4.x branch.
