### ISSUE TITLE
Mistake in `qutip.liouvillian`

### ISSUE THREAD

**Issue by jond01** [qutip/qutip#1285]
**Describe the bug**
I think there is a mistake in the Hamiltonian's part inside the `liouvillian` function:
https://github.com/qutip/qutip/blob/c62a8e99f503b864933cd6bb31e259d47770b95a/qutip/superoperator.py#L122-L127

However, according to [Linblad equation](https://en.wikipedia.org/wiki/Lindbladian#Definition) it should be:
```python
         data = -1j * zcsr_kron(H.data, spI)
         data += 1j * zcsr_kron(spI, Ht)
```

**To Reproduce**
Comparison of qutip vs. numpy:

```python
import numpy as np
import qutip

n_H = 2  # the dimension of the Hilbert space

# qutip's liouvillian
H_qutip = qutip.sigmaz()
L_qutip = qutip.liouvillian(H_qutip, [])

# numpy's liouvillian
H_np = np.diag([1, -1])
L_np = -1j * (np.kron(H_np, np.eye(n_H)) - np.kron(np.eye(n_H), H_np.T))

# comparison
print('1. H_qutip == H_np:', np.array_equal(H_qutip, H_np))
print('2. L_qutip == L_np:', np.array_equal(L_qutip, L_np))
print('3. L_qutip == -L_np:', np.array_equal(L_qutip, -L_np))
```
The terminal out put is
```
1. H_qutip == H_np: True
2. L_qutip == L_np: False
3. L_qutip == -L_np: True
```
(The construction of the Liouvillian with numpy is based on eq. (A6) in:
https://arxiv.org/pdf/1909.11619.pdf#page=16)

**Expected behavior**
1 is True as expected.
2 should be True and 3 should be False, but the opposite happens because of the sign mistake.

**Your Environment**
```
QuTiP Version:      4.5.0
Numpy Version:      1.18.1
Scipy Version:      1.4.1
Cython Version:     0.29.15
Matplotlib Version: 3.1.3
Python Version:     3.7.6
Number of CPUs:     6
BLAS Info:          INTEL MKL
OPENMP Installed:   False
INTEL MKL Ext:      True
Platform Info:      Windows (AMD64)
```
(Probably irrelevant.)

**Additional context**
Please let me know that you approve the change in the description and I will make a quick PR.

**Comment by nathanshammah** [comment]
I think the current behaviour is fine, it just depends on the way the kronecker product is done in QuTiP. Pinging @nwlambert.

**Comment by nwlambert** [comment]
Yep, nathan is correct, if you check spre() and spost() as well you can see the convention qutip uses.  H in superoperator form acting from the left is given by spre(H) which is equivalent to  zcsr_kron(spI, H.data).

I think this choice was made early on to make it consistent with the quantum optics toolbox in Matlab.

Everytime i do this by hand I do it wrong (same with the ordering in turning states into vectors).

**Comment by jond01** [comment]
Hi @nathanshammah and @nwlambert, thanks for the quick replys!

Please let me inspect this a bit further, but I would like to hear what you think about the comparison, I still think the numpy's "by-hand" version is correct.

**Comment by nwlambert** [comment]
i think this difference comes because, if you look at equation A1 in Fabrizio's paper you linked, they do a row-ordering convention in turning states into vectors.

Qutip does a column ordering convention, as described here 
http://qutip.org/docs/latest/guide/guide-states.html#superoperators-and-vectorized-operators

this is an arbitrary choice, as long as you do it consistently with the definition of states and superoperators.  This means in our case -i[H, rho] gives -i[spre(H) -spost(H)] == -i zcsr_kron(spI, H.data) + 1j * zcsr_kron(Ht, spI).  

i think row ordering is more intuitive, but column ordering is what we do.

**Comment by jond01** [comment]
Indeed you are right, it turns out to be a matter of convention and everything is correct (`spre`, `spost`, `lindblad_dissipator`).

For multiple superoperators, I prefer using numpy because of its powerful broadcasting support.

Hopefully, this discussion will help anyone else facing a similar situation. Keep doing great!
