### ISSUE TITLE
Set point transparency on Bloch sphere

### ISSUE THREAD

**Issue by fretchen** [qutip/qutip#1287]
**Is your feature request related to a problem? Please describe.**
In our simulations we frequently run Monte-Carlo samples that would be great to visualize on the Bloch sphere. However, an alpha value would be very helpful.

**Describe the solution you'd like**
Bloch().add_points(pnt, alpha = 0.3)

**Describe alternatives you've considered**
Absolutely not sure.

**Additional context**
In a similiar fashion I wonder if colormaps etc would become possible.

**Comment by xspronken** [comment]
Hi! I'm working on this issue and was wondering if the alpha value should be an array-like that would apply to each point or vector individually, similarly to the color option I've seen in dev.major, or make it more simple. Where a single value would apply to all the rendered vectors or points in their add method.

**Comment by fretchen** [comment]
I personally would be actually a bit confused if the alpha values were array-like and the simple solution would certainly be enough for me. But then again I do not have the very big picture of `qutip`.
