### ISSUE TITLE
reversed definition for sigmam() and sigmap() ?

### ISSUE THREAD

**Issue by tesla-cat** [qutip/qutip#1294]
![image](https://user-images.githubusercontent.com/28215638/85133689-c389f880-b26d-11ea-9501-225ba741128e.png)

**Comment by nathanshammah** [comment]
@tesla-cat this is because of the convention between how the bosonic basis and the two-level-system ground states are set in the basis, as explained [here](http://qutip.org/docs/latest/guide/guide-states.html#qubit-two-level-systems) in the documentation.

**Comment by tesla-cat** [comment]
@nathanshammah  Thank you for the rapid reply!
