### ISSUE TITLE
qutip 4.5.0 tests fail when scipy 1.5.0 (released 8 days ago) is used

### ISSUE THREAD

**Issue by victoriaqc02** [qutip/qutip#1304]
**Describe the bug**
AttributeError: module 'scipy.sparse._sparsetools' has no attribute 'csr_matmat_pass1' 

**To Reproduce**
Install the latest version of scipy 1.5.0, install qutip, and run the tests. The following fail due to the AttributeError specified above:
- test_basis_transformation.py::test_transformations_from_qobj_and_direct_eigenbases_match[True-2-rand_bra]
- test_basis_transformation.py::test_transformations_from_qobj_and_direct_eigenbases_match[True-10-rand_bra]
- test_basis_transformation.py::test_transformations_from_qobj_and_direct_eigenbases_match[False-2-rand_bra]
- test_basis_transformation.py::test_transformations_from_qobj_and_direct_eigenbases_match[False-10-rand_bra]
- test_brtools.py::test_zheevr
I stopped running the tests after these errors appear, and I don't know if it causes other tests to fail as well.
The test_zheevr shows another error, but it fixes when using a previous version of scipy (e.g. 1.3). 

The terminal out put is
```
>       fn = getattr(_sparsetools, self.format + '_matmat_pass1')
E       AttributeError: module 'scipy.sparse._sparsetools' has no attribute 'csr_matmat_pass1'

/usr/local/lib/python3.6/dist-packages/qutip-4.5.0-py3.6-linux-x86_64.egg/qutip/fastsparse.py:197: AttributeError
```

**Your Environment**
QuTiP: Quantum Toolbox in Python
================================
Copyright (c) QuTiP team 2011 and later.
Original developers: R. J. Johansson & P. D. Nation.
Previous lead developers: Chris Granade & A. Grimsmo.
Current admin team: Alexander Pitchford, Paul D. Nation, Nathan Shammah, Shahnawaz Ahmed, Neill Lambert, and Eric Giguère.
Project Manager: Franco Nori.
Currently developed through wide collaboration. See https://github.com/qutip for details.

QuTiP Version:      4.5.0
Numpy Version:      1.19.0
Scipy Version:      1.3.0 (error fixed)
Scipy Version:      1.5.0 (error present)
Cython Version:     0.29.20
Matplotlib Version: 3.2.2
Python Version:     3.6.9
Number of CPUs:     4
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Linux (x86_64)
Installation path:  /usr/local/lib/python3.6/dist-packages/qutip-4.5.0-py3.6-linux-x86_64.egg/qutip
==============================================================================
Please cite QuTiP in your publication.
==============================================================================
For your convenience a bibtex reference can be easily generated using `qutip.cite()`

**Comment by jakelishman** [comment]
Thanks for reporting this. We've already fixed it in `master`, but haven't yet pushed a new patch release out. We hope to do that soon.

You can temporarily work around it by installing SciPy 1.4 in your QuTiP environment, or building QuTiP from the latest source.

**Comment by nathanshammah** [comment]
Should be closed by QuTiP [v. 4.5.2](https://github.com/qutip/qutip/releases/tag/v4.5.2), just released.
