### ISSUE TITLE
Docstring for Variable Returns!

### ISSUE THREAD

**Issue by sarsid** [qutip/qutip#1305]
Topic:

The `measure(state, ops)` and `measurement_statistics(state, ops)` functions in the measurement PR #1274 have different return types based on whether `ops` is a single observable or a list of POVMs. For e.g. the `measurement_statistics` returns
 
>  eigenvalues: List of floats
        The list of eigenvalues of the measurement operator.
    eigenstates_or_projectors: List of Qobj
        If the state was a ket, return the eigenstates of the measurement
        operator. Otherwise return the projectors onto the eigenstates.
    probabilities: List of floats
        The probability of measuring the state as being in the
        corresponding eigenstate (and the measurement result being
        the corresponding eigenvalue).

if `ops` is an observable and 
  
> collapsed_states : List of Qobjs
                    the collapsed states (density matrices) obtained after
                    measuring the qubits and obtaining the
                    qubit specified by the target in the state
                    specified by the index.
    probabilities : List of floats
                    the probability of measuring a state in a the state
                    specified by the index.

if `ops` is a list of POVMs/PVMs. Is there a good way to specify a numpy docstring for the function given that the return variables can vary !

**Comment by sarsid** [comment]
It was decided to describe the returns summarily in the dosctring for `measurement_statistics` and refer to the `measurement_statistics_povm` and `measurement_statistics_observable` functions returns (in the respective docstrings). Similarly for the `measure` function!

**Comment by BoxiLi** [comment]
Just for the future reference, I found this example in NumPy: https://numpy.org/doc/stable/reference/generated/numpy.unique.html
