### ISSUE TITLE
fileio tests are failing on windows

### ISSUE THREAD

**Issue by BoxiLi** [qutip/qutip#1311]
**Describe the bug**
`test_fileio` is failing on Windows because this use of `tempfile.NamedTemporaryFile` doesn't work on windows. The temporary files cannot be opened twice on Windows according to https://docs.python.org/3.8/library/tempfile.html#tempfile.NamedTemporaryFile.
https://github.com/qutip/qutip/blob/9e82f5b81955952833e25bb3eeff3fa24d36556b/qutip/tests/conftest.py#L194-L197
followed by
https://github.com/qutip/qutip/blob/9e82f5b81955952833e25bb3eeff3fa24d36556b/qutip/fileio.py#L70
results in a permission error.

**To Reproduce**
Run `test_fileio.py` on windows.

**Your Environment**
QuTiP Version:      4.6.0.dev0+6ad7f2b8
Numpy Version:      1.18.2
Scipy Version:      1.4.1
Cython Version:     0.29.20
Matplotlib Version: 3.2.1
Python Version:     3.7.2
Number of CPUs:     12
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Windows (AMD64)

Do you have any idea on a replacement @jakelishman ?

**Comment by jakelishman** [comment]
Ugh, Windows sucks soooo much.  Is that the only test that fails because of it?

**Comment by BoxiLi** [comment]
Yeah, the `fileio` test is the only one. `tempfile` is also only used there (sofar).

**Comment by jakelishman** [comment]
Hopefully #1311 should fix it, then.
