### ISSUE TITLE
ptrace inconsistent between sparse and dense

### ISSUE THREAD

**Issue by jakelishman** [qutip/qutip#1325]
`Qobj.ptrace` is inconsistent between `sparse=True` and `sparse=False` arguments if the selection arguments are not in order:

```python
>>> import qutip
>>> a, b, c = qutip.rand_ket(2), qutip.rand_ket(3), qutip.rand_ket(4)
>>> sparse = qutip.tensor(a, b, c).ptrace([2, 1], sparse=True)
>>> dense = qutip.tensor(a, b, c).ptrace([2, 1], sparse=False)
>>> sparse.dims == dense.dims
False
>>> sparse.dims
[[4, 3], [4, 3]]
>>> dense.dims
[[3, 4], [3, 4]]
```

I'm fairly sure the only problem is that the dimensions come out incorrectly - for separable states, we find
```python
>>> ptraced = qutip.tensor(a, b, c).ptrace([2, 1])
>>> built = a.proj().tr() * qutip.tensor(b.proj(), c.proj())
>>> np.allclose(ptraced.full(), built.full())
True
```
which is also consistent with `_ptrace_dense` (which sorts `sel`).

Pretty sure the solution is just to sort `sel` on input, but wanted to check with @Ericgig.

**Comment by jakelishman** [comment]
Also, I was just quickly searching for a quick-and-dirty "obviously correct" method of doing the partial trace to use as the test case (rather than keeping around a legacy Cython version just to test against), and found [this StackOverflow answer](https://scicomp.stackexchange.com/questions/27496/calculating-partial-trace-of-array-in-numpy) which has like 3 people telling someone "don't do it yourself, just use QuTiP"!  Pretty neat!

**Comment by Ericgig** [comment]
I looked at the documentation and there is no mention about which is expected.

But sparse seems in the wrong here since only the dims are switched, not the data.
I would have expected:
```
ptraced = qutip.tensor(a, b, c).ptrace([2, 1])
built = a.proj().tr() * qutip.tensor(c.proj(), b.proj())
ptraced == built
```
Yes, just sorting `sel` seems appropriate.
