### ISSUE TITLE
Bug in `rand_unitary` function

### ISSUE THREAD

**Issue by araza6** [qutip/qutip#1327]
**Describe the bug**
For a unitary matrix, U:
UU^{\dagger} = I or U^{\dagger}U = I

This does not quite happen with QuTiP's `rand_unitary`

**To Reproduce**

```python
from qutip import rand_unitary
rand_unitary(3)*rand_unitary(3).dag()
```
The terminal output is not an identity matrix.

**Comment by sarsid** [comment]
I think this is because it is generating two different unitaries in this case. What your (probably) want is:

`from qutip import rand_unitary
U = rand_unitary(3)
A*A.dag()`

This gives me the expected result locally!

**Comment by araza6** [comment]
Oops, that's right. Closing this
