### ISSUE TITLE
problems with running 'mcsolve' in .py file

### ISSUE THREAD

**Issue by sa14004049** [qutip/qutip#1343]
I am using the function 'mcsolve'. I encounter a problem: when I run it in the jupyter (i.e., run the .ipynb file), everything is fine,
and I get the right result. But when I export this file as an executable file (i.e., .py), and run it in an IDE (I am using Spyder), I get into trouble.
The IDE keeps running, and never stop to give an answer. It looks like it is stuck at somewhere.
The following is my code, could anyone help?

> from qutip import *
import numpy as np
import matplotlib.pyplot as plt
tlist=np.linspace(0,40,4001)
N=2 # number of basis states to consider
psi0=1/(np.sqrt(2))*(basis(2,1)+basis(2,0))
gamma=1/10
omega=0
sigp=destroy(N)
sigm=sigp.dag()
cp=np.sqrt(gamma)*sigp
cm=np.sqrt(gamma)*sigm
hopt=-omega/2*sigmax()
obs=fock_dm(2,0)
**mc=mcsolve(hopt,psi0,tlist,cm,obs,1)**
plt.plot(tlist,mc.expect[0])

**Comment by BoxiLi** [comment]
Hi, sorry for the late reply. It is known that `mcsolve` have some problem on Windows (and probably also on Mac?) that the code freezes. Did you solve your problem? Your code runs fine on my computer, however. Could you type in your python console `qutip.about()` and copy the result here? More information will be helpful.

**Comment by sa14004049** [comment]
Hi, thanks for the reply! My solution is never use spyder again, just use jupyter... and it works fine for me. :-)
The following is what I get after running qutip.about():
QuTiP: Quantum Toolbox in Python
================================
Copyright (c) QuTiP team 2011 and later.
Original developers: R. J. Johansson & P. D. Nation.
Previous lead developers: Chris Granade & A. Grimsmo.
Current admin team: Alexander Pitchford, Paul D. Nation, Nathan Shammah, Shahnawaz Ahmed, Neill Lambert, Eric Giguère, and Boxi Li
Project Manager: Franco Nori.
Currently developed through wide collaboration. See https://github.com/qutip for details.

QuTiP Version:      4.5.2
Numpy Version:      1.19.1
Scipy Version:      1.2.0
Cython Version:     0.29.12
Matplotlib Version: 3.1.0
Python Version:     3.7.3
Number of CPUs:     4
BLAS Info:          INTEL MKL
OPENMP Installed:   True
INTEL MKL Ext:      True
Platform Info:      Windows (AMD64)
Installation path:  D:\python1\lib\site-packages\qutip
==============================================================================
Please cite QuTiP in your publication.
==============================================================================
For your convenience a bibtex reference can be easily generated using `qutip.cite()`

**Comment by BoxiLi** [comment]
Glad to hear that the problem was solved!
