### ISSUE TITLE
Precision control of photocurrent_mesolve's solver

### ISSUE THREAD

**Issue by LoserWu** [qutip/qutip#1357]
Hi, I'm wondering if it's possible to control the precision of 'predictor-corrector' solver of the photocurrent_mesolve? Seems like the 'tol' has no effect on the 'predictor-corrector' solver.

Here's my code. I was trying to use stochastic master equation to generate the outcome photon sequence from a CPT set up, but I got a diverged outcome sometimes.

```
from qutip import *
import matplotlib.pyplot as plt
import numpy as np
import matplotlib as mpl


params = {
	'axes.labelsize': 12,
	'legend.fontsize': 10,
	'xtick.labelsize': 10,
	'ytick.labelsize': 10,
	'figure.figsize': [3*1.4/1.2, 2.8/1.2],#2.3
	'lines.linewidth' : 1,
	'axes.linewidth':0.9,
	'figure.subplot.left':0,
	'figure.subplot.right':1,
	'figure.subplot.bottom':0,
	'figure.subplot.top':1,
	'grid.linestyle':'--',
	'axes.grid':False,
	"font.family":"serif",
	"xtick.direction":"in",
	"ytick.direction":"in",

	}
mpl.rcParams.update(params)


T = 100
N = 100000
Gamma = 2*np.pi*13
Omega = 2*np.pi*2

times = np.linspace(0,T,N)
ge = fock(3, 0) * fock(3, 1).dag()
se = fock(3, 2) * fock(3, 1).dag()
ss = fock(3, 2) * fock(3, 2).dag()
ee = fock(3, 1) * fock(3, 1).dag()
dark = (fock(3, 2) - fock(3, 0)).unit()
dd = dark*dark.dag()


bias = 2*np.pi*0.1

psi0 = dark

H = Omega * (ge + ge.dag() + se + se.dag()) + bias*ss

result_sme = photocurrent_mesolve(H, psi0, times, c_ops = [],sc_ops = [np.sqrt(Gamma/2)*ge + np.sqrt(Gamma/2)*se]\
	, e_ops = [dd, ee], store_measurement=True, options=Options(store_states=True), nsubsteps=100, \
	solver='predictor-corrector')

hermitian = [(result_sme.states[0][i]).isherm for i in range(N)]

plt.plot(times, result_sme.expect[0], color = 'orange', label='dark')
plt.plot(times, result_sme.expect[1], color = 'black', label='e')
plt.plot(times, hermitian, color = 'blue')
plt.xlim(0,100)
plt.xlabel('Time')
plt.ylabel('Population')
plt.savefig('sme.pdf',bbox_inches='tight',pad_inches=0)
plt.close()

```
And the result,
[sme.pdf](https://github.com/qutip/qutip/files/5207120/sme.pdf)
(The decline of the blue curve means the density matrix is no longer Hermitian thus diverge.)

**Comment by Ericgig** [comment]
The stochastic ode solver are not smart and do not adjust the step to meet a desired tolerance. You can manually increase the precision by increasing the number of sub-steps `nsubsteps`. 
Since you don't have any c_ops, see if you can use mcsolve instead. It accept `atol `and `rtol `options and you should be able to rebuild the measurement from the collapse.

**Comment by LoserWu** [comment]
Thanks for your suggestion! I tried to increase the sub-steps, but the optimal (a tradeoff between precision and speed) `nsubsteps` is very sensitive to the parameter of the Hamiltonian (bias). To simulate a time-dependent bias, I have to set an extremely large `nsubsteps` then practical unable to complete. Mcsolve works perfect for this setup, but I also want to add some extra c_ops later. I would like to ensure if the `nsubsteps` is the only way to control the precision? If so, I will make things simpler and use mcsolve.

**Comment by Ericgig** [comment]
Yes `nsubsteps` and `tlist` are the only way to control precision with `photocurrent_mesolve`, `mcsolve` does not support a mix of `c_ops` and `sc_ops` so if both of them are needed `photocurrent_mesolve` is your only option available.

**Comment by LoserWu** [comment]
Thanks, this answers my question.
