### ISSUE TITLE
Steadystate function for a time-dependent Hamiltonian

### ISSUE THREAD

**Issue by albertomercurio** [qutip/qutip#1377]
**Describe the issue**
Hello,
I'm studying the classical case of a driven qubit, and i want to know the steady state of the system.

**To Reproduce**
I declared the following Hamiltonian
```python
H_0 = 0.5 * h * w_eg * sigmaz()
H_1 = A * sigmax()
def H_1_t(t, args):
    return cos(w * t)

H = [H_0, [H_1, H_1_t]]
```
but using `rho_ss = steadystate(H, c_ops)` returns the error
```
TypeError: Solving for steady states requires Liouvillian (super) operators
```
This implies that i can't see the spectrum through `spectrum(H, w, c_ops, sigmap(), sigmam())` because it calculates the steady state first, and so returns the same error.
A way to do that is by calculating the propagator and then the FFT of the correlation function
```python
U = propagator(H, 2 * pi / w, c_ops)
rho_ss = propagator_steadystate(U)
rho_ss
corr = correlation_2op_1t(H, rho_ss, t, c_ops, sigmap(), sigmam())
wlist1, spec1 = spectrum_correlation_fft(t, corr)
```

Of course using `steadystate(H, c_ops)` function is much simpler and straightforward, and my question is if is it normal that `steadystate(H, c_ops)` returns error.

**Comment by Ericgig** [comment]
`steadystate` does not support time dependent Hamiltonian. It sees that H is a list, not a Qobj, then fails.

**Comment by tehruhn** [comment]
@nwlambert didn't we fix this by natively allowing time dependent Hamiltonians in our solver? Maybe we should mention the repo here since it's relevant.

**Comment by nwlambert** [comment]
Unfortunately it doesn't really help here for the steady state stuff. I
guess generally speaking systems which are strongly driven don't have a
steady state in the normal sense, however periodic driving sometimes leads
to periodic steady states.

I guess propagator_steadystate calculated the rho which satisfies

U(t)rho= rho ?

Given that in the original code snippet t=2 pi/w I suppose this gives one
part of the potentially periodic solution? (Though if the driving is weak
and on resonance this periodic oscillation will be a small modulation on
top of the rwa result)

As for calculating the spectrum, I am not sure. I guess
s I would argue that the steady state used as the initial condition in the
correlation function should be the average of the periodic steady state
over one period?
