### ISSUE TITLE
Bloch sphere deformed for matplotlib >= 3.3.0

### ISSUE THREAD

**Issue by steffen-mdv** [qutip/qutip#1385]
**Describe the bug**
When plotting the Bloch sphere with qutip and matplotlib >=3.3.0 the sphere appears deformed in z-direction.
This is a result of a change in matplotlib Axes3D: https://matplotlib.org/3.3.0/users/whats_new.html#d-axes-improvements

**To Reproduce**

```python
import qutip
b = qutip.Bloch()
b.show()
```

**Work around**
1) downgrade to matplotlib 3.2.2
or
2) set aspect ratio manually
```python
import qutip
b = qutip.Bloch()
b.show()
if hasattr(b.axes, 'set_box_aspect'):
    b.axes.set_box_aspect([1,1,1])
```

**Environment**
QuTiP Version:      4.5.2
Numpy Version:      1.19.2
Scipy Version:      1.5.2
Cython Version:     0.29.21
Matplotlib Version: 3.3.2
Python Version:     3.7.9
Number of CPUs:     6
BLAS Info:          INTEL MKL
OPENMP Installed:   False
INTEL MKL Ext:      True
Platform Info:      Linux (x86_64)

**Comment by paniash** [comment]
This is an issue with `matplotlib` rather than `QuTiP`. A possible workaround is downgrading to version 3.2.2.

**Comment by jakobjakobson13** [comment]
The underlying reason is that matplotlib made some [changes](https://matplotlib.org/3.3.0/users/whats_new.html#axes3d-no-longer-distorts-the-3d-plot-to-match-the-2d-aspect-ratio) in the `Axes3D` module.
