### ISSUE TITLE
unsuccessful installing qutip on CentOS8 

### ISSUE THREAD

**Issue by ZahraQI** [qutip/qutip#1391]
After installing qutip, in order to test qutip installation, I type "python" in terminal and then type "import qutip.testing as qt", getteing to the following error.

import qutip.testing as qt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'qutip'
>>> qt.run()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'qt' is not defined

If anyone can help to solve the problem?
Thanks

**Comment by quantshah** [comment]
Hi, are you sure you are not in the QuTiP folder when you start your Python
interpreter? Please provide some information as to how you installed QuTiP.
Which Python version are you using?

You can just type the command

>> which python

To find out the Python you are using. I would suggest the best way to run
QuTiP is using the conda installation.

**Comment by BoxiLi** [comment]
It's very likely that the Python you used to install QuTiP was not the one you used to import it. It can happen when several Python versions/environments are present (e.g. on a server).

**Comment by ZahraQI** [comment]
Thanks for your replies.
I did not have any python on my computer. Firstly, I installed Anaconda, then build a qutip-env.  I typed "conda activate qutip-env" and then used the following command to install the requirements: "conda install numpy scipy cython matplotlib pytest pytest-cov jupyter notebook spyder" .
Then, I added "conda config --append channels conda-forge", getting the following warning: "conda-forge already in channels list, moving to the bottem".
Then, I run "conda install qutip" with no errors.
qutip was installed in "/root/anaconda3/env" and i opened a terminal in "/root", typed "python" and then "import qutip.testing as qt" getting the above error.
I really appreciate any help!

**Comment by ZahraQI** [comment]
Also, my python version is : 3.8.5

**Comment by BoxiLi** [comment]
Every time you open a new terminal, you will need to activate the conda environment by `conda activate qutip-env`. QuTiP is only installed in this environment. If you are interested, you could check https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html for details.

**Comment by ZahraQI** [comment]
Thanks alot for your great help.
Activating conda solved the problem, but still the command "import numpy as
np" leads to the following error:

  File "<stdin>", line 1
    import numpy as np
    ^
IndentationError: unexpected indent

Other commands like "import matplotlib.pyplot as plt" works fine but
something like "r=np.random.rand(4,4)" does not work.
My numpy version is 1.19.2

Would you please help me to solve the problem.
Many thanks

**Comment by BoxiLi** [comment]
`IndentationError: unexpected indent` means that you have unnecessary spacing before `import numpy as np`. It's a common programming mistake in Python, an explanation should be easily found online. E.g. https://stackoverflow.com/questions/1016814/what-to-do-with-unexpected-indent-in-python

**Comment by ZahraQI** [comment]
Thank you very much for your great help.
Solved.
