### ISSUE TITLE
How to plot trace distance as a function of time?

### ISSUE THREAD

**Issue by rupayan2029** [qutip/qutip#1397]
I am simulating two dynamics via two mesolves. I want to plot the dynamics of the trace distance between the underlying two density matrices. Can someone kindly suggest a way to do that?

**Comment by jakelishman** [comment]
QuTiP provides a function `qutip.tracedist` to calculate this, so if you have your density matrices, you just need to use that function.  You need to make sure you store the states during the evolution (QuTiP does this by default unless you specify any `e_ops`).  For example,
```python
times = np.linspace(0, 1, 101)
opts = qutip.Options(store_states=True)
result_1 = qutip.mesolve(H, state_1, times, c_ops=..., e_ops=..., options=opts)
result_2 = qutip.mesolve(H, state_2, times, c_ops=..., e_ops=..., options=opts)
distances = np.array([qutip.tracedist(a, b) for a, b in zip(result_1.states, result_2.states)])
```

**Comment by rupayan2029** [comment]
Thanks, Jakelishman for this. I will try it first then will get back to you. Kindly don't  close the issue yet.

**Comment by rupayan2029** [comment]
Thanks.. for the help..and you can close the issue .
