### ISSUE TITLE
can't install qutip on my mac

### ISSUE THREAD

**Issue by pifparfait** [qutip/qutip#1404]
**Describe the bug**
Hi world, I can't install qutip on my computer with this features:
System information
Python	3.7.6 (default, Jan 8 2020, 13:42:34) [Clang 4.0.1 (tags/RELEASE_401/final)]
OS	Darwin Version 10.15.7
CPUs	8
Memory (Gb)	16.0
Wed Dec 09 15:00:15 2020 EST

Any help?

Building wheels for collected packages: qutip
  Building wheel for qutip (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/xk/b7_mprf9407c0l8kvdj_f8_80000gs/T/tmpxkq1pgdg
       cwd: /private/var/folders/xk/b7_mprf9407c0l8kvdj_f8_80000gs/T/pip-install-ehditow9/qutip
  Complete output (299 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.7
  creating build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/countstat.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/scattering.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/metrics.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/mesolve.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/wigner.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/expect.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/cite.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/permute.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/three_level_atom.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/steadystate.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/sesolve.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/version.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/bloch.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/solver.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/rhs_generate.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/continuous_variables.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/eseries.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/dimensions.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/superop_reps.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/bloch_redfield.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/fastsparse.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/graph.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/stochastic.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/simdiag.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/random_objects.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/semidefinite.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/about.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/visualization.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/tensor.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/rcsolve.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/distributions.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/hardware_info.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/floquet.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/configrc.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/orbital.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/ipynbtools.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/lattice.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/subsystem_apply.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/superoperator.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/qobjevo_codegen.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/topology.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/piqs.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/sparse.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/settings.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/qobj.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/interpolate.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/qobjevo.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/mcsolve.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/tomography.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/bloch3d.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/utilities.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/operators.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/parallel.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/testing.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/states.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/correlation.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/pdpsolve.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/propagator.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/essolve.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/matplotlib_utilities.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/entropy.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/fileio.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/logging_utils.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/partial_transpose.py -> build/lib.macosx-10.9-x86_64-3.7/qutip
  creating build/lib.macosx-10.9-x86_64-3.7/qutip/ui
  copying qutip/ui/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/ui
  copying qutip/ui/progressbar.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/ui
  creating build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/pyxbuilder.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/br_codegen.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/utilities.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/codegen.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'setup_require'
    warnings.warn(msg)
  package init file 'qutip/cy/src/__init__.py' not found (or not a regular file)
  creating build/lib.macosx-10.9-x86_64-3.7/qutip/qip
  copying qutip/qip/pulse.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/qip
  copying qutip/qip/circuit.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/qip
  copying qutip/qip/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/qip
  copying qutip/qip/gates.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/qip
  copying qutip/qip/noise.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/qip
  copying qutip/qip/qip_depracation.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/qip
  copying qutip/qip/qubits.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/qip
  copying qutip/qip/circuit_latex.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/qip
  creating build/lib.macosx-10.9-x86_64-3.7/qutip/qip/device
  copying qutip/qip/device/cavityqed.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/qip/device
  copying qutip/qip/device/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/qip/device
  copying qutip/qip/device/processor.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/qip/device
  copying qutip/qip/device/spinchain.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/qip/device
  copying qutip/qip/device/optpulseprocessor.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/qip/device
  copying qutip/qip/device/modelprocessor.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/qip/device
  creating build/lib.macosx-10.9-x86_64-3.7/qutip/qip/operations
  copying qutip/qip/operations/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/qip/operations
  copying qutip/qip/operations/gates.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/qip/operations
  creating build/lib.macosx-10.9-x86_64-3.7/qutip/qip/compiler
  copying qutip/qip/compiler/spinchaincompiler.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/qip/compiler
  copying qutip/qip/compiler/cavityqedcompiler.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/qip/compiler
  copying qutip/qip/compiler/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/qip/compiler
  copying qutip/qip/compiler/gatecompiler.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/qip/compiler
  creating build/lib.macosx-10.9-x86_64-3.7/qutip/qip/algorithms
  copying qutip/qip/algorithms/qft.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/qip/algorithms
  copying qutip/qip/algorithms/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/qip/algorithms
  creating build/lib.macosx-10.9-x86_64-3.7/qutip/control
  copying qutip/control/fidcomp.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/control
  copying qutip/control/optimresult.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/control
  copying qutip/control/pulseoptim.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/control
  copying qutip/control/io.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/control
  copying qutip/control/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/control
  copying qutip/control/dump.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/control
  copying qutip/control/optimconfig.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/control
  copying qutip/control/symplectic.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/control
  copying qutip/control/stats.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/control
  copying qutip/control/termcond.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/control
  copying qutip/control/optimizer.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/control
  copying qutip/control/errors.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/control
  copying qutip/control/propcomp.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/control
  copying qutip/control/grape.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/control
  copying qutip/control/pulsegen.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/control
  copying qutip/control/tslotcomp.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/control
  copying qutip/control/loadparams.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/control
  copying qutip/control/dynamics.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/control
  creating build/lib.macosx-10.9-x86_64-3.7/qutip/nonmarkov
  copying qutip/nonmarkov/memorycascade.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/nonmarkov
  copying qutip/nonmarkov/transfertensor.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/nonmarkov
  copying qutip/nonmarkov/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/nonmarkov
  copying qutip/nonmarkov/heom.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/nonmarkov
  creating build/lib.macosx-10.9-x86_64-3.7/qutip/_mkl
  copying qutip/_mkl/spmv.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/_mkl
  copying qutip/_mkl/spsolve.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/_mkl
  copying qutip/_mkl/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/_mkl
  copying qutip/_mkl/utilities.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/_mkl
  creating build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_tensor.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_brtools.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_spinchain.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_spmath.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_mkl.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_sesolve.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_basis_transformation.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_td_formats.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_noise.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_qubit_evolution.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_heom_solver.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_sparse.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_brmesolve_td.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_mesolve.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_metrics.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_three_level.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_superoper.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_propagator.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_qft.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_qubits.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_stochastic_me.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_optpulseprocessor.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_qpt.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_enr_state_operator.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_qubitcircuit.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_states.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_steadystate.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_operators.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_utilities.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_sp_eigs.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_fileio.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_subsys_apply.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_cy_structs.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_partial_transpose.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_pulse.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_lattice.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_qobj.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_piqs.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_rhs_reuse.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_stochastic_se.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_fastsparse.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_expect.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_wigner.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_mcsolve.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_parallel.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_qobjevo.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_cavityqed.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_correlation.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_superop_reps.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_rand.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_floquet.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_countstat.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_ptrace.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_entropy.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_openmp.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_processor.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_scattering.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_graph.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_gates.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_eigenstates.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_dimensions.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_random.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_interpolate.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_brmesolve.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/tests/test_control_pulseoptim.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  creating build/lib.macosx-10.9-x86_64-3.7/qutip/legacy
  copying qutip/legacy/ptrace.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/legacy
  copying qutip/legacy/bloch_redfield.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/legacy
  copying qutip/legacy/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/legacy
  creating build/lib.macosx-10.9-x86_64-3.7/qutip/cy/openmp
  copying qutip/cy/openmp/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy/openmp
  copying qutip/cy/openmp/bench_openmp.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy/openmp
  copying qutip/cy/openmp/utilities.py -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy/openmp
  package init file 'qutip/cy/openmp/src/__init__.py' not found (or not a regular file)
  running egg_info
  writing qutip.egg-info/PKG-INFO
  writing dependency_links to qutip.egg-info/dependency_links.txt
  writing requirements to qutip.egg-info/requires.txt
  writing top-level names to qutip.egg-info/top_level.txt
  reading manifest file 'qutip.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'qutip.egg-info/SOURCES.txt'
  copying qutip/configspec.ini -> build/lib.macosx-10.9-x86_64-3.7/qutip
  copying qutip/cy/br_tensor.cpp -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/br_tensor.pyx -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/brtools.cpp -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/brtools.pxd -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/brtools.pyx -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/brtools_checks.cpp -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/brtools_checks.pyx -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/checks.cpp -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/checks.pyx -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/complex_math.pxi -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/cqobjevo.cpp -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/cqobjevo.pxd -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/cqobjevo.pyx -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/cqobjevo_factor.cpp -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/cqobjevo_factor.pxd -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/cqobjevo_factor.pyx -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/graph_utils.cpp -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/graph_utils.pyx -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/heom.cpp -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/heom.pyx -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/inter.cpp -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/inter.pxd -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/inter.pyx -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/interpolate.cpp -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/interpolate.pxd -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/interpolate.pyx -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/math.cpp -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/math.pxd -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/math.pyx -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/mcsolve.cpp -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/mcsolve.pyx -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/parameters.pxi -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/piqs.cpp -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/piqs.pyx -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/ptrace.cpp -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/ptrace.pyx -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/sparse_routines.pxi -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/sparse_structs.pxd -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/sparse_utils.cpp -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/sparse_utils.pyx -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/spconvert.cpp -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/spconvert.pxd -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/spconvert.pyx -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/spmatfuncs.cpp -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/spmatfuncs.pxd -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/spmatfuncs.pyx -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/spmath.cpp -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/spmath.pxd -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/spmath.pyx -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/stochastic.cpp -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  copying qutip/cy/stochastic.pyx -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy
  creating build/lib.macosx-10.9-x86_64-3.7/qutip/cy/src
  copying qutip/cy/src/zspmv.cpp -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy/src
  copying qutip/cy/src/zspmv.hpp -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy/src
  copying qutip/control/cy_grape.cpp -> build/lib.macosx-10.9-x86_64-3.7/qutip/control
  copying qutip/control/cy_grape.pyx -> build/lib.macosx-10.9-x86_64-3.7/qutip/control
  copying qutip/tests/Hadamard_params.ini -> build/lib.macosx-10.9-x86_64-3.7/qutip/tests
  copying qutip/cy/openmp/benchmark.pyx -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy/openmp
  copying qutip/cy/openmp/br_omp.pxd -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy/openmp
  copying qutip/cy/openmp/br_omp.pyx -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy/openmp
  copying qutip/cy/openmp/cqobjevo_omp.pyx -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy/openmp
  copying qutip/cy/openmp/omp_sparse_utils.pyx -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy/openmp
  copying qutip/cy/openmp/parfuncs.pxd -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy/openmp
  copying qutip/cy/openmp/parfuncs.pyx -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy/openmp
  creating build/lib.macosx-10.9-x86_64-3.7/qutip/cy/openmp/src
  copying qutip/cy/openmp/src/zspmv_openmp.hpp -> build/lib.macosx-10.9-x86_64-3.7/qutip/cy/openmp/src
  running build_ext
  building 'qutip.cy.spmatfuncs' extension
  creating build/temp.macosx-10.9-x86_64-3.7
  creating build/temp.macosx-10.9-x86_64-3.7/qutip
  creating build/temp.macosx-10.9-x86_64-3.7/qutip/cy
  creating build/temp.macosx-10.9-x86_64-3.7/qutip/cy/src
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -Iqutip/cy -I/private/var/folders/xk/b7_mprf9407c0l8kvdj_f8_80000gs/T/pip-build-env-ob76l82e/overlay/lib/python3.7/site-packages/numpy/core/include -I/private/var/folders/xk/b7_mprf9407c0l8kvdj_f8_80000gs/T/pip-build-env-ob76l82e/overlay/lib/python3.7/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c qutip/cy/spmatfuncs.cpp -o build/temp.macosx-10.9-x86_64-3.7/qutip/cy/spmatfuncs.o -w -O3 -funroll-loops -mmacosx-version-min=10.9
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for qutip
Failed to build qutip
ERROR: Could not build wheels for qutip which use PEP 517 and cannot be installed directly

Many thanks

**Comment by jakelishman** [comment]
You'll find it easier installing from conda-forge, since we distribute binary releases there: see the [installation guide](http://qutip.org/docs/latest/installation.html) here.

If you want to install from source using `pip`, you need to configure your C++ development environment correctly - you'll probably need to enable the XCode command-line tools ([see e.g. this](https://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/)).

**Comment by pifparfait** [comment]
Many thanks! I solved it!
Now I have this WARNING:matplotlib.animation:MovieWriter avconv
unavailable. Trying to use pillow instead.
*Many thanks*

*P**arfait Atchadé*

*Tel Spain: 0034661205543*
*Tel Deutsch: 00491706659017*

**Comment by nathanshammah** [comment]
Thanks @jakelishman for solving it. @pifparfait feel free to reopen if necessary.
