### ISSUE TITLE
Segmentation fault while trying to make large tensor product

### ISSUE THREAD

**Issue by evanphilip** [qutip/qutip#1406]
**Describe the bug**

When I try to make a tensor profuct of a large number of qubits, I get a segmentation fault.

**To Reproduce**

```python
from qutip import *; tensor([basis(2,0) for i in range(31)])
```

The terminal out put is
```
Fatal Python error: Segmentation fault

Current thread 0x000000011b71be00 (most recent call first):
  File "/Users/evanphilip/opt/miniforge3/lib/python3.8/site-packages/qutip/tensor.py", line 116 in tensor
  File "<stdin>", line 1 in <module>
zsh: segmentation fault  python3 -q -X faulthandler
```

**Your Environment**

QuTiP: Quantum Toolbox in Python
================================
Copyright (c) QuTiP team 2011 and later.
Original developers: R. J. Johansson & P. D. Nation.
Previous lead developers: Chris Granade & A. Grimsmo.
Current admin team: Alexander Pitchford, Paul D. Nation, Nathan Shammah, Shahnawaz Ahmed, Neill Lambert, Eric Giguère, and Boxi Li
Project Manager: Franco Nori.
Currently developed through wide collaboration. See https://github.com/qutip for details.

QuTiP Version:      4.5.2
Numpy Version:      1.19.2
Scipy Version:      1.5.2
Cython Version:     None
Matplotlib Version: 3.3.2
Python Version:     3.8.6
Number of CPUs:     4
BLAS Info:          INTEL MKL
OPENMP Installed:   False
INTEL MKL Ext:      True
Platform Info:      Darwin (x86_64)
Installation path:  /Users/evanphilip/opt/miniforge3/lib/python3.8/site-packages/qutip
==============================================================================
Please cite QuTiP in your publication.
==============================================================================
For your convenience a bibtex reference can be easily generated using `qutip.cite()`

**Comment by jakelishman** [comment]
This shouldn't segfault (we should detect it and turn it into a Python error, so that's definitely a bug), but do note that you'd need a supercomputer to actually use a system of that size - storing a single operator or state of this system would require 8GB of RAM even if it were the 0 operator.
