### ISSUE TITLE
Taking the partial trace of a quantum object over its own basis generates an error now

### ISSUE THREAD

**Issue by RobDecoded** [qutip/qutip#1413]
I apologize for not being that familiar with the technical terminology anymore as I have been out of quantum optics research for over 3 years, but I hope that I'll be able to explain the issue anyway.

**Describe the issue**
Taking partial trace of a quantum object over its basis does not return the quantum object itself anymore but produces a type error.

**To Reproduce**
Since version 4.5.0 running
```python
psi = qt.thermal_dm(2,1)
psi.ptrace(0)
```

Produces the following error

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-87c31fb793ec> in <module>
----> 1 psi.ptrace(0)

~/opt/anaconda3/lib/python3.8/site-packages/qutip/qobj.py in ptrace(self, sel, sparse)
   1353             return q.tidyup() if settings.auto_tidyup else q
   1354         else:
-> 1355             return _ptrace_dense(self, sel)
   1356 
   1357     def permute(self, order):

~/opt/anaconda3/lib/python3.8/site-packages/qutip/qobj.py in _ptrace_dense(Q, sel)
   2203         rhomat = vmat.dot(vmat.conj().T)
   2204     else:
-> 2205         rhomat = np.trace(Q.full()
   2206                           .reshape(rd + rd)
   2207                           .transpose(qtrace + [nd + q for q in qtrace] +

TypeError: 'numpy.float64' object cannot be interpreted as an integer
```

Whereas in versions older than 4.5.0 (verified in 4.3.2 and 4.4.1) running
```python
psi = qt.thermal_dm(2,1)
psi.ptrace(0)
```
produced the Qobj psi as the output. 

```
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True

(0.667, 0.0,
0.0, 0.333)
```

Is this change on purpose? I've found it very useful in older versions to loop over taking the partial trace of quantum objects whether it was necessary or not and I believe that unless there is any specific reason for the change other people may prefer the older output generation. Curious what other people think, thanks!

**Comment by nathanshammah** [comment]
Thanks for the comment. I was not aware of the change, but actually I do not understand the meaning of partial trace over an object that is not made of multiple tensored objects? And the output in the previous case was the quantum object itself, i.e., there is no effect of `ptrace` if the object is already a single subspace object, right? I see it can come handy in some applications where there is an iterative process of partial tracing subsystems. Not sure of why the change was made, maybe @Ericgig knows more. I still need to understand better to have an opinion. Thanks for opening the issue. Maybe a deprecation warning could be of use, replacing the old mechanism, if the devs want to change the feature with a major release.

**Comment by jakelishman** [comment]
I'd call the behaviour a bug.  The partial trace keeping all possible subspaces has a clear, sensible meaning; I can't think of any circumstance where it would be surprising that it's a no-op.

The behaviour happens because we're not explicit about the output type of `np.prod` in a few places in `_ptrace_dense` - I think we may have seen this before but looks like we never pushed the fix.  I can do that shortly.
