### ISSUE TITLE
Creating entanglement between two entangled pairs

### ISSUE THREAD

**Issue by ganeshmylavarapu-qp** [qutip/qutip#1425]
**Describe the issue**
Let us say Alice, Bob, Charlie share two entangled pairs among them. Bob creates two entangled pairs (A1, B1 is one entangled pair and B2, C2 another entangled pair). Bob distributes qubit A1 to Alice and distributes qubit C2 to Charlie. Now to create entanglement between Alice and Charlie, Bob has to create an entanglement between B1 and B2. Is there a possibility in QuTip to replicate this scenario and create entanglement between B1 and B2?

**To Reproduce**
If applicable, Please provide a minimal working example. For instance:

```python
from qutip import identity
print(identity(2))
```
The terminal out put is
```
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]
```

**Comment by nathanshammah** [comment]
It is possible, using a tensor structure for the Hilbert space, with a subsystem assigned to each player. You can have a look at the documentation, where it shows the case of [three coupled qubits](http://qutip.org/docs/latest/guide/guide-tensor.html#three-coupled-qubits). A library that specifically tackles quantum games is [toqito](https://toqito.readthedocs.io/en/latest/), by @vprusso. You can ask more support in the google group [forum](https://groups.google.com/forum/#!forum/qutip), I am closing the issue.

**Comment by vprusso** [comment]
Thanks for the mention @nathanshammah. @ganeshmylavarapu-qp, if you have any questions about how to make use of `toqito` for your particular use case, feel free to let me know how I can help out. Cheers!

**Comment by ganeshmylavarapu-qp** [comment]
Thanks Nathan and Vincent. I will go theought the links provided by Nathan and will get back to you in case of any queries.

Regards,
Ganesh M

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
