### ISSUE TITLE
How to teleport a qubit when represented in density matrix form rather than a ket form

### ISSUE THREAD

**Issue by ganeshmylavarapu-qp** [qutip/qutip#1428]
**Describe the issue**
I want to calculate the teleportation fidelity for a two qubit mixed entangled state. I am writing a generalised mixed state for two qubit in density matrix form and then I create a random qubit to be teleported. 

I am able to write a teleportation program when I create the entanglement in the form of kets and use snot and cnot gates to teleport a qubit, but I am unable to do it in when I create in the form of density matrices.

Is there a way in QuTip to do teleportation when we create the mixed entangled pairs in the form of density matrices?

**To Reproduce**
If applicable, Please provide a minimal working example. For instance:

```python
from qutip import identity
print(identity(2))
```
The terminal out put is
```
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]
```

**Comment by BoxiLi** [comment]
QuTiP `QubitCircuit` does not support density matrices. (Please correct me if I'm wrong @sarsid). But you can easily do it yourself. Applying a gate on a density matrix can be represented as `C * rho * C.dag()` where `C` is your gate operator.
