### ISSUE TITLE
SeQuencing: pulse sequencer for mesolve simulations

### ISSUE THREAD

**Issue by loganbvh** [qutip/qutip#1439]
I have recently released a package, [sequencing](https://github.com/sequencing-dev/sequencing), which provides an "experimentalist-friendly" layer on top of QuTiP for constructing and simulating time-dependent Hamiltonians, especially those composed of sequences of pulses.

- Repo: https://github.com/sequencing-dev/sequencing
- Docs: https://sequencing.readthedocs.io/en/latest/

I think this package could be of great use to many QuTiP users who are interested in simulating realistic pulse sequences acting on noisy devices. There is some conceptual overlap with `qutip.qip`, but the implementation is rather different.

I'm not sure if GH issues is the right forum on which to share this information - I apologize if it's not. What would be the best way to share this project with the QuTiP community?

Thanks!

**Comment by BoxiLi** [comment]
Hi @loganbvh

Thanks for the interest!

The package you developed looks very nice. It does have some overlap with `qutip.qip`, but more following the perspective of experimentalists as you said. The start point of `qutip.qip` is a framework of simulating quantum circuit with more realistic noise.

We are considering building an ecosystem around `qutip`, as described in a [roadmap discussion](https://github.com/qutip/qutip-doc/pull/125/files). If you are interested, we could propagate it as a "QuTiP affilliated packages" (packages that developed upon qutip but not maintained by the QuTiP team).

We are also very interested in building APIs for importation and exportation pulses defined in other libraries. A possible GSoC project is listed [here](https://github.com/qutip/qutip/wiki//Google-Summer-of-Code-2021#4-pulse-level-description-of-quantum-circuits).

Best
Boxi

**Comment by loganbvh** [comment]
Hi Boxi, thanks for the response.

> If you are interested, we could propagate it as a "QuTiP affilliated packages"

That would be great! It's not clear from the roadmap document exactly what "QuTiP affiliated" means in practice. I guess there will just be a list in the qutip docs/website with links to such packages?

The GSoC project looks interesting. I may apply if it looks like I will have time this summer.

**Comment by BoxiLi** [comment]
Yes, how that will look like is still under discussion and a list in the qutip docs/website is indeed a good candidate. It will probably come along with QuTiP 5.0 later this year.

I'm closing the issue as issues are meant for ongoing bugs and enhancement in code. Free feel to discuss further in our [Google group](https://groups.google.com/g/qutip) or per emails!
