### ISSUE TITLE
Support for numpy v1.20

### ISSUE THREAD

**Issue by dwang429** [qutip/qutip#1442]
**Describe the bug**
In qobj.py, on line 1699 in the image below, ket was a QObj when using numpy v1.19 but in numpy v1.20 it's a numpy array.

**To Reproduce**
![image](https://user-images.githubusercontent.com/16978018/108094096-4d73a680-7033-11eb-9448-46199697e14c.png)

**Expected behavior**
In line 1699 in the image above, ket should not be a numpy array but rather stay a QObj.

**Your Environment**
QuTiP Version:      4.5.2
Numpy Version:      1.20.1
Scipy Version:      1.6.0
Cython Version:     0.29.21
Matplotlib Version: 3.3.4
Python Version:     3.7.8
Number of CPUs:     8
BLAS Info:          Generic
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Windows (AMD64)

**Additional context**
Working with @marcolincs on this.

**Comment by jakelishman** [comment]
Thanks for this.  We've already merged a fix to master, and we'll be released a new version of QuTiP in the coming days that will officially support Numpy 1.20.

In the meantime, you can work around by pinning your Numpy version 1.19 (there are some other problems within all current released QuTiP versions when dealing with Numpy 1.20 as well).
