### ISSUE TITLE
plot with different parameters

### ISSUE THREAD

**Issue by mba5811** [qutip/qutip#1443]
Dear friends,
Consider, just as an example, y=a * sin(x). "y" is going to be used in a few lines of my code for example: H=2*y ... . Finally, I am going to plot those quantities , say "H" versus "x" for different values of "a". What can i do? Is it possible to define "a" by a list at the beginning of the code and then use it? Any tips is highly welcome. Thanks for attention,
Regards,
Mohammad

**Comment by BoxiLi** [comment]
I'm not sure if I understand the question. Sounds like you can define `a` as a list e.g `a=[1, 2, 3]` and use a for loop iterate over all elements. Please be more specific about the question and provide code examples when possible.

PS: For general python coding questions and using QuTiP for specific physics problem, it is better to use the google group: https://groups.google.com/g/qutip.
