### ISSUE TITLE
Time dependent hamiltonian in a rotating frame approximation

### ISSUE THREAD

**Issue by atmalik123** [qutip/qutip#1466]
I've got this code which uses a rotating frame approximation. I got it to work when the Hamiltonian was time independent, but now I'm trying to implement a time dependent Hamiltonian and nothing happens to the graph. I understand how to do this, but I'm not sure how it differs when using a rotating frame approximation.

h = 6.62607015e-34
b = 0.1786195317554453  #magnetic field
b_AC = 3.572390635108906e-05  #oscillating magnetic field
g = 2 #g-factor
u = 9.274E-24 #bohr magneton
w = g*u*b/h #omega 
w0 = 5e9  # omega0 is the rotating frame frequency

gamma_phi = 999000
gamma_minus = 1000

epsilon = g*u*b/h*(2*cmath.pi)
Delta = g*u*b_AC/h*(2*cmath.pi)

H0 = (w-w0)*epsilon/2 * sz #+ Delta/2*sy

def pulse(t0,t):
    return np.heaviside(t0,2e-9)

def H1_coeff(t,args):
    t0=args['t0']
    phi=args['phi']
    return Delta*pulse(t0,t)*np.sin((w-w0)*t+phi)

H = [H0,[sx,H1_coeff]]

times=np.linspace(0, 0.0001, 1000)

#our initial qubit state 
state0=(state_z_plus)/(np.sqrt(1))

**Comment by BoxiLi** [comment]
This is the same as https://github.com/qutip/qutip/issues/1247

QuTiP uses sparse matrices, so a matrix element smaller than a certain threshold (by default 1e-7) will be discarded. This can be changed in the settings.

Consider changing your unit to avoid very small values, for instance, by writing the formula with h=1` and in nanosecond time unit.

**Comment by atmalik123** [comment]
> This is the same as #1247
> 
> QuTiP uses sparse matrices, so a matrix element smaller than a certain threshold (by default 1e-7) will be discarded. This can be changed in the settings.
> 
> Consider changing your unit to avoid very small values, for instance, by writing the formula with h=1` and in nanosecond time unit.

Sorry which formula are you referring to when you say h=1'?

**Comment by BoxiLi** [comment]
After a second look, I realize that small numbers might not be the problem here. I was thinking that the `coeffs` you computed is too small so that it gets discarded. It turned out that your `Delta` is around 10^6, which is not small at all. Apologies for the rush. 

Then, there could be several reasons:
- In the example you give, `w-w0` is actually 0, if you then choose phi=0, the `coeffs` is always 0. But this maybe just a mistake from extracting this example.
- A more likely problem is that `pulse` function, `t` is not used at all. I guess you probably mean that the pulse is turned on at `t=t0`, which should be:
```
def pulse(t0,t):
    return np.heaviside(t - t0, 2e-9)
```

**Comment by atmalik123** [comment]
I tried your suggestions but unfortunately nothing changes. I think my issue is with the way the rotating frame approximation is being implemented. Prior to this, my issue was that the graph couldn't be plotted over a large time scale because w0 is so high, so I added (w-w0) to H0. That fixed it, but I'm not sure how that affects the H1_coeff function. Is it as simple as including a (w-w0) term there as well, or do I need to adjust it some other way? As you can see, the pulse does exist, but for some reason nothing I change in the code causes the pulse to affect the graphs in any way. 

Also, I realized that the heaviside function may not actually be appropriate for this situation. My goal is to create a pulse that spikes up and dies down, but the heaviside function is a step function so it spikes up and stays there. Do you know if qutip has any functions for such pulses?

![k](https://user-images.githubusercontent.com/29261370/113001273-42ce2600-9136-11eb-84f3-a4bcdd7c458f.PNG)

**Comment by BoxiLi** [comment]
About the simulation, the frequency of your `H0` is at the level of 10^12 (with w0=0), while your control amplitude `Delta` is only 10^6! This is a huge difference. I feel like there might be an error in the unit somewhere. The number of time steps sampled needs to be hundreds of millions. Simulate this whole process is not practical. By setting `w-w0=0` you discard the fast process and what remains is only `Delta`. I get reasonable oscillation with the following code
```
def pulse(t0,t):
    return np.heaviside(t-t0,2e-9)

def H1_coeff(t,args):
    t0=args['t0']
    phi=args['phi']
    return Delta*pulse(t0,t)*np.sin((w-w0)*t+phi)

H = [H0,[sx,H1_coeff]]

times=np.linspace(0, 0.00001, 1000)

args = {"t0":0, "phi":np.pi/2}
result = mesolve(H, basis(2,0), times, args=args, e_ops=[sz])
plt.plot(result.expect[0])
plt.show()
```

If you want to observe the effect of RWA, you could set `w-w0` to be about 10 times `Delta`. That is, the frequency of your system's dynamics is about ten times larger than your driving. Discarding the system dynamics by RWA will lead to some visible error in the plot, but not significantly enough to destroy the driving dynamics.


About the heaviside function. A spike at one single time point is not well defined. Mathematically the integral will be 0 (in measures that makes sense here at least). If you want a pulse that is turned on for a certain duration and then off, you can use two Heaviside. But much easier: you can just shift your time scale and define your tlist `times` to be that time duration from `0` to `t_end` is when you turn on your pulse.

**Comment by atmalik123** [comment]
Sorry if this is a silly question, but are you basically saying to replace w-w0 with 0? Wouldn't H0 be 0 then? Wouldn't that make the sine term multiplying the pulse irrelevant?

**Comment by BoxiLi** [comment]
No, I'm using `w-w0` just to show that the code works fine with my suggested changes in `pulse(t0,t)`. It is just the numbers that are wrong.

First, please check the equation you are using again because (I guess) `H0` should be `(w-w0)/2 * sz` and not the one you give in the code above. In your definition, `w-w0` and `epsilon` is the same thing. The drive frequency (in sinus function) should match with `H0`.

Second, it not clear to me what you want to achieve with this. If the drive frequency matches the system frequency (both `w-w0` here), H0 is exactly 0 in the rotating frame.

**Comment by atmalik123** [comment]
Thank you for your feedback. I was able to get the results I wanted. Just to provide some closure, I'm sending a photo

![Image from iOS](https://user-images.githubusercontent.com/29261370/113462422-67e8c000-93e6-11eb-95ef-6d20f89b3851.jpg)

**Comment by atmalik123** [comment]
Hi sorry to lengthen this thread but I have another question pertaining to this. I am trying to determine the relationship between Delta and the frequency of this graph. I put all the code that creates the pulse into a for loop and replaced Delta with "x" so the loop can run over different values. For each Delta ("x"), I use lmfit to fit the curve to a decaying oscillation equation and determine its frequency, then I plot the fit. I've noticed that the fit is worse for the lower values of Delta in the for loop. I think restricting the fit to the region over which the pulse actually acts can improve it. The pulse occurs from 0 to 0.5e-5 seconds which is half the length of the times array (1e-5). len(times) outputs 1000, so I thought I could accomplish this by writing times[0:500] and results.expect[1][0:500], but I get an error.

from lmfit import Minimizer, Parameters, report_fit

h = 6.62607015e-34
b = 0.1786195317554453  #magnetic field
b_AC = 3.572390635108906e-05  #oscillating magnetic field
g = 2 #g-factor
u = 9.274E-24 #bohr magneton
w =  g*u*b/h #omega 
w0 = 5e9  # omega0 is the rotating frame frequency

gamma_phi = 999000
gamma_minus = 1000

epsilon = g*u*b/h*(2*cmath.pi)
Delta =  g*u*b_AC/h*(2*cmath.pi)

H0 = (w-w0)/2 * sz #+ Delta/2*sy

times=np.linspace(0, 0.00001, 1000)
state0=(state_z_plus)/(np.sqrt(1))

for x in range(2000000,10000000,900000):
    
    def pulse(t0,t1,t):
        return np.heaviside(t-t0,2e-9)-np.heaviside(t-t1,2e-9)
    
    def H1_coeff(t,args):
        t0=args['t0'] #pulse start time
        t1=args['t1'] #pulse end time
        phi=args['phi'] #phase
        return x*pulse(t0,t1,t)*np.sin((w-w0)*t+phi)
    
    args = {"t0":0,"t1":0.5e-5 ,"phi":(1/4)*np.pi}
    
    H = [H0,[sx,H1_coeff]]
    
    results=q.mesolve(H, state0, times, e_ops=[sx, sy, sz],c_ops=[cmath.sqrt(gamma_phi/2)*sz,cmath.sqrt(gamma_minus)*sm], options=qutip_options, args=args)
    
    def fcn2min(params, x, data):
        amp = params['amp']
        shift = params['shift']
        omega = params['omega']
        decay = params['decay']
        model = amp * np.sin(x*omega + shift) * np.exp(-x*x*decay)
        return model - data
    
    params = Parameters()
    params.add('amp', value=1, min=0)
    params.add('decay', value=5)
    params.add('shift', value=0, min=-np.pi/2., max=np.pi/2.)
    params.add('omega', value=5e9)
    
    minner = Minimizer(fcn2min, params, fcn_args=(times, results.expect[1]))
    result = minner.minimize()
    final = results.expect[1] + result.residual
    
    #report_fit(result)


    
    fig, ax=plt.subplots()
    #ax.plot(times, results.expect[0], label=r'$\langle \sigma_x \rangle$')
    ax.plot(times, results.expect[1], label=r'$\langle \sigma_y \rangle$')
    #ax.plot(times, results.expect[2], label=r'$\langle \sigma_z \rangle$')
    ax.plot(times, pulse(0,0.5e-5,times))
    ax.plot(times, final, 'r')
   
    
    ax.set_xlabel("time")
    ax.legend();

    
![l](https://user-images.githubusercontent.com/29261370/118360472-5bab6300-b54d-11eb-97f4-8e3e47d37588.PNG)
![k](https://user-images.githubusercontent.com/29261370/118360516-ad53ed80-b54d-11eb-8436-cf172bdbaf28.PNG)
