### ISSUE TITLE
Trouble accessing Boxi Li's FOSDEM slides

### ISSUE THREAD

**Issue by purva-thakre** [qutip/qutip#1467]
I am unable to open slides that were provided on [FOSDEM 2020 presentation](https://archive.fosdem.org/2020/schedule/event/quantum_qutip/). I am able to download the slides but I don't know what format these slides are in. 

This presentation was references[ here](https://github.com/qutip/qutip/wiki/Google-Summer-of-Code-2021#1-error-mitigation-in-qutip).

**Comment by BoxiLi** [comment]
Thanks for reporting this. That's strange, I don't know if I can change what on the website. Somehow FOSDEM renamed it, without the extension. The format is `.pptx`. It should work if you add it to the end of the file name.
