### ISSUE TITLE
OpenMP broken in current master, OpenMP tests worrying

### ISSUE THREAD

**Issue by jakelishman** [qutip/qutip#1470]
OpenMP handling is broken in the current `master`.  It is likely caused by changes made in #1289.  Trying to `import qutip` with OpenMP built produces errors
```python
In [1]: import qutip
Calibrating OPENMP threshold...
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-e01d5608f34f> in <module>
----> 1 import qutip

~/code/qutip/qutip/qutip/__init__.py in <module>
    277         print('Calibrating OPENMP threshold...')
    278         thrsh = calculate_openmp_thresh()
--> 279         qutip.configrc.write_rc_key(rc_file, 'openmp_thresh', thrsh)
    280
    281 # Load the config file

~/code/qutip/qutip/qutip/configrc.py in write_rc_key(key, value, section, rc_file)
    169     config.read(rc_file)
    170     if not config.has_section(section):
--> 171         config.add_section(section)
    172     config.set(section, key, str(value))
    173

~/.anaconda3/envs/qutip-dev/lib/python3.8/configparser.py in add_section(self, section)
   1205         RawConfigParser.add_section by validating if the section name is
   1206         a string."""
-> 1207         self._validate_value_types(section=section)
   1208         super().add_section(section)
   1209

~/.anaconda3/envs/qutip-dev/lib/python3.8/configparser.py in _validate_value_types(self, section, option, value)
   1178         """
   1179         if not isinstance(section, str):
-> 1180             raise TypeError("section names must be strings")
   1181         if not isinstance(option, str):
   1182             raise TypeError("option keys must be strings")

TypeError: section names must be strings
```

The issue is probably due to `__init__.py` being out-of-date with regards to the change to how the `qutiprc` file is written.  The immediate fix should be very simple, however it highlights a larger problem with our testing - this should have been caught by the OpenMP tests.

In this case, I believe that the tests don't see the issue because there is a test in `__init__.py` that doesn't trigger the OpenMP calibration if only there is only 1 CPU.  Presumably, we only ever get allocated single-CPU VMs on Travis, so it hasn't got caught.  That makes me worry a lot that the OpenMP code isn't even being tested correctly.

**Comment by Ericgig** [comment]
In testing.py, we made sure openmp was used even on 1 cpu for the tests. But this is no longer used with changes to travis.yml to use pytest. I believe `pytest.fixture` could be used to set `openmp_thresh` for openmp tests, but I don't see how to catch issues in `__init__.py` with that.

**Comment by Ericgig** [comment]
Good first issue?

**Comment by jakelishman** [comment]
I already fixed it, to be honest.  I was just also tidying up `__init__.py` while I was at it before making the PR.

**Comment by jakelishman** [comment]
Also, we can "solve" the testing issue by forcing the environment variable `QUTIP_NUM_PROCESSES=2` before importing QuTiP, I think.
