### ISSUE TITLE
Cannot Import Qutip in Jupyter Notebook on M1 Mac

### ISSUE THREAD

**Issue by rickypang0219** [qutip/qutip#1473]
I am new to quantum computing and I want to use  Qutip to calculate the entanglement entropy on my M1 MacBook Pro. However, I cannot import the Qutip library into either Jupyter notebook or Python3.9. The error message as shown in follow. May I ask how to solve this problem? Thank you. 

```python
IndexError                                Traceback (most recent call last)
<ipython-input-4-82c62ef8635d> in <module>
----> 1 from qutip import *

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/qutip/__init__.py in <module>
    145     # if num_cpu is 0 set it to the available number of cores
    146     import qutip.hardware_info
--> 147     info =  qutip.hardware_info.hardware_info()
    148     if 'cpus' in info:
    149         qutip.settings.num_cpus = info['cpus']

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/qutip/hardware_info.py in hardware_info()
    121     """
    122     if sys.platform == 'darwin':
--> 123         out = _mac_hardware_info()
    124     elif sys.platform == 'win32':
    125         out = _win_hardware_info()

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/qutip/hardware_info.py in _mac_hardware_info()
     46             l[1].strip('.\n ')
     47     results.update({'cpus': int(info['physicalcpu'])})
---> 48     results.update({'cpu_freq': int(float(os.popen('sysctl -n machdep.cpu.brand_string')
     49                                 .readlines()[0].split('@')[1][:-4])*1000)})
     50     results.update({'memsize': int(int(info['memsize']) / (1024 ** 2))})

IndexError: list index out of range
```

**Comment by MrRobot2211** [comment]
Hi which version of qutip are you running ? This seems to be fixed on the current master.

**Comment by rickypang0219** [comment]
Thank you for your reply. I used pip to download the qutip and the version of qutip is 4.5.3

**Comment by jakelishman** [comment]
QuTiP 4.5.3 doesn't support M1 Macs, sorry. None of us has access to one to test, and our CI didn't support them for quite a while.

This will be fixed in the next release of QuTiP. In the meantime, you can either build the package from the current source code here, or you can go into your QuTiP installation folder and make a change to one file, as discussed in the comments of #1395.

**Comment by rickypang0219** [comment]
Thank you for your reply, jakelishman. Now I can run Qutip code on my M1 Mac.

**Comment by hodgestar** [comment]
@rickypang0219 That's great!
