### ISSUE TITLE
Bloch sphere requires matplotlib >= 3.3

### ISSUE THREAD

**Issue by jakelishman** [qutip/qutip#1502]
#1496 updated the Bloch sphere to prevent distortion in matplotlib 3.3+.  This appears to have inadvertantly pinned the effective matplotlib dependency to `matplotlib>=3.3`, because it uses `Axes3D.set_box_aspect` which didn't exist before then.  We might need to add a small version-dependent switch beacuse matplotlib 3.3 is under a year old, so it's a very recent version to be depending on.

I would like to keep the optional matplotlib dependency to at least `matplotlib>=3` if at all possible, since I don't think we're using much cutting-edge stuff.

Note we now have `packaging` as a run-time dependency, which will make any version comparisons much easier (e.g. 
```python
from packaging.version import parse as parse_version

if parse_version(matplotlib.__version__) > parse_version('3.3'):
    ...
else:
    ...
```

@BoxiLi: do you have thoughts?

**Comment by BoxiLi** [comment]
Sounds good! @jakelishman  Thanks for pointing this out.

Minor comment: It should be `parse_version(matplotlib.__version__) >= parse_version('3.3'):` to also include 3.3.0?

**Comment by jakelishman** [comment]
Ok cool, I'll leave it for other contributors for the time being. You're probably right about the version comparison - I hadn't really intended it to be accurate, just illustrative of what's possible.

**Comment by MrRobot2211** [comment]
Hi, just to clarify: the intention here is to have the two behaviours mediated by  a `settings` flag  or just an in-place version check?

**Comment by BoxiLi** [comment]
I think an in-place version check should be sufficient? But I remember you guys had a deeper discussion over the Scipy version check so you might have a different optinion.
