### ISSUE TITLE
matplotlib 3.4 issues new deprecation warnings

### ISSUE THREAD

**Issue by jakelishman** [qutip/qutip#1503]
matplotlib 3.4 has begun issuing some new deprecation warnings against some of the stuff we do in `bloch.py`.

Simple reproducer from within `ipython --matplotlib`:
```python
In [1]: import qutip
   ...: b = qutip.Bloch()
   ...: b.add_vectors([0, 1, 0])
   ...: b.render()
```
produces
```
/Users/jake/.anaconda3/envs/qutip/lib/python3.9/site-packages/qutip/bloch.py:451: MatplotlibDeprecationWarning: Axes3D(fig) adding itself to the figure is deprecated since 3.4. Pass the keyword argument auto_add_to_figure=False and use fig.add_axes(ax) to suppress this warning. The default value of auto_add_to_figure will change to False in mpl3.5 and True values will no longer work in 3.6.  This is consistent with other Axes classes.
  self.axes = Axes3D(self.fig, azim=self.view[0], elev=self.view[1])

/Users/jake/.anaconda3/envs/qutip/lib/python3.9/site-packages/qutip/bloch.py:59: MatplotlibDeprecationWarning:
The M attribute was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use self.axes.M instead.
  xs, ys, zs = proj3d.proj_transform(xs3d, ys3d, zs3d, renderer.M)
```

This particular environment had `matplotlib==3.4.1`.

The warnings themselves suggest fixes, however some care needs to be taken; I suspect that the additional keyword `auto_add_to_figure` might be new in matplotlib 3.4 (not sure about the `.M` attribute).  We want to keep compatibility with at least `matplotlib>=3` (we don't want to picky so it's easy to use QuTiP with other packages), so it might be necessary to include a version test using `packaging.version.parse`.  If someone could test whether that's necessary, that'd be great.

**Comment by hodgestar** [comment]
Confirming that `auto_add_to_figure` is new in matplotlib 3.4.
