### ISSUE TITLE
tarball from PyPI requires git

### ISSUE THREAD

**Issue by yurivict** [qutip/qutip#1514]
**Describe the bug**
Source tarball taken from PyPI https://pypi.org/project/qutip/ fails without git:
```
===>  Configuring for py38-qutip-4.6.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 231, in <module>
    options = process_options()
  File "setup.py", line 45, in process_options
    options = _determine_version(options)
  File "setup.py", line 127, in _determine_version
    git_out = subprocess.run(
  File "/usr/local/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git'
```

git shouldn't be required because PyPI != GitHub and it is expected to be just a directory and not a cloned git repository.

**Comment by jakelishman** [comment]
Ah, this is the confluence of two bugs, unfortunately.  As an immediate workaround, you should be able to set the environment variable `CI_QUTIP_RELEASE=1` before running `pip` (assuming it propagates the env), and it should build without an error.

The two bugs:
1. building in "release mode" isn't the default; on CI to build the wheels we set a release-mode flag, but the sdist can't tell.  That's what the environment variable above does.  I'll have to think a little about how we'll do versioning.  This bug slipped in in #1465, where the primary concern was getting wheels built, and I didn't notice that the sdist wouldn't build in release mode.
2. `git` isn't meant to be required - in dev mode, it should just get to the string "nogit". That error is actually within a `try/except` block, except it only catches `subprocess.SubprocessError`, when it should catch both `subprocess.SubprocessError` and `OSError`.

Thanks for the report.

**Comment by jakelishman** [comment]
@yurivict QuTiP 4.6.1 is now live on `pip` which should have fixed these bugs in the sdist.

**Comment by yurivict** [comment]
Thanks!
