### ISSUE TITLE
Document random qobjs

### ISSUE THREAD

**Issue by cgranade** [qutip/qutip#1523]
The new random Qobj functions `rand_ket_haar`, `rand_dm_hs`, `rand_dm_ginibre`, `rand_unitary_haar` and `rand_super_bcsz` need to be explained in the Guide as well as in the apidocs.

**Comment by hodgestar** [comment]
For QuTiP 5 the random generators were reorganized. There are now fewer of them (without loss of functionality) and they're better document. We could probably still use a tutorial on them, but closing this for now.
