### ISSUE TITLE
DOC: Hyperlinks to QuTiP functions and classes

### ISSUE THREAD

**Issue by nathanshammah** [qutip/qutip#1526]
It would be nice if the docstrings in QuTiP were well formatted, such that, when Sphinx builds the API and guidelines documentation, there are working link to QuTiP functions and classes. An example of working link is `qutip.steadystate.steadystate` in
http://qutip.org/docs/latest/guide/guide-steady.html#steady-state-solvers-in-qutip

An example of working link in the API doc is options: `qutip.solver.Options` in the attributes of the  `HEOMSolver` class
http://qutip.org/docs/latest/apidoc/classes.html#non-markovian-solvers

A way to proceed would be to:

1) reformat all instances in the docstrings of qutip/qutip such that they are in the form of :py:meth:`mymodule.MyClass.mymethod`, see
 https://stackoverflow.com/questions/22700606/how-would-i-cross-reference-a-function-generated-by-autodoc-in-sphinx

2) Build the documentation with Sphinx to check that the change works and generates an active hyperlink in the relative html page of the documentation. 

3) Iterate 1) and 2) for instances in which Qobj or other QuTiP functions or classes are found.

**Comment by spinolino** [comment]
I just registered for the unitaryhack and saw this issue. I could have a look at it.

**Comment by hodgestar** [comment]
@spinolino I'm unaware of anyone else looking at this right now, so feel free to go ahead. Also, hello again! :D

**Comment by spinolino** [comment]
@hodgestar : The hyperlinks should be updated on dev.major?

**Comment by hodgestar** [comment]
@spinolino I think they should be updated in the `master` branch and then backported to `dev.major` later (probably the backport i not part of this issue, since we seem to be backporting code to dev.major in batches).
