### ISSUE TITLE
Automate or simplify documentation release

### ISSUE THREAD

**Issue by nathanshammah** [qutip/qutip#1533]
# Change log
Right now, maintainers need to go through the PRs in `qutip/qutip` to update the changelog. This is quite time consuming. 

There may be automated tools to generate the change log. 

I propose at minimum to keep a changelog file also in `qutip/qutip`, asking contributors to update it before merging the PR. This makes it simpler than for them to open another PR to `qutip/qutip-doc`.

# Classes and functions
As note in the [`release_distribution`](https://github.com/qutip/qutip-doc/blob/master/release_distribution.rst) guidelines, one should check that new functions and classes are included in the `classes.rst` and `functions.rst` files. Having a recipe to check this quickly or automatically, maybe with a script like this [one](https://stackoverflow.com/questions/1796180/how-can-i-get-a-list-of-all-classes-within-current-module-in-python).

**Comment by hodgestar** [comment]
Superseded by #1894.
