### ISSUE TITLE
How does unit() function works

### ISSUE THREAD

**Issue by ganeshmylavarapu-qp** [qutip/qutip#1572]
How does unit() function works in qutip. Generally in matrices, when we have to find the normalized matrices, we find the square root of sum of squares of all the elements and divide each element with the result.

Is it the same thing happens when we use unit() function? Or I just want to understand the logic behind unit() function.

Regards,
Ganesh M

**Comment by jakelishman** [comment]
`unit` refers to the quantum operation of normalising a state (i.e. setting its norm to unity).  For a ket, the default norm in QuTiP is the L2 norm (what you described), and for density matrices it's the trace norm (which in this special case is the sum of the eigenvalues).  You can see the code for that here: https://github.com/qutip/qutip/blob/faafd4a9f1cfb476a35c0ee46d8716583bba77db/qutip/qobj.py#L1309-L1349, though the norms are calculated elsewhere.
