### ISSUE TITLE
dev.major's Qobj's __matmul__ set wrong superrep for operator-ket

### ISSUE THREAD

**Issue by Ericgig** [qutip/qutip#1586]
**Describe the bug**
`operator-ket`'s `superrep` is `None` at creation.
But `Qobj.__matmul__` set the `superrep` of the output to the one of the left `Qobj`.
Thus `super-operator @ operator-ket` result  in an `operator-ket` with `superrep != None`.
Some operations, such as addition, cannot be done between object with different `superrep`.

**To Reproduce**
```
operket = qutip.operator_to_vector(qutip.qeye(2))
super_oper = qutip.spre(qutip.qeye(2))
super_oper @ operket - operket
```
the last operation result in a `TypeError`.

(#1476)

**Comment by hodgestar** [comment]
Fixed by #1590.
