### ISSUE TITLE
Curve fitting issue 

### ISSUE THREAD

**Issue by atmalik123** [qutip/qutip#1596]
This code creates a pulse (i.e.: sinusoid that decays over a particular period of time as determined by the pulse width). I'm trying to find the relationship between the different parameters of the pulse equation and the frequency of the graph. I basically loop over different values of a given parameter to create multiple graphs and use lmfit to get their frequency. I did this for Delta and it worked fine, now I want to do it for omega. Initially, omega and omega0 are both 5e9 (on resonance), but now I'm scanning over a small range within 10MHz of resonance. The problem is that the graph is behaving very strangely, as well as the fit, and I can't explain this. I just don't understand why this worked for Delta but not omega (red is fit, orange is graph).
![o](https://user-images.githubusercontent.com/29261370/124292582-5a44f280-db1b-11eb-9afa-acf7f1407e50.PNG)
![q](https://user-images.githubusercontent.com/29261370/124292584-5a44f280-db1b-11eb-8c2f-a7f869f3c0ba.PNG)

 
w =  g*u*b/h #omega 
w0 = 5e9  # omega0 is the rotating frame frequency

for x in range(5040000000,5090000000,5000000):
    
    def pulse(t0,t1,t):
        return np.heaviside(t-t0,2e-9)-np.heaviside(t-t1,2e-9)
    
    def H1_coeff(t,args):
        t0=args['t0'] #pulse start time
        t1=args['t1'] #pulse end time
        phi=args['phi'] #phase
        return Delta*pulse(t0,t1,t)*np.sin((x-w0)*t+phi)
    
    args = {"t0":0,"t1":0.5e-5 ,"phi":(1/4)*np.pi}
    
    H = [H0,[sx,H1_coeff]]
    
    results=q.mesolve(H, state0, times, e_ops=[sx, sy, sz],c_ops=[cmath.sqrt(gamma_phi/2)*sz,cmath.sqrt(gamma_minus)*sm], options=qutip_options, args=args)
    
    def fcn2min(params, x, data):
        amp = params['amp']
        shift = params['shift']
        omega = params['omega']
        decay = params['decay']
        model = amp * np.sin(x*omega + shift) * np.exp(-x*decay)
        return model - data
    
    params = Parameters()
    params.add('amp', value=10, min=-10)
    params.add('decay', value=6)
    params.add('shift', value=0, min=-np.pi/2., max=np.pi/2.)
    params.add('omega', value=5.03e9)
    
    minner = Minimizer(fcn2min, params, fcn_args=(times[0:500], results.expect[1][0:500]))
    result = minner.minimize()
    final = results.expect[1][0:500] + result.residual
    
    #report_fit(result)

**Comment by Ericgig** [comment]
Looking quickly, the sampling seems too low for the frequency.
You measure each ~3e-8, but the frequency is ~5e9.
You will probably get better result with `times=np.linspace(0, 0.00001, 30000)`.

**Comment by atmalik123** [comment]
Unfortunately that didn't make a big difference. I just don't understand why the fit is so off from the graph itself

**Comment by hodgestar** [comment]
@atmalik123 The formatting of your code in this issue isn't great, so it's a big hard to see what is going on. If you believe this is a bug in QuTiP, could you perhaps shorten your example code to something smaller that shows the issue more directly?

**Comment by atmalik123** [comment]
> Looking quickly, the sampling seems too low for the frequency.
> You measure each ~3e-8, but the frequency is ~5e9.
> You will probably get better result with `times=np.linspace(0, 0.00001, 30000)`.

This actually was the issue. Turns out scanning over 1GHz range was too much, so I needed to sample more. I reduced to scanning over 1KHz and I could properly plot without increasing the number of sampled points. Thanks so much for your help

**Comment by hodgestar** [comment]
@atmalik123 Great! Glad @Ericgig's suggestion worked and thank you for reporting back.
