### ISSUE TITLE
Documentation for rand_dm

### ISSUE THREAD

**Issue by Wikstahl** [qutip/qutip#1598]
**Describe the bug**
Providing seed as an integer to `rand_dm` does not fixate the seed but randomizes it for each run. In the documentation of `rand_dm` a description of seed is missing.

**To Reproduce**
```python
from qutip import rand_dm
rho = rand_dm(2, density=0.75, pure = True, seed = 1)
print(rho)
```
The terminal out put is different for each run

**Expected behavior**
This gives the correct expected behavior
```python
from qutip import rand_dm
rho = rand_dm(2, density=0.75, pure = True, seed = np.random.seed(1))
print(rho)
```

**Additional context**
Please add a description of seed in `rand_dm` that specifies that the seed parameter should be given as `np.random.seed`

**Comment by Ericgig** [comment]
The seed is ignored when `pure=True`.
Thank you for catching this.
