### ISSUE TITLE
qutip.qip.device.processor.Processor.run_analytically does not include drift

### ISSUE THREAD

**Issue by s-a-sutherland** [qutip/qutip#1602]
When calculating the propagators analytically it does not include the drift hamiltonian, which can result in a significantly different operator. This is particularly relevant to me as the drift hamiltonian changes depending on which qubit is being controlled because the basis is changed to a different rotating frame. This means I replace the drift when operating a pulse. If the drift is not included in the propagator calculation it results in a substantially incorrect matrix.

I think there should be an include_drift=True/False option in the function definition which if true adds the drift hamiltonian before it exponentiates.

**Comment by BoxiLi** [comment]
Thanks for reporting this, indeed it was missing. I have made a PR to fix it. After the PR is merged, you can use the fixed version by compiling `qutip` from the source yourself or wait for the next release (in a few weeks hopefully).

If you want to use the fixed sooner and without compiling `qutip` yourself. An alternative is to use the `qutip-qip` package. Which is equivalent to the module `qutip.qip` you are using. Everything should work if you replace `from qutip.qip import ...` by `from qutip_qip import ...`.
