### ISSUE TITLE
Bad Results with Random Time Values for Small Valued Hamiltonian Coefficients

### ISSUE THREAD

**Issue by naahiv** [qutip/qutip#1638]
Hello. I am currently running a simulation with `mesolve` (yet the same error occurs with `sesolve`) with a slow perturbation, such that close to zero the Hamiltonian is very close to zero (the perturbation is a thin Gaussian distribution). When I run `mesolve`, instead of running my time-dependent coefficients for the values in `tlist` (where in this case I had 250 times in `tlist`), **QuTiP** uses about 20 seemingly random time values, some of which are not even in `tlist`. 

I believe this error is stemming from the Hamiltonian changing extremely slowly and being close to zero for a long period of time. This is because **QuTiP** began working normally when I added the constant 0.00001 to my time-dependent coefficient. Is there a bug here, or is there something I am missing about small-frame limits of the software?

An example piece of code that reproduces this error is below.
```python
import numpy as np
import qutip as qt

def StandardGaussianPi(t):
    def gauss_distr(x, sigma, mu):
        return np.exp(-((x - mu)/sigma)**2 / 2) / (sigma * np.sqrt(2 * np.pi))
    return np.pi * gauss_distr(t, 2, 20)

def run_experiment(waveform, tlist, a):
    def coeff_1(t, args):
        print(t)
        return -1/2 * waveform(t) * -1
    coeff_2 = lambda t, args: coeff_1(t, args) * np.sqrt(2) * np.cos(a * t)
    coeff_3 = lambda t, args: coeff_1(t, args) * np.sqrt(2) * np.sin(a * t)
    hamiltonian = [[gm(1), coeff_1], [gm(6), coeff_2], [gm(7), coeff_3]]
    initial_state = qt.basis(3, 0)
    e_ops = [gm(1), gm(2), gm(3)]
    return qt.mesolve(hamiltonian, initial_state, tlist, None, e_ops).expect

run_experiment(StandardGaussianPi, np.linspace(0, 40, 250), -0.2)
```
The function `gm` was used to generate matrices. These matrices come from:
```python
gell_mann = [[], [], [], [], [], [], [], []]

gell_mann[0] = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]]) / np.sqrt(2 / 3)
gell_mann[1] = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 0]])
gell_mann[2] = np.array([[0, -1j, 0], [1j, 0, 0], [0, 0, 0]])
gell_mann[3] = np.array([[1, 0, 0], [0, -1, 0], [0, 0, 0]])
gell_mann[4] = np.array([[0, 0, 1], [0, 0, 0], [1, 0, 0]])
gell_mann[5] = np.array([[0, 0, -1j], [0, 0, 0], [1j, 0, 0]])
gell_mann[6] = np.array([[0, 0, 0], [0, 0, 1], [0, 1, 0]])
gell_mann[7] = np.array([[0, 0, 0], [0, 0, -1j], [0, 1j, 0]])

def gm(n):
    return qt.Qobj(gell_mann[n])
```

The code above has the following output.
```
0.0
0.0
0.0
0.0
0.0
0.0
7.569736410260631e-09
7.569736410260631e-09
7.569736410260631e-09
1.1027338361068281e-05
1.1027338361068281e-05
1.1027338361068281e-05
5.5136691805341405e-06
5.5136691805341405e-06
5.5136691805341405e-06
0.05514220547452194
0.05514220547452194
0.05514220547452194
0.6065091235279361
0.6065091235279361
0.6065091235279361
6.120178304062077
6.120178304062077
6.120178304062077
60.14556517658347
60.14556517658347
60.14556517658347
```
Without even looking at the output of `mesolve`, there is an issue. Note that the values being printed are generated from the time dependent coefficient `coeff_1`, where I am just printing out the values of time that it has been given. Clearly, there are *not* 250 values, here, and in addition, values like 60.1 are not even in `tlist`, which ranges from 0 to 40.

My `about()` is below; thank you in advance for any help.
```
QuTiP Version:      4.6.2
Numpy Version:      1.20.1
Scipy Version:      1.6.2
Cython Version:     0.29.23
Matplotlib Version: 3.3.4
Python Version:     3.8.8
```

**Comment by naahiv** [comment]
Hello. After doing some more searching, I have found that the solution to this issue is to increase the `atol` value in the `qutip.solver.Options` class.

**Comment by hodgestar** [comment]
@naahiv It's expected that the coefficient function will be evaluated at times not in tlist. The `tlist` specifies the times at which the QuTiP solver should record results, but the numeric solver underlying this may evaluate the operators at many other times too.
