### ISSUE TITLE
Generating positive semi definite matrices using rand_herm produces matrices with negative eigenvalues

### ISSUE THREAD

**Issue by gaurav-iiser** [qutip/qutip#1640]
**Describe the bug**
While calling rand_herm and keeping 'pos_def = True' with density > 0.5, the eigenvalues are coming out to be negative. (For density < 0.5, all works well.) 

**To Reproduce**
Please provide a minimal working example. For instance:
````
import numpy as np
from numpy.linalg import eig
from qutip import *

N = 3
for i in range(10):
    E = qutip.rand_herm(N, 0.65, None, True, None)
    w,v=eig(E)
    print('E-value:', w.real)
````

**The terminal output is**
```
E-value: [ 3.86382692  0.63496876 -0.87459622]
E-value: [ 4.46602374 -0.73195683  0.28172253]
E-value: [ 4.559515    0.33078172 -0.64515643]
E-value: [ 4.63877517 -0.37108524  0.82463744]
E-value: [ 5.46271073 -0.15759687  0.500013  ]
E-value: [ 4.60573553  0.42088337 -0.86184648]
E-value: [ 4.85255845  0.72066688 -0.44991021]
E-value: [ 4.95333863 -0.89975462  0.42454032]
E-value: [4.27421937 1.13664227 0.06540866]
E-value: [ 3.62355797  0.92034471 -1.65694779]
```

**Expected behavior**
The eigenvalues must be non-negative.

**Your Environment**
QuTiP: Quantum Toolbox in Python
================================
Copyright (c) QuTiP team 2011 and later.
Current admin team: Alexander Pitchford, Nathan Shammah, Shahnawaz Ahmed, Neill Lambert, Eric Giguère, Boxi Li, Jake Lishman and Simon Cross.
Board members: Daniel Burgarth, Robert Johansson, Anton F. Kockum, Franco Nori and Will Zeng.
Original developers: R. J. Johansson & P. D. Nation.
Previous lead developers: Chris Granade & A. Grimsmo.
Currently developed through wide collaboration. See https://github.com/qutip for details.

QuTiP Version:      4.6.2
Numpy Version:      1.21.1
Scipy Version:      1.7.0
Cython Version:     None
Matplotlib Version: 3.4.2
Python Version:     3.8.11
Number of CPUs:     8
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Windows (AMD64)
Installation path:  C:\Users\acer\anaconda3\envs\learning_qutip\lib\site-packages\qutip
================================================================================
Please cite QuTiP in your publication.
================================================================================
For your convenience a bibtex reference can be easily generated using `qutip.cite()`

**Additional context**
I separately tried the function '_rand_herm_dense', and it works perfectly fine. I was not able to spot the negative values show up when I keep density > 0.5
rand_herm function given here: https://qutip.org/docs/latest/modules/qutip/random_objects.html#rand_herm

**Comment by Ericgig** [comment]
Thank you for reporting.
This should be already fixed in the `master` branch.
You can use `master`, we keep it stable enough that it can be used at any time, or wait for the next release.

**Comment by nathanshammah** [comment]
Thanks @gaurav-iiser for the bug report and @Ericgig for the fix.
