### ISSUE TITLE
Eigenvalues of positive semi definite matrices generated using rand_herm are not random

### ISSUE THREAD

**Issue by gaurav-iiser** [qutip/qutip#1642]
**Describe the issue**
I was trying to generate random positive semi-definite matrices using the function `rand_herm` but the eigenvalues clearly don't seem to be random. For example, if I choose the dimension to be 3, then the eigenvalues are always like `3.something` or `4.something` or `5.something`; if I choose the dimension to be 4, the eigenvalues are always like '4.something` or `5.something` or `6.something`, and similarly for other dimensions.

**To Reproduce**

```
import numpy as np
from numpy.linalg import eig

N = 4
for i in range(10):
    E = qutip.rand_herm(N, 0.35, None, True, None)
    w,v=eig(E)
    print('E-value:', w.real)
```
**The terminal output is**
```
E-value: [6.32043755 6.06791959 5.24578891 4.99327095]
E-value: [5.37493846 5.8003551  6.26253682 5.65685425]
E-value: [5.17596435 5.5020902  5.8116183  6.13774415]
E-value: [6.25884718 5.05486132 5.71761238 5.59609612]
E-value: [5.94609905 5.36760945 6.2943825  5.33641017]
E-value: [6.25296302 5.06074548 5.65685425 5.65685425]
E-value: [4.81999397 5.75787997 6.57166109 5.65685425]
E-value: [5.23867334 6.35633232 5.8283425  5.65685425]
E-value: [5.13755732 5.71669004 6.21844559 5.65685425]
E-value: [6.32817223 5.48538456 5.30187642 6.01183208]
```
**Expected Behaviour**
The eigenvalues should be random.

**Your Environment**
```
QuTiP: Quantum Toolbox in Python
================================
Copyright (c) QuTiP team 2011 and later.
Current admin team: Alexander Pitchford, Nathan Shammah, Shahnawaz Ahmed, Neill Lambert, Eric Giguère, Boxi Li, Jake Lishman and Simon Cross.
Board members: Daniel Burgarth, Robert Johansson, Anton F. Kockum, Franco Nori and Will Zeng.
Original developers: R. J. Johansson & P. D. Nation.
Previous lead developers: Chris Granade & A. Grimsmo.
Currently developed through wide collaboration. See https://github.com/qutip for details.

QuTiP Version:      4.7.0.dev0+nogit
Numpy Version:      1.21.1
Scipy Version:      1.7.0
Cython Version:     None
Matplotlib Version: 3.4.2
Python Version:     3.8.11
Number of CPUs:     8
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Windows (AMD64)
Installation path:  C:\Users\acer\anaconda3\envs\learning_qutip\lib\site-packages\qutip
================================================================================
Please cite QuTiP in your publication.
================================================================================
For your convenience a bibtex reference can be easily generated using `qutip.cite()`
```

**Comment by hodgestar** [comment]
The function `rand_herm` doesn't return a uniformly random sample from the space of Hermitean matrices -- instead it uses by default a simpler procedure of generating a random matrix with moderately sized entries and then calculating `M + M.conj().transpose()`.

The following note in the `rand_herm` documentation explains how to select the eigenvalues:

> If given a list/ndarray as input 'N', this function returns a
> random Hermitian object with eigenvalues given in the list/ndarray.
> This is accomplished via complex Jacobi rotations.  While this method
> is ~50% faster than the corresponding (real only) Matlab code, it should
> not be repeatedly used for generating matrices larger than ~1000x1000.

Specifically one may generate random eigenvalues and supply those.

I don't think anyone is against improving the `rand_XXX` function to have better statistical properties, but they're primarily used for testing and simple trial data at the moment, so their implementations have been good enough so far.

**Comment by jakelishman** [comment]
Looking at our algorithm, it does seem a bit questionable for positive-definite matrices, but to be fair, what constitutes sufficiently random?  The eigenvalues being chosen on the range `[0, 1]` is also pretty arbitrary.   When you start throwing in extra constraints like "matrix density" and "positive-definite", it becomes difficult to sample a useful measure that has an intuitive definition of random.  We're certainly not against improving the algorithm if you've got ideas, though.

@hodgestar: this is specifically about positive-definite matrices, and supplying eigenvalues is incompatible with that (though perhaps that's a bug!).  It shouldn't be too difficult to make that work by messing around with the Cholesky decomposition, but that would be hard to get right with respect to the density.

**Comment by hodgestar** [comment]
@jakelishman Yes, I was imagining supplying only positive eigenvalues in the list.

**Comment by jakelishman** [comment]
Oh yeah, of course.  For some reason I forgot that it wouldn't make sense to specify `pos_def` with negative eigenvalues in an array.

**Comment by hodgestar** [comment]
Supplying negative or zero eigenvalues in the list and `pos_def=True` is certainly non-sensical input and should possibly return an error (and I think doesn't at the moment).

**Comment by gaurav-iiser** [comment]
@hodgestar @jakelishman  Thanks for your responses. What I was actually trying to do was to generate random PSD matrices less than identity. Now, of course, one way is to randomly generate eigenvalues and use `rand_herm` to construct a PSD matrix. What I was also thinking as I was reading your comments was this - is there a feature to generate POVM elements (because POVMs are often used in quantum information)? 

P.S.: I am sorry if it already exists, I am fairly new to qutip library
