### ISSUE TITLE
Request to add a steadystate solver for periodic driven systems

### ISSUE THREAD

**Issue by albertomercurio** [qutip/qutip#1659]
**Is your feature request related to a problem? Please describe.**
The current steadystate solver requires a time-independent Hamiltonian. This is obvious because a time-dependent Hamiltonian cannot have a steadystate.
However, if the Hamiltonian can be decomposed in a time-independent part H_0 and a periodic time-dependent part cos(w t) * H_i, the system reaches a stroboscopic steadystate. If the perturbation is small, this stroboscopic steadystate fluctuates so slightly that it can be considered as a real steadystate.

**Describe the solution you'd like**
I rewrote the Matrix Continued Fractions method [implemented in the Quantum Toolbox for Matlab](https://copilot.caltech.edu/documents/16743/qousersguide.pdf) to fit with python and qutip objects. It is 100% working, with running times lower than the second with an Hamiltonian 40 x 40.
I'm ready to do a pull request (this is my first time). I understood that I have to write an issue first right?

**Comment by Ericgig** [comment]
Hi albertomercurio, it's not needed to open an issue first but always nice to know it's coming.
The feature seems interesting, thank you for contributing.

I took a quick look at your `steadystate-floquet` branch, the function look good. 
Have you added new tests for it?
Please open the PR when you have time, it does not have to be final.

**Comment by albertomercurio** [comment]
Hi Ericgig, i tested it with a Rabi Hamiltonian. It returns the steadystate immediately! [This is the plot](https://ibb.co/PthSzRd) of the master equation time evolution with the direct steadystate expectation value.
