### ISSUE TITLE
Master equation

### ISSUE THREAD

**Issue by Hosseinyeganeh** [qutip/qutip#1665]
I have master equation that used in many atomic physics to from 

<img src="https://render.githubusercontent.com/render/math?math=i \hbar \frac{d}{dt}\rho=[H,\rho]-i\hbar \frac{1}{2}(\Gamma\rho %2B \rho \Gamma)%2B i \hbar \Lambda">

Where <img src="https://render.githubusercontent.com/render/math?math=\Gamma  and \Lambda"> are diagonal matrix.

Pleas help me to employ this master equation in Qutip.

**Comment by Ericgig** [comment]
Hi Hosseinyeganeh,
For question about qutip usage, please use the google group: https://groups.google.com/g/qutip

For this equation, for arbitrary ![image](https://user-images.githubusercontent.com/17770236/134023271-5fe9e6ca-b841-4a9d-9b35-70307701df80.png) you will have to build the super-operator yourself and pass it to `mesolve` as `H` with no `c_ops`.

**Comment by Hosseinyeganeh** [comment]
Thanks for responding 
Can you give example please 

Best

**Comment by Ericgig** [comment]
I cannot give an example without knowing what lambda is.
If the lambda term does not depend on rho, I would not use `mesolve` but just build the matrix using `numpy` and `scipy`.
The other terms can be represented as `qutip.liouvillian(H) - (qutip.spre(T) - qutip.spost(T))/2`.

**Comment by Hosseinyeganeh** [comment]
Hi
Lambda is diagonal matrix that describes repopulation in atomic system
and not act on density matrix in master equation 
You can see more details in chapter 5 of book:
Optically polarized atoms
By Simon M. Rochester

Thanks again

**Comment by hodgestar** [comment]
@Hosseinyeganeh It sounds like you are asking us to implement homework for you. Even if this is not the case 1) please ask for general help on the QuTiP mailing list which Eric pointed you too, not here on the bug tracker, and 2) please be prepared to put in a bit more effort yourself when asking for assistance. No one is going to do all the legwork for you.

**Comment by Hosseinyeganeh** [comment]
It is not homework baby
Qutip don't solve master equation in this form
you have no answer so be quite please
















Hossein Davoodi Yeganeh, PhD, Quantum Computing and Quantum Information
 Postdoctoral researcher at Department of Engineering Science, University of Tehran
https://scholar.google.com/citations?user=eL6Urg4AAAAJ&hl=en
Email: ***@***.***
 

    On Tuesday, September 21, 2021, 02:09:03 PM GMT+4:30, Simon Cross ***@***.***> wrote:  
 
 


@Hosseinyeganeh It sounds like you are asking us to implement homework for you. Even if this is not the case 1) please ask for general help on the QuTiP mailing list which Eric pointed you too, not here on the bug tracker, and 2) please be prepared to put in a bit more effort yourself when asking for assistance. No one is going to do all the legwork for you.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jakelishman** [comment]
Simon, Eric, and I are all administrators on QuTiP.  It doesn't matter what your academic position is, if you're going to put in no effort and be rude when this is pointed out, you'll find no help from us here.  Consider this the first and final warning. If you keep being rude to our contributors, you'll be banned from interacting with the QuTiP organisation.

**Comment by Hosseinyeganeh** [comment]
@jakelishman You are not allowed to speak in bad form. I have question and talk with  @Ericgig  

you and @hodgestar  should not make fun of it . I'm sorry

Best

**Comment by nathanshammah** [comment]
@Hosseinyeganeh no one was making fun of your question. Only, it seemed that too much was asked from the developers, without enough details surrounding the issue. 
Also, as pointed out by @Ericgig in the first reply, the correct space for physics-related and use-related questions, unless they are bug reports,  feature requests, or questions on the code and community, is https://groups.google.com/g/qutip. Please feel free to ask the question there and I hope that the information provided here already helped with the problem.
