### ISSUE TITLE
Update the "Stochastic Solver" page on the Users Guide

### ISSUE THREAD

**Issue by Leo-am** [qutip/qutip#1706]
**Describe the issue**

The "Stochastic Solver" page on the users guide currently have typos on equations and the text. Additionally, I believe the page could be improved by: 
- adding an example for qutip.smesolve;
- adding references for the equations discussed on the page (Chapter 4, Quantum Measurement and Control, from Wiseman and Milburn, for example);
-  add links on the page for [this](https://nbviewer.ipython.org/github/qutip/qutip-notebooks/blob/master/examples/smesolve-heterodyne.ipynb) and [this](https://nbviewer.ipython.org/github/qutip/qutip-notebooks/blob/master/examples/smesolve-inefficient-detection.ipynb) tutorials.

I would like to volunteer to make these changes.

**Comment by Ericgig** [comment]
Hi Leo-am, 
Thank you for your interest, any help would be greatly appreciated.
`stochastic` documentation is certainly lacking. 

If there are any error in the equations, please let me know so I can check that they are not also present in the code.

**Comment by Leo-am** [comment]
Hi Eric, 

thanks for your eager response.
I'll let you know if I find any errors.

Since you mentioned the equations in the code, I believe it would be interesting to add explicitly which equations are solved when the options `method="homodyne"` and `method="heterodyne"` are selected. Specifically, I would like to check what are the values of dW_factors in both cases.

**Comment by Ericgig** [comment]
I rechecked the equations:
The stochastic integration has the general form:
![image](https://user-images.githubusercontent.com/17770236/140782543-9d8ff092-b9cb-4b17-98e8-85ab0254b425.png)
For `ssesolve`:
![image](https://user-images.githubusercontent.com/17770236/140783379-72e48698-4f2d-4ebc-bfac-95630e8724b1.png)

And for `smesolve`:
![image](https://user-images.githubusercontent.com/17770236/140784174-e9fdb33b-2fee-4795-a93d-e7d1abe32ddd.png)

The liouvillian use both the `sc_ops` and `c_ops` for collapse, but the `d_2` part only use `sc_ops`.


In heterodyne detection, each `sc_ops` is split into 2 parts computed individually: 
![image](https://user-images.githubusercontent.com/17770236/140784227-39e67d38-33bf-47c8-ab57-afd41c23afa6.png)

`m_ops` for homodyne:
![image](https://user-images.githubusercontent.com/17770236/140784715-a7861965-6b30-4a47-a7a6-e19d4dd8b430.png)

`m_ops` for heterodyne:
![image](https://user-images.githubusercontent.com/17770236/140784760-5adb2535-ff63-4b2d-bba8-b10b6422b5db.png)

In both case the `dW`'s default is `1`. In the heterodyne case, the `sqrt(2)` is expected to be included inside `dW_factor` when it's length is the same as `m_ops`.

**Comment by Leo-am** [comment]
The equation for `d_{2,i}` for `ssesolve` seems to be missing a 1/2 term. I checked two sources: Quantum Measurement and Control, Wiseman and Milburn (equation 4.76, page 162), and [the development notebook for SSE](https://nbviewer.ipython.org/github/qutip/qutip-notebooks/blob/master/development/development-ssesolve-tests.ipynb). In both cases, the expression for d_{2, i} for the SSE is: 

<img width="278" alt="Untitled" src="https://user-images.githubusercontent.com/39472087/145735966-85d0c932-a247-42e7-91e1-98fc0f6d0c49.png">

For the stochastic master equation, I also found a different expression for `d_{2,i}`. Both book (equations 4.24 and 4.72 in pages 152 and 161, respectively) and development notebook, state that it should be written:

<img width="483" alt="d2master" src="https://user-images.githubusercontent.com/39472087/145737189-9e3996a5-186a-47e3-9e2f-7e365e00e5ea.png">

To test the current qutip implementation, I tried to replicate the results of both [SSE](https://nbviewer.ipython.org/github/qutip/qutip-notebooks/blob/master/development/development-ssesolve-tests.ipynb) and [SME](https://nbviewer.ipython.org/github/qutip/qutip-notebooks/blob/master/development/development-smesolve-tests.ipynb) development notebooks. The results obtained with QuTiP homodyne and heterodyne methods were similar to the results obtained with the d_1 and d_2 implemented 'by hand' in the notebooks, which used the expressions I listed above. In my tests, I used QuTiP 4.5.2.

**Comment by Ericgig** [comment]
You are right, I made the mistake writing the equations here.

**Comment by Leo-am** [comment]
Hi Eric, 

I'm almost done, there is just one warning that I would like to check with you before I submit a PR.

```
WARNING: autodoc: failed to import class 'QFunc' from module 'qutip'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/leo/miniconda3/envs/qutip-doc-build/lib/python3.8/site-packages/sphinx/util/inspect.py", line 403, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'qutip' has no attribute 'QFunc'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/leo/miniconda3/envs/qutip-doc-build/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 111, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/Users/leo/miniconda3/envs/qutip-doc-build/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 320, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/Users/leo/miniconda3/envs/qutip-doc-build/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2604, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/Users/leo/miniconda3/envs/qutip-doc-build/lib/python3.8/site-packages/sphinx/util/inspect.py", line 419, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: QFunc
```

Do you know a possible cause for this warning?
I checked both

**Comment by Ericgig** [comment]
No, I never got similar error...
You seems to be following the instruction in the doc's readme which usually work well.
Your branch seems to be not up to date with master, maybe if you merge the recent changes and rebuild qutip from source, it would work.

**Comment by hodgestar** [comment]
@Leo-am Tx for closing!
