### ISSUE TITLE
Better operator dimension parameterisation

### ISSUE THREAD

**Issue by pierreguilmin** [qutip/qutip#1722]
**Is your feature request related to a problem? Please describe.**
The dimension argument of qutip operators are quite inconsistent in the **naming**, **type** and **description**. Here are a few examples picked from the [functions doc page](https://qutip.org/docs/latest/apidoc/functions.html):
- `basis` > `dimensions: int or list of ints` _Number of Fock states in Hilbert space. If a list, then the resultant object will be a tensor product over spaces with those dimensions._
- `enr_fock` > `dims: list` _A list of the dimensions of each subsystem of a composite quantum system._
- `enr_state_dictionaries` > `dims: list` _A list with the number of states in each sub-system._
- `phase_basis` > `N: int` _Number of basis vectors in Hilbert space._
- `projection` > `N: int` _Number of basis states in Hilbert space._
- `momentum` > `N: int` _Number of Fock states in Hilbert space._
- `num` > `N: int` _The dimension of the Hilbert space._
- `qeye` > `dimensions: (int) or (list of int) or (list of list of int)` _Dimension of Hilbert space. If provided as a list of ints, then the dimension is the product over this list, but the dims property of the new Qobj are set to this list. This can produce either oper or super depending on the passed dimensions._

Is there a reason for this apparent disorder? I'd be happy to propose a PR.

**Describe the solution you'd like**
Harmonise the naming, type and description of the operators dimension argument.

**Describe alternatives you've considered**
Even if not all operators are meant to work on composite Hilbert spaces, harmonising the naming and docstring would already be helpful.

**Additional context**
Cc @francois-marie for indicating the issue.

**Comment by PierreGuilmin** [comment]
We can maybe make a distinction between operators that act on any Hilbert space, including composite Hilbert space, (like `qeye`) vs operators that act on a specific Hilbert space (like `momentum` or `num`). The first would take a `dimensions: int or list of ints` as argument, and the second a `N: int` argument.

**Comment by Ericgig** [comment]
Thank you for pointing, these functions were added and modified over years and it would be a good idea to unify the documentation. 

However we are short handed, so it will probably wait until we rework the dimension representation in a future major release
( #1476). We are open to help until then.

**Comment by soma2000-lang** [comment]
@Ericgig can i work on this issue

**Comment by Ericgig** [comment]
Hi @soma2000-lang,
Yes, it would be a great help.

**Comment by PriyanshuPansari** [comment]
Is someone working on it? if not can I work on this?

**Comment by Ericgig** [comment]
As far as I know, no one is actively working on it. Any help would be appreciated.

**Comment by PriyanshuPansari** [comment]
can you suggest what kind of convention I should change it to?

**Comment by PriyanshuPansari** [comment]
@Ericgig I have implemented the enhancement required please have a look.

**Comment by PriyanshuPansari** [comment]
@Ericgig Made the suggested changes please have a look.

**Comment by Ericgig** [comment]
Fixed in #2289
