### ISSUE TITLE
Creating Hamiltonian and density operator from sparse matrix 

### ISSUE THREAD

**Issue by j1ver** [qutip/qutip#1737]
I have a time-independent Hamiltonian as a sparse matrix and the same for the density operator at t=0. 
I want to calculate the time evolution of this density operator. 

Is it possible to create the Qobjs from these two and does it stay sparse during the time evolution?
If it needs to be dense, I get problems with the ram because of the dimensions of my matrices.

**Comment by j1ver** [comment]
Alright I found that I can build one myself by a list. But can this list be sparse?

**Comment by jakelishman** [comment]
Internally all `Qobj` use sparse matrices, no matter what type of data you give them.  Whether your density matrix stays sparse during the time evolution depends on the Hamiltonian.  In general, especially if there's any environmental interaction, it likely won't, but that's just down to the physics.

**Comment by j1ver** [comment]
Okay that answers my question! Thank you very much!
