### ISSUE TITLE
Requirements file for QuTiP dev environment

### ISSUE THREAD

**Issue by anna-naden** [qutip/qutip#1763]
### Describe the Issue!

Building the development version of QuTip is challenging because the required modules are not identified in a single file, and may be out of date.

**Comment by hodgestar** [comment]
The requirements are described in the pyproject.toml file (which seems to be considered the current "best practice" for Python projects) and the setup.cfg file (which is an older best practice). Typically for development one would install with either `python setup.py develop` or `pip install -e '.[full]'` both of which should read the dependencies from the pyproject.toml file.

Closing this for now but happy to help more if needed.
