### ISSUE TITLE
Adding up two QobjEvo with operlapping parameter names merges those parameters

### ISSUE THREAD

**Issue by yarrriv** [qutip/qutip#1765]
### Bug Description

When two QobjEvo objects are added up that have time dependence with the same parameter names but with different values in the arg dictionary, the combined QObjEvo merges the dictionaries, resulting in the wrong time dependence for some of the Hamiltonians.

### Code to Reproduce the Bug

```shell
a = destroy(3)
n = a.dag()*a

w0 = 1
g = 0.1
H0 = w0*n
es0 = H0.eigenstates()
def Hdr(wdr) :
  return QobjEvo([[a + a.dag(),'2*cos(w*t)']], args=dict({'w':wdr}))

SE0 = sesolve(H0+g*Hdr(w0),es0[1][0],np.linspace(0,np.pi/2/g,101))
SE1 = sesolve(H0+g*Hdr(w0)+0*Hdr(2*w0),es0[1][0],np.linspace(0,np.pi/2/g,101))
[plt.plot(expect(n,s.states)) for s in [SE0, SE1]]
SE0.states[-1].overlap(SE1.states[-1])
```

### Expected Behaviour

SE0 and SE 1 should have been the same

### Your Environment

```shell
QuTiP Version:      4.6.2
Numpy Version:      1.19.5
Scipy Version:      1.4.1
Cython Version:     0.29.26
Matplotlib Version: 3.2.2
Python Version:     3.7.12
Number of CPUs:     1
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Linux (x86_64)
Installation path:  /usr/local/lib/python3.7/dist-packages/qutip
```

**Comment by Ericgig** [comment]
A `QobjEvo` contain only one `args` dictionary, thus it cannot handle overlapping names. 
There are plans to change this in the next major release (already changed in dev.major), but not in v4.
