### ISSUE TITLE
Clarification of user's guide

### ISSUE THREAD

**Issue by anna-naden** [qutip/qutip#1770]
### Describe the Issue!

Discussion of state vectors and density matrices in users' guide is slightly muddy

**Comment by hrahman12** [comment]
Hi Anna would you mind being a little more specific on which version/s you are currently using? 
Currently for the state vectors we typically create them along the lines of creating a Fock state in |0> in a Hilbert space: `vac = basis(6,0)`'print vac'
which gives us the dimensions, shape and type of the Qobj
`Quantum object: dims = [[6], [1]], shape = (6, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]`
if we have the fock state as a density matrix it will be something like `fock_dm(5,2)` which also gives us whether it is Hermitian or not

**Comment by hodgestar** [comment]
Closing this issue as a bit too broad / vague, but happy to discuss further if more details are provided.
