### ISSUE TITLE
Support measurments of observables with degenerate eigenvalues

### ISSUE THREAD

**Issue by Sola85** [qutip/qutip#1800]
Currently the `qutip.measurement.measure_observable` function always uses rank-1 projectors to determine the final state after the measurement. But for obervables with degenerate eigenvalues you might just want to project the state onto a higher-dimensional eigenspace. Eg. measuring the $Z \otimes Z$ operator on the Bell state $\ket{\psi} = 1/\sqrt{2} (\ket{00} + \ket{11})$ using qutip will return either $\ket{00}$ or $\ket{11}$ despite the state being an eigenstate of the observable.
```
import qutip as qt
import qutip.measurement as meas
import numpy as np

#Prepare Bell state
state = qt.tensor([qt.basis(2, 0)]*2) + qt.tensor([qt.basis(2, 1)]*2)
state = state.unit()

# ZZ operator
op = qt.tensor([qt.sigmaz()]*2)

result_eigenvalue, final_state = meas.measure(state, op)

#Check that the measurement didn't change the state (because it is an eigenstate of the measurement operator)
assert np.isclose(qt.fidelity(final_state, state), 1) #fails
```

I am aware that I can get my intended behaviour by explicity passing the list of projection operators to the `measure` function, but the following enhancement would be very useful:
An option `respect_degenerate_eigenvalues=False` in `qutip.measurement.measure_observable` that groups the eigenstate projectors based on eigenvalue degeneracy. In the above example the rank-2 projectors |00><00| + |11><11| and |01><01| + |10><10| would be used and the Bell state would be preseved during a ZZ measurement.

**Comment by sumeetshirgure** [comment]
Hello. I'm hoping to participate in GSOC, and would like to take a look into this issue as a first contribution.

I think the `measurement_statistics_observable` function need not return a list of eigenstates of the observable. After all, the user could just call `op.eigenstates()` directly themselves. If the signature is changed to return all of the possible states immediately after measurement, this can be made the default behavior as in the following code. (I.e, without needing a `respect_degenerate_eigenvalues` option.) Density matrices will then return projectors on the corresponding degenerate eigenspaces.

```
    eigenvalues, op_eigenstates = op.eigenstates()

    unique_eigenvalues, inverted_indices = np.unique(
        eigenvalues, return_inverse=True)
    op_eigenspaces = list([] for _ in range(len(unique_eigenvalues)))
    for index, inverted_index in enumerate(inverted_indices) :
        op_eigenspaces[inverted_index].append(op_eigenstates[index])

    if state.isket:
        poststates = [ sum( (v.dag() * state) * v for v in eigenbases )
            for eigenbases in op_eigenspaces ]
        probabilities = [e.norm() ** 2 for e in poststates]
        return unique_eigenvalues, poststates, probabilities
    else:
        projectors = [ sum((v * v.dag()) for v in eigenbases)
            for eigenbases in op_eigenspaces ]
        probabilities = [(p * state).tr() for p in projectors]
        return unique_eigenvalues, projectors, probabilities
```

Note however, that even if this is implemented, the degeneracy of eigenspaces is determined by the precision with which their eigenvalues are calculated. E.g if two values differ by just 1e-16, they'll still be considered distinct by np.unique().

**Comment by Sola85** [comment]
Would it make sense to add a np.round before the np.unique call? Then the user could specify the accuracy needed for two eigenvalues to be considered distinct.

**Comment by sumeetshirgure** [comment]
Yeah, I would think so too. Most of the times the energy gap is quite large compared to calculation errors.
But I'm really a newbie, so I'm not sure what the day-to-day users need. It would be great if a contributor could pitch in if this is a good idea.

**Comment by Anika-Roy** [comment]
Hello! is this still open to contributions?

**Comment by PriyanshuPansari** [comment]
Is someone working on this issue? If not is it open for the contribution I am interested in working on it.

**Comment by Ericgig** [comment]
The issue is open for contribution.

**Comment by pschindler** [comment]
@PriyanshuPansari I have a (very inefficient) code that works somewhat for this. I ran into some issues with calculating the eigenstates (see #1998) which is the reason for the many options for calculating the eigenvalues.   I paste it here for your reference:

```python
def get_unique_projectors(operator, state, tol=1e-10, sparse=True, use_qutip_eig=False,
                          is_hermitian=False, return_projector=False):
    if (return_projector is True) and (state.isket) :
        state = q.ket2dm(state)
        
    if use_qutip_eig:
        eigv_list, eigs_list = operator.eigenstates(sparse=sparse)
    else:
        op_array = operator.full()
        if is_hermitian:
            eigv_list, eigs_array_list = scipy.linalg.eigh(op_array)
        else:
            eigv_list, eigs_array_list = scipy.linalg.eig(op_array)
        eigv_list = np.array(eigv_list)
        eigs_list = []
        for eigs_array in eigs_array_list:
            eigs_list.append(q.Qobj(eigs_array))

    unique_idx = 0
    unique_idx_list = []
    this_idx_list = []
    used_idx_list = []
    for idx, eigv in enumerate(eigv_list):
        if idx not in used_idx_list:
            idx_list = list(np.isclose(eigv_list[idx], eigv_list, atol=1e-5))
            similar_indices = [i for i, x in enumerate(idx_list) if x]
            this_idx_list.append(similar_indices)
            used_idx_list += similar_indices
            
    unique_idx_list = this_idx_list
    unique_op_list = []
    probability_list = []
    unique_eigv_list = []
    for idx_list in unique_idx_list:

        projected_state = 0
        eigv = eigv_list[idx_list[0]]
        unique_eigv_list.append(eigv)
        if state.isket and (return_projector is False):
            for eigstate in [eigs_list[i] for i in idx_list]: 
                projected_state += eigstate.dag() * state * eigstate
            probability = projected_state.norm() ** 2
            norm = projected_state.norm()
            if norm <1e-6:
                norm = 1
            unique_op_list.append(projected_state/norm)
            probability_list.append(probability)
        else:
            for eigstate in [eigs_list[i] for i in idx_list]: 
                projected_state += eigstate * eigstate.dag()
            probability = (projected_state * state).tr()
            unique_op_list.append(projected_state)
            probability_list.append(probability)
    return unique_op_list, probability_list, unique_eigv_list


if __name__ == '__main__':
    op = q.tensor(q.sigmax(), q.sigmax())
    state = q.tensor(q.basis(2,0), q.basis(2,0))
    ops, prob, eigvals = get_unique_projectors(op, state, sparse=False, use_qutip_eig=True)
    print(ops, prob, eigvals)
```

**Comment by PriyanshuPansari** [comment]
Thanks @pschindler, This solved some problems I was having.
