### ISSUE TITLE
linear response of resonator-qubit coupled system 

### ISSUE THREAD

**Issue by amrit-poudel** [qutip/qutip#1806]
### Bug Description

Power spectrum of the resonator-qubit (2-level system) system does not show two peaks based on the state of the qubit. Qubit is prepared either in the ground or excited state before the density matrix equation of the coupled system is solved and then the power spectrum is computed off of steady state solution.

### Code to Reproduce the Bug

```shell
import numpy as np
from matplotlib import pyplot
import qutip

N = 4                      # number of cavity fock states
wc = wa = 1.0 * 2 * np.pi  # cavity and atom frequency
g  = 0.1 * 2 * np.pi       # coupling strength
kappa = 0.75               # cavity dissipation rate
gamma = 0.25               # atom dissipation rate

# Jaynes-Cummings Hamiltonian
a  = qutip.tensor(qutip.destroy(N), qutip.qeye(2))
sm = qutip.tensor(qutip.qeye(N), qutip.destroy(2))
H = wc*a.dag()*a + wa*sm.dag()*sm + g*(a.dag()*sm + a*sm.dag())

tlist = np.linspace(0, 100, 5000)
corr = qutip.correlation_2op_1t(H, None, tlist, c_ops, a.dag(), a)
wlist1, spec1 = qutip.spectrum_correlation_fft(tlist, corr)
```

### Expected Behaviour

The power spectrum does show vacuum Rabi splitting, which is fine.  However,  if the qubit is prepared in the ground state or the excited state, the spectrum does not shift based on the state of the qubit.

### Your Environment

```shell
qutip v 4.6
python v 3.9
```

**Comment by nwlambert** [comment]
hi amrit,

correlation_2op_1t() calculates the correlation function based on the steady-state of the Hamiltonian+collapse operators you provide, it doesn't take an initial condition as input (the steady-state will the the same irrespective of the initial condition of the qubit).

For non-steady state correlations and spectrum, I think what is described here might be what you need:
https://qutip.org/docs/latest/guide/guide-correlation.html#non-steadystate-correlation-function

This kind of question is probably better to ask in the QuTiP mailing list, https://groups.google.com/g/qutip
you will receive a wider range of responses there, so I am going to close this issue.  If you find some problem with the above approach that you think is a code bug, feel free to reopen it.
