### ISSUE TITLE
incorrect behaviour of correlation_2op_2t when using time-dependent Hamiltonian terms and collapse operators

### ISSUE THREAD

**Issue by AFvanloo** [qutip/qutip#1808]
### Bug Description

The correlation 2op_2t does not give correct results when using time-dependent hamiltonians and collapse operators.

It seems that this could be solved by changing one line of the code inside correlatation.py, in def _correlation_me_2t:

from:
H_shifted, c_op * rho * a_op, taulist, c_ops_shifted, 

to:
H_shifted, c_op * rho * a_op, taulist + tlist[t_idx], c_ops_shifted,

The accompanying code demonstrating the issue and help finding the issue and solution were provided by M. Pechal

Issue was found in qutip version 4.6.2 and 4.6.3

### Code to Reproduce the Bug

```shell
# Qubit evolving only under energy relaxation (with H = 0 and the only collapse operator being qt.destroy(2)).
# The relaxation rate is time-dependent.
#
# A simple calculation shows that <ad(t2).a(t1)> = exp( - ( int_0^t1 Gamma(t) dt + int_0^t2 Gamma(t) dt ) / 2 )

H = 0.0 * qt.identity(2)
psi0 = qt.basis(2, 1)
tlist = np.linspace(0, 1, 101)
def Gamma(t):
    return 8.0 * t
cops = [[qt.destroy(2), lambda t, args: np.sqrt(Gamma(t))]]
a = qt.destroy(2)
ad = a.dag()

testcorr = qt.correlation_2op_2t(H, psi0, tlist, tlist, cops, ad, a)
#testcorrM = qt.correlation_2op_2t_MPAF(H, psi0, tlist, tlist, cops, ad, a)

i1 = 20
i2 = 50
print('qt.correlation_2op_2t:')
print('<ad(t2).a(t1)> =',testcorr[i1, i2 - i1])

#print('qt.correlation_2op_2t MPAF:')
#print('<ad(t2).a(t1)> =',testcorrM[i1, i2 - i1])


print('------')
print('"manual" calculation using mesolve:')
rhom = qt.mesolve(H, psi0, np.linspace(0, tlist[i1], 101), cops).states[-1]
print('<ad(t2).a(t1)> =',(qt.mesolve(H, a*rhom, np.linspace(tlist[i1], tlist[i2], 101), cops).states[-1] * ad).tr())

print('------')
print('theory:')
t1 = tlist[i1]
t2 = tlist[i2]
print('<ad(t2).a(t1)> =', np.exp(-(4.0*t1**2 + 4.0*t2**2)/2))
```

### Code Output

```shell
qt.correlation_2op_2t:
<ad(t2).a(t1)> = (0.7117768902828536+0j)
------
"manual" calculation using mesolve:
<ad(t2).a(t1)> = 0.5598976820725802
------
theory:
<ad(t2).a(t1)> = 0.559898366565402
```

### Expected Behaviour

qt.correlation_2op_2t should reproduce numbers from theory and 'manual' calculations

### Your Environment

```shell
QuTiP Version:      4.6.3
Numpy Version:      1.20.3
Scipy Version:      1.7.1
Cython Version:     0.29.24
Matplotlib Version: 3.4.2
Python Version:     3.8.10
Number of CPUs:     8
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Linux (x86_64)
```

**Comment by victor-onofre** [comment]
Hello @Ericgig. I'm participating in the unitary hack. This looks like a good issue to start in qutip. Is necessary to add tests for `correalation.py ` once the function ` correlation_me_2t` has been changed?   

Thanks!

**Comment by Ericgig** [comment]
Hi @victor-onofre, I don't think that this issue has a bounty for the unitary hack, but we would be grateful if you want to tackle it.
Yes, if you can add a test that would have failed but is now passing, it would be great. Also, I believe the same bug can be found in `_correlation_me_2t`, which should also be fixed.

**Comment by nwlambert** [comment]
This is definitely a bug.  Looking at correlation.py it looks like _transform_L_t_shift_new() and _args["_t0"] = tlist[t_idx]   are supposed to take care of this, but it seems broken for time-dependent collapse operators for two reasons.

1) _args["_t0"] = tlist[t_idx]  is only set if H is time-dependent, not if the c_ops are

2) The parsing of the c_ops list in _transform_shift_one_op() is  a bit broken (it seems to expect [[c,func]] to be one list deeper or something like that?)

I am wondering if the above proposed fix of just shifting tlist in the mesolve() call might clash with (potentially) working code for time-dependent Hamiltonians and introduce a new bug in that case? It could  perhaps better to fix the existing functionality by fixing the two issues above.  On the other, that existing functionality is fairly clunky..... any reason not just to ditch it all and have the shifted tlist in mesolve for all cases?

**Comment by victor-onofre** [comment]
Hi @Ericgig, @AFvanloo, and @nwlambert, this bug has become more interested. This week I will be busy, but I will dive down into the functions and propose a good solution during the weekend. It looks that the solution @nwlambert  is proposing is the best one but I want to check if there is something else to do here. 

Thanks!

**Comment by victor-onofre** [comment]
I did the changes recommended by @AFvanloo. Given that this is my first time contributing to qutip, I didn't want to make so many changes for me to get used to the workflow. I think I can implement the comments of @nwlambert later but for now, these changes solve the issue.

Thanks!
