### ISSUE TITLE
QObj LaTeX expression is not shown in Visual Studio Code

### ISSUE THREAD

**Issue by albertomercurio** [qutip/qutip#1809]
### Describe the Issue!

Hello,

I'm not able to see the latex expression of a QObj inside Visual Studio Code. For example, if I run in one cell

```python
>> qutip.destroy(2)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False\begin{equation*}\left(\begin{array}{{11}c}0.0 & 1.0\0.0 & 0.0\\end{array}\right)\end{equation}
```

while I'm able to correctly show it in web Jupyter Lab.

Here, there are my system properties

```
QuTiP Version:      4.6.2
Numpy Version:      1.21.2
Scipy Version:      1.7.3
Cython Version:     0.29.25
Matplotlib Version: 3.5.0
Python Version:     3.9.7
Number of CPUs:     6
BLAS Info:          INTEL MKL
OPENMP Installed:   False
INTEL MKL Ext:      True
Platform Info:      Linux (x86_64)
Installation path:  [/home/alberto/anaconda3/envs/physics/lib/python3.9/site-packages/qutip]()
```

**Comment by hodgestar** [comment]
@albertomercurio I am completely unfamiliar with Visual Studio. Do you know how to indicate to Visual Studio how the output should be rendered? And where I could find documentation on the mechanism? E.g. Jupyter looks for the `_repr_latex_` method and calls that if it is present.

**Comment by albertomercurio** [comment]
I think that the rendering is executed through the Visual Studio extension called "[Jupyter Notebook Renderers](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter-renderers)".

I apparently solved this issue by simply downgrading the version of this extension, since I read in the changelog of the latest version "Removed rendering of text/latex in favor of built-in support.". Thus the problem was in the Visual Studio part, however it still remain opened in the case one decide to install the latest version of this extension.

Thank you.

**Comment by hiliuzheng** [comment]
It seems that VS Code does not support render both basic texts and Latex together. On the other hand, the latex code generated by _repr_latex_ is not compatible with Katex (the render engine of Latex used in VS Code).
I tried to modify the code, and the output in VS Code works.

(The style is not beautiful, waiting for someone else to improve the code~)
![image](https://user-images.githubusercontent.com/8891351/165754296-d53b8efc-4aaf-4768-8728-c769b5f7718c.png)
[_repr_latex_.py.txt](https://github.com/qutip/qutip/files/8582772/_repr_latex_.py.txt)

**Comment by jiwooseo98** [comment]
> I think that the rendering is executed through the Visual Studio extension called "[Jupyter Notebook Renderers](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter-renderers)".
> 
> I apparently solved this issue by simply downgrading the version of this extension, since I read in the changelog of the latest version "Removed rendering of text/latex in favor of built-in support.". Thus the problem was in the Visual Studio part, however it still remain opened in the case one decide to install the latest version of this extension.
> 
> Thank you.

Thank you so much for sharing this!

The cell outputs that included Qobj with Latex code wasn't rendering properly for me just like your issue (although Latex code in the Markdown cells was rendering correctly). I spent hours and tried countless online suggestions to fix the issue with no success, until I re-installed the the 'Jupyter Notebook 'Renderers' extension to the old version (v1.0.4) before it removed the latex support.

Now I have the option to 'change presentation' of the output cells so it uses the old version of the extension, and now it finally displays the output with the Latex rendered correctly!

Thank you again for suggesting the only solution that worked for me.
