### ISSUE TITLE
mesolve uses tidyup() method after disabling auto_tidyup in settings

### ISSUE THREAD

**Issue by amitjansc** [qutip/qutip#1831]
### Bug Description

This bug is related to the one explained in #1829.

After setting to False the `auto_tidyup` variable in settings, `mesolve` still calls `tidyup` and sets to 0 all values lower than 1e-12.

The following code is from a [QuTiP example](https://qutip.org/docs/latest/guide/dynamics/dynamics-time.html#function-based-time-dependence), but removing the collapse operators and multiplying the constant hamiltonian with a very small value (and changing the time vector accordingly). More specifically, I create two different hamiltonians by multiplying `H0` by 1e-12 and 1e-13 respectively. After computing the `mesolve` for both hamiltonians, one can see that in the second case all values have been set to 0. 

### Code to Reproduce the Bug

```shell
from qutip import basis, tensor, qeye, destroy, num, mesolve, settings
import numpy as np

settings.auto_tidyup = False

ustate = basis(3, 0)
excited = basis(3, 1)
ground = basis(3, 2)

N = 2  # Set where to truncate Fock state for cavity
sigma_ge = tensor(qeye(N), ground * excited.dag())  # |g><e|
sigma_ue = tensor(qeye(N), ustate * excited.dag())  # |u><e|
a = tensor(destroy(N), qeye(3))
ada = tensor(num(N), qeye(3))

t = np.linspace(-15, 15 * 1e11, 10)  # Define time vector
psi0 = tensor(basis(N, 0), ustate)  # Define initial state

g = 5  # coupling strength
H0 = -g * (sigma_ge.dag() * a + a.dag() * sigma_ge)  # time-independent term
H1 = (sigma_ue.dag() + sigma_ue)  # time-dependent term


def H1_coeff(t, args):
    return 9 * np.exp(-(t / 5.) ** 2)


H_0 = [H0 * 1e-12, [H1, H1_coeff]]
H_1 = [H0 * 1e-13, [H1, H1_coeff]]
output_1 = mesolve(H_0, psi0, t, e_ops=[ada])
output_2 = mesolve(H_1, psi0, t, e_ops=[ada])
print(output_1.expect[0])
print(output_2.expect[0])
```

### Code Output

```shell
[0.         0.48307748 0.87367156 0.3158159  0.03202178 0.64420957
 0.8108019  0.1667205  0.12343592 0.77580413]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
```

### Expected Behaviour

The second print should NOT have been all 0s.

### Your Environment

```shell
QuTiP Version:      4.6.3
Numpy Version:      1.22.3
Scipy Version:      1.8.0
Cython Version:     None
Matplotlib Version: 3.5.1
Python Version:     3.10.2
Number of CPUs:     8
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Linux (x86_64)
```

**Comment by Ericgig** [comment]
`mesolve` use cython code for speed and there was a strange bug when using sparse matrix with stored `0` so the `tidyup` is needed. As long as pure `0` are not kept, small values can be used.  For now `..solve` will respond to `settings.auto_tidyup_atol` with #1832 for such cases.

In a future major release (branch `dev.major` if you are curious), the support is for sparse matrix is improved a lot and those settings are used in the sparse matrices operations directly, so they will apply everywhere.
