### ISSUE TITLE
Qutip and the Numpy Gradient

### ISSUE THREAD

**Issue by sahrak** [qutip/qutip#1834]
Hello,

   I have a time dependent hamiltionian with a simple polynomial function, whose gradient I find using Numpy's gradient function. I also specify the step size that the gradient function should use.

However, when passing the function and its gradient to Qutips mesolve function, i get the error:

ValueError: Shape of array too small to calculate a numerical gradient, at least (edge_order + 1) elements are required.

I think this is because usually you would pass the whole array of time which Numpy would calculate the gradient of, but in the case of mesolve in qutip, we are passing a float instead of an array, i.e. calculating 1 time point which numpy cannot use.
I need the gradient function and its step size, rather than using the analytical gradient as a simply function due to the simulations I am trying to make.

I would appreciate any and all insight into this problem, thank you.

```python
import scipy as sp
import numpy
from qutip import *
import matplotlib.pyplot as plt


# pre define transport functions (time dependent functions for use in hamiltonian)
def q_c(t,t_f,d): #position of ion
    return d*(10*(t/t_f)**3 - 15*(t/t_f)**4 + 6*(t/t_f)**5)

def grad_q_c(t,t_f,step,d): #velocity
    return np.gradient(q_c(t,t_f,d),step)

def grad2_q_c(t,t_f,step,d): #acceleration
    return np.gradient(grad_q_c(t,t_f,step,d),step)

def q_0(t,args): #position of trap (harmonic well)
    '''
    t: time step
    t_f: final time (total time)
    step: step size for gradient function
    d: total distance of transport'''
    t_f,step,d = args['t_f'],args['step'],args['d']
    return grad2_q_c(t,t_f,step,d)/(w_z**2) + q_c(t,t_f,d)

def q_02(t,args): #position of trap
    t_f,step,d = args['t_f'],args['step'],args['d']
    return (grad2_q_c(t,t_f,step,d)/(w_z**2) + q_c(t,t_f,d))**2



# set up initial conditions and parameters for ion
N = 200                      # hilbert space dimension  
w = 2 * pi * 200e3           # angulr frequency of oscillator (Hz)
m = 171  * 1.66e-27          # mass of ion (kg)
hbar = 1                     # reduced plancks constant (eVs) 

# set up operators
a = destroy(N)
n = a.dag()*a
x = np.sqrt(hbar/(2*m*w))*(a +  a.dag())       #position operator (m)
p = 1j*np.sqrt((hbar*m*w)/2) * (a - a.dag())   #momentum operator (kg(m/s))

# duration of ion transport
T = 1
t_f = (2*pi*T)/w
t_list = linspace(0,t_f,1001)

# total distance travelled
dist = 220e-6                    # distance in (m)

# pre-define arguments
args = {'d' : dist, 't_f' : t_f, 'step' : t_list[1]-t_list[0]}

# hamiltonian 
H_0 = (p**2)/(2*m) + (m/2)*(w**2)*(x**2)

H = [H_0,
    [-m*(w**2)*x,q_0], 
    [(m/2)*(w**2)*qeye(N),q_02]]

# initial state
psi0 = basis(N,0)


# solve
result = mesolve(H,                           # hamiltonian
                 psi0,                        # initial state
                 t_list,                      # time
                 [],                          # expectation operators
                 args=args,                   # arguments to time dependent function
                 options=Options(nsteps=1e9), # number of steps solver can take
                 progress_bar=True)           # progress bar
```

**Comment by BoxiLi** [comment]
I slightly edited the question to make the code easier to read.

You should probably consider using the array-based format https://qutip.org/docs/latest/guide/dynamics/dynamics-time.html#methods-for-writing-time-dependent-operators.

Precompute the `q_0` and `q_02` as NumPy arrays with respect to each `t` in the `t_list` using `np.gradient`. Then give them to the solver.

**Comment by Ericgig** [comment]
`np.gradient` compute the gradient of an array, not the gradient of a function at a certain point.
I would suggest to pre compute the gradient arrays or use a scipy spline interpolation method that support derivative such as [CubicSpline](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.CubicSpline.html).

Since this is not about an issue in qutip but a general usage question, I will close this issue. If you have more question, please ask them on the qutip [help group](https://groups.google.com/g/qutip).
