### ISSUE TITLE
Unify random `Qobj` creation functions support of `dims`.

### ISSUE THREAD

**Issue by Ericgig** [qutip/qutip#1838]
### Describe the Issue!

Most of the functions in `random_objects.py` take an `N` input and an optional `dims`. Those input are redundant as the size (`N`) can be obtained from the `dims`. However the way they handle this inconsistent:
- Many functions, such as `rand_super`, `rand_dm`, check that the dims matches the size and raise an error if it doesn't.
- `rand_dm_ginibre`, `rand_super_bcsz` just pass the `dims` to `Qobj` without any checks.
- `rand_ket` has a default `N=0` and obtain the size from `dims` when `N` is `0`, but it raise a division per zero error when neither `N` nor `dims` is passed.
- `rand_ket_haar` also tries to obtain the size from `dims` when `N` is `0`, but the default value of `N` is `2`, thus one need to pass `N=0` to use it. `N=0` would fail almost everywhere else.

Also some function have a default size, other not: `rand_unitary(N, ...)`, `rand_unitary_haar(N=2, ...)`.

The interface of these functions need to be unified.

Some options:
- `N` is always needed and `dims` are checked to match.
- A default of `None` is used for `N` and either `N` or `dims` is needed. If both are given, we check that they are compatible. If none are passed, we raise an appropriate error.
- (For `dev.major`) Remove the `dims` parameter and replace `N` with `dimensions`, which act as `N` if an integer is given and `dims` is a list is. This is already the behavior of `qeye` and `qzero`.

**Comment by Leo-am** [comment]
Hi, @Ericgig! I would like to work on this issue.

We cannot adopt the 3rd option in the master branch due to backwards compatibility, right? I'd rather avoid any single character variable wherever possible.

That said, I believe the second option you gave is the best one to adopt in the master branch. Once I finish, I can work on dev.major implementing the third option.

**Comment by Ericgig** [comment]
Hi @Leo-am,
Thank you for taking this issue.

Yes, with `dev.major` we can change the function call more easily, where as `master` should backwards compatibility.
So doing 2 first for v4.7 and 3 for v5 is the ideal.

**Comment by hodgestar** [comment]
Fixed in #1976.
