### ISSUE TITLE
Add test for orbital

### ISSUE THREAD

**Issue by Ericgig** [qutip/qutip#1839]
### Describe the Issue!

The function `orbital` is not tested and there seems to have an error in the spherical harmonics computation.
Adding a test and fixing any error, possibly using `scipy.special.sph_harm`, would be helpful.

**Comment by spinolino** [comment]
Hello Eric,
I could have a look at it and add a test with the `scipy.special.sph_harm` .
Could you explain in more detail what errors you got?

**Comment by spinolino** [comment]
OK, i will leave this issue for the GSoC.

**Comment by christian512** [comment]
I guess it is my turn then :) 
I looked at the `orbital` function and compared it  to the scipy implementation of `sph_harm` and the results don't seem to agree. There is one detail I need for clarification: The `orbital` function uses `ket`states as input. Which component of the `ket` state should refer to which configuration of `m`? 

For example, if I pass `basis(3,0)` as argument is the corresponding setting `l = 1, m = -1` or `l = 1, m = 0` or `l = 1, m = 1`? 
I am not sure what the desired assignment  is. For me it makes sense to start with the smallest `m` (in the example `m=-1`).

**Comment by Ericgig** [comment]
Thank you for taking this issue.

The contribution to the phase is `np.exp(1.0j * 1 * phi)`, ignoring the `m` and it's not documented. So I guess all ket are `m = 1`...
Since it's wrong and not documented, you are free to choose which ever way you prefer. But please update the docstring so that is is clear.
