### ISSUE TITLE
Circuit plotting with measurements fails when `reverse_states=False`

### ISSUE THREAD

**Issue by jneer** [qutip/qutip#1842]
The LaTeX code generated for the following simple circuit is invalid, and trying to plot the circuit results in a RuntimeError:

```
qc = QubitCircuit(1, num_cbits=1, reverse_states=False)
qc.add_measurement("M0", targets=0, classical_store=0)
qc.png
```
Setting `reverse_states=True` works fine.

The following line in `QubitCircuit.latex_code()` needs to include a sign dependent on the value of `reverse_states`:
https://github.com/qutip/qutip/blob/00d0fe43055cff44fad803bd1ad1530e17fedeee/qutip/qip/circuit.py#L1741

**Comment by hodgestar** [comment]
Fixed by #1847.
