### ISSUE TITLE
Build the documentation PDF either on every commit or as part of deployment.

### ISSUE THREAD

**Issue by hodgestar** [qutip/qutip#1858]
### Problem Description

Currently the documentation PDF has to be built locally for each release.

### Proposed Solution

Build the documentation in a GitHub action either for each push or when deploying a release.

**Comment by christian512** [comment]
Hi, I can work on this issue. 

The HTML Documentation is uploaded to `qutip_html_docs` in the GitHub Action. Is there anything similar for the PDF docs?
