### ISSUE TITLE
It seems that VS Code does not support render both basic texts and Latex together. On the other hand, the latex code generated by _repr_latex_ is not compatible with Katex (the render engine of Latex used in VS Code).

### ISSUE THREAD

**Issue by hiliuzheng** [qutip/qutip#1887]
It seems that VS Code does not support render both basic texts and Latex together. On the other hand, the latex code generated by _repr_latex_ is not compatible with Katex (the render engine of Latex used in VS Code).
I tried to modify the code, and the output in VS Code works.

(The style is not beautiful, waiting for someone else to improve the code~)
![image](https://user-images.githubusercontent.com/8891351/165754296-d53b8efc-4aaf-4768-8728-c769b5f7718c.png)
[_repr_latex_.py.txt](https://github.com/qutip/qutip/files/8582772/_repr_latex_.py.txt)

_Originally posted by @hiliuzheng in https://github.com/qutip/qutip/issues/1809#issuecomment-1112157441_

**Comment by drodper** [comment]
Is anyone working on this? I see no assignee, and it would be nice to get this feature on a stable release.

**Comment by hodgestar** [comment]
@drodper If you would be up for creating a pull request with the code changes, we can review and perhaps including in 4.7.1.

**Comment by drodper** [comment]
@hiliuzheng Care to share the code you changed to get the renderings above?
