### ISSUE TITLE
Make transition to SolverOptions easier for users in QuTiP 5

### ISSUE THREAD

**Issue by hodgestar** [qutip/qutip#1891]
### Problem Description

In QuTiP 4, option for solvers used a class named `Options` but in QuTiP 5 this class is named `SolverOptions`. Having to import different classes in QuTiP 4 and 5 makes it awkward to support both versions of QuTiP.

### Proposed Solution

To make things easier for our users we could:

- Add `SolverOptions` as an alias for `Options` in QuTiP 4
- Or add `Options` as an alias for `SolverOptions` in QuTiP 5

I would prefer the second option, but deprecate the `Options` alias for removal in 5.2.

**Comment by Ericgig** [comment]
@hodgestar
Can we close this?
We now use simple dict for options and `Options` exist for backward compatibility.

**Comment by hodgestar** [comment]
Yep, we can close!
