### ISSUE TITLE
Setting `qutip-qip` as an optional package for qutip-5

### ISSUE THREAD

**Issue by BoxiLi** [qutip/qutip#1893]
### Problem Description

From version 5.0, the subpackage `qutip.qip` will be removed and replaced by a separate package `qutip-qip`. To make it easier for others to migrate from 4.7 to 5.0, we can set up `qutip-qip` as an optional plug-in for qutip, so that if `qutip-qip` is installed, the `qutip.qip` name space can be used as before.

### Expected behaviour
- If only `qutip` is installed, importing `qutip.qip` will raise an `ImportError` with instruction for installing `qutip_qip`.
- If `qutip-qip` is installed, using `qutip.qip` will automatically use the `qutip_qip` namespace, with no difference in the user interface.
- Update `setup.cfg` so that `pip install qutip[qip]` will automatically install `qutip_qip`.

E.g. the following should work if `qutip`-5.0 and `qutip-qip` are both installed
```python
# The following should be the same
from qutip.qip.circuit import QubitCircuit
from qutip_qip.circuit import QubitCircuit
```

### Proposed Solution

See https://github.com/qutip/qutip/discussions/1500 for ideals on the implementation.

**Note: The implementation should be done against the `dev.major` branch of qutip.**

**Comment by HGSilveri** [comment]
Hey! I'd like to help you out with this, is that okay @nathanshammah @hodgestar ? If there's a problem with me being a maintainer at Unitaryhack just let me know, no hard feelings of course

**Comment by hodgestar** [comment]
@HGSilveri @nathanshammah will have to be final arbitrator on the rules, but from my side there are no objections. Note that this would be a PR againt the `dev.major` branch.

**Comment by nathanshammah** [comment]
@HGSilveri that's totally fine, no restrictions whatsoever! Actually that's very cool. I hope I can make some contributions too...

**Comment by HGSilveri** [comment]
Awesome, I'll do my best!

> Note that this would be a PR againt the `dev.major` branch.

Does this entail any extra steps not encompassed in the contributing guidelines, or is it just a matter of branching from and PRing to `dev.major` instead of `master`?

**Comment by hodgestar** [comment]
> Does this entail any extra steps not encompassed in the contributing guidelines, or is it just a matter of branching from and PRing to `dev.major` instead of `master`?

Just branching from and PRing to `dev.major` -- the contribution guidelines are the same.
