### ISSUE TITLE
Unify qutip's graphing interface

### ISSUE THREAD

**Issue by Ericgig** [qutip/qutip#1910]
### Problem Description

There are a few issues with graphic capacities in Qutip.

1. Most are not tested. Only Bloch.py has some tests associated. While testing graphs is not evident, matplotlib has testing functions to compare graphs etc. and just running it to ensure that no errors are raised would be a nice start. Here are some files and their coverage:
- tomography.py 50%
- visualization.py 8%
- distribution.py 23%
- bloch.py 55%
- bloch3d.py 8%

2. The interface is not uniform. Most functions take 'fig' and 'ax', but `hilton` only takes 'ax' but no 'fig'. Maybe one third of the function in visualization accepts 'title' and half a 'figsize'. The order of these options is also inconsistent, 'fig', 'ax' can be the first parameters or the last... As seen in #1573, some want more control so `matrix_histogram` accepts `options`. I am all for more control, but being available for only one function feels wrong. On the bloch side, there is a mismatch between `add_vectors`, `add_points`, which takes `color` and `alpha` as input, and `add_arc`, `add_line` which takes `**kwargs`.

3. The colorblind mode should works everywhere, but presently only `hilton` support it.

### Proposed Solution

So for v5 release, the interface of all these should be clean and uniform, with proper tests.

**Comment by AGaliciaMartinez** [comment]
I agree that unifying the interface would be ideal for QuTiP 5.0. I was aiming to do so with Bloch and also clean-up the code on my way. For tomography, visualization and distribution, we may be able to include them in the Unitary Hack if we make a more detailed issue with the requirements (provided there is still enough room for new bounties).

**Comment by Ericgig** [comment]
@nathanshammah would know if we can add new bounties, but I believe the deadline was last week.
