### ISSUE TITLE
QuTiP eagerly imports scipy.fft, causing failures on SciPy 1.8.1

### ISSUE THREAD

**Issue by cgranade** [qutip/qutip#1915]
### Bug Description

Running `import qutip` eagerly imports `scipy.fft` via `qutip.correlation`, causing all native dependencies of `scipy.fft`'s fftpack-based implementation to load. In particular when using SciPy 1.8.1 on Linux, fftpack requires `GLIBCXX_3.4.30` but contains a private copy of `GLIBCXX_3.4.29` such that the import fails unless another Python package provides its own implementation of `GLIBCXX_3.4.30` (typically, PyZMQ via `jupyter-client`). This in turn can cause `import qutip` to fail even when not using features backed by fftpack (e.g.: as happened in the case of https://github.com/microsoft/iqsharp/pull/676).

### Code to Reproduce the Bug

```shell
import qutip
```

### Code Output

```shell
# Example from build logs for https://dev.azure.com/ms-quantum-public/Microsoft%20Quantum%20(public)/_build/results?buildId=42116&view=logs&j=1c33f9fa-7159-5ed6-d128-ab2ed6cefd14&t=74d456a9-739b-5d92-ed57-026d8fef9427, 
$PREFIX/lib/python3.8/site-packages/zmq/backend/cython/../../../../.././libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by $PREFIX/lib/python3.8/site-packages/scipy/fft/_pocketfft/pypocketfft.cpython-38-x86_64-linux-gnu.so)
```

### Expected Behaviour

`import qutip` should not cause native dependencies of `scipy.fft` to be imported eagerly.

### Your Environment

```shell
(omitted --- `qutip.about()` failed to execute due to error running `import qutip`)
```

**Comment by hodgestar** [comment]
I'm happy to help mitigate this in QuTiP since importing less during "import qutip" would be a good thing, but not being able to import "scipy.fft" when SciPy has been installed because it vendors the wrong `GLIBCXX` seems like a fairly serious SciPy bug?

**Comment by hodgestar** [comment]
This did just bite me when trying to deploy QuTiP to MyBinder for my QuTiP SciPy tutorial and I can confirm this bug is incredibly annoying.
