### ISSUE TITLE
Dicke Entropy returns -Inf

### ISSUE THREAD

**Issue by christian512** [qutip/qutip#1919]
### Bug Description

This issue originates from a [problem in the Help Group](https://groups.google.com/g/qutip/c/F7tOoZzMjto).

Calculating the entropy of a density matrix in the Dicke basis leads to -Inf, while the standard calculation with "entropy_vn" returns a finite (more logical) result. 
I already tracked down the problem to the calculation of eigenvalues in `dicke_trace_function`. Due to numerical behaviour some eigenvalues have very small negative values, which lead to -Inf entropy. If these values are rounded to zero, the problem disappears. However, I am not sure, which way is the best way to perform this rounding. 
@nathanshammah @quantshah 

### Code to Reproduce the Bug

```shell
from qutip import *
from qutip.piqs import *
import numpy as np
import numpy.random
from scipy.linalg import eig
from scipy.sparse import block_diag

N = 10
system = Dicke(N)
[jx, jy, jz] = jspin(N,basis="dicke")
jx=jx*2
jy=jy*2
jz=jz*2

V=3
g=1
system.emission = 1
system.hamiltonian = V/(2*(N-1)) * jz*jz + g/2 * jx
D_tls = system.liouvillian()
rho_ss = steadystate(D_tls,method='eigen',)
vn_dicke=entropy_vn_dicke(rho_ss)
vn_dicke_over=entropy_vn(Qobj(block_diag(dicke_blocks_full(rho_ss))))

print(vn_dicke,vn_dicke_over)
```

### Code Output

```shell
-inf 0.006061297461844266
```

### Expected Behaviour

The value for the entropy should not depend on the way it is calculated. I.e., we should have `vn_dicke == vn_dicke_over` up to numerical uncertainty.

### Your Environment

```shell
uTiP Version:      5.0.0.dev0+ee51e50
Numpy Version:      1.21.0
Scipy Version:      1.6.2
Cython Version:     0.29.23
Matplotlib Version: 3.3.4
Python Version:     3.8.10
Number of CPUs:     4
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Linux (x86_64)
```

**Comment by pyukey** [comment]
The example provided no longer produces that error when I run it. However, the error still occurs whenever I run an odd value for N. I would like to look more into this issue and try to resolve it.
### Code Output
For N=10 `0.006061302499141838 0.006061302499140235`
For N=5 `-inf 0.004046653546081098`
For N=7 `-inf 0.004630127471444943`
For N=9 `-inf 0.005564781691231526`
### Your Environment
```
uTiP Version:      5.0.2
Numpy Version:     1.26.4
Scipy Version:     1.12.0
Cython Version:    3.0.10
Matplotlib Version:3.5.1
Python Version:    3.10.12
Number of CPUs:    8
BLAS Info:         OPENBLAS
OPENMP Installed:  False
INTEL MKL Ext:     False
Platform Info:     Linux (x86_64)
```
