### ISSUE TITLE
Use qiskit calibration data for noisy simulation in Qutip

### ISSUE THREAD

**Issue by rockingcubes** [qutip/qutip#1923]
### Describe the Issue!

Hi, is it possible to illustrate an example code in which a quantum circuit is taken as an input and the qiskit backend properties are feed to a custom compiler to perform noisy simulation?

**Comment by BoxiLi** [comment]
Hi @rockingcubes,

There is an example notebook that describes how to build custom compilers https://nbviewer.ipython.org/github/qutip/qutip-notebooks/blob/master/examples/qip-customize-device.ipynb

If you can extract the properties including the pulse strength and duration etc from the qiksit backend. Then you can use them to build the compiler.

BTW, I would recommend to use the separate package [`qutip-qip`](https://qutip-qip.readthedocs.io/) which is same as `qutip.qip` but with a few new features. We are also planning to build a Qiskit backend in that package in the next few month.
