### ISSUE TITLE
Documentation of qutip does not work with recent versions of numpy

### ISSUE THREAD

**Issue by eendebakpt** [qutip/qutip#1944]
### Bug Description

The qutip documentation at https://qutip.org/docs/4.0.2/guide/dynamics/dynamics-master.html#unitary-evolution has the code
```
In [1]: H = 2 * np.pi * 0.1 * sigmax()

In [2]: psi0 = basis(2, 0)

In [3]: times = np.linspace(0.0, 10.0, 20.0)

In [4]: result = mesolve(H, psi0, times, [], [sigmaz()])
```
This does not work with recent versions of numpy. In particular `np.linspace(0.0, 10.0, 20.0)` generates the exception `TypeError: 'float' object cannot be interpreted as an integer`

### Code to Reproduce the Bug

```shell
import numpy as np
np.linspace(0.0, 10.0, 20.0)
```

### Expected Behaviour

Documenation examples should be able to execute

### Your Environment

```shell
QuTiP: Quantum Toolbox in Python
================================
Copyright (c) QuTiP team 2011 and later.
Current admin team: Alexander Pitchford, Nathan Shammah, Shahnawaz Ahmed, Neill Lambert, Eric Giguère, Boxi Li, Jake Lishman, Simon Cross and Asier Galicia.
Board members: Daniel Burgarth, Robert Johansson, Anton F. Kockum, Franco Nori and Will Zeng.
Original developers: R. J. Johansson & P. D. Nation.
Previous lead developers: Chris Granade & A. Grimsmo.
Currently developed through wide collaboration. See https://github.com/qutip for details.

QuTiP Version:      5.0.0.dev0+7425775
Numpy Version:      1.21.6
Scipy Version:      1.8.0
Cython Version:     0.29.30
Matplotlib Version: 3.5.1
Python Version:     3.10.0
Number of CPUs:     8
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Windows (AMD64)
Installation path:  c:\projects\misc\qutip\qutip
================================================================================
Please cite QuTiP in your publication.
================================================================================
For your convenience a bibtex reference can be easily generated using `qutip.cite()`
```

### Additional Context

None

**Comment by christian512** [comment]
Hi @eendebakpt ,
the link you provided refers to an old version of the docs for QuTiP Version 4.0.2.
You can find the documentation for the unitary evolution of the current QuTiP version here: [https://qutip.org/docs/latest/guide/dynamics/dynamics-master.html#unitary-evolution](https://qutip.org/docs/latest/guide/dynamics/dynamics-master.html#unitary-evolution).

The code in the latest docs seems to be correct: 
`np.linspace(0.0, 10.0, 20)`

I suggest to close this issue!

**Comment by hodgestar** [comment]
@eendebakpt, thank you for reporting this, and @christian512 thank you for looking into it. I'm closing it for now as @christian512 suggested.
