### ISSUE TITLE
parfor and brmesolve - Cythonizing problem in v5

### ISSUE THREAD

**Issue by christian512** [qutip/qutip#1963]
### Bug Description

When combining `parfor` with `brmesolve` and a time-dependent Hamiltonian, the compilation of the Hamiltonian seems to interfer with the correct functioning of `parfor`. The call results in an error, that the coefficient file is too short. 

I guess this could also happen when using `parfor` with other solvers.

### Code to Reproduce the Bug

```shell
from qutip import brmesolve, sigmaz, sigmax, basis, parfor
import numpy as np

psi0 = basis(2, 0)
H_S = np.pi * sigmaz()
H_I = sigmax()
tlist = np.linspace(0, 100, 101)
pulse_shape = "exp(- t**2)"

def brme(A):
    H_tmp = [A * H_S, [H_I, pulse_shape]]

    return brmesolve(
        H_tmp, psi0, tlist, e_ops=[sigmaz()]
    ).expect[0][-1]

results = parfor(brme, np.linspace(0, np.pi, 10))
```

### Code Output

```shell
ImportError: /home/chris/.qutip/qutip_coeffs_1.1/qtcoeff_4c859672674b8b603bd243ba3f4a8d.cpython-38-x86_64-linux-gnu.so: file too short
```

### Expected Behaviour

`parfor` should wait for the compilation to finish and then start the parallel processes.

### Your Environment

```shell
QuTiP Version:      5.0.0.dev0+c64f38e
Numpy Version:      1.23.0
Scipy Version:      1.8.1
Cython Version:     0.29.30
Matplotlib Version: 3.5.2
Python Version:     3.8.10
Number of CPUs:     4
```

**Comment by Ericgig** [comment]
This won't be easy to fix, if the compilation is in the task, `parfor` cannot know about it to wait for it.
The simplest would be to have only the main process able to compile. This code will still raise an error, but the solution would be in the error message.
Otherwise communication between process would be needed and this can get tricky.

Also `parfor` will be removed. It says in its [documentation](https://qutip.org/docs/latest/apidoc/functions.html#qutip.parallel.parfor) to use `parallel_map` instead since v3.

**Comment by hodgestar** [comment]
@christian512 Perhaps we should try replace parfor with parallel_map in the notebooks and see what happens?

**Comment by hodgestar** [comment]
@Ericgig Should we just drop parfor in v5?

**Comment by Ericgig** [comment]
Yes, there is no reason to keep both `parallel_map` and `parfor` in v5.

**Comment by christian512** [comment]
I updated the the notebooks to use `parallel_map` instead of `parfor` in https://github.com/qutip/qutip-tutorials/pull/31.
I guess we can close this issue?

**Comment by hodgestar** [comment]
@christian512 Could you remove the "pre-compilation" of the Cython files from qutip/qutip-tutorials#31? Then if that works we can close this issue.

**Comment by christian512** [comment]
I removed the "pre-compilation" and it worked in the tutorial. Since we will change from using `brmesolve` to `BRSolver` in that notebook (see https://github.com/qutip/qutip-tutorials/pull/31#discussion_r946862389) I will close this issue.
