### ISSUE TITLE
Plot Spin Distribution - Matplotlib deprecation

### ISSUE THREAD

**Issue by christian512** [qutip/qutip#1973]
### Bug Description

The `plot_spin_distribution_2d` function allows to project a spin distribution function from the surface of a unit sphere to the unit disk. QuTiP uses `matplotlib.pyplot.pcolor` to perform this task and calculates a meshgrid `X, Y` to plot the function to. Due to some changes in `matplotlib` the current implementation is deprecated and will return errors in a few minor releases.

We could quickly fix this by passing `shading='auto'` to the call of `ax.pcolor()` in the [visualization.py](https://github.com/qutip/qutip/blob/82c6704c6fea8a2801492865ad1ef7c1d73c8840/qutip/visualization.py#L1313). However, this raises another UserWarning that the center points are not monotonically sorted.

The cleanest way to fix this bug would be to pass the edges of the quadrilaterals to `pcolor()`. But we can not calculate them exactly from the given points in `theta, phi`. Hence, we would need to redesign the interface to this function and to related functions like `plot_spin_distribution_3d` and `spin_q_function`.

### Code to Reproduce the Bug

```shell
import qutip as qt
import numpy as np
import matplotlib.pyplot as plt

j = 5
psi = qt.spin_coherent(j, np.random.rand() * np.pi, np.random.rand() * 2 * np.pi)
rho = qt.ket2dm(psi)

theta = np.linspace(0, np.pi, 50)
phi = np.linspace(0, 2 * np.pi, 50)

Q, THETA, PHI = qt.spin_q_function(psi, theta, phi)
fig, ax = qt.plot_spin_distribution_2d(Q, THETA, PHI)
plt.show()
```

### Code Output

```shell
MatplotlibDeprecationWarning: shading='flat' when X and Y have the same dimensions as C is deprecated since 3.3.  Either specify the corners of the quadrilaterals with X and Y, or pass shading='auto', 'nearest' or 'gouraud', or set rcParams['pcolor.shading'].  This will become an error two minor releases later.
  ax.pcolor(X, Y, P.real, cmap=cmap)
```

### Expected Behaviour

I expect the same plot, but without the warning which becomes an error in the future.

### Your Environment

```shell
QuTiP Version:      5.0.0.dev0+67add84
Numpy Version:      1.21.0
Scipy Version:      1.6.2
Cython Version:     0.29.23
Matplotlib Version: 3.3.4
Python Version:     3.8.10
Number of CPUs:     4
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Linux (x86_64)
```

**Comment by Ericgig** [comment]
Fixed on matplotlib side as of 3.8.
