### ISSUE TITLE
Collapse Operator Malfuncioning 

### ISSUE THREAD

**Issue by EeshGupta** [qutip/qutip#1985]
### Bug Description

In master equation solver, the case where **collapse operator = None** vs the case where **collapse operator = [0 * some matrix]** outputs different results. This behavior can be found [here](https://github.com/EeshGupta/Multimode-Conditional-Displacements/blob/main/hpc_runs/two_mode_ecd/Qutip%20Batch%20Optimizer%20Inconsistency/Qutip%20Collapse%20Operator%20Bug.ipynb).

### Code to Reproduce the Bug

```shell
from qutip import *

initial = tensor(basis(2, 0))
target = tensor(basis(2,0))

c_ops1 = None
c_ops2 = [0*qeye(2)]

T = 10
times = [i for i in range(T)]
opts = Options(store_states=True, store_final_state=True,nsteps = 4000,max_step = 10)

#collapse ops = None
output1 = mesolve(sigmax(), initial , times, c_ops1, [], options =opts)
rho1 = output1.states[-1] #final state 
#collapse ops = 0*matrix
output2 = mesolve(H, initial , times, c_ops, [], options =opts)
rho2 = output2.states[-1]

fid1 = rho1.overlap(target)
fid2 = rho2.overlap(target)

print('fid1: ' + str(fid1))
print('fid2: ' + str(fid2))
print('Is fid1 = fid2? ' + str(fid1==fid2))
```

### Code Output
`fid1: 0.911130904224875
fid2: 0.8301538149349885
Is fid1 = fid2? False`
### Expected Behaviour

Both cases should give the same output, say x.
```
fid1: x
fid2: x
Is fid1 = fid2? True
```

### Your Environment

```shell
QuTiP Version:      4.6.2
Numpy Version:      1.18.5
Scipy Version:      1.4.1
Cython Version:     0.29.23
Matplotlib Version: 3.3.4
Python Version:     3.8.8
Number of CPUs:     2
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Windows (AMD64)
```

**Comment by Ericgig** [comment]
When no `c_ops` are passed, `mesolve` fallback to `sesolve` and the output states are `ket`.
`ket1.overlap(ket2)` (fid1) is computed as `< ket1 | ket2 >`, while `dm.overlap(psi)` (fid2) as `<psi | dm | psi>`.
You can see that `fid1**2 == fid2`, up to numerical noise.

**Comment by hodgestar** [comment]
It looks like the mystery is solved!
