### ISSUE TITLE
Clean up qutip.ipynbtools for version 5

### ISSUE THREAD

**Issue by hodgestar** [qutip/qutip#2001]
### Bug Description

In https://github.com/qutip/qutip-tutorials/pull/42#pullrequestreview-1119409348 @BoxiLi noticed that `qutip.ipynbtools` imports Cython without a `try: ... except: ...` around the import. This results in `qutip.ipynbtools.version_table()` failing even though Cython isn't a required dependency of QuTiP.

We should do a thorough clean up of this module in dev-major and fix this particular issue while we're there.

### Expected Behaviour

`qutip.ipynbtools.version_table()` can be called without Cython installed.

### Your Environment

```shell
QuTiP version: 5.0.0.dev
```

**Comment by gadhvirushiraj** [comment]
@hodgestar Please review the PR. Thanks!
