### ISSUE TITLE
`visualization.hinton` scaling is incorrect

### ISSUE THREAD

**Issue by PierreGuilmin** [qutip/qutip#2010]
### Bug Description

The `hinton` visualization method doesn't have the correct square area scaling.

### Code to Reproduce the Bug

```shell
import qutip as qt
u = qt.Qobj([[0.1, 0.1],
             [1.0, 0.1]])
qt.hinton(u)
```

### Expected Behaviour

Output:
![6ec9b5de-a6b1-4ed1-a730-e35e158c8ae3](https://user-images.githubusercontent.com/38159029/197496789-7cf89a2e-a395-43ad-a21d-87d1734d8cea.png)

Expected (including the matrix transpose correction, see also issue #2009):
![bafa400f-c2c3-4b71-8ff7-fefec3a8c9ce](https://user-images.githubusercontent.com/38159029/197497261-6b4a310a-041e-49c0-965a-75847901873c.png)

### Your Environment

```shell
QuTiP Version:      4.7.0
Numpy Version:      1.23.1
Scipy Version:      1.9.0
Cython Version:     None
Matplotlib Version: 3.5.2
Python Version:     3.9.9
Number of CPUs:     8
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Darwin (arm64)
```

### Additional Context

I am happy to help fixing this if you confirm the issue, I think the `w_max` should not be computed from the diagonal but rather from all matrix elements: https://github.com/qutip/qutip/blob/8118ee8e1a96d45dcf9187a71f7ec1413e55b22f/qutip/visualization.py#L306

Suggested correction:
```python
w_max = 1.25 * max(abs(np.array(W)).flatten())
```

**Comment by Ericgig** [comment]
@PierreGuilmin, Thank you for reporting.
The changes you are proposing seems good. 
If you can make a PR, we would be grateful.
