### ISSUE TITLE
Qutip fails to install on Python 3.11.0

### ISSUE THREAD

**Issue by HGSilveri** [qutip/qutip#2036]
### Bug Description

Installing `qutip` with `pip` on Python 3.11 fails at the "Getting the requirements to build the wheel" stage.

Potentially related to [these changes](https://github.com/pypa/packaging/pull/407) in `packaging`, introduced in the latest update to `22.0`.

### Code to Reproduce the Bug

```shell
pip install qutip --no-cache-dir
```

### Code Output

```shell
Collecting qutip
  Downloading qutip-4.7.0.tar.gz (3.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 18.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/Users/hsilver/opt/miniconda3/envs/py311/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/Users/hsilver/opt/miniconda3/envs/py311/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/hsilver/opt/miniconda3/envs/py311/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/h9/04p7x4ds0hvfmd80jt8gx3kc0000gn/T/pip-build-env-dzdmg7x6/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/h9/04p7x4ds0hvfmd80jt8gx3kc0000gn/T/pip-build-env-dzdmg7x6/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/h9/04p7x4ds0hvfmd80jt8gx3kc0000gn/T/pip-build-env-dzdmg7x6/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 247, in <module>
        File "<string>", line 46, in process_options
        File "<string>", line 130, in _determine_version
      AttributeError: module 'packaging.version' has no attribute 'LegacyVersion'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### Expected Behaviour

Should install `qutip` without errors.

### Your Environment

```shell
QuTip Version: 4.7.0
Python version: 3.11.0
`packaging` version: 22.0
`pip` version: 22.3.1
```

### Additional Context

I explicitly mention Python 3.11 because I failed to replicate the issue on a fresh Python 3.10 environment. 

EDIT: Looking deeper into the [qutip built distributions](https://pypi.org/project/qutip/#files), the reason why this is failing only for Python 3.11 is because earlier versions of Python have built distributions, unlike Python 3.11. 

This indicates that building the wheel from source is generally broken, which I confirmed by forcing an installation from source on Python 3.10 with
```bash
pip install qutip --no-cache-dir --no-binary :all:
```

**Comment by hodgestar** [comment]
Thanks for reporting this. The new version of packaging removed LegacyVersion. They deprecated *constructing* LegacyVersion for two years, but not doing the right thing and checking for LegacyVersion ourselves. So we'll have to remove our check and release 4.7.1 to fix this.

**Comment by hodgestar** [comment]
It doesn't fail on Python 3.10 and below,  because there are pre-built wheels for those Pythons. Python 3.11 wasn't released when 4.7.0 came out, so there aren't prebuilt wheels for that.

**Comment by hodgestar** [comment]
This also affects qutip-qip and other family packages that inherited the qutip `setup.py` file.

**Comment by HGSilveri** [comment]
Thanks for your work on this, @hodgestar . I hope you don't mind me asking: do you have a planned release date for `v4.7.1`? I just need to know so that I can decide whether I wait for it to be released or if I look for a temporary workaround.

**Comment by hodgestar** [comment]
We'll have a new release before Monday, and maybe today.

**Comment by hodgestar** [comment]
I'm busy checking builds in #2046, and hopefully once those are running successfully, we can release. It's the usual dance of figuring out which versions of SciPy and numpy to build for.

**Comment by hodgestar** [comment]
QuTiP 4.7.1 has been released to PyPI -- https://pypi.org/project/qutip/4.7.1/ -- and `pip install qutip` now works for me on Python 3.11.

**Comment by sub-mersion** [comment]
Thank you @hodgestar!
