### ISSUE TITLE
Measurement.measure produces wrong output density matrix in two-qubit system

### ISSUE THREAD

**Issue by RMaier1** [qutip/qutip#2054]
### Bug Description

It seems like the measurement.measure function does not produce the correct density matrix after the measurement of a two-qubit system. In the minimal example below I prepared the density matrix $\rho$ of two qubits, both in $|X\rangle$ eigenstate:
$\rho_i = |X\rangle \langle X| \otimes |X\rangle \langle X|$

If I measure the projection along the $X$-axis of the first qubit with the operator 
$\hat{O} = \sigma_x \otimes \mathbb{I}$
the measurement function produces the correct eigenvalue (which is 1), but not the correct output density matrix $\rho_e$ (which should be equal to the input density matrix $\rho_i$, since the first qubit is already in the eigenstate of $\hat{O}$)

### Code to Reproduce the Bug

```shell
import qutip

rho_1 = qutip.Qobj([[1,1],[1,1]]).unit()    # Initialize two qubits, both in |+X>-state
rho_tot = qutip.tensor(rho_1, rho_1)        # Density matrix of combined system

op = qutip.tensor(qutip.sigmax(), qutip.qeye(2))    # Measurement operator acting on first Qubit, measuring projection in x-direction

result = qutip.measurement.measure(rho_tot, op) 
print(result)
```

### Code Output

```shell
50 % of the time:

(1.0, Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.  0.  0.  0. ]
 [0.  0.5 0.  0.5]
 [0.  0.  0.  0. ]
 [0.  0.5 0.  0.5]])


Other 50 % of the time:

(1.0, Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.5 0.  0.5 0. ]
 [0.  0.  0.  0. ]
 [0.5 0.  0.5 0. ]
 [0.  0.  0.  0. ]])
```

### Expected Behaviour

The correct result of the output matrix should be $rho_i$, as the input matrix is already an eigenstate of $\hat{O}$.
The output of the measurement shoud be:
$\rho_e = |X\rangle \langle X| \otimes |X\rangle \langle X| =$ [[0.25  0.25  0.25  0.25], [0.25  0.25  0.25  0.25], [0.25  0.25  0.25  0.25], [0.25  0.25  0.25  0.25]]

Instead the measurement output is given by:
$\rho_e = |X\rangle \langle X| \otimes |Z\rangle \langle Z|$ and $\rho_e = |X\rangle \langle X| \otimes |-Z\rangle \langle -Z|$
which is the expected output if the measurement operator would be $\hat{O} = \sigma_x \otimes \sigma_z$, instead of $\hat{O} = \sigma_x \otimes \mathbb{I}$

### Your Environment

```shell
QuTip version: 4.7.0
```

### Additional Context

The error does not occure if state vectors are used as input for the measurement.measure function instead of the density matrices.

**Comment by Ericgig** [comment]
Fixed in version 5
