### ISSUE TITLE
Can superoperators work in Monte Carlo solver in QuTip?

### ISSUE THREAD

**Issue by Karhoi** [qutip/qutip#2060]
### Describe the Issue!

The Monte Carlo solver works with kets instead of density matrices. It doesn't allow superoperators as c_ops (error message: c_ops are not consistant with psi0). Since my master equation has lindblad dissipators (which are superoperators), I have trouble using mcsolve. The only way I can think of is converting the initial state to a superket. But that has type operator-ket and QuTip doesn't seem to want me do type casting. How can I circumvent this problem?

**Comment by Ericgig** [comment]
No, not yet, it will be supported in v5.
You could try to use `photocurrent_mesolve` which is very similar, but with a slower algorithm.

ps. There is an error in the formula in the [documentation](https://qutip.org/docs/latest/guide/dynamics/dynamics-photocurrent.html#open-system):
L_eff(rho) = L(rho) - C_dag*C*rho - rho*C_dag*C + tr(C_dag*C*rho - rho*C_dag*C)

**Comment by Ericgig** [comment]
V5 is now out. It support using a Liouvillian instead of Hamiltonian in mcsolve.
