### ISSUE TITLE
Variable used before declaration in `smesolve` for heterodyne detection.

### ISSUE THREAD

**Issue by theodotk** [qutip/qutip#2078]
In `smesolve` if heterodyne detection is chosen and custom measurement operators are provided, the variable `m_ops` is used before being declared [here](https://github.com/qutip/qutip/blob/1253740be0600315286438d1a64f172920b0dadc/qutip/solve/stochastic.py#L604).

A quick fix would be changing this line to
```python
if sso.m_ops is None:
    sso.m_ops = m_ops
```
But probably adding some checks (correct shape, and whether the measured ops look like quadratures) would be nice.

Thank you for the tremendous work, by the way!

**Comment by hodgestar** [comment]
Fixed in #2081.
