### ISSUE TITLE
Fidelity off by power of 2

### ISSUE THREAD

**Issue by manavbabel** [qutip/qutip#2102]
### Bug Description

It appears that the fidelity function is off by a power of 2. It returns the square root of the conventionally accepted definition of fidelity. For example, we expect that the fidelity between the states |0> and |+> is 0.5, but executing the code below returns the square root of this.

### Code to Reproduce the Bug

```shell
from qutip import basis, fidelity, ket2dm
import numpy as np

a = basis(2,0)
b = (basis(2,0)+basis(2,1)) / np.sqrt(2)
fidelity(a,b)

a, b = ket2dm(a), ket2dm(b)
fidelity(a,b)
```

### Code Output

```shell
0.7071067811865475
0.7071067811865475
```

### Expected Behaviour

The expected output for both is 0.5.

### Your Environment

```shell
QuTiP Version:      4.7.1
Numpy Version:      1.23.4
Scipy Version:      1.9.3
Cython Version:     None
Matplotlib Version: 3.6.1
Python Version:     3.11.0
Number of CPUs:     8
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Windows (AMD64)
```

**Comment by Ericgig** [comment]
The `fidelity` function use the Nielsen & Chuang definition.

In a future release, [process_fidelity](https://github.com/qutip/qutip/blob/eeae142630e23818cd08a6b3ea5f6145e3e60225/qutip/core/metrics.py#L148), will be the fidelity version you expect.

**Comment by manavbabel** [comment]
Thank you for the clarification. A suggestion would be to also relabel `fidelity` to make this clear.
