### ISSUE TITLE
The documentation for HEOM does not render correctly.

### ISSUE THREAD

**Issue by AGaliciaMartinez** [qutip/qutip#2104]
### Bug Description

![image](https://user-images.githubusercontent.com/57414022/222287157-149fe2ed-20e4-4a76-a1ed-051cda29b648.png)
This is from the master branch documentation.

### Expected Behaviour

The format of the title should be correct.

**Comment by hodgestar** [comment]
This should already be fixed on master.

**Comment by hodgestar** [comment]
A bit unrelated, this build of the 4.7.X docs failed -- https://readthedocs.org/projects/qutip/builds/19616097/

**Comment by AGaliciaMartinez** [comment]
Yes, it does, both for 4.7 and master.

Im now wondering how and when did I see this compiled wrongly.

**Comment by AGaliciaMartinez** [comment]
oky, I got it from here: https://qutip.org/docs/pre-release/guide/guide-heom.html.

This is the link that "online html documentation" links to in the qutip webpage. Is this not keept up to date, as https://qutip.readthedocs.io/en/master/guide/guide-heom.html is?

**Comment by hodgestar** [comment]
The Read The Docs version is compiled on each commit, but the website version requires downloading the update version and manually updating the website repo.

**Comment by AGaliciaMartinez** [comment]
I see, thanks for the explanation!
