### ISSUE TITLE
Allow solvers to use `HTMLProgressBar`

### ISSUE THREAD

**Issue by Ericgig** [qutip/qutip#2108]
### Describe the Issue!

Most of our progress bars are in `qutip/ui/progressbar.py`, with the exception of `HTMLProgressBar` which is in `qutip/ipynbtools.py`. It is not available by the solvers.

It should be moved with the other and added it to the `progess_bars` dictionary so it's usable with `mesolve`, etc.

**Comment by HarshKhilawala** [comment]
@Ericgig I would like to take up this issue. Can you please assign it to me?
