### ISSUE TITLE
Prepare qutip for cython 3.0

### ISSUE THREAD

**Issue by Ericgig** [qutip/qutip#2117]
### Describe the Issue!

Cython is getting close to release a new major release. It bring 2 changes that we must asses to be compatible with it.
- The order of the `nogil` and `except` keyword. In cython 0.29, both `nogil except ...` and `except ... nogil` are supported. From 3.0, a warning is raised when the first is used. We used the first order almost everywhere. We need to reorder them all... 
- Cython 0.29 do not use reverse operations such as  `__rmatmul__` and `__rmul__`, but call `__mul__` with reverse order (`__mul__(other, self)`). With cython 3, `__rmul__` is used and `self` is always the first input. This breaks some of our tests.  The failing tests are related to `Coefficient.__mul__` in qutip/core/cy/coefficient.pyx,  `Data.__mul__` in qutip/core/data/base.pyx and `_ConstantElement.__matmul__` and  `_EvoElement.__matmul__` both in qutip/core/cy/_element.pyx.  While never used, the `__mul__` methods in the last file would break if called in the wrong order.
- One of the automated tests in github action should run using cython 3.

ps. This could be solved in 2 PR, an easy one for the first bullet point and another one more involved for the 2 others.

**Comment by Prashik123** [comment]
Hi Eric, I would like to work on this issue. Can you give me a bit more details on this?

**Comment by Ericgig** [comment]
@Prashik123, sure you can work on it.

If you are not sure where to start, install qutip from source using the version 3 of cython in pre-release. You will get a lot of warnings related to the point 1 above. Fix those warnings and make a PR.
