### ISSUE TITLE
Encountering TypeError on second run of any code on Linux

### ISSUE THREAD

**Issue by prem314** [qutip/qutip#2121]
### Bug Description

I am encountering a TypeError whenever I run any code for the second time. The behaviour is as expected when I run the code for the first time. I am encountering this error only on Linux. It is working fine on my Windows laptop.

### Code to Reproduce the Bug

```shell
from qutip import *

import numpy as np

import matplotlib.pyplot as plt

qutip.about()
```

### Code Output

```shell
File "/home/premkr/.local/lib/python3.7/site-packages/qutip/operators.py", line 80, in jmat
    A = 0.5 * (_jplus(j) + _jplus(j).getH())

TypeError: unsupported operand type(s) for +: 'fast_csr_matrix' and 'fast_csr_matrix'
```

### Expected Behaviour

QuTiP Version:      4.7.1
Numpy Version:      1.21.6
Scipy Version:      1.7.3
Cython Version:     0.29.33
Matplotlib Version: 3.0.2
Python Version:     3.7.3
Number of CPUs:     8
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Linux (x86_64)
Installation path:  /home/premkr/.local/lib/python3.7/site-packages/qutip

### Your Environment

```shell
QuTiP Version:      4.7.1
Numpy Version:      1.21.6
Scipy Version:      1.7.3
Cython Version:     0.29.33
Matplotlib Version: 3.0.2
Python Version:     3.7.3
Number of CPUs:     8
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Linux (x86_64)
Installation path:  /home/premkr/.local/lib/python3.7/site-packages/qutip
```

**Comment by hodgestar** [comment]
This is quite odd because running this code again should do almost nothing. How are you running the code again? Are you running it in a Jupyter notebook and are you using something that reloads modules? E.g. `%autoreload`?

Could you try shortening the code that you run twice? Is just running `import qutip` twice sufficient?

Could you also provide the full traceback and not just the last two lines?

**Comment by prem314** [comment]
I am using spyder. When I run the code once by pressing F5 button, then I get expected behaviour. But when I press F5 again, then I get error. If I modify the code and press F5, same error. If I restart spyder, then again I do not get any error on the first run, but the error repeats on subsequent runs.

Yes, just running `import qutip` also gives the same error.

I guess you are asking for the full error message and not just the last two lines. Here it is for `import qutip` for two subsequent runs.-

IN [1]: runfile('/home/premkr/Dropbox/work/python/qutip/gksl_learning.py', wdir='/home/premkr/Dropbox/work/python/qutip')

IN [2]: runfile('/home/premkr/Dropbox/work/python/qutip/gksl_learning.py', wdir='/home/premkr/Dropbox/work/python/qutip')
Traceback (most recent call last):

  File "<ipython-input-2-af424448e75a>", line 1, in <module>
    runfile('/home/premkr/Dropbox/work/python/qutip/gksl_learning.py', wdir='/home/premkr/Dropbox/work/python/qutip')

  File "/usr/lib/python3/dist-packages/spyder_kernels/customize/spydercustomize.py", line 678, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python3/dist-packages/spyder_kernels/customize/spydercustomize.py", line 106, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/premkr/Dropbox/work/python/qutip/gksl_learning.py", line 11, in <module>
    import qutip

  File "/home/premkr/.local/lib/python3.7/site-packages/qutip/__init__.py", line 106, in <module>
    from qutip.qobj import *

  File "/home/premkr/.local/lib/python3.7/site-packages/qutip/qobj.py", line 2526, in <module>
    import qutip.superop_reps as sr

  File "/home/premkr/.local/lib/python3.7/site-packages/qutip/superop_reps.py", line 74, in <module>
    _SINGLE_QUBIT_PAULI_BASIS = (identity(2), sigmax(), sigmay(), sigmaz())

  File "/home/premkr/.local/lib/python3.7/site-packages/qutip/operators.py", line 278, in sigmax
    return 2 * jmat(1 / 2, 'x')

  File "/home/premkr/.local/lib/python3.7/site-packages/qutip/operators.py", line 80, in jmat
    A = 0.5 * (_jplus(j) + _jplus(j).getH())

TypeError: unsupported operand type(s) for +: 'fast_csr_matrix' and 'fast_csr_matrix'

**Comment by hodgestar** [comment]
If you are using Spyder and its User Module Reloader (UMR), could you try finding the preference `Set UMR excluded (not reloaded) modules` and add `qutip` to the list of modules to exclude?

**Comment by hodgestar** [comment]
Yay, I'm glad that helped.

I'm going to close this issue since it doesn't appear to be a bug in QuTiP, but happy to reopen it if that proves wrong & happy to keep helping with debugging here for a bit.

Reloading modules in Python often results in strange behaviour. Perhaps also adding `numpy` and `scipy` to the modules not to reload will help?

I did try using `importlib.reload(qutip)` but I couldn't replicate your issue that way,

**Comment by prem314** [comment]
Thanks. I added numpy, scipy and matplotlib to the modules not to be reloaded, and the issue seems to have resolved.

By the way, I am using an old version of spyder on my device. Could that be the cause of this issue? I do not have the admin control over the device, so if that is likely a cause, I will ask the admin to update spyder.

**Comment by hodgestar** [comment]
I don't know Spyder well, but it is not unlikely that a newer version includes some improvements to reloading. If might be nice to have a newer version of your development environment regardless?

Glad everything is working for you now!
