### ISSUE TITLE
ENR states errors with v5 solvers

### ISSUE THREAD

**Issue by nwlambert** [qutip/qutip#2122]
### Bug Description

ENR states and operators produce an error when used with v5 solvers (mesolve and mcsolve at least, sesolve seems ok).

Key feature of ENR states is that dims and shape do not match, which can cause issues if dims and not shape are used in various operations.  Chatted with @hodgestar and in this case we think we pinned it down to iadd in QobjEvo creating an identity matrix based on the dims and not the shape.

https://github.com/qutip/qutip/blob/afd160bce00df522b9bcb0f856bc06d63296998d/qutip/core/cy/qobjevo.pyx#L459

though perhaps other issues could arise.

### Code to Reproduce the Bug

```shell
from qutip import *
import numpy as np
N = 4                        # number of cavities
M = 2                        # number of cavity states
dims = [M] * N
#The number of excitations in the chain
excitations = 1              # total number of excitations
initial_excitiations = 1     # initial number of excitations
#Construct ENR operators and states

d = enr_destroy(dims, excitations)
psi0 = enr_fock(dims, excitations, [initial_excitiations if m == 1 else 0 for m in range(N)])

H = sum([dd.dag() * dd for dd in d])

# coupling between cavities
e_ops = [dd.dag() * dd for dd in d]
c_ops = [0.01 * dd for dd in d]
times = np.linspace(0, 250, 1000)
result = mesolve(H, psi0, times, c_ops, e_ops)

#More minimal failure can be found with running this instead of mesolve:
H=QobjEvo(H)
QobjEvo(H+0)
```

### Code Output

```shell
line 24, in <module>
    QobjEvo(H)
  File "qutip/core/cy/qobjevo.pyx", line 196, in qutip.core.cy.qobjevo.QobjEvo.__init__
  File "qutip/core/cy/qobjevo.pyx", line 757, in genexpr
  File "/home/neill/anaconda3/envs/qutip5dev/lib/python3.11/site-packages/qutip-5.0.0.dev0+nogit-py3.11-linux-x86_64.egg/qutip/core/qobj.py", line 134, in out
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/neill/anaconda3/envs/qutip5dev/lib/python3.11/site-packages/qutip-5.0.0.dev0+nogit-py3.11-linux-x86_64.egg/qutip/core/qobj.py", line 408, in __add__
    return Qobj(_data.add(self._data, other._data),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "qutip/core/data/dispatch.pyx", line 583, in qutip.core.data.dispatch.Dispatcher.__call__
  File "qutip/core/data/dispatch.pyx", line 292, in qutip.core.data.dispatch._constructed_specialisation.prebound
  File "qutip/core/data/add.pyx", line 122, in qutip.core.data.add.add_csr
  File "qutip/core/data/add.pyx", line 144, in qutip.core.data.add.add_csr
  File "qutip/core/data/add.pyx", line 36, in qutip.core.data.add._check_shape
ValueError: incompatible matrix shapes (5, 5) and (16, 16)
```

### Expected Behaviour

should work!

### Your Environment

```shell
QuTiP Version:      5.0.0.dev0+nogit
Numpy Version:      1.24.1
Scipy Version:      1.10.0
Cython Version:     0.29.33
Matplotlib Version: 3.6.3
Python Version:     3.11.0
Number of CPUs:     28
BLAS Info:          Generic
INTEL MKL Ext:      False
Platform Info:      Linux (x86_64)
```

**Comment by hodgestar** [comment]
Somewhat related -- I'd like to have `qeye_like(op)` that takes an operator and produces the appropriate identity. One might naively think that `qeye(dims[0])` does the right thing, but this issue shows that the situation is more complex than that. 

We can already solve this without #1996 by just constructing a data object identity with the right shape and passing that to Qobj with the correct dims (but #1996 will make the situation a lot clearer).

**Comment by Ericgig** [comment]
The `qeye_like` would be great. potential `good first issue`?
Presently I think enr is the only exception to `qeye(dims[0])` working.
I think ENR dims are wrong here: dims should contain the information about the space of the states and operators and with enr important information is missing.

**Comment by hodgestar** [comment]
Re `qeye_like`: It sounds like a great first issue.

Re ENR: Agreed information is missing.

**Comment by Ericgig** [comment]
`qeye_like` and ENR dimensions have been created.
