### ISSUE TITLE
ptrace() Qobj method returns a ket if no subsystem is traced out

### ISSUE THREAD

**Issue by udevd** [qutip/qutip#2129]
### Bug Description

When trying to perform a trivial partial trace (of a ket) when no subsystem is traced over (all subsystems are kept), the result is a ket.

### Code to Reproduce the Bug

```shell
from qutip import tensor,basis
psi = tensor(basis(2, 0), basis(2, 1))
print(psi.ptrace([0,1]))
```

### Code Output

```shell
Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]]
```

### Expected Behaviour

A density operator should be returned for consistency. The documentation (https://qutip.org/docs/latest/guide/guide-tensor.html) also mentions that: 

> Note that the partial trace always results in a density matrix (mixed state), regardless of whether the composite system is a pure state (described by a state vector) or a mixed state (described by a density matrix)

### Your Environment

```shell
QuTiP version: 4.7.1
```

### Additional Context

The issue seems to originate in _ptrace_dense (see https://qutip.org/docs/latest/modules/qutip/qobj.html), where the following code appears:
```
    if not dtrace:
        # If we are keeping all dimensions, no need to construct an ndarray.
        return Q.copy()
```
A projector onto the state should be returned here instead of the copy of the state.

**Comment by AGaliciaMartinez** [comment]
Thanks for letting us know! Fortunately, this is already fix in 5.0.0 but it would good to also change this for qutip 4.7.

**Comment by udevd** [comment]
The problem seems pretty simple, I think I could take care of it. However, I don't have much experience in collaborative programming, in particular I don't know what the local customs are. (I know how to use git, but I'm not familiar with the layout of the library, what tests should I perform [or even add my own, since this issue wasn't noticed before 5.0.0] etc.)

**Comment by udevd** [comment]
Sorry, didn't mean to close the issue, just a missclick.

**Comment by yash-gupta167** [comment]
A possible workaround for this issue is to manually convert the resulting ket state to a density operator by taking the outer product of the state with itself.
For example:
```
from qutip import tensor,basis
psi = tensor(basis(2, 0), basis(2, 1))
rho = psi * psi.dag()
print(rho.ptrace([0,1]))
```
This should give you the expected density operator as the result of the partial trace.
Please Let me know, if I am going correct, please do assist me further on this issue

**Comment by udevd** [comment]
I would check if the result is indeed a ket first. That's the code I'm using at the moment as a workaround:
```
        reduced_density_matrix = state.ptrace(qubits)
        # Check if the result is a ket -- see https://github.com/qutip/qutip/issues/2129
        if reduced_density_matrix.isket:
            # Turn the ket into a density operator
            reduced_density_matrix = ket2dm(reduced_density_matrix)
```

**Comment by yash-gupta167** [comment]
Thank you for the acknowledgement! Should I work further upon this issue, Please let me know and Provide me further assistance.
