### ISSUE TITLE
mcsolve many partially traced matrixes simultaneously

### ISSUE THREAD

**Issue by partus** [qutip/qutip#213]
In mcsolve_f90
`ptrace_sel` specifies which dimensions you want to keep after calculation, and it's a useful feature, but suppose you have a system containing 100 electrons, and what you need is to know evolution of density matrix of each electron. You cant keep the state of the   whole system in memory as it will take too much memory. 
The problem is that with ptrace_sel you can get  only one partially traced  density matrix.(if we consider the system with electrons, you can monitor only one electron or several electrons)
So it would be nice to have functionality  which will allow to get many partially traced matrixes simultaneously.

**Comment by nonhermitian** [comment]
I believe we are not supporting any changes to the Fortran code now that the mcsolver is on par performance wise.  Thus closing this question.
