### ISSUE TITLE
EnhancedTextProgressBar not coherent with docstring of BaseProgressBar

### ISSUE THREAD

**Issue by NathalyaaHikari** [qutip/qutip#2148]
### Bug Description

When initializing an `EnhancedTextProgressBar` object the `__init__` method is calling the `start` method of it's super class instead of it's own. When then using `update` (without calling `start` manually again) there will be an `AttributeError` because `width` is not getting initialized by `__init__`

### Code to Reproduce the Bug

```shell
from qutip.ui.progressbar import *

n = 10
a = EnhancedTextProgressBar(n)
# a.start(n)
for i in range(n):
    a.update(i)
a.finished()
```

### Code Output

```shell
Traceback (most recent call last):
  File "C:\Users\Name\Desktop\qutip_bug.py", line 6, in <module>
    a.update(i)
  File "C:\Users\Name\AppData\Local\Programs\Python\Python311\Lib\site-packages\qutip\ui\progressbar.py", line 96, in update
    all_full = self.width - 2
               ^^^^^^^^^^
AttributeError: 'EnhancedTextProgressBar' object has no attribute 'width'
```

### Expected Behaviour

Proper initialization of the `width` attribute by `EnhancedTextProgressBar.__init__`

### Your Environment

```shell
QuTiP Version:      4.7.1
Numpy Version:      1.24.2
Scipy Version:      1.10.1
Cython Version:     0.29.33
Matplotlib Version: 3.7.1
Python Version:     3.11.0
Number of CPUs:     8
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Windows (AMD64)
```

### Additional Context

Currently in master the `__init__` for both `TextProgressBar` and `EnhancedTextProgressBar` have been commented out and made to just pass. See https://github.com/qutip/qutip/blob/af49884aa1db47a980626ac00adfe83277d8d261/qutip/ui/progressbar.py#L66 and https://github.com/qutip/qutip/blob/af49884aa1db47a980626ac00adfe83277d8d261/qutip/ui/progressbar.py#L94

I would suggest making them both call their own `start` method to omit an additional call of start by the user right after initialization. This would also make both classes be in line with the usage suggested by the docstring of `BaseProgressBar.` Otherwise I would suggest to include the call to start in said docstring.

As I'm pretty new to github and git in general I would like to try and create a PR myself once you give me approval for the suggested change here.

**Comment by Ericgig** [comment]
Fixed in v5
