### ISSUE TITLE
Fermionic creation and annihilation operators

### ISSUE THREAD

**Issue by BoxiLi** [qutip/qutip#2165]
### Problem Description

QuTiP has bosonic `destroy` and `create` operators that satisfy the commutation relation. The same can be defined for fermions, with the name `fermionic_destroy`, and `fermionic_create` (better suggestions on names are welcome) that satisfy the anti-commutation relations.

### Proposed Solution

- Implement the function `fermionic_destroy`, and `fermionic_create`.
- Add tests to verify the implementation.
- Add docstrings with the math formulas and conventions used.

The mathematical formulas and other related  issues:
- https://mareknarozniak.com/2020/10/14/jordan-wigner-transformation/ (note that $\sigma^{-}=\sigma_x+i\sigma_y$, which is predefined in qutip).
- https://github.com/qutip/qutip/issues/863

**Comment by rum1887** [comment]
hello team, this is interesting! I'm working out the details rn. Will get back to you !

**Comment by QuantumAsma** [comment]
Hi! I'd like working on this issue.

**Comment by QuantumAsma** [comment]
@BoxiLi can I  work on this issue?

**Comment by BoxiLi** [comment]
Hi @QuantumAsma, I'm afraid that there is already a PR on this issue. Hope you could find a different task!

**Comment by natestemen** [comment]
@khnikhil remember to comment on this issue so that @BoxiLi can assign it to you!

**Comment by nathanshammah** [comment]
Congrats @khnikhil!

**Comment by khnikhil** [comment]
> @khnikhil remember to comment on this issue so that @BoxiLi can assign it to you!

Thanks Nate :) and big thank you to @BoxiLi and @Ericgig for the support and detailed comments!
