### ISSUE TITLE
MemoryError when trying to allocate big numpy array

### ISSUE THREAD

**Issue by silvio-sjsj** [qutip/qutip#2176]
### Describe the Issue!

I have a big matrix which is a [QuTiP](https://qutip.org/) object. I am trying to run this line of code:

    ops_numpy = [op.full() for op in m_ops] # convert the QuTiP Qobj to numpy arrays

But I am getting the following error:

    MemoryError: Unable to allocate 16.0 TiB for an array with shape (1048576, 1048576) and
    data type complex128

Here, `m_ops` is a list with `len(m_ops) = 27` and every `m_ops[i]` is a quantum object of shape

    In [91]: m_ops[1].shape
    Out[91]: (1048576, 1048576)

Ok, I can see that I am trying to convert a QuTiP object into a numpy array but this object is so big that I have a memory issue. My question is simple: is there any way to overcome this issue? can I 'cut' the object in smaller pieces to convert it and then put the "pieces back together"?

I really have no idea. Maybe I am not doing in the optimal way but I was working with really smaller matrix until this one and I didn't foresaw this problem.

Any help or reference will be highly appreciated. This is really important for me.

 ----------------------------------------------------------------

EDIT with the full code:

    """."""
    import numpy as np
    import tensorflow as tf
    from qutip import tensor
    from qutip import sigmax, sigmaz, sigmay
    from qutip import coherent, coherent_dm, expect, Qobj, fidelity, hinton
    from tqdm.auto import tqdm

    #%load_ext autoreload
    tf.keras.backend.set_floatx('float64') # Set float64 as the default

    # Local paths:
    local_path = "0_qst_master/cgan_tf_20qb/%s"
    data_path = "0_qst_master/cgan_tf_20qb/data/%s"

    # Reading projectors
    projs_settings = np.loadtxt(data_path % 'measurement_settings.txt', dtype=str)

    X = sigmax()
    Y = sigmay()
    Z = sigmaz()

    m_ops = [] # measurement operators

    def string_to_operator(basis):  
        mat_real = []
    
        for j in range(len(basis)):
            if basis[j] == 'X':
                mat_real.append(X)     
            if basis[j] =='Y':
                mat_real.append(Y)     
            if basis[j] =='-Y':
                mat_real.append(-Y)     
            if basis[j] == 'Z':
                mat_real.append(Z)   
        return mat_real

    for i in range(27):
        U = string_to_operator(projs_settings[i])
        U = tensor(U)
        m_ops.append(U)

    ops_numpy = [op.full() for op in m_ops] # convert the QuTiP Qobj to numpy arrays

Another EDIT:

The `measurement_settings.txt` is a .txt file with the following:

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/YtF6j.png

**Comment by BoxiLi** [comment]
NumPy uses dense array. You simply need such a big memory to store those NumPy matrices. There is no way around it.

It is important to understand what you want to do with those matrices afterwards. Keeping them as dense matrices is just infeasible. Maybe you can try to get the sparse data by `Qobj.data` and work with that.

**Comment by BoxiLi** [comment]
`Qobj` also supports `tr()`. It would be nice for performance reasons to stay in QuTiP if possible. But if you do want to get the raw data, `Qobj.data` returns you a custom version of scipy's sparse matrix. You need to use `scipy.sparse.csr_matrix(qobj.data)` to make it compatible with the default scipy csr matrix before using anything like `scipy.sparse.linalg` I think.

**Comment by hodgestar** [comment]
@BoxiLi has kindly showed how to achieve the desired result. Closing this for now.
