### ISSUE TITLE
Deprecation warning with numpy 1.25 for np.product

### ISSUE THREAD

**Issue by LaurentBergeron** [qutip/qutip#2179]
### Bug Description

A new warning is raised when using qutip with numpy 1.25:

`photonic-quantum-circuit-simulator-8sWQjw5Q-py3.9\lib\site-packages\qutip\superop_reps.py:241: DeprecationWarning: product is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use prod instead.
    nq = _nq(q_oper.dims)`

Should be a simple fix of renaming `np.product` by `np.prod`.

### Expected Behaviour

No warnings should be raised

### Your Environment

```shell
QuTiP Version:      4.7.1
Numpy Version:      1.25.0
Scipy Version:      1.10.1
Cython Version:     None
Matplotlib Version: 3.7.1
Python Version:     3.9.13
Number of CPUs:     16
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Windows (AMD64)
```

### Additional Context

The whole codebase should be searched for `np.product`

**Comment by Ericgig** [comment]
The fix is already merged in the qutip-4.7.X branch (#2178).
I can't say when the patch will be officially released, but I am expecting it to come sooner than later.
