### ISSUE TITLE
.pyx file is not deleted after compilation

### ISSUE THREAD

**Issue by qilesu** [qutip/qutip#2231]
### Bug Description

In `qutip.qobjevo.compile`, on line 1646, the `.pyx` file created by qutip is registered into the global variable `coeff_files` containing a `_file_list` object using the method `coeff_files.add(file_)`. The `add` method appends a `.pyx` extension on line 60 to the string `file_`
```
self.files += [file_ + ".pyx"]
```
However, the `file_` string generated by `_compiled_coeffs` already has the file extension, judging from the return value of `qutip.qobjevo_codegen._import_str`, on line 54
```
    return coeff_obj, try_file + ext
```
I believe this causes `coeff_files.clean()` on line 1697 of `qutip.qobjevo.compile` to not delete the `.pyx` files after the cython class has been loaded.

### Code to Reproduce the Bug

```shell
import qutip as qt
qt.sesolve([qt.identity(2), [qt.sigmax(), 'sin(t)']], qt.basis(2, 0),
    tlist=[0, 2])
```

### Code Output

```shell
creates the file cqobjevo_compiled_coeff_6095589624050.pyx in the working directory.
```

### Expected Behaviour

The `.pyx` file in the working directory should be deleted.

### Your Environment

```shell
QuTiP Version:      4.7.2
Numpy Version:      1.25.2
Scipy Version:      1.11.2
Cython Version:     0.29.36
Matplotlib Version: 3.7.2
Python Version:     3.10.12
Number of CPUs:     4
BLAS Info:          Generic
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Linux (x86_64)
```

**Comment by Ericgig** [comment]
Thank you for reporting.
