### ISSUE TITLE
qutip.testing.run() failed

### ISSUE THREAD

**Issue by HamadPhy** [qutip/qutip#2245]
### Describe the Issue!

I install Qutip from source by following the instruction.
After installing the build requirements, I ran the following command,

qutip.testing.run() 
At around 14%, the test halt, giving no report. i tried few times but same results.
(anaconda3/lib/site-packages/qutip/tests/test_correlation.py::TestTimeDependence::test_hamiltonian_from_function_2ls PASSED [ 14%]
anaconda3/lib/site-packages/qutip/tests/test_correlation.py::TestTimeDependence::test_correlation_c_ops_td[me] PASSED [ 14%]
anaconda3/lib/site-packages/qutip/tests/test_correlation.py::TestTimeDependence::test_correlation_c_ops_td[mc]     )

![pyTest](https://github.com/qutip/qutip/assets/125566140/725c9acc-d29d-4bbd-a337-e4979a844151)
![pyth](https://github.com/qutip/qutip/assets/125566140/cb641e22-f5c9-4afa-bf98-e990d144bd48)

**Comment by Ericgig** [comment]
We don't support cython 3.X and the fix for matplotlib 3.8 is not released yet.
My guess is if you roll back cython to 0.29.36 it will work.

Fix for cython 3.X will be in the next major release.

**Comment by HamadPhy** [comment]
> Thank you for your reply. However, the problem didn't solve after installing cython 0.29.36.

![image](https://github.com/qutip/qutip/assets/125566140/ed96af0d-3dc7-497c-91f9-196154d7a13f)

**Comment by hodgestar** [comment]
Closing this because the original issue is resolved.

Some support for Cython 3.0 is now available, but the situation is still a bit fluid and complex as Cython 3.0 stabilizes. We'll likely need a few more specific issues to deal with Cython 3.0 support. Anyone reading feel free to open such an issue.
