### ISSUE TITLE
`mesolve` outputs different results for H_d in form [ops, func] and [ops, ndarray] 

### ISSUE THREAD

**Issue by RunawayFancy** [qutip/qutip#2253]
### Bug Description

I try to use `mesolve` to do a system dynamics with a system static Hamiltonian `H_0` under a driving term governed by a cosine shape waveform `cos_waveform`. 

We try to method to construct the dynamical hamiltonain `H_d` in two ways: one is `H_d = [H_0, [a_dag + a, cos_waveform]]` and `H_d = [H_0, [a_dag + a, cos_waveform_array]]`, corresponding to `[ops, func]` and `[ops, ndarray]` cases, respectively.

You can see from the code I provided, the cos_waveform_array is given by `drive_pulse_y = np.array([cos_waveform(t, None) for t in tlist], dtype=np.complex128)`.

We expect the simulation result of the system should be the same under these two cases. We plot the diagonal matrix elements of the density matrix to see the dynamics of the system. But the result are different.

I try to find the issue probably happens due to function `mesolve._qobjevo_set` or the different treatments in `QobjEvo.ops` as it contains a string `"func"` and `"ndarray"` in our cases, and the `"ndarray"` case has some code errors.

### Code to Reproduce the Bug

```shell
from qutip import *
import numpy as np
import matplotlib.pyplot as plt

# Define the pulse

t_rising = 15 # ns
t_g = t_rising + 150
phase = 0
freq = 6.3
ampli = -0.2 * 2*np.pi
t_delay = 0

def cos_waveform(t, args):
    t_relative = t - t_delay
    if t_relative < 0: 
        return 0
    if 0 <= t_relative <= t_rising:
        return ampli/2 * np.cos(freq * np.pi * 2 * t_relative + phase)* (1 - np.cos(np.pi * t_relative / t_rising)) 
    if t_rising < t_relative < t_g - t_rising:
        return ampli * np.cos(freq * np.pi *  2 * t_relative)
    if t_g - t_rising <= t_relative  <= t_g:
        return ampli/2 * np.cos(freq * np.pi * 2 * t_relative + phase)* (1 - np.cos(np.pi * ( t_relative - t_g + 2 * t_rising)/t_rising))
    if t_g < t_relative: 
        return 0

# Setup a single transmon
N = 4
w = 6.3
alpha = -0.3

a = destroy(N)
a_dag = a.dag()

H_0 = w* a_dag * a + alpha/2 * a_dag * a_dag * a * a
H_0 *= 2 * np.pi
state_0 = H_0.eigenstates()[1][0]
state_1 = H_0.eigenstates()[1][1]
state_2 = H_0.eigenstates()[1][2]

# Simulation time and steps
s_time = 200
s_step = 2000

tlist = np.linspace(0,s_time ,s_step)
option = Options(rtol=1e-8)

# Try [ops, func] case
H_d = [H_0, [a_dag + a, cos_waveform]]
result = mesolve(H_d, ket2dm(state_0), tlist, options=option)

plt.plot(tlist,expect(result.states, state_0 * dag(state_0)), label=r'$\rho_{0,0}$');
plt.plot(tlist,expect(result.states, state_1 * dag(state_1)), label=r'$\rho_{1,1}$');
plt.plot(tlist,expect(result.states, state_2 * dag(state_2)), label=r'$\rho_{2,2}$');
plt.ylabel(r"$\rho_{ij}$")
plt.xlabel("t (ns)")
plt.legend()
plt.show()

# Try [ops, ndarray] case
drive_pulse_y = np.array([cos_waveform(t, None) for t in tlist], dtype=np.complex128)
H_d = [H_0, [a_dag + a, drive_pulse_y]]
result = mesolve(H_d, ket2dm(state_0), tlist, options=option)

plt.plot(tlist,expect(result.states, state_0 * dag(state_0)), label=r'$\rho_{0,0}$');
plt.plot(tlist,expect(result.states, state_1 * dag(state_1)), label=r'$\rho_{1,1}$');
plt.plot(tlist,expect(result.states, state_2 * dag(state_2)), label=r'$\rho_{2,2}$');
plt.ylabel(r"$\rho_{ij}$")
plt.xlabel("t (ns)")
plt.legend()
plt.show()

# The simulation results are different, for the same system, same option, same initial state, the same driving pulse, just the input form of the driving pulse to the mesolve is different, but this should not cause differences in the result.
```

### Code Output

```shell
Two plots.
```

### Expected Behaviour

The simulation results are different, for the same system, same option, same initial state, the same driving pulse, just the input form of the driving pulse to the mesolve is different, but this should not cause differences in the result.

The simulation result using `[ops, func]` should be correct, and the case `[ops, ndarray]` should be wrong.

### Your Environment

```shell
QuTiP Version:      4.7.2
Numpy Version:      1.25.2
Scipy Version:      1.11.1
Cython Version:     None
Matplotlib Version: 3.7.2
Python Version:     3.10.11
Number of CPUs:     8
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Windows (AMD64)
```

### Additional Context

For `[ops, func]` case, the simulation result is
![image](https://github.com/qutip/qutip/assets/54537763/1a054b23-7c94-44be-af37-9ef67550e3a1)
which is correct.

For `[ops, ndarrray]` case, the simulation result is:
![image](https://github.com/qutip/qutip/assets/54537763/7b58ab46-1604-4768-be89-e8e9bc704935)
which is incorrect.

**Comment by Ericgig** [comment]
Looking at it quickly, I see a period of about `0.16` for your wave, but a sampling rate of 0.1` for the array...
This sampling is insufficient to properly represent the wave.

**Comment by RunawayFancy** [comment]
Oh, yes, I increase the sampling rate. Indeed the correct result is recovered. Great thanks
