### ISSUE TITLE
Improve documentation for mesolve's support of QobjEvo

### ISSUE THREAD

**Issue by amirebrahimi** [qutip/qutip#2270]
In the [documentation for `mesolve`](https://qutip.org/docs/latest/apidoc/functions.html?highlight=mesolve#module-qutip.mesolve) it says that callback functions are not supported for `c_ops`, but [support does exist for QobjEvo](https://github.com/qutip/qutip/blob/qutip-4.7.X/qutip/mesolve.py#L275), which are callables.

Separately, `propagator` [checks](https://github.com/qutip/qutip/blob/qutip-4.7.X/qutip/propagator.py#L96) that `c_ops` are [only `Qobj` or lists of `Qobj`](https://github.com/qutip/qutip/blob/qutip-4.7.X/qutip/solver.py#L910), but can actually be `QobjEvo` due to `mesolve`'s support. It's easy to workaround this by setting `_safe_mode=False`.

Although it seems qutip 5 has fixed these issues it would be good to have the documentation reflect the current level of support.

**Comment by Ericgig** [comment]
It should be fixed with v5's release.
Now the documentation says that `c_ops` can be a list of `QobjEvo` or anything that can be interpreted as such, including functions.
