### ISSUE TITLE
QuTiP compatibility with `accelerate` BLAS on Apple M1/M2

### ISSUE THREAD

**Issue by joeybarreto** [qutip/qutip#2273]
### Bug Description

Following the advice from [this SE post](https://stackoverflow.com/questions/70240506/why-is-numpy-native-on-m1-max-greatly-slower-than-on-old-intel-i5), I have been trying to install QuTiP in a fresh environment along with the BLAS `accelerate` libraries specific to the Apple M1/M2 chips, in order to get a speedup by using a BLAS library designed for my laptop.

In a blank environment, I first ran `conda install numpy "libblas=*=*accelerate"`, followed by `conda install qutip` and got the following error message: 

```
The following specifications were found to be incompatible with your system:

  - feature:/osx-arm64::__osx==13.4=0
  - feature:|@/osx-arm64::__osx==13.4=0
  - qutip -> numpy[version='>=1.22.4,<2.0a0'] -> __osx[version='>=10.9']

Your installed version is: 13.4
```
This is odd given that I am using `numpy 1.26.2` and `Mac OS 13.4`, which appear to satisfy the requirements.  Instead, I tried using `pip install qutip` which circumvented this error, but results in incorrect behavior as described below.

### Code to Reproduce the Bug

```shell
import numpy as np
import qutip as qt

X = qt.sigmax()
print(np.linalg.eigh(X)[1])
```

### Code Output

```shell
`
[[-0.70710678-0.70710678j  0.70710678+1.20710678j]
 [ 0.70710678+0.70710678j  0.70710678+0.5j       ]]
`
```

### Expected Behaviour

`
[[-0.70710678+0.j  0.70710678+0.j]
 [ 0.70710678+0.j  0.70710678+0.j]]
`

### Your Environment

```shell
QuTiP Version:      4.7.3
Numpy Version:      1.26.2
Scipy Version:      1.11.4
Cython Version:     None
Matplotlib Version: 3.8.2
Python Version:     3.12.0
Number of CPUs:     10
BLAS Info:          Generic
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Darwin (arm64)
```

### Additional Context

I am just comparing the behavior between two environments.  The first one correctly diagonalizes the Pauli X operator with a Hadamard, and the second does not.  The "correct" environment uses a standard numpy 1.26.2 install, with qutip installed with conda.  The "incorrect" environment uses the `accelerate` numpy install, and qutip installed with pip.  Each environment has the same `qutip.about()` return string.

In reality, my use case is more complex than this, but I managed to boil down the error to faulty matrix diagonlization.  I also want to add that I do indeed get a factor of ~4 speedup in pure numpy examples (like those linked in the SE post), so it's only when integrating with QuTiP that something goes awry.  It might be the case that there really is some compatibility issue, and using `pip` doesn't really fix anything.  I'm mainly wondering whether this behavior is expected, or if there is a correct way of getting QuTiP and the `accelerate` BLAS to work together that I am missing.

**Comment by Ericgig** [comment]
You could try your simulation to run with `qutip.setting.eigh_unsafe = True`.
This will tell qutip to use `eig` instead of `eigh` and to the ortho-normalization manually. 

There are bugs with `eigh` on mac, see https://github.com/numpy/numpy/issues/24640, #1288...

**Comment by joeybarreto** [comment]
Thanks for the heads-up, I didn't know there were issues with `eigh` on Mac.  Where in QuTiP is the `qutip.setting.eigh_unsafe` attribute defined?  A quick search of the repo didn't turn up anything.  Also, I just came across an example where `eigh` succeeds on a complex Hermitian matrix, but `eig` fails, so now I'm pretty confused.
