### ISSUE TITLE
Non Unitary evolution using sesolve

### ISSUE THREAD

**Issue by ejblackwell** [qutip/qutip#2275]
### Bug Description

When passing sesolve a time independent Hamiltonian, there is still time-dependent evolution returned. It seems to depend on the number of time steps passed to the solver, with more time steps giving more drastic time-dependent evolution. 

### Code to Reproduce the Bug

```shell
import matplotlib.pyplot as plt
import numpy as np
from qutip import *

qubit_freq = 5000

# operators
a = destroy(2)

# Basis States
z_p = basis(2,0)
z_m = basis(2,1)
x_p = (z_p + z_m)/np.sqrt(2)
x_m = (z_p - z_m)/np.sqrt(2)
y_p = (z_p + 1j*z_m)/np.sqrt(2)
y_m = (z_p - 1j*z_m)/np.sqrt(2) 

psi0 = x_p

# Hamiltonian
H = qubit_freq*2*np.pi * (a.dag() * a + 1/2)

tlist = np.linspace(0, 0.1, 100000)

output1 = sesolve(H, psi0, tlist, e_ops=[a.dag()*a])
n_a = output1.expect[0]

# Plot Occupation with respect to time
fig, axes = plt.subplots(1, 1, figsize=(10,6))
axes.plot(tlist, n_a, label="Qubit")
axes.legend(loc=0)
axes.set_xlabel('Time')
axes.set_ylabel('Occupation probability')
plt.show()
```

### Expected Behaviour

The graph provided should be a flat line, indicating no time evolution. 

### Your Environment

```shell
QuTiP Version:      4.7.3
Numpy Version:      1.23.5
Scipy Version:      1.11.4
Cython Version:     3.0.6
Matplotlib Version: 3.7.1
Python Version:     3.10.12
Number of CPUs:     2
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Linux (x86_64)
```

### Additional Context

![image](https://github.com/qutip/qutip/assets/112031379/cfee4cd8-6b7a-4b9c-87b3-a81d45128132)

This plot shows a loss in population when beginning in the x state of a simple two level system. Playing around with the code, I find the slope of this line changes as you give a different number of points in tlist. This also happens with mesolve and mcsolve with no collapse operators (although I suspect this is because behind the scenes, it's just using sesolve).

**Comment by Ericgig** [comment]
This is numerical error from the ODE solver.
Try changing the solver tolerance:
`sesolve(..., options=Options(atol=1e-10)`

**Comment by ejblackwell** [comment]
Thanks for the help! I've tried changing both atol and rtol up to 10^-30 to no effect. I've also (I think) played with all of the solver settings that are relevant to sesolve to no effect.

**Comment by Ericgig** [comment]
This is what I get by changing `atol`:

![image](https://github.com/qutip/qutip/assets/17770236/071d6300-a78c-41f6-ab68-60d75127a50a)

**Comment by Ericgig** [comment]
Closing as it is stale. 
Hopefully you solved the issue.
Feel free to reopen if you're still stuck.
