### ISSUE TITLE
Help requested: How to add controllable phase in Hamiltonian?

### ISSUE THREAD

**Issue by christopherkang** [qutip/qutip#2297]
### Describe the Issue!

I'm trying to follow the [CRAB / pulse optimizer tutorial](https://github.com/qutip/qutip-notebooks/blob/master/examples/control-pulseoptim-CRAB-QFT.ipynb) but realize that my Hamiltonian takes a slightly different form than the control form ("H_c") they use. They use a list of QObjs w/ variable amplitude, whereas my Hamiltonian has the following term which seems challenging to input:

$$ 
f_j(t) (a_j e^{-i \phi_j(t)} - a^\dagger_j e^{i \phi_j(t)})
$$

Even for $j \in [1]$ only, how can I make it so that this term has two controls, one which controls the amplitude and one which controls the phase?

**Comment by Ericgig** [comment]
We use github issues for bug report or feature request.
Questions about usage often slip between the cracks.
They are best asked on the [google group](https://groups.google.com/g/qutip).
