### ISSUE TITLE
MemoryError when updating to latest qutip

### ISSUE THREAD

**Issue by Matt-Ord** [qutip/qutip#2299]
### Bug Description

Might just be me mis-using the new 5.X branch of Qutip. I get a memory error when upgrading to the new branch.

It appears to fail when performing self._to_dm(state) for each state. My states are vectors of length 800 - so it runs out of memory. Is it possible to request the solver only stores the wavefunction at each timestep? I want the wavefunction for each trajectory for each timestep. Alternatively one could introduce a new "proj" data storage to make this more efficient.

### Code to Reproduce the Bug

```shell
result = qutip.ssesolve(
        hamiltonian_qobj,
        initial_state_qobj,
        times.times,
        sc_ops=sc_ops,
        e_ops=[],
        options={
            "method": "euler",
            "progress_bar": "enhanced",
            "store_states": True,
            "keep_runs_results": True,
            "improved_sampling": False,
            "dt": times.delta_t / times.fundamental_n,
        },
        ntraj=n_trajectories,  # cspell:disable-line
    )
```

### Code Output

```shell
File "...", line 270, in solve_stochastic_schrodinger_equation
    result = qutip.ssesolve(
             ^^^^^^^^^^^^^^^
  File "...\.venv\Lib\site-packages\qutip\solver\stochastic.py", line 461, in ssesolve
    return sol.run(
           ^^^^^^^^
  File "...\.venv\Lib\site-packages\qutip\solver\multitraj.py", line 198, in run
    map_func(
  File "...\.venv\Lib\site-packages\qutip\solver\parallel.py", line 122, in serial_map
    remaining_ntraj = reduce_func(result)
                      ^^^^^^^^^^^^^^^^^^^
  File "...\.venv\Lib\site-packages\qutip\solver\result.py", line 645, in add   
    op(trajectory)
  File "...\.venv\Lib\site-packages\qutip\solver\result.py", line 519, in _reduce_states
    accu + self._to_dm(state)
    ~~~~~^~~~~~~~~~~~~~~~~~~~
  File "...\.venv\Lib\site-packages\qutip\core\qobj.py", line 134, in out
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "...\.venv\Lib\site-packages\qutip\core\qobj.py", line 408, in __add__   
    return Qobj(_data.add(self._data, other._data),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "qutip\\core\\data\\dispatch.pyx", line 392, in qutip.core.data.dispatch.Dispatcher.__call__
  File "qutip\\core\\data\\add.pyx", line 118, in qutip.core.data.add.add_csr
  File "qutip\\core\\data\\add.pyx", line 154, in qutip.core.data.add.add_csr
  File "qutip\\core\\data\\csr.pyx", line 159, in qutip.core.data.csr.CSR.copy
  File "qutip\\core\\data\\csr.pyx", line 542, in qutip.core.data.csr.empty_like
  File "qutip\\core\\data\\csr.pyx", line 533, in qutip.core.data.csr.empty
MemoryError
```

### Expected Behaviour

Code should not have to store the full density matrix, and should not lead to a memory error

### Your Environment

```shell
QuTiP Version:      5.0.0a2
Numpy Version:      1.26.3
Scipy Version:      1.12.0
Cython Version:     None
Matplotlib Version: 3.8.2
Python Version:     3.12.1
Number of CPUs:     4
BLAS Info:          Generic
INTEL MKL Ext:      False
Platform Info:      Windows (AMD64)
Installation path:  ...
```

**Comment by Ericgig** [comment]
About only storing kets, but not averaging into a dm, we can't do that yet, but it's easy to implement so if useful, we can add the option.

The error is not in the `_to_dm`, but in the addition, which is done in the sparse CSR format. No dense conversion are made. But the `proj` operator does not have a tidyup step, so any non-zero are kept, however small they are. This is also an easy fix that could help.

The `MemoryError` is also not that helpful, we should improve the error message to tell what size of arrays are allocated.

Thank you for reporting these and trying the alpha version.

I see you don't have cython, do you have a way to compile the source yourself? 
Once fixed, I would be curious to have you try the development version without waiting for a release.

**Comment by Matt-Ord** [comment]
Thanks for the quick response - currently I've just pip-installed the package, but I would be happy to use the main branch if you would be able to fix this. I would find this very useful - for the quantities I am interested in calculating I need much less than 800 repeats to get convergence. I understand it is possible to calculate the expectation directly in ssesolve but I find it is useful to save the states to a file so I have more freedom to calculate a range of different operators at a later date.

**Comment by Ericgig** [comment]
Saving to a file without averaging is possible.

`e_ops` accept any function `f(t: float, state: Qobj) -> number`. That function can save the state to a file and return a dummy value. However, it does not know which trajectories it belong to so it would only work with `serial_map`.

_Expectation functions_ are always called, it would remove the need to keep trajectories and store states.

`Qobj.data_as("CSR")` will extract the state as a scipy CSR matrix (if already in `csr`, does not do the conversion).

**Comment by Matt-Ord** [comment]
Yeah I'm not really interested in using e_ops this way - it feels like a hack. I really just want the states of each trajectory so I can do what I want, and it seems silly I have to also pay the price of storing the density matrix. Wouldn't there be significant overhead calling to python each step and opening/writing to a file

**Comment by Ericgig** [comment]
Yes, it's a hack, but it's probably the best option you have until we fix it. So if you are in an hurry for your research, just know the method exist.
