### ISSUE TITLE
Implement += operator between Qobj's

### ISSUE THREAD

**Issue by gabbence95** [qutip/qutip#2326]
### Problem Description

It would be nice, if one coud simply use th += operator for Qobj's. Now it raises TypeError:

```
--> 219     else: H_L_lab += H_L_laser
    220 return H_L_lab

TypeError: operand 'Qobj' does not support ufuncs (__array_ufunc__=None)
```

### Proposed Solution

By defining the method `__iadd__` in the constructor, it could be easily done.

**Comment by aadya940** [comment]
Hello! If I'm not wrong, it should be something like this:

```
def __iadd__(self, other):
    if other == 0:
        return self
    self._data = _data.add(self._data, other._data)
    self._isherm = (self._isherm and other._isherm) or None
    return self
```

What do you think?

**Comment by gabbence95** [comment]
Seems about right, thank you.

**Comment by hodgestar** [comment]
This does not raise a type error for me in either qutip 4.7.X or qutip 5.0.0a.
```python
>>> import qutip
>>> qutip.__version__
'4.7.3'
>>> x = qutip.sigmax()
>>> x += x
>>> x
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 2.]
 [2. 0.]]
```
and
```python
>>> import qutip
q>>> qutip.__version__
'5.0.0.dev0+ec33e6b'
>>> x = qutip.sigmax()
>>> x += x
>>> x
Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', isherm=True
Qobj data =
[[0. 2.]
 [2. 0.]]
```
Could you give a minimal reproducing example and the QuTiP version you're using?

**Comment by hodgestar** [comment]
This error message suggests to me that one of the things you're trying to add might be a numpy array:
```
TypeError: operand 'Qobj' does not support ufuncs (__array_ufunc__=None)
```

**Comment by gabbence95** [comment]
> This error message suggests to me that one of the things you're trying to add might be a numpy array:
> 
> ```
> TypeError: operand 'Qobj' does not support ufuncs (__array_ufunc__=None)
> ```

Yes, you are right, sorry. I am closing the issue.
