### ISSUE TITLE
Typos in qutip.expect()'s docstring

### ISSUE THREAD

**Issue by gabbence95** [qutip/qutip#2331]
### Bug Description

Two words in the docstring contain typos. See below.

### Code to Reproduce the Bug

```shell
from qutip import expect
print(expect.__doc__)
```

### Code Output

```shell
Parameters
----------
oper : qobj/array-like
    A single or a `list` or operators for expectation value.

state : qobj/array-like
    A single or a `list` of quantum states or density matrices.

Returns
-------
expt : float/complex/array-like
    Expectation value.  ``real`` if `oper` is Hermitian, ``complex``
    otherwise. A (nested) array of expectaction values of state or operator
    are arrays.
```

### Expected Behaviour

Parameters
----------
oper : qobj/array-like
    A single or a `list` **~~or~~** **_of_** operators for expectation value.

state : qobj/array-like
    A single or a `list` of quantum states or density matrices.

Returns
-------
expt : float/complex/array-like
    Expectation value.  ``real`` if `oper` is Hermitian, ``complex``
    otherwise. A (nested) array of expectaction values **~~of~~** **_if_** state or operator
    are arrays.

### Your Environment

```shell
QuTiP Version:      4.7.5
Numpy Version:      1.26.4
Scipy Version:      1.11.4
Cython Version:     None
Matplotlib Version: 3.8.3
Python Version:     3.12.2
Number of CPUs:     8
BLAS Info:          Generic
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Windows (AMD64)
```

**Comment by Ericgig** [comment]
@gabbence95 
Thank you for catching the error.
