### ISSUE TITLE
Add `dtype` to the printed output of `Qobj`.

### ISSUE THREAD

**Issue by Ericgig** [qutip/qutip#2339]
### Problem Description

`Qobj` and `QobjEvo` have the new property dtype that can greatly affect performance.
However, this new information can be hard to find. Having it included in the output of `__repr__` could help.

### Proposed Solution

An an dtype entry in `Qobj._str_header`.

### Additional Context

First advanced in #2328.

**Comment by rochisha0** [comment]
Can I work on this issue, @Ericgig ?
