### ISSUE TITLE
Negativity function does not work

### ISSUE THREAD

**Issue by nwlambert** [qutip/qutip#2345]
### Bug Description

The function `negativity() ` is currently broken because of a broken import of `partial_transpose()`.   This is probably an easy fix and good first issue, but more importantly we need a test for this function, and anything else that currently is not tested in `entropy.py`.

Also, might be useful to either properly support kets in negativity (i think it just assumes at the moment the input state is a density operator, and incorrectly acts on kets), or give a warning if a state is provided, and not a density operator.

### Code to Reproduce the Bug

```shell
import numpy as np
from qutip import *

test = (tensor(basis(2,0),basis(2,1)) + tensor(basis(2,1),basis(2,0)))/np.sqrt(2)
negativity(test * test.dag(),0)
```

### Code Output

```shell
123 """
    124 Compute the negativity for a multipartite quantum system described
    125 by the density matrix rho. The subsys argument is an index that
   (...)
    130     Experimental.
    131 """
    132 mask = [idx == subsys for idx, n in enumerate(rho.dims[0])]
--> 133 rho_pt = partial_transpose(rho, mask)
    135 if method == 'tracenorm':
    136     N = ((rho_pt.dag() * rho_pt).sqrtm().tr().real - 1)/2.0

TypeError: 'module' object is not callable
```

### Expected Behaviour

should be = 0.5

### Your Environment

```shell
QuTiP Version:      5.0.0.dev0+c745ace
Numpy Version:      1.26.3
Scipy Version:      1.11.4
Cython Version:     3.0.8
Matplotlib Version: 3.8.0
Python Version:     3.12.1
Number of CPUs:     28
BLAS Info:          Generic
INTEL MKL Ext:      False
Platform Info:      Linux (x86_64)
```

**Comment by vikas-chaudhary-2802** [comment]
@nwlambert I love to work on this issue.

**Comment by nwlambert** [comment]
thanks @vikas-chaudhary-2802 that would be great

**Comment by vikas-chaudhary-2802** [comment]
Unable to run the test cases in (entropy.py) it show this error 
<img width="850" alt="Screenshot 2024-03-20 at 2 48 54 AM" src="https://github.com/qutip/qutip/assets/147247481/710869a8-79e6-4941-b6d6-2ad0cf9fd76d">
Can you please suggest me the solution to solve it ?

**Comment by BoxiLi** [comment]
@vikas-chaudhary-2802 It looks like something went wrong with the installation. Make sure that you really installed the master branch and are testing it.

**Comment by nwlambert** [comment]
Sorry @vikas-chaudhary-2802 I didn't notice your question last week. As boxi said, might be a bad install or you are using the wrong version.  The ''how to contribute to qutip'' section of this tutorial might be useful for setting things up https://colab.research.google.com/drive/1RcgX7oEzGjzPAF8Ryus54Q5UmyMddmLA?usp=sharing

**Comment by Sombra-Online** [comment]
I can take a look at the code and see how I can help.
