### ISSUE TITLE
A matrix operation in the exponent

### ISSUE THREAD

**Issue by adithi16** [qutip/qutip#2370]
### Discussed in https://github.com/qutip/qutip/discussions/2362

<div type='discussions-op-text'>

<sup>Originally posted by **adithi16** March 26, 2024</sup>
Hello, 

I would like to write an operation that looks like `n^(a^{\dagger}a)`
where n is the average number of photons and a is the annihilation operator. However exponentiation gives error since I cannot use ** or pow() for Qobj. 

In particular, I would like to create a density matrix for a squeezed state with a thermal ensemble. 
Since the already available option of using thermal_dm only creates the state close to the vacuum, I would like to know if there is a way to do this for any state (say a squeezed state or a coherent state).

I would be happy to know! 

</div>

**Comment by loganbvh** [comment]
Can you use `Qobj.expm()` with the identity `n ** x == (exp(log(n)) ** x == exp(x * log(n))`?

**Comment by Ericgig** [comment]
Does this solution work for you?

ps. We mostly use the google group for that kind of discussion. (https://groups.google.com/g/qutip)

**Comment by adithi16** [comment]
It is a good starting point for what I want to do. thank you so much!
