### ISSUE TITLE
result.states is empty when providing e_op

### ISSUE THREAD

**Issue by Ehud-Shahar** [qutip/qutip#2390]
### Bug Description

Hello,
I am using mesolve, and when I provide it with expect_operators, it doesn't save the states of the system and the result.states is an empty list []. when I don't provide a e_op the list is filled like it should.... 
Can you pleas help me with this problem?

### Expected Behaviour

I would expect the mesolve to keep both result.states and result.expect at the same time.

### Your Environment

```shell
qutip version - 5.
```

**Comment by Ericgig** [comment]
You can set the options `store_states` to `True` to always have them in the results.
```
result = mesolve(H, psi0, tlist, c_ops, e_ops=e_ops, options={"store_states": True})
```

**Comment by Ehud-Shahar** [comment]
It worked, Thank you very much!
