### ISSUE TITLE
the difference of superoperator generation on qutip 5.0 and 4.7

### ISSUE THREAD

**Issue by ZhuangMaMS** [qutip/qutip#2411]
### Describe the Issue!

In Qutip 4.7, I can generate chi 
```python
A = qt.Qobj(np.dot(np.dot(Gamma,rho_fin_matrix),Gamma), type ='super', superrep = 'chi')
```
But in qutip 5.0, the parameter `type` has been deleted. How to generate a superoperator from array in qutip 5.0?``

**Comment by Ericgig** [comment]
The type is determined from the dimensions.
Set `dims=[[[N], [N]], [[N], [N]]]` with `N=sqrt(rho.shape[0])` .
