### ISSUE TITLE
mesolve produces unphysical result in qutip v5.0.1 (and not in v4.6)

### ISSUE THREAD

**Issue by mgely** [qutip/qutip#2426]
### Bug Description

When computing the evolution of a density matrix with off-diagonal elements, in presence of decoherence, the matrix is left un-changed in qutip v5.0.1. In qutip v4.6, I obtain the expected behavior: the off-diagonal elements decay.

### Code to Reproduce the Bug

```shell
import qutip as qt
rho_final = qt.mesolve(
                0*qt.sigmaz(), # Hamiltonian set to 0
                rho0=qt.sigmax(), # Initial state with off-diagonal elements
                tlist=[0,1], # a.u. for time
                c_ops=[qt.sigmaz()] # Large amount of decoherence
                ).states[-1]
print(rho_final)
```

### Code Output

```shell
Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=True
Qobj data =
[[0.  0.5]
 [0.5 0. ]]
```

### Expected Behaviour

The same code in Qutip v4.6 produces the expected outcome:

```
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.         0.13533571]
 [0.13533571 0.        ]]
```

### Your Environment

```shell
QuTiP Version:      5.0.1
Numpy Version:      1.26.2
Scipy Version:      1.11.4
Cython Version:     0.29.24
Matplotlib Version: 3.4.3
Python Version:     3.9.7
Number of CPUs:     12
BLAS Info:          Generic
INTEL MKL Ext:      False
Platform Info:      Windows (AMD64)
```

**Comment by Ericgig** [comment]
Qutip 5 normalize the density matrices per default.
When the initial  density matrix trace is not 1, that normalization breaks the evolution.
`options={"normalize_output": False}` should fix your issue.
