### ISSUE TITLE
Seeding the whole of numpy instead of only result of rand_ket_haar

### ISSUE THREAD

**Issue by davidvrchen** [qutip/qutip#2438]
### Bug Description

The `qutip.rand_ket_haar` accepts a seed value.
I expected that this would always give me the same state but would otherwise not interfere with my code.
However, I encountered some unexpected behaviour, it seems that some underlying function sets the seed for the random number generator of `numpy` itself.
After jumping to the definition a few times I see the following:
> `rand_ket_haar` gets its randomness/seeding via `rand_unitary_haar`
> `rand_unitary_haar` gets its randomness/seeding via `randnz`
> In the `randnz` function the following code appears:

`if seed is not None:`
---- `np.random.seed(seed=seed)`

This does the seeding in `numpy` itself and this affects the code where `rand_ket_haar` was called with a seed.

The `numpy` seeding documentation ([docs](https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.Generator)) recommends the following
`rng = np.random.default_rng(seed=seed)`
now `rng` can be used to generate random stuff but this leaves the seeding of `numpy` itself unchanged.

For now I can use such an `rng` object for the other randomness needs inside my program.
I do however think that this was not the intended purpose of the seeding of such a function call.

### Code to Reproduce the Bug

```shell
import qutip as qt
import numpy as np

print(qt.rand_ket_haar(2, seed=42))
print(x1:=np.random.rand(5))
print(qt.rand_ket_haar(2, seed=42))
print(x2:=np.random.rand(5))

print((x1==x2).all())
```

### Code Output

```shell
Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[ 0.81060152-0.22563732j]
 [-0.38212135-0.38209455j]]
[0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[ 0.81060152-0.22563732j]
 [-0.38212135-0.38209455j]]
[0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
True
```

### Expected Behaviour

The two `np.random.rand(5)` calls should not have the same random output.
As the example shows only the `rand_ket_haar` function calls are seeded and are thus expected to return the same output.

### Your Environment

```shell
QuTiP: Quantum Toolbox in Python
================================
Copyright (c) QuTiP team 2011 and later.
Current admin team: Alexander Pitchford, Nathan Shammah, Shahnawaz Ahmed, Neill Lambert, Eric Giguère, Boxi Li, Jake Lishman, Simon Cross and Asier Galicia.
Board members: Daniel Burgarth, Robert Johansson, Anton F. Kockum, Franco Nori and Will Zeng.
Original developers: R. J. Johansson & P. D. Nation.
Previous lead developers: Chris Granade & A. Grimsmo.
Currently developed through wide collaboration. See https://github.com/qutip for details.

QuTiP Version:      4.7.5
Numpy Version:      1.24.3
Scipy Version:      1.12.0
Cython Version:     None
Matplotlib Version: 3.8.3
Python Version:     3.11.5
Number of CPUs:     6
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Windows (AMD64)
Installation path:  c:\Users\Admin\Desktop\BFP\quantum-channel-approximation\venv\Lib\site-packages\qutip
================================================================================
Please cite QuTiP in your publication.
================================================================================
For your convenience a bibtex reference can be easily generated using `qutip.cite()`
```

**Comment by Ericgig** [comment]
Qutip 5 uses local generators and does not seed `numpy.random` itself.

**Comment by davidvrchen** [comment]
Thanks for your quick reply, I upgraded qutip and the issue is indeed fixed
