### ISSUE TITLE
Parallelizing `mcsolve` doesn't work with qutip Integrators with `improved_sampling=False`

### ISSUE THREAD

**Issue by obliviateandsurrender** [qutip/qutip#2450]
### Bug Description

When using qutip integrators with `mcsolve`, parallelizing fails with both `parallel` and `loky` map methods when one doesn't use improved sampling.

Also, a side note - memory consumption seems to have gotten worse in setting up the mcsolve problem in v5.0 as compared to v4.7. I can provide some benchmarks later, but I am unable to go to similar truncation sizes as I could before.

### Code to Reproduce the Bug

```py
import qutip as qp
import numpy as np
N = 2
a1 = qp.tensor(qp.destroy(N), qp.qeye(N))
a2 = qp.tensor(qp.qeye(N), qp.destroy(N))
H = -1j * 0.4 * ((a1.dag()*a1.dag() - a1 * a1) + (a2.dag()*a2.dag() - a2*a2))
psi01 = qp.tensor(qp.states.basis(N, 0), qp.states.basis(N, 0))
tlist = np.linspace(0.0, 30.0, 501)
c_ops = [np.sqrt(5)*a1*a1, np.sqrt(5)*a2*a2]
result = qp.mcsolve(H, psi01, tlist, c_ops, ntraj=500, options=dict(map="parallel", method="vern9", improved_sampling=False))
```

### Code Output

```shell
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/lib/python3.10/multiprocessing/queues.py", line 245, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "<stringsource>", line 2, in View.MemoryView._memoryviewslice.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
```

### Expected Behaviour

Parallelizing should work independently of the sampling method. 

### Your Environment

```shell
QuTiP Version:      5.0.2
Numpy Version:      1.26.4
Scipy Version:      1.12.0
Cython Version:     None
Matplotlib Version: 3.9.0
Python Version:     3.10.4
Number of CPUs:     8
BLAS Info:          Generic
INTEL MKL Ext:      False
Platform Info:      Darwin (arm64)
```

**Comment by Ericgig** [comment]
Not sure what you mean.

The issue is isolated to the `vernN` methods, so any other methods can be used.
Is there a specific reason you need to use that specific method?

**Comment by obliviateandsurrender** [comment]
I wanted to use them to benchmark some of the results I got with other solvers. 
I think I was able to make it work locally by fiddling with the `Explicit_RungeKutta` class. Would you want me to open a PR for it, if you'd like?

**Comment by Ericgig** [comment]
Sure, please do.

I do not expect these methods to get a lot of use, but they are the only one that don't need the state to be a numpy array.
