### ISSUE TITLE
`qutip.expect` does not support numpy array as input

### ISSUE THREAD

**Issue by BoxiLi** [qutip/qutip#2456]
### Bug Description

In documentation of `qutip.expect` both NumPy array and Qobj are allowed as input, but it is not.

### Code to Reproduce the Bug

```shell
import qutip
qutip.expect(qutip.sigmaz().full(), qutip.ket([0],[2]).full())
```

### Code Output

```shell
AttributeError: 'numpy.complex128' object has no attribute 'isherm'
```

### Expected Behaviour

Either fix the documentation or fix the code to support NumPy array. It would be nice to keep the NumPy support though

### Your Environment

```shell
QuTiP Version:      5.1.0.dev0+0aee93e
Numpy Version:      1.26.4
Scipy Version:      1.12.0
Cython Version:     None
Matplotlib Version: 3.9.0
Python Version:     3.11.9
Number of CPUs:     40
BLAS Info:          Generic
INTEL MKL Ext:      False
Platform Info:      Linux (x86_64)
```

**Comment by Ericgig** [comment]
It accept an array of Qobj:
```
qt.expect(qt.num(3), np.array([qt.basis(3,0), qt.basis(3,1), qt.basis(3,2)], dtype=object))
```
I believe the docstring is sufficient:  `A single or a `list` of operators for expectation value.`

But looking at it for type hints make it look strange. If one of the operator(s) and state(s) is a list, the output it an array, but if both are lists, we get a list of arrays... Also only `list` and `array` are accepted, but array-like could be understood to also accept tuple and other...
