### ISSUE TITLE
Displacement operation not working

### ISSUE THREAD

**Issue by Chengie6** [qutip/qutip#2495]
### Bug Description

Hi there, I'm using qutip 4.7.2. I recently ran into some unitary transformation problem. So I want to use the displacement operator to displace the annihilation operator by 1, so I tried to define my displacement operator, and unitary transform the annihilation operator. I want to compare the result with that of directly adding 1 to the annihilation operator by looking at their trace distance, which is supposed to be 0. However, the result is 5... I don't know where it goes run, and just wonder if anyone knows what's going on?

### Code to Reproduce the Bug

```shell
from qutip import *

dim = 10

# Create and destroy operators
a = destroy(dim)
D = (a.dag() - a).expm()

# Displaced annihilation operator
a_displaced = D.dag() * a * D

# Check trace distance between the displaced operator and (a + 1)
trace_distance = tracedist(a_displaced, a + 1)

print(f"The trace distance is {trace_distance}")
```

### Code Output

```shell
The trace distance is 5.00000005039634
```

### Expected Behaviour

The trace distance should be 0.

### Your Environment

```shell
QuTiP Version:      4.7.2
Numpy Version:      1.24.2
Scipy Version:      1.10.1
Cython Version:     None
Matplotlib Version: 3.7.1
Python Version:     3.11.9
Number of CPUs:     8
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Windows (AMD64)
```

**Comment by Chengie6** [comment]
> This is not a bug in QuTiP _per se_, but an artifact of the Fock space cutoff. In a numerical calculation, we can only use finite matrices, but the ladder operators can not be represented with finite matrices (Stone-von Neumann theorem).
> 
> You can try printing `a * a.dag() - a.dag() * a` for different values of `dim`. You will find that it gives the expected result (identity matrix) except in the very bottom right matrix element. That matrix element however deviates a lot, and the more you increase `dims` the more it will deviate. So if you compute the trace distance of `a * a.dag()` and `a.dag() * a + 1`, you will get a large number instead of zero. In your example, the basic problem is the same.
> 
> Usually this is not a problem because we assume the cutoff is larger than the number of excitations in any state we are looking at. In other words, in vector form, the bottom-most entries of any state are very (exponentially) small, and the deviations in the operators in those entries then don't play a role. However, when calculating a norm (such as the trace distance), entries corresponding to low-energy states or to high-energy states contribute equally, and we can get nonsensical results.
> 
> You could try projecting out high-energy states before calculating the norm:
> 
> ```
> dim = 25
> dim2 = 10
> 
> a = destroy(dim)
> D = (a.dag() - a).expm()
> a_displaced = D.dag() * a * D
> 
> proj = sum(projection(dim, i, i) for i in range(dim2))
> diff = a_displaced - (a + 1)
> print((proj * diff * proj).norm('tr'))
> # 1.3039375636172088e-07
> ```

Hi Paul, thank you very much for your response! It’s really helpful :) From what I tried so far, and if I understand you correctly, as I will eventually calculate their expectation values with respect to some vectors, that abnormal large number at the corner of their matrix would be suppressed and the final results would be the same, or?

**Comment by pmenczel** [comment]
> as I will eventually calculate their expectation values with respect to some vectors, that abnormal large number at the corner of their matrix would be suppressed and the final results would be the same, or?

Yes, exactly, that is the idea
