### ISSUE TITLE
How to get a QuTiP install with 'INTEL MKL Ext' set to True?

### ISSUE THREAD

**Issue by DHuybrechts** [qutip/qutip#2496]
Hello, 
I wish to install QuTiP with the INTEL MKL ext. set to True. I have been having issues with this on various laptops (MacBook Pro M1, as well as a Windows i7). I have set below the information I obtained on the Windows i7 machine following various installation attempts in different conda environments. Sometimes I manage for ‘BLAS Info’ to show INTEL MKL, but the ‘INTEL MKL Ext’ flag remains False. It is unclear to me how I should obtain this result, could anyone help me with this issue?

The underlying reason for wanting to have MKL is that it allowed me in the past (on the same machine but with a different conda environment I no longer have access to) to calculate the steady states of much larger Liouvillians than I am now able to. I am unfortunately unable to reproduce this environment.

Below you can find the outcomes of various installation processes, each in a new conda environment:

**Attempt 1a:** 
Conda install mkl
conda install numpy
conda install scipy
conda install conda-forge::qutip
**Results:** 
QuTiP Version:      	5.0.3
Numpy Version:      	2.0.0
Scipy Version:      	1.14.0
Cython Version:     	None
Matplotlib Version: 	None
Python Version:     	3.12.4
Number of CPUs:     	12
BLAS Info:          		Generic
INTEL MKL Ext:      	False
Platform Info:      	Windows (AMD64)

**Attempt 1b:**
Conda install mkl
conda install scipy 
conda install conda-forge::qutip
**Results:**
QuTiP Version:      	5.0.3
Numpy Version:      	1.26.4
Scipy Version:     	 1.10.1
Cython Version:     	None
Matplotlib Version: 	None
Python Version:     	3.10.14
Number of CPUs:     	12
BLAS Info:         		INTEL MKL
INTEL MKL Ext:      	False
Platform Info:      	Windows (AMD64)

**Attempt 1c:**
Conda install mkl
conda install conda-forge::qutip
**Results**
QuTiP Version:      5.0.3
Numpy Version:      2.0.0
Scipy Version:      1.14.0
Cython Version:     None
Matplotlib Version: None
Python Version:     3.12.4
Number of CPUs:     12
BLAS Info:          Generic
INTEL MKL Ext:      False
Platform Info:      Windows (AMD64)

**Attempt 2:** 
Conda install conda-forge::qutip
**Results**: obtained errors when importing qutip (ImportError: DLL load failed while importing _arpack: The specified module could not be found.)

**Attempt 2b:**
Conda install scipy
conda install conda-forge::qutip
**Results:**
QuTiP Version:      5.0.3
Numpy Version:      1.26.4
Scipy Version:      1.10.1
Cython Version:     None
Matplotlib Version: None
Python Version:     3.10.14
Number of CPUs:     12
BLAS Info:          INTEL MKL
INTEL MKL Ext:      False
Platform Info:      Windows (AMD64)

**Comment by Ericgig** [comment]
Thank you for reporting.
There seems to be an issue with our detection of mkl for a while.
Since it's an optional dependancy, the related tests have been quietly skipped for a while...

You could probably manually import it until we make a patch:
```
from ctypes import cdll
import sys
import os

qutip.settings._mkl_lib = cdll.LoadLibrary( os.path.dirname(sys.executable) + r'\Library\bin\mkl_rt.dll' )
```

**Comment by DHuybrechts** [comment]
Thank you for your swift response Eric. 

Your suggestion helped me out. Apparently the relevant .dll file in my \Library\bin\ folder was named 'mkl_rt.2.dll', rather than 'mkl_rt.dll'. I duplicated the my file and renamed it and now everything works as expected. 

It seems when qutip is checking for mkl with qutip.settings._find_mkl() it specifically looks for '\mkl_rt.dll'. Probably including the possibility for a deviation of the above form should patch it.

**Comment by jpedrego** [comment]
I am having the same issue but with Linux. MKL libraries are properly installed (import mkl works), but qutip tells me they are not there

**Comment by jpedrego** [comment]
For info:

```
QuTiP: Quantum Toolbox in Python
================================
Copyright (c) QuTiP team 2011 and later.
Current admin team: Alexander Pitchford, Nathan Shammah, Shahnawaz Ahmed, Neill Lambert, Eric Giguère, Boxi Li, Jake Lishman, Simon Cross, Asier Galicia, Paul Menczel, and Patrick Hopf.
Board members: Daniel Burgarth, Robert Johansson, Anton F. Kockum, Franco Nori and Will Zeng.
Original developers: R. J. Johansson & P. D. Nation.
Previous lead developers: Chris Granade & A. Grimsmo.
Currently developed through wide collaboration. See https://github.com/qutip for details.

QuTiP Version:      5.0.4
Numpy Version:      1.26.4
Scipy Version:      1.13.1
Cython Version:     None
Matplotlib Version: 3.9.2
Python Version:     3.12.2
Number of CPUs:     24
BLAS Info:          Generic
INTEL MKL Ext:      False
```

and

```
import mkl
mkl.get_version_string()
'Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications'
```

**Comment by jpedrego** [comment]
The following command does not give errors when executed:
```
qtp.settings._mkl_lib = ctypes.cdll.LoadLibrary( '/home/jpedrego/miniconda3/lib/libmkl_rt.so' )
```
But I still have `INTEL MKL Ext:      False`

**Comment by nwlambert** [comment]
just a note that I had no problem getting mkl working on linux. I will try again, from scratch, and see if I can reproduce this issue. are you using Conda?

**Comment by jpedrego** [comment]
Hi nwlambert,
First of all, thank you for taking the time to look into it!

Regarding miniconda. In principle, miniconda and conda only differ on the amount of packages installed by default at the start.
I installed all the python packages via conda, so in principle, numpy should be the one build using MKL. For what is worth, `numpy.show_config()` shows (among other things):
```
 "blas": {
      "name": "mkl-sdl",
      "found": true,
      "version": "2023.1",
      "detection method": "pkgconfig",
      "include directory": "/home/jpedrego/miniconda3/include",
      "lib directory": "/home/jpedrego/miniconda3/lib",
      "openblas configuration": "unknown",
      "pc file directory": "/home/jpedrego/miniconda3/lib/pkgconfig"
    }
```
which I interpret as that Blas uses MKL.

So, the problem is not getting MLK working on a Linux install, is rather for Qutip to be aware it is there, and make sure it uses it.

**Comment by Ericgig** [comment]
You probably need to use the development version (or patch `qutip/settings.py`).

With the development version, you should be able to do
`qutip.settings.mkl_lib_location = ".../miniconda3/lib/libmkl_rt.so"`

In the version you have, there is a mistake in the property `mkl_lib`. It tries to reload the library each time it's call instead of using `self._mkl_lib`:
https://github.com/qutip/qutip/blob/b6ebfe679d7a6008bb0ee85b971c42a642127f8f/qutip/settings.py#L143-L147
I don't think you can make it work without having that fixed...
If you can patch it, your attempt of manually loading the library in `settings._mkl_lib` should work.

**Comment by jpedrego** [comment]
Thanks for the tip. I went to the `master` branch, and copy paste the setting into my local install (I know, I know) and now MLK works without having to specify the location.
Things run faster now! 
Thanks!!!
