### ISSUE TITLE
Qutip result changed from 3 years ago

### ISSUE THREAD

**Issue by yuchiuchao** [qutip/qutip#2501]
### Bug Description

I took a qutip script created 3 years ago (named "Ikonen First Shot New  Unitary Trans States 2 level Full H Gated Test 2 - Copy.ipynb") and ran it now (exact copied named "Test.ipynb") and got different results.
There is a caveat, whether relevant or not.  When I ran the duplicated script (Test.ipynb) this time, I got errors keeping me from importing qutip.  I submitted a ticket yesterday (#2500), which was kindly addressed, recommending that I uninstall cvxpy to remove conflict.  I did that and was able to import qutip.
I then ran the duplicate script, but got a different result from 3 years ago.  If you compare the output at block 23, you'll see it deviates significantly from the corresponding block in the old script.  I have changed nothing in hte duplicated script, other than uninstalling cvxpy to make it run.
I then reinstalled cvxpy with upgrade and then qutip again.  This time I can still import qutip, but with a warning.  I ran the script with no problem, but still got the same deviated behavior from 3 years ago.

[codes.zip](https://github.com/user-attachments/files/16367713/codes.zip)

The 3-year-old script is included only to show the previous results.  It is not meant to be run.  I suspect if you run it with your likely different setup, you might get the same deviation as I did, or even yet another different deviation.  I cannot recall the state of installation I had from 3 years ago.  I believe I did it through conda.

I just realized that I cannot include qutip scripts with this report.  I included a zipped folder containing these two files.  Please let me know if it didn'tgo through.  Thank you! 

### Code to Reproduce the Bug

```shell
Old code in "Ikonen First Shot New  Unitary Trans States 2 level Full H Gated Test 2 - Copy.ipynb"
New code in "Test.ipynb"
Both attached.
These two codes are exactly identical.  Only difference is in the qutip installation, one from 3 years ago and one just completed.
```

### Code Output

```shell
Output in block 23 in the new code is significantly different from that in block 215 in the old code.
```

### Expected Behaviour

Expected qutip to produce same results on identical codes 3 years apart.

### Your Environment

```shell
QuTiP: Quantum Toolbox in Python
================================
Copyright (c) QuTiP team 2011 and later.
Current admin team: Alexander Pitchford, Nathan Shammah, Shahnawaz Ahmed, Neill Lambert, Eric Giguère, Boxi Li, Jake Lishman, Simon Cross, Asier Galicia, Paul Menczel, and Patrick Hopf.
Board members: Daniel Burgarth, Robert Johansson, Anton F. Kockum, Franco Nori and Will Zeng.
Original developers: R. J. Johansson & P. D. Nation.
Previous lead developers: Chris Granade & A. Grimsmo.
Currently developed through wide collaboration. See https://github.com/qutip for details.

QuTiP Version:      5.0.3.post1
Numpy Version:      2.0.1
Scipy Version:      1.13.1
Cython Version:     0.29.24
Matplotlib Version: 3.9.1
Python Version:     3.9.7
Number of CPUs:     8
BLAS Info:          Generic
INTEL MKL Ext:      False
Platform Info:      Windows (AMD64)
Installation path:  C:\Users\ychao\Anaconda3\lib\site-packages\qutip
================================================================================
Please cite QuTiP in your publication.
================================================================================
For your convenience a bibtex reference can be easily generated using `qutip.cite()`
```

### Additional Context

[codes.zip](https://github.com/user-attachments/files/16367722/codes.zip)
Including the zip folder containing the two files)

**Comment by yuchiuchao** [comment]
New information:
I ran the same script on another PC and it reproduced the same result as 3 years ago.  Also, I didn't encounter the same importing problem as reported in #2500 .
I am reproducing the qutip.about() output below for this other PC:

QuTiP: Quantum Toolbox in Python
================================
Copyright (c) QuTiP team 2011 and later.
Current admin team: Alexander Pitchford, Nathan Shammah, Shahnawaz Ahmed, Neill Lambert, Eric Giguère, Boxi Li, Jake Lishman and Simon Cross.
Board members: Daniel Burgarth, Robert Johansson, Anton F. Kockum, Franco Nori and Will Zeng.
Original developers: R. J. Johansson & P. D. Nation.
Previous lead developers: Chris Granade & A. Grimsmo.
Currently developed through wide collaboration. See https://github.com/qutip for details.

QuTiP Version:      4.6.2
Numpy Version:      1.21.5
Scipy Version:      1.7.3
Cython Version:     None
Matplotlib Version: 3.5.1
Python Version:     3.9.9
Number of CPUs:     8
BLAS Info:          Generic
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Windows (AMD64)
Installation path:  C:\Users\ychao\Anaconda3\envs\qutip-env\lib\site-packages\qutip
================================================================================
Please cite QuTiP in your publication.
================================================================================
For your convenience a bibtex reference can be easily generated using `qutip.cite()`

**Comment by pmenczel** [comment]
Just a few comments:
* The changes in behavior are probably due to a different QuTiP version. Your `qutip.about()` output shows that you have installed version 5.0.3 on the one PC and version 4.6.2 on the other. Version 5 was recently released, and it is a major update and changes many of the internals of QuTiP. Old code should still work with version 5 in the majority of cases, but it is not guaranteed to always work. For old code, you might therefore prefer to use version 4 (the latest release of version 4 is v4.7.6).
* Your notebooks are rather long, and for a person who has not written them it can be hard to figure out what they do. If you would like to investigate in detail where the different behavior comes from, I would recommend to try to boil it down to a *short, self-contained* example script that gives different results in versions 4 and 5.
* The differing plots show values with a magnitude of $10^{-14}$ or so. That is rather small. By default, QuTiP's solvers use tolerances of $10^{-12}$, so you should not expect the numerical results to have a higher precision than that. In numerical calculations, it is generally recommended to rescale your units such that your parameters and results have a magnitude around $1$ if possible.

**Comment by yuchiuchao** [comment]
Great!  Thanks a lot for these points.

**Comment by yuchiuchao** [comment]
I believe the detailed comments from [pmenczel](https://github.com/pmenczel) is sufficient to wrap up this case.
