### ISSUE TITLE
'SMESolver' object has no attribute 'run_from_experiment'

### ISSUE THREAD

**Issue by sk0rte** [qutip/qutip#2525]
### Describe the Issue!

When running the example code from the documentation https://qutip.readthedocs.io/en/master/guide/dynamics/dynamics-stochastic.html using version 5.0.4 I get the AttributeError: 'SMESolver' object has no attribute 'run_from_experiment' . When looking at my local version of the stochastic.py, then the class StochasticSolver does not have the function run_from_experiment, but that function exists on the github version.

**Comment by Ericgig** [comment]
Thank you for your interest.
You are looking at the development version of the documentation (`master` instead of `latest`).
If you want to try that function, you will need to install qutip from source or wait until the 5.1 release. (Should be released this fall.)
