### ISSUE TITLE
Slow brmesolve() for certain problems & bloch-redfield tensor always returned Dense

### ISSUE THREAD

**Issue by nwlambert** [qutip/qutip#2530]
### Bug Description

I updated some old code from v4.7 to v5 this week and found some examples of brmesolve which were substantially slower... going from 30 seconds to 15+ minutes.   Fiddling around a little I narrowed it down to at least one issue (though there may be others).  This is particularly tricky because I also have examples which are substantially faster in v5.

The one issue I found was that  bloch_redfield_tensor() always returns a dense bloch-redfield tensor, even if you set br_type to sparse.  It does return a sparse one if fock_basis=false, which points at the issue being
https://github.com/qutip/qutip/blob/0b4260e821cf4d095df6fa02ea5a71bc0655516c/qutip/core/_brtensor.pyx#L281
so this call to from_eigbasis() in _brtools always returning a dense object
https://github.com/qutip/qutip/blob/0b4260e821cf4d095df6fa02ea5a71bc0655516c/qutip/core/_brtools.pyx#L290

if i manually convert the tensor back to sparse again, and use it, it speeds up these hard cases by a factor of 5 or 6.  Not sure if it resolves my original 30seconds -> 15 minutes problem completely, will check a bit more.

In some sense this relates to the old issue of how broadly default_dtype should be applied, but here it seems more specific in that one requests a sparse tensor and gets a dense one.

### Code to Reproduce the Bug

```shell
R = bloch_redfield_tensor(H, [[Q, Lor]], fock_basis=True, sparse_eigensolver=True, br_dtype='sparse')
print(R.dtype)
```

### Code Output

```shell
<class 'qutip.core.data.dense.Dense'>
```

### Expected Behaviour

Sparse tensor and fast brmesolve!

### Your Environment

```shell
QuTiP Version:      5.1.0.dev0+8efc188
Numpy Version:      2.0.1
Scipy Version:      1.14.0
Cython Version:     3.0.11
Matplotlib Version: 3.9.1.post1
Python Version:     3.10.12
Number of CPUs:     28
BLAS Info:          Generic
INTEL MKL Ext:      False
Platform Info:      Linux (x86_64)
```

**Comment by Ericgig** [comment]
Could you send the example?
If it's constant, I am surprised that you cannot get under one minute after converting to csr.

Looking back at the code and it's clearly optimised for dense. 
`from_eigbasis` does something like `Dense @ CSR @ Dense.dag()`, since we don't have `Dense @ CSR` it convert to dense representation. It would work better with anything but CSR...

**Comment by nwlambert** [comment]
Quick example is below.  To add a bit more,  the ''slowness'''of the standard brmesolve() run in this example depends on whether I install mkl or not. without mkl, its >10 mins, with mkl, about one minute.    The run with converting the tensor to sparse always takes around 30-40 seconds, and doesn't depend too much on mkl.

`import qutip as qt
import numpy as np

#spectral density
def Jw(w): 
    return lam**2 * gamma * w / ((w0**2 - w**2)**2 + (gamma**2) * (w**2))
    
  
#power spectrum
def J_power_spectrum(w):
    """ The Ohmic bath power spectrum as a function of w
        (and the bath parameters).
    """
    return (
        Jw(w) * 2 * (w>0)
    )
def Ising_solve(N, g0, J0, gamma, tlist, options, use_csr=True):
    # N  : number of spins
    # g0 : splitting
    # J0 : couplings


    #Setup operators for individual qubits
    sx_list, sy_list, sz_list = [], [], []
    for i in range(N):
        op_list = [qt.qeye(2)] * N
        op_list[i] = qt.sigmax()
        sx_list.append(qt.tensor(op_list))
        op_list[i] = qt.sigmay()
        sy_list.append(qt.tensor(op_list))
        op_list[i] = qt.sigmaz()
        sz_list.append(qt.tensor(op_list))

    # Hamiltonian - Energy splitting terms
    H = 0.
    for i in range(N):
        H += g0 * sz_list[i]

    # Interaction terms
    for n in range(N - 1):
        H += -J0 * sx_list[n] * sx_list[n + 1]

    # Initial state
    state_list = [qt.basis(2, 1)] * (N-1)
    state_list.append(qt.basis(2, 0))
    psi0 = qt.tensor(state_list)
    fx = 1
    fy = 1.1
    fz = 0.9
    coup =  (fx *  (sx_list[N-1]) 
        + fy * (sy_list[N-1])
        + fz * (sz_list[N-1]))

    
    if use_csr:
        R = qt.bloch_redfield_tensor(H, [[sx_list[N-1], J_power_spectrum]], fock_basis=True, sparse_eigensolver=True,br_dtype = 'sparse', sec_cutoff=-1)
        R = R.to('csr').tidyup()
        result = qt.mesolve(R,psi0, tlist, options=options)
    else:
        result = qt.brmesolve(H, psi0, tlist, a_ops = [[coup, J_power_spectrum]], e_ops=sz_list, options=options, sec_cutoff=-1)
    return result

#bath sd params
lam = 5
w0 = 10
gamma = 5
 

#system params
N = 5
g0 = 1
J0 = 5


tlist = np.linspace(0, 100, 1000)
options ={"nsteps": 15000, "store_states": True, "progress_bar": True} 

#standard
result_ising = Ising_solve(N, g0, J0, gamma, tlist, options, use_csr=False)
#convert to CSR
result_ising = Ising_solve(N, g0, J0, gamma, tlist, options, use_csr=True)`

**Comment by Ericgig** [comment]
There is a bug in `brmesolve`. When it prepare the system, it convert everything to `QobjEvo` to allows list format. But then `bloch_redfield_tensor` use `Qobj` vs `QobjEvo` to determine if the system depend on time (since the spectra could depend on time and there is no check for that, we use the class of the corresponding `a_op`). Therefore, when using `brmesolve`, it always use the time-dependent version that compute the eigen states at each time step...
