### ISSUE TITLE
mcsolver: increasing jump rate does not monotonically increase the number of jumps

### ISSUE THREAD

**Issue by emilyt-nist** [qutip/qutip#2539]
### Describe the Issue!

I'm not sure if this is a bug, or I don't understand something. I'm using mcsolve and keeping trajectories.  I've got a single type of collapse/jump operator, which moves a single electron of my system from one site to another.  
```
for jump_rate in  [0.01, 0.1, 0.5, 1.0, 1.5, 2, 4, 8, 16, 32]:
   result = mcsolve(H, initial_state, tlist, [np.sqrt(jump_rate)*jump_op], number_operators, ntraj = ntraject,
                options={"keep_runs_results": True, "store_states": True, "improved_sampling": True})
```
 I'm increasing the jump_rate, and looking at when the jumps occur using result.collapse (which keeps track of which trajectory contributed a jump).  I'm using ntraject = 10 or 100.  I've tried with and without improved sampling.  

When I use a jump rate less than 2, the number of jumps I see in each trajectory goes up with the jump rate.  However for a jump rate of 4 or higher, the number of jumps I see in each trajectory goes down with jump rate.  (I realize that for the Lindblad equation to be a good approximation, the interaction hamiltonian (and thus jump rate) should be small compared to the system Hamiltonian, but I still want to understand this behavior.)

Can anybody explain why a higher jump rate doesn't give more jumps in a trajectory?  

Also, I'd like to understand result.photocurrent, which seems to combine the jumps for all trajectories, but also seems to divide by the number of trajectories, and maybe the number of timesteps?

Thanks,
Emily
Here are a couple of plots showing all the jumps in 10 trajectories, for a jump rate of 4 (more jumps) and of 0.5 (fewer jumps) and 32 (fewer jumps)
![Colmcsolve6sites0 5C0 5N0 2ex4JR10NTEvery_other_site_state](https://github.com/user-attachments/assets/21b08700-3cae-4584-a26e-31821362e285)
![Colmcsolve6sites0 5C0 5N0 2ex0 5JR10NTEvery_other_site_state](https://github.com/user-attachments/assets/a61c1a5d-823f-4718-baf1-c679f5a25165)
![Colmcsolve6sites0 5C0 5N0 2ex32JR10NTEvery_other_site_state](https://github.com/user-attachments/assets/6e5a1354-2b8f-4666-a451-b6b74ffdccd9)

**Comment by pmenczel** [comment]
Congratulations, you have rediscovered the quantum Zeno effect :-) There is nothing wrong with qutip here, I think.

You don't write what your system is exactly, but I assume something like $H=\sigma_x$ and jump operator $\sigma_-$. The effect of the environment can be thought of as measuring the system continuously, with a strength proportional to the coupling rate, which you call jump rate.

Jump rate is indeed a slightly misleading (but commonly used) name. Its meaning is the reciprocal of the expected time until a jump, if the system is in the excited state. However, due to the continuous measurement and the quantum Zeno effect, the system rarely makes it to the excited state in the first place.

Mathematically, where it comes from is that the deterministic trajectory evolution (between the jumps) is given not by the system Hamiltonian, but by an effective (non hermitian) Hamiltonian. In the limit of large coupling rates, this effective Hamiltonian becomes approximately diagonal.

**Comment by emilyt-nist** [comment]
Thank you...there was something telling me it was something like the Zeno effect, but I just couldn't put my finger on how it was happening.  I had forgotten that of course between jumps the Hamiltonian is not the unitary non-interacting Hamiltonian, but the non-Hermitian Hamiltonian.
________________________________

**Comment by emilyt-nist** [comment]
Can you please say something about result.photocurrent?  I can see it contains all the jumps from all the trajectories, but what is the meaning of the value associated with each jump?  It believe it goes down when I increase the number of trajectories or timesteps, so I think it is perhaps dividing by those numbers?  But I don't know what else it might depend on.  Thanks.

**Comment by Ericgig** [comment]
The photocurrent is the rate of collapse, or the average number of collapse for a time 1 in tlist unit, computed for each tlist increments. It does not decrease when increasing the number of trajectories or timesteps, but it get less noisy.

ps. A good way to compare with different `tlist` to align data properly:
```
plt.bar(tlist[:-1], photocurrent, width=np.diff(tlist), align="edge")
```

**Comment by emilyt-nist** [comment]
Hi Ericgig, 
Thanks for getting back to me.  I still have a question.  What I see in result.photocurrent is a list of one element (because I have one jump operator), that element being an array of float64s which has the length of np.diff(tlist) as you imply above.  Each element of the array is either a zero or an integer multiple of some number, let's call this x.  But x (the number that result.photocurrent[0][t] is an integer multiple of) changes when I change the number of trajectories, when I make no other changes. For example, for ten trajectories x is around 2.66513039, but with 100 trajectories x is 0.24228458.  When I run it again with the same number of trajectories, x is the same, though of course which times have a value of zero,1x, 2x, etc. change.  I'm trying to determine what meaning to assign to x.  My jump rate in this case is 0.5, and I have 601 times, so 600 diffs.

(Also, just as an aside, I found that some of the jumps do not show up in the histogram when I plot with: 
`plt.bar(tlist[:-1], result.photocurrent[0], width=np.diff(tlist), align="edge")`
instead I'm using:
`plt.plot(tlist[0:-1], result.photocurrent[0])`
which more accurately captures all of the jumps that I can see when I examine the array of float64s.)
Emily

**Comment by pmenczel** [comment]
Hi Emily,

The photocurrent is the number of detector clicks (i.e., jumps) per unit time, averaged over all trajectories. For sufficiently many trajectories, it will approximate $tr[C_n \rho(t) C_n^\dagger]$. If I'm not mistaken, you should find that
```math
x = \frac{1}{\Delta t} \frac{1}{N_t}
```
where $\Delta t$ is the spacing in your `tlist` and $N_t$ the number of trajectories. The integer (photocurrent/x) is simply the number of clicks in that time interval in all trajectories; we multiply with x for the "per unit time, averaged over all trajectories" that I wrote above.

Paul

(PS. I only noticed your username now - is it possible we had a chat at QTD in August? Hope you are doing well!)
