### ISSUE TITLE
`mesolve` gives wildly different expectation values when changing number of `tlist` steps

### ISSUE THREAD

**Issue by khanhuyengiang** [qutip/qutip#2549]
I am simulating transmon (Duffing) Hamiltonian, according to:

$$
H_{\text{nonlin}} = \frac{\alpha_0}{2} a_0^\dagger a_0^\dagger a_0 a_0 + \frac{\alpha_1}{2} a_1^\dagger a_1^\dagger a_1 a_1 + J \left( a_0^\dagger a_1 + a_1^\dagger a_0 \right)
$$

$$
H_{\text{drive}} = \Omega \cos(\phi_0) \left( a_0^\dagger + a_0 \right) + \Omega \cos(\phi_1) \left( a_1^\dagger + a_1 \right)
$$

$$
H_{\text{detune}} = (\nu_0 - \nu_d) \, a_0^\dagger a_0 + (\nu_1 - \nu_d)  a_1^\dagger a_1
$$

When changing the time steps in tlist (for example, from `np.linspace(0, 10, 200)` to `np.linspace(0, 10, 300)` the results differ a lot, while I would expect them to be just higher resolution version. I have identify that the problem come from the detuning term, but I'm not sure why.

![image](https://github.com/user-attachments/assets/a94d9680-43cb-40a9-a59d-aaa1e708ddc9)

MWE:

```
import numpy as np
import matplotlib.pyplot as plt
from qutip import (basis, tensor, destroy, qeye, mesolve, sigmax, sigmay, sigmaz,
                   ptrace, expect, Options)

coeff = 2 * np.pi
dim = 2

# States
ground_state = tensor(basis(dim, 0), basis(dim, 0))

# Simulation options
options = Options(nsteps=30000)

# Frequencies (multiplied by 2 pi)
v_0 = 4888.2059 * coeff  # Frequency of qubit A
v_1 = 4795.5696 * coeff  # Frequency of qubit B
Omega = 20
drive_detuning = 30 * coeff
v_d = v_0 - drive_detuning

# Operators
a_0 = tensor(destroy(dim), qeye(dim))
a_1 = tensor(qeye(dim), destroy(dim))

# Hamiltonian
H_drive = Omega * (a_0.dag() + a_0) + Omega * (a_1.dag() + a_1)
H_detune = (v_0 - v_d) * a_0.dag() @ a_0 + (v_1 - v_d) * a_1.dag() @ a_1
H = [H_detune, H_drive]

# Time evolution
tlist_200 = np.linspace(0, 10, 200)
tlist_300 = np.linspace(0, 10, 300)
tlist_400 = np.linspace(0, 10, 400)

result_200 = mesolve(H, ground_state, tlist_200, [], options=options)
result_300 = mesolve(H, ground_state, tlist_300, [], options=options)
result_400 = mesolve(H, ground_state, tlist_400, [], options=options)

# Expectation values
q_200 = [ptrace(state, 0) for state in result_200.states]
q_300 = [ptrace(state, 0) for state in result_300.states]
q_400 = [ptrace(state, 0) for state in result_400.states]

exp_200 = expect(sigmax(), q_200)
exp_300 = expect(sigmax(), q_300)
exp_400 = expect(sigmax(), q_400)

fig, axs = plt.subplots(3, 1, figsize=(16, 8))
axs[0].plot(tlist_200,exp_200,label='200')
axs[1].plot(tlist_300,exp_300,label='300',color='C1')
axs[2].plot(tlist_400,exp_400,label='400',color='C2')

axs[0].set_title('tlist = np.linspace(0, 10, 200)')
axs[1].set_title('tlist = np.linspace(0, 10, 300)')
axs[2].set_title('tlist = np.linspace(0, 10, 400)')

plt.xlabel('Time (us)')

```

**Comment by Ericgig** [comment]
The result is probably oscillating too quickly for the tlist.

You can see similar effect when plotting sin waves:
```
for N in [50, 100, 200]:
    ts = np.linspace(0, 1, N)
    plt.plot(ts, np.sin(ts * 300))
    plt.show()
```

**Comment by khanhuyengiang** [comment]
@Ericgig Thank you for responding. That is likely the issue - the beat pattern is due to the time discretization. Do you know why this Hamiltonian is oscillating so fast? It supposed to give a ZZ interaction, and on the QPU based on this Hamiltonian, it gives a slow oscillation with period about $4 \mu s$.

**Comment by BoxiLi** [comment]
You are measuring the expectation of sigmax, if you measure the expectation value of sigmaz, or the population, you will not observe such a big oscillation but very small oscillations.

Not sure what you want to achieve, but your detuning is negligibly small compared to the frequency. It has little effect.

You have a time-independent Hamiltonian, so if you want to compute the ZZ interaction, you can simply diagonalize the matrix and see if you have a ZZ coupling term.

**Comment by nonhermitian** [comment]
There is a `max_step` option for the solvers that helps in cases like this.
