### ISSUE TITLE
Parfor is not usable

### ISSUE THREAD

**Issue by joseantonio-marin** [qutip/qutip#2551]
### Describe the Issue!

I have installed Qutip version 5.0.2, and I've been trying to use the parfor method (see https://qutip.org/docs/4.0.2/guide/guide-parfor.html). When calling it, I get the error: "NameError: name 'parfor' is not defined".
 I'm not trying to do anything exotic yet, I was just testing the rudimentary example from the webpage:

from qutip import *
def func1(x):  
    return x, x**2, x**3
a, b, c = parfor(func1, range(10))
print(a)

**Comment by pmenczel** [comment]
Hi, you are using QuTiP 5 but it seems that you are consulting the QuTiP 4 documentation. The most up-to-date documentation is found here: https://qutip.readthedocs.io/en/stable/index.html

Usually, older code can still be used with newer QuTiP versions, but version 5 made a few breaking changes. One of them was the removal of the `parfor` function, see https://qutip.readthedocs.io/en/master/changelog.html#feature-removals

You can use `qutip.parallel_map` instead, which does the same thing: https://qutip.readthedocs.io/en/stable/apidoc/functions.html#qutip.solver.parallel.parallel_map
