### ISSUE TITLE
mesolve give wrong probability of the evolution of very simple Hamiltonian

### ISSUE THREAD

**Issue by khanhuyengiang** [qutip/qutip#2560]
### Describe the Issue!

I am using `mesolve` to simulate the following Hamiltonian, with initial state $\ket{+}$ and plotting the probability that the qubit is in state $\ket{0}$ or $\ket{1}$:

$$H = \begin{pmatrix} 0&0 \\\ 0&5000 \end{pmatrix}$$

Since $H = 2500 ( id - \sigma_Z)$, I would expect the probability that the qubit is in either state to be constant at 0.5. However the probability increases with time. I also plot the probability using numpy and it stays flat.

![image](https://github.com/user-attachments/assets/ae457442-899b-40c5-9b7b-f31b905815fb)

### MWE:
```python
import numpy as np
from qutip import *
import matplotlib.pyplot as plt
from scipy.linalg import expm

H = Qobj([[0,0],[0,5e3]])
psi0 = Qobj([1,1]).unit()
tlist = np.linspace(0, 100, 1431)

#qutip
result = mesolve(H,psi0,tlist)
prob_qutip_0 = []
prob_qutip_1 = []
for state in result.states:
    probabilities = [abs(state[i])**2 for i in range(2)]
    prob_qutip_0.append(probabilities[0])
    prob_qutip_1.append(probabilities[1])

#numpy
prob_np_0 = []
prob_np_1 = []
for t in tlist:
    state = expm(-1j*t*H.full()) @ psi0.full()
    probabilities = [abs(state[i])**2 for i in range(2)]
    prob_np_0.append(probabilities[0])
    prob_np_1.append(probabilities[1])

#plot
plt.plot(tlist,prob_qutip_0,label='qutip')
plt.plot(tlist,prob_np_0,label='numpy')
plt.ylim([0,1.1])
plt.ylabel('Probability of qubit in level n=0')
plt.xlabel('Time [us]')
plt.legend()
```

I have tried increasing the nsteps and max_step options but it doesn't help. Any help is appreciated.

**Comment by Ericgig** [comment]
You need to change the options `rtol`:
![plt](https://github.com/user-attachments/assets/8c833116-4ef6-48bc-8e4b-3793ee0189f9)
