### ISSUE TITLE
ImportError: cannot import name 'dense' from partially initialized module 'qutip.core.data' (most likely due to a circular import)

### ISSUE THREAD

**Issue by LemonMM9** [qutip/qutip#2566]
### Bug Description

I installed qutip through Pycharm Coummunity Edition 2023.1.4. The installation was successful but when I tried to verify the installation through testing.py , I received following error:

### Code to Reproduce the Bug

```shell
D:\simulation\qutip-qutip-5.0.X> python -m qutip.testing
```

### Code Output

```shell
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "D:\simulation\qutip-qutip-5.0.X\qutip\__init__.py", line 33, in <module>
    from .core import *
  File "D:\simulation\qutip-qutip-5.0.X\qutip\core\__init__.py", line 2, in <module>
    from .coefficient import *
  File "D:\simulation\qutip-qutip-5.0.X\qutip\core\coefficient.py", line 23, in <module>
    from .data import Data
  File "D:\simulation\qutip-qutip-5.0.X\qutip\core\data\__init__.py", line 3, in <module>
    from . import dense, csr
ImportError: cannot import name 'dense' from partially initialized module 'qutip.core.data' (most likely due to a circular import) (D:\simulation\qutip-qutip-5.0.X\qutip\core\data\__init__.py)
```

### Expected Behaviour

test scripts for QuTip

### Your Environment

```shell
I can't produce environment by using qutip.about()
```

**Comment by pmenczel** [comment]
Hi, I see two issues here: (1) Your working directory cannot be the qutip installation directory. If you try to run any code (that imports qutip) from inside the installation directory, it will fail. If you try any other directory, the error should go away. (2) `python -m qutip.testing` is not the correct way to run the test suite. In fact, the command does nothing. If you could let us know where you got this wrong command from, we can perhaps fix that part of the documentation. These should work (from any directory other than the installation directory):
```bash
pytest --pyargs qutip.tests
```
or
```bash
python -c 'from qutip import testing; testing.run()'
```

**Comment by Ericgig** [comment]
Hopefully Paul's solution worked.
