### ISSUE TITLE
Add support dense matrix representation in Qobj

### ISSUE THREAD

**Issue by jrjohansson** [qutip/qutip#26]
Qobj currently use sparse matrix representation for operators and kets/bras, which is optimal for large systen but suboptimal for small systems. We want Qobj to support both sparse and dense matrix representation for the quantum object it represents. This should probably be implemented with two different classes, QobjSparse and QobjDense which inherit a common  interface from a parent class Qobj.

**Comment by nonhermitian** [comment]
I doubt we will ever get around to this, so I will close this issue.

**Comment by ajgpitch** [comment]
This is now more urgent. In answer to #370  I submitted #397. However, it was found that significant performance degradation occurred in the control evolution calculation for small systems, and as such a retrofit of ndarray option for internal operator type was made.  This leads to pretty untidy code, and means that subclasses for propagator and gradient calculations, fidelity, and evolution calculations all need to implement conditional methods.  

Implementation of a dense Qobj would resolve these problems, and as mentioned above, could lead to performance improvements in many of the other solvers.

Many of the solvers assume sparsity, and so they too may need changes to support dense states and operators.
