### ISSUE TITLE
T_0 triplet state not normalized

### ISSUE THREAD

**Issue by airikh** [qutip/qutip#305]
FYI: I believe the T<sub>0</sub> state is not normalized. I think it should be
```python
    ...
    trip_states.append(
       (tensor(basis(2), basis(2, 1))+tensor(basis(2, 1), basis(2))).unit())
    ...
```

**Comment by jrjohansson** [comment]
You're right, thanks for pointing this out. Would you be willing to submit a PR that fixes this?

**Comment by airikh** [comment]
I would be happy to submit a PR for the fix. I forked the repo, added a test for the bug fix, and fixed the bug to pass the test. I just submitted the request.

**Comment by nonhermitian** [comment]
This has been taken care of.
