### ISSUE TITLE
setup.py tries to install on arm architecture with option '-mfpmath=sse'

### ISSUE THREAD

**Issue by wetlife** [qutip/qutip#309]
It seems like I could change or remove the option if I could find it. Here is a dump of my issue with  setup.py: 

$ sudo python setup.py install
Installing without the fortran mcsolver.
running install
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building py_modules sources
building extension "qutip.cy.spmatfuncs" sources
building extension "qutip.cy.stochastic" sources
building extension "qutip.cy.sparse_utils" sources
building extension "qutip.cy.graph_utils" sources
building extension "qutip.control.cy_grape" sources
building data_files sources
build_src: building npy-pkg config files
running build_py
copying qutip/version.py -> build/lib.linux-armv7l-2.7/qutip
copying build/src.linux-armv7l-2.7/qutip/__config__.py -> build/lib.linux-armv7l-2.7/qutip
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
building 'qutip.cy.spmatfuncs' extension
compiling C sources
C compiler: arm-linux-gnueabihf-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC

compile options: '-I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c'
extra options: '-w -ffast-math -O3 -march=native -mfpmath=sse'
arm-linux-gnueabihf-gcc: qutip/cy/spmatfuncs.c
arm-linux-gnueabihf-gcc: error: unrecognized command line option '-mfpmath=sse'
arm-linux-gnueabihf-gcc: error: unrecognized command line option '-mfpmath=sse'
error: Command "arm-linux-gnueabihf-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c qutip/cy/spmatfuncs.c -o build/temp.linux-armv7l-2.7/qutip/cy/spmatfuncs.o -w -ffast-math -O3 -march=native -mfpmath=sse" failed with exit status 1

**Comment by nonhermitian** [comment]
That particular flag is causing trouble as ARM cpus do not have the SSE extensions.  Instead ARM v7+ use the NEON extensions.  As such, the build is failing.  However, this flag is really only useful for x86 (32-bit) systems where the fpmath is not set to use SSE by default.  On x64 it is.  If you want to remove this flag yourself, it is in the setup.py files in the 'cy' and 'control' directories inside the qutip directory.

Given that their are no commercially available ARM systems outside of the Raspberry PI and MS Surface.  I am not sure if adding support for ARM extensions is really necessary at the moment.

**Comment by nonhermitian** [comment]
This is fixed in #311.

**Comment by jrjohansson** [comment]
Out of curiosity, which ARM hardware are you trying to use QuTiP on?

**Comment by nonhermitian** [comment]
Closing this issue since it has been addressed, and no response to the final question.
