### ISSUE TITLE
Improved random quantum objects

### ISSUE THREAD

**Issue by cgranade** [qutip/qutip#315]
I think it would make sense to add to the current random quantum objects functionality support for sampling from a few more commonly-used distributions. In particular, the Ginibre and Haar distributions for density operators as well as the [Bruzda et al distribution for CPTP maps](http://www.sciencedirect.com/science/article/pii/S0375960108016885) would be quite nice to have sampling support for. I've written up all three of these based on existing QuTiP functions, such that if there's interest, it would be rather straightforward for me to make a PR for this enhancement.

**Comment by jrjohansson** [comment]
That sounds interesting. Your PR would be most welcome.

**Comment by nonhermitian** [comment]
I second this.  The current random states are not so physical, except for satisfying the usual constraints.

**Comment by cgranade** [comment]
Sounds good, then. I'll get this done in the next couple days, then. Thank you for the feedback!

**Comment by cgranade** [comment]
This isn't quite ready for a PR (not tested, missing documentation, etc.), but should show the general scope of what I am planning on. I went with the convention of naming new functions something along the lines of ``rand_dm_ginibre`` to differentiate from existing functions like ``rand_dm``. Does this make sense, or is there another API design that would work better? Thanks!

**Comment by nonhermitian** [comment]
This is now closed.
