### ISSUE TITLE
Efficient method to estimate time to reach steady state

### ISSUE THREAD

**Issue by yipk2** [qutip/qutip#319]
Hi!
Assume that the system will reach a steady state.
Is there an efficient method to estimate the time it takes to reach the steady state (or to enter and remain within a specified error band)? 
My wish is that I do not have to calculate the steady state (using the steadystate function or others) to achieve that. Thank you very much.

**Comment by nonhermitian** [comment]
In short the answer is no. One could think of a couple of ways of trying to determine whether the system has reached the steady state or not, but for nonlinear systems this is difficult. In addition, how would you calculate the error if you dont know the steady state solution in the first place?

**Comment by nonhermitian** [comment]
I am assuming that this question is closed since a reply has not been received in six days.
