### ISSUE TITLE
`mcsolve` differs substantially from the algorithm described in the literature

### ISSUE THREAD

**Issue by Krastanov** [qutip/qutip#344]
Could you provide a reference describing the `mcsolve` algorithm that you have implemented as the implementation in `qutip` is quite different from the version described here https://www.osapublishing.org/josab/abstract.cfm?uri=josab-10-3-524 ?

**Comment by nonhermitian** [comment]
It is actually basically the same thing.  However, there are several technicalities that need to be addressed in the implementation.  For example, one does not know the collapse times a priori, so one has to evolve pass this time and then take a step back. Can also see:

Monte Carlo simulation of the atomic master equation for spontaneous emission
R. Dum, P. Zoller, and H. Ritsch
Phys. Rev. A 45, 4879 – Published 1 April 1992

**Comment by Krastanov** [comment]
I was claiming that the algorithm from the Molmer paper is different because it relies on small timesteps and it does not use stepping back (or more generally, it does not use any form of root finding). They are probably equivalent, but I did not find the equivalence obvious.

Thanks for the reference, I will check it out.

Also, for the sake of more efficient root finding (if I understand correctly currently you are just repeating the integration over a smaller interval) you might find this interesting: http://mail.scipy.org/pipermail/scipy-user/2010-March/024890.html

**Comment by nonhermitian** [comment]
Yes, these are the implementation issues I discussed.  Calling the ode solver of course takes small steps, with the step size based on the requested tolerance level.  Our root finding is trivial in this case.  We linearize the evolution and then find the intercept.  It almost always works in a single step, and is quite efficient.

**Comment by Krastanov** [comment]
Thanks! This cleared up my confusion.
