### ISSUE TITLE
Bug in control/optimizer.py 

### ISSUE THREAD

**Issue by zerodynamics** [qutip/qutip#353]
There appears to be a bug in OptimizerLBFGSB.run_optimization .  At line 901, _build_bounds_list is called and correctly constructs the list of upper and lower bound tuples and sets self.bounds, however there is no return value.  At line 939,  the empty variable 'bounds' is passed to scipy.fmin_l_bfgs_b and therefore the constraints are not active.  

Easy solution is to change "bounds=bounds" to "bounds=self.bounds" in line 939.

**Comment by ajgpitch** [comment]
Good spot. A lot of changes were made to the Optimizer class when the CRAB algorithm, I think this slipped in then.  You will see on line 518 that the base class method passes the bounds as you suggest. Therefore the if you specify optim_method='l-bfgs-b' in any of the pulseoptim methods then your bounds should work and you will be using L-BFGS-B. 

I'll create a pull request with this fix now though. 
Thanks

**Comment by ajgpitch** [comment]
There appear to be a few issues with the bounds. I will take a better look later or tomorrow.

**Comment by zerodynamics** [comment]
In some spot testing, I found that making the proposed change (bounds -> self.bounds) sets the constraints correctly.

**Comment by ajgpitch** [comment]
You'll see I had to make a coupled of other small changes to ensure the bounds passed in pulseoptim methods are applied to the Optimizer as well as the PulseGen

Thanks again for reporting this.
