### ISSUE TITLE
six library not available during Travis tests

### ISSUE THREAD

**Issue by ajgpitch** [qutip/qutip#378]
The six library is used for Python 2.x and 3.x compatibility tricks. It failed to import during Travis tests. Should we make this library available in Travis tests?

**Comment by jrjohansson** [comment]
Is six used in qutip now? If so then go ahead and add it as a dependency, I'd say. Personally I don't like use six, and prefer to write idiomatic Python 3 code that also work for Python 2, but I don't see any problems with anyone else using it. It is a pretty standard dependency for Python 2 and 3 compatibility needs.

**Comment by ajgpitch** [comment]
Yes, I had used it to check whether a variable was a string type. I saw it suggested somewhere. It has only just come up as I am adding (long overdue) tests for the control modules.  I have now replaced the six based method with something else, but I think the six.string_types method was more elegant.

**Comment by nonhermitian** [comment]
This is now closed.
