### ISSUE TITLE
mesolve: allow superoperator as initial condition

### ISSUE THREAD

**Issue by arnelg** [qutip/qutip#384]
Hi all,

There are quite a few applications when it is convenient to solve the Lindblad master equation for a superoperator, i.e.,

![equation](https://dl.dropboxusercontent.com/u/6042643/Tex2Img_1445353534.jpg)

where the last equation shows how the density matrix is found from the time-propagator (i.e., the superoperator solution to the Lindblad equation). The initial condition to the first equation is typically the identity superoperator.

As an example, I've typically come across the need for this when dealing with non-Markovian problems. Certain non-Markovian problems can be dealt with using time-propagators of the above type where the Lindblad evolution is in an "enlarged" Hilbert space of some sort. In fact, to give some motivation for implementing this feature, I am currently working on a sub-package for qutip with a few solvers for non-Markovian problems, one of them being the so-called "Transfer Tensor Method" (TTM) [PRL 112, 110401 (2014)], which takes as input a list of precomputed dynamical maps in the form of superoperators. A typical usecase could be to generate these with a (costly) Lindblad equation in a large Hilbert space, and use the TTM to extrapolate to larger times. My code is not quite ready for a pull request yet (due to this issue amongst other things), but when it is I would also like to discuss the structure of such a package. I guess it is best to leave that to when I have a pull request ready though.

For now I have a local modified version of the `_mesolve_const` function that allows a superoperator in place of `rho0`. The necessary modification is actually only to the function implementing the "right hand side" (RHS) of the differential equation, as this now needs to implement a matrix-matrix multiplication instead of a matrix-vector multiplication. For illustration purposes I will attach a code for a modified `_mesolve_const` below, that does the job, but the RHS is not implemented in cython.

I think implementing this feature in qutip should be relatively straight forward, but possibly a bit tedious since it there are so many different dispatch functions from `mesolve` depending on the different types of time-dependence etc. One would also need cython implementations of the RHS functions for superoperator evolutions.

Please let me know what you think about implementing this in qutip.

Here is the code for a function that propagates the Lindblad equation with a superoperator as initial value (written as a standalone module for illustration purposes). As you will notice in the code, there is a subtle issue with needing to transpose the Lindbladian to get the correct result. I'm not sure why this is the case.. must be something with the superoperator representation. Perhaps @cgranade knows?

````python
import scipy

from qutip.mesolve import _generic_ode_solve
from qutip.superoperator import liouvillian, mat2vec
from qutip.settings import debug

if debug:
    import inspect


def _mesolve_const_super(H, E0, tlist, c_op_list, e_ops, args, opt,
                   progress_bar):
    """
    Evolve the super-operator `E0` using an ODE solver, for constant 
    Liouvillian
    """

    if debug:
        print(inspect.stack()[0][3])

    """
    #
    # check initial state
    #
    if isket(rho0):
        # if initial state is a ket and no collapse operator where given,
        # fall back on the unitary schrodinger equation solver
        if len(c_op_list) == 0 and isoper(H):
            return _sesolve_const(H, rho0, tlist, e_ops, args, opt,
                                  progress_bar)

        # Got a wave function as initial state: convert to density matrix.
        rho0 = ket2dm(rho0)
    """

    #
    # check initial value
    #
    if not E0.issuper:
        raise TypeError("Argument 'E0' should be a super-operator")

    #
    # construct liouvillian
    #
    if opt.tidy:
        H = H.tidyup(opt.atol)

    L = liouvillian(H, c_op_list)

    #
    # setup integrator
    #
    initial_vector = mat2vec(E0.full()).ravel()
    # r = scipy.integrate.ode(cy_ode_rhs)
    r = scipy.integrate.ode(_rhs)
    # r.set_f_params(L.data.data, L.data.indices, L.data.indptr)
    # not sure why I need to transpose L here:
    r.set_f_params(L.trans().data)
    r.set_integrator('zvode', method=opt.method, order=opt.order,
                     atol=opt.atol, rtol=opt.rtol, nsteps=opt.nsteps,
                     first_step=opt.first_step, min_step=opt.min_step,
                     max_step=opt.max_step)
    r.set_initial_value(initial_vector, tlist[0])

    #
    # call generic ODE code
    #
    return _generic_ode_solve(r, E0, tlist, e_ops, opt, progress_bar)


def _rhs(t,y,data):
    ym = y.reshape(data.shape)
    return (ym*data).ravel()
````

**Comment by jrjohansson** [comment]
Sounds like a great idea to me. Certainly within the scope of QuTiP. Please go ahead and make a pull request.

**Comment by nonhermitian** [comment]
It does sound interesting. I dont think the cython part would be too difficult to implement if the changes are as small as you  suggest. 
Paul

**Comment by arnelg** [comment]
I'm (slowly) working on this, and right now I'm writing unit tests. Is there a unit test anywhere for the `_mesolve_func_td` function in the `mesolve` module?
