### ISSUE TITLE
Anaconda install on OS X no fortran compiler

### ISSUE THREAD

**Issue by src10** [qutip/qutip#391]
Hello!!!

I installed python using anaconda on my mac and then installed qutip.

When I run the installation test I always get

Fortran mcsolver:   False

How can I install the Fortran compiler needed.

Thanks

Regards!!

Sebastian

**Comment by nonhermitian** [comment]
Did you install using --with-mcf90 ?

**Comment by cgranade** [comment]
Installing FORTRAN on OS X can be a bit tricky, but I've seen several people successfully use the [HPC for OS X](http://hpc.sourceforge.net/) builds of gfortran.

**Comment by src10** [comment]
yes! I installed it using --with-mcf90

Am I supposed to install fortran compiler besides the ones I have on anconda?

**Comment by nonhermitian** [comment]
By default, OSX does not have a fortran solver.  One way to get one is to use macports and install the gcc compiler that includes gfortran.  However, as of version 3.1, the standard monte carlo solver is on par with the fortran solver, so unless you are doing something where a factor of 2 or so is really important, then you do not need this feature.

**Comment by arnelg** [comment]
I didn't know the native solver had become so fast. Maybe we should add a deprecation warning of some sort to the fortran solver, with the intention of eventually phasing it out, or at least to encourage using the native solver instead.

**Comment by nonhermitian** [comment]
Resolved
