### ISSUE TITLE
sesolve accepts only kets

### ISSUE THREAD

**Issue by co9olguy** [qutip/qutip#402]
The docs for the sesolve function are ambiguous about the form of the input state. In several places, it mentions that density matrixes are an option (even using the name 'rho0' as an argument). However, when trying to solve using a density matrix, I get the TypeError "psi0 must be a ket"

Sample code:

```
from qutip import *
H = tensor(sigmaz())
rho = tensor(identity(2))/2
tlist = range(0,10)
sesolve(H,rho,tlist,[])
```

**Comment by nathanshammah** [comment]
Documentation needs fixing. Change `rho0` to `psi0` only. Add explanation of dUdt=-iHU in documentation.

**Comment by nathanshammah** [comment]
Now fixed in the docstrings of sesolve.py.
