### ISSUE TITLE
`qutip.control.optimize_pulse` does not treat 'num_waves' key in `init_pulse_params` correctly for periodic pulses

### ISSUE THREAD

**Issue by arnelg** [qutip/qutip#412]
I tried modifying the frequency of a periodic pulse using the `init_pulse_params` argument to `qutip.control.optimize_pulse` (GRAPE algorithm). I tried passing, for example,

````
init_pulse_params = {'num_waves': 2.0}
````
but no matter what I choose for 'num_waves', I always get exactly one period (`num_waves`=1.0) for the initial pulse. Similarly if I try to pass a 'freq' key in the dictionary. Looking at the code, it looks like this is hard coded in `create_pulse_optimizer` (line 1942: `pgen.num_waves = 1.0`). Either this is a bug, or I'm misunderstanding how to use the interface.

**Comment by ajgpitch** [comment]
Seems quite likely that there is a bug here. I will investigate further and try to fix now.

**Comment by ajgpitch** [comment]
I have replicated this. The hardcode num_waves seems a bit spurious. I think it is best to delete it altogether. It does mean that it breaks backward compatibility, but I can't why anyone would rely on this (or why I coded it that way in the first place)

I am working on unit tests for this now.

**Comment by ajgpitch** [comment]
Solved by #415
