### ISSUE TITLE
Version table ncpus key missing

### ISSUE THREAD

**Issue by ajgpitch** [qutip/qutip#423]
I was helping someone with an install on windows 7 yesterday.
We were testing using a notebook, and it worked fine except the version_table. The first error was resolved by installing ipython parallel. Still after that it was failing with something like key 'ncpus' missing. Sorry for not supplying exact errors. I could ask the user to post them if necessary.

@nonhermitian is #421 likely to resolve this? Even if say they don't have win32com or comtypes installed?

**Comment by nonhermitian** [comment]
The parallel issue was resolved earlier. See the ipynbtools import of ipyparallel. ncps should not be an issue as it has always has fallen back on the multiprocessing count

**Comment by ajgpitch** [comment]
Well, yesterday when helping said user, I installed a fresh Anaconda 32bit for winodws + mingw + libpython. Then I installed the latest github release of qutip. And still I got these issues.
I could try to reproduce on a clean win7 virtual machine I have here?

**Comment by nonhermitian** [comment]
I see the issue. I did not upload all my fixes for that issue. Just the change supporting jupyter. Will upload tonight. Sorry, too many repos to keep track of.

**Comment by ajgpitch** [comment]
Good news. All makes sense now

**Comment by nonhermitian** [comment]
npus should be fixed with Pull #421 .

**Comment by nonhermitian** [comment]
This is fixed.
