### ISSUE TITLE
Qobj trunc_neg causing Travis errors

### ISSUE THREAD

**Issue by ajgpitch** [qutip/qutip#425]
The tests for this are sometimes erroring in Travis
See test result for #424 
ERROR: Test Qobj: trunc_neg works for non-diagonal opers.

I saw a conversation about this somewhere, but can't find it now

**Comment by cgranade** [comment]
I'll take a look, then, figure out why it's giving an IndexError.

**Comment by cgranade** [comment]
This should be fixed by #428. I tried running tests locally several times, and didn't observe any failures. If Travis checks out on that PR, I'll merge it and close both issues.
