### ISSUE TITLE
Trigonometric functions of Qobj

### ISSUE THREAD

**Issue by Phyks** [qutip/qutip#427]
Hi,

I had to call `sin` and `cos` on operators.

```python3
>>> from qutip import destroy
>>> from numpy import sin
>>> sin(destroy(3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Qobj' object has no attribute 'sin'
```

However, `sin(destroy(3).data)` works. It seems that a method is not forwarded from the `Qobj` object to the underlying sparse matrix. Would it be possible to apply such a trigonometric function on the `Qobj` and still have a `Qobj` afterwards?

Thanks

**Comment by Phyks** [comment]
Oops, was mistakingly thinking that `numpy.sin` of a matrix was computing the `sin` of this matrix. It is not the case actually.

Still, it could be useful to be able to compute such functions on `Qobj`.

**Comment by nonhermitian** [comment]
You can use 0.5*((1j*A).expm()+(-1j*A).expm()) etc to get what you want.

**Comment by cgranade** [comment]
If this is a common enough requirement, I can go on and add ``cosm`` and ``sinm`` functions to ``Qobj`` that use @nonhermitian's example. That has the benefit over ``scipy.linalg.cosm`` that it preserves ``dims``, ``type`` and other similar metadata (though we would not want to preserve ``isherm``).

**Comment by Phyks** [comment]
@nonhermitian Thanks, it's much easier that what I was dealing with!

@cgranade Indeed, conserving the metadata is a really good thing. For more (scientific) information, I am dealing with Josephson junctions with an hamiltonian of the form $\hbar \omega a^{\dagger}a - E_J \cos \varphi$ where $\varphi$ is proportional to $a + a^{\dagger}$. I wanted to try to analyze the full hamiltonian with QuTIP and comparing with some expansions.

**Comment by Phyks** [comment]
Any news on this? I would personnally find it particularly useful to have `cosm` and `sinm` methods on `Qobj` class. I can submit a PR with it if you want.

If such methods are not to be added, I think this issue can be safely closed.

**Comment by nonhermitian** [comment]
It is already in the latest dev version on github.

**Comment by Phyks** [comment]
Indeed, sorry for the noise, I completely missed it when it got added. Closing the issue as it is no longer relevant. Thanks!
