### ISSUE TITLE
MemoryError when printing

### ISSUE THREAD

**Issue by Phyks** [qutip/qutip#432]
Hi,

```python
import qutip
qutip.tensor(qutip.destroy(20), qutip.destroy(20), qutip.destroy(20))
```
works fine, but gives a `MemoryError` (in a Jupyter Notebook for instance) as it trying to print the full size matrix.

Maybe above a given size, it would be better to just display the `.data` (sparse matrix) attribute rather than trying to display the full matrix and raising `MemoryError`? (plus a sparse matrix may give more information than the full matrix).

**Comment by nonhermitian** [comment]
It is likely that the 64 million elements it the array are causing the issue.

**Comment by ajgpitch** [comment]
Yes, you should avoid printing such a large object. I imagine the memoryerror occurs when it is generating the full() representation for printing

```
q = qutip.tensor(qutip.destroy(20), qutip.destroy(20), qutip.destroy(20))
```

would avoid the object being printed in the notebook.
I have no experience of working with such a large object though, so I can't say that you would be able to anything useful with it.

**Comment by cgranade** [comment]
I'm actually a bit confused about why there would be a ``MemoryError`` when outputting in Jupyter Notebook, since ``Qobj._repr_latex_`` currently only converts the first and last five rows and columns. Indeed, when I ran the exact code listed in a Jupyter Notebook, the output was properly truncated to prevent printing a gigantic matrix:

<img width="584" src="https://cloud.githubusercontent.com/assets/31516/13064734/8ba727fe-d4a9-11e5-9a81-134bc2eaccfe.PNG">

**Comment by Phyks** [comment]
Just to be sure we are talking about the same thing, I was indeed talking about the Jupyter Notebook output (`Qobj._repr_latex_`), as shown by @cgranade, and not any direct printing (`print(Qobj)`) or REPL print (`qutip.tensor(qutip.destroy(20), qutip.destroy(20), qutip.destroy(20))` in the interpreter).

My issue actually has two points:

* First, I had this `MemoryError` when doing exactly what is shown on @cgranade screenshot, which I cannot reproduce at the moment. My bet is that I was running out of RAM, and while I could still represent any other output, the `_repr_latex` was giving `MemoryError`. I will try to reproduce and investigate this further.
* Second, as shown on @cgranade screenshot, the output is not really interesting in this particular case, as we basically only see zeros. In my opinion, in such a case, it would be more interesting for the user to have an output of `Qobj.data` which states the number of non-zero elements. See screenshot below for the output I am talking about.

![2016-02-16-110408](https://cloud.githubusercontent.com/assets/3856586/13073062/25c24952-d49d-11e5-9fb0-1d717475fbd6.png)

**Comment by nonhermitian** [comment]
I also get no error.  The user already has access to Q.data, so if this is what they want, then it is already available.  I do not see any benefit of changing the display output.

**Comment by nonhermitian** [comment]
I will close this issue as it looks like there is nothing more to say on the issue.
