### ISSUE TITLE
test_SuperChoiChiSuper issues a UserWarning

### ISSUE THREAD

**Issue by ajgpitch** [qutip/qutip#433]
UserWarning: Multiplying superoperators with different representations
issued during tests.
@cgranade I think you implemented this part. Is this something to concern
I mainly raised it as I have spent my evening removing all the other warnings from the tests, so would be nice to clear them all

**Comment by cgranade** [comment]
Sorry, caught me while I was travelling to Albuquerque. I'll take a look ASAP, then.

**Comment by ajgpitch** [comment]
I would not by any means call it urgent. More like something to look at some time

**Comment by cgranade** [comment]
All the same, I'd very much like to further reduce warnings. I've literally had Firefox crash trying to load the entire Travis logs.
