### ISSUE TITLE
Fortran solver does not work using Anaconda

### ISSUE THREAD

**Issue by nonhermitian** [qutip/qutip#439]
We are planning on moving to use the Anaconda suite as the primary method for installing and using QuTiP.  However, this means that one can not install the mcf90 files in a straightforward manner.  How are we going to handle these fortran files from here on out?

**Comment by ajgpitch** [comment]
Yes, I have not been able to install mcf90 under anaconda.
I think I remember seeing some discussion suggesting that the mcf90 has little or any performance improvement over the standard mcsolver. I have not tried myself. Being an anaconda user, this would take some effort for me.
I think that if it is not offering much greater performance, then we should just exclude it from the conda package.

**Comment by arnelg** [comment]
I personally haven't used mcf90 for a looong time. If it is true that it does not give much of a performance improvement any more I think it makes sense to phase it out.

**Comment by nonhermitian** [comment]
Since we are now using Anaconda as the default installation platform, I think that it is time to move the mcf90 module to its own installer.  This can be done in Pull #648, with the files left where they are, and then moved to another install when we get around to it.

**Comment by ajgpitch** [comment]
I agree. Problems installing with the mcf90 option do cause quite a lot of confusion with new users

**Comment by nonhermitian** [comment]
No longer an issue.
