### ISSUE TITLE
Documentation about progressbar

### ISSUE THREAD

**Issue by Phyks** [qutip/qutip#444]
Hi,

I cannot find any doc (except the source code itself) about which progress bar are available and how to use them. Especially, the only references to the progress bar in [the doc](http://qutip.org/docs/3.1.0/) are the options for `mesolve` etc.

I think it could be really useful to document it, or provide an iPython notebook making use of it.

EDIT: Plus the docstring of `mesolve` function (for instance) seems to contradict the first lines of the function:
```
progress_bar: BaseProgressBar
        Optional instance of BaseProgressBar, or a subclass thereof, for
        showing the progress of the simulation.
```

versus

```python
    if progress_bar is None:
        progress_bar = BaseProgressBar()
    elif progress_bar is True:
        progress_bar = TextProgressBar()
```

**Comment by ajgpitch** [comment]
Hi, thanks for raising this. I have raised an issue in the docs repo for the documentation gap. So I guess in this issue we will focus on the possible contradiction. There are others who know this solver better than me, so I will wait to see if they comment before I investigate further.

**Comment by eliemichel** [comment]
It's not completely contradictory: if you provide an instance of `BaseProgressBar`, it'll work. And the argument is optional. Just that on top of that, you can just say `True` to avoid instanciating yourself the progress object, and this is not documented.
Anyway, I'm just noticing, I don't know the neither. ;)

**Comment by Phyks** [comment]
@ajgpitch Maybe I should close this issue and move the discussion to the linked issue in the doc repo?
