### ISSUE TITLE
Does not compile under MS Visual C

### ISSUE THREAD

**Issue by ajgpitch** [qutip/qutip#447]
Not really expecting anyone to fix this urgently, I am just recording some ideas, as I have spent a lot of time looking into this recently while try to build a conda package

Currently on Windows we compile under mingw. This is sub-optimal, according to various sources, including:
https://wiki.python.org/moin/WindowsCompilers
Python C extensions should be compiled using the same compiler that was used to compile the Python distro that is being used. Failing to do so can result in some strange behaviour. I have experienced issues with qutip tests hanging on Windows. Therefore it would clearly be beneficial if we could build qutip under MSVC. It is of particular interest now that we have a conda recipe that autobuilds for all the version, platform variations.

**Comment by ajgpitch** [comment]
MSVC v10 (that is for py < 35) reports a failure to find complex.h
MSVC v14 (for py35) reports issues with pyx_build (can't remember exactly)

**Comment by ajgpitch** [comment]
It would seem to sense to look into how other packages that have C extension (e.g. numpy) deal with these issues.

**Comment by nonhermitian** [comment]
I have looked into this a bit. Everything compiles fine except the things that require complex.h. VS 15 has this library, and MS even highlights their compatibility with C99. However, others have found that the MS complex type is not compatible with C99. Therefore, one gets a typedef conversion error. Therefore we would have to write a conversion function. Another possibility is to use the Intel compilers. I believe one can get them for free if in academics.

**Comment by cgohlke** [comment]
FWIW, I used Intel compilers on Windows to compile QuTip (http://www.lfd.uci.edu/~gohlke/pythonlibs/#qutip). One issue is that Cython uses GCC some extensions instead of C99 for complex types. That's easy to fix by patching either Cython or the generated C files: change `__real__` to `creal` and 
`__imag__` to `cimag`.

**Comment by nonhermitian** [comment]
Thanks for pointing this out.  I did not know that this was the case.  Ironically the complex numbers are done this way to support compilers (VS in particular) that do not obey C99.  The suggested patch is a bit difficult to implement as the runtime generated Cython code is compiled via pyximport and getting in there to change the c files would be a bit tricky.  However, I know that the Intel compiler has no problem with the Cython code (at least on Linux).  So perhaps that is the way to go for Python 3.5.

**Comment by ajgpitch** [comment]
I thought that it was highly recommended to use the same compiler for
extensions that is used for python itself? Is this just an ideal rather
than a necessity?

Also, it would be ideal to try and use a compiler that is available on the
conda-forge.  Not sure whether the Intel one is or not.

**Comment by nonhermitian** [comment]
Well, we have been using mingw for qutip, while the Win Python has always been compiled with VS.  while I agree with your statement, using VS seems not to be an option for us. I haven't had any problems in mu minimal testing.

**Comment by ajgpitch** [comment]
I agree, I have also not had any problems with mingw.
The only issue seems to be that it won't work with python 3.5. Perhaps they
will fix that and solve our problem that way.

**Comment by nonhermitian** [comment]
According to this thread mingw32 is not going to happen for Py35:

https://github.com/statsmodels/statsmodels/issues/2751

But supposedly mingw64 will.  The current solution is VS 15 or Intel. I will try to get something cooking with Intel tonight.  I will try Anaconda and the Intel Python distro.  The later is compiled with the Intel compilers, so hopefully things will work more or less straight forward.

**Comment by nonhermitian** [comment]
Actually, it seems that now the Intel distro is built with VS15, and distutils does not know how to handle Intel compilers.  However, I am sure that the earlier tech preview was all Intel, and I even had to install the Intel compilers to get anything to build.  Regardless, it seems that we need to wait until mingw is supported on Py35.

**Comment by cgohlke** [comment]
Python distutils does not support Intel compilers but [numpy distutils](https://github.com/numpy/numpy/blob/master/numpy/distutils/intelccompiler.py#L72) does. It is used to [build qutip](https://github.com/qutip/qutip/blob/master/setup.py#L49).

**Comment by nonhermitian** [comment]
The issue is that we need to compile at runtime in Cython using pyximport.  I do not know a way to get pyximport to use numpy distutils.

**Comment by nonhermitian** [comment]
This is closed.
