### ISSUE TITLE
Tests not properly working on Canopy

### ISSUE THREAD

**Issue by lightning469** [qutip/qutip#469]
Hi,
I just recently installed qutip on Canopy using a Windows Binary. When I try to run one of the tests, e.g. test_wigner.py, I get this error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
C:\Users\David Feng\Desktop\qutip-3.1.0\qutip\tests\test_wigner.py in <module>()
     37 from numpy.testing import assert_, run_module_suite, assert_equal
     38 
---> 39 from qutip.states import coherent, fock
     40 from qutip.wigner import wigner
     41 from qutip.random_objects import rand_dm, rand_ket

C:\Users\David Feng\Desktop\qutip-3.1.0\qutip\__init__.pyc in <module>()
     60     qutip.settings.ipython = True
     61 except:
---> 62     qutip.settings.ipython = False
     63 
     64 # -----------------------------------------------------------------------------

AttributeError: 'module' object has no attribute 'settings' 

The AttributeError also appears when I simply try to import qutip from the command line. I'm not too familiar with Python scripting so any assistance on the matter would be greatly appreciated. Thank you!

**Comment by nonhermitian** [comment]
It seems that you are running qutip from the installation directory. You should change directories first.

**Comment by lightning469** [comment]
Thanks, it worked! I simply moved it to the library where third-party packages are installed in Canopy.
