### ISSUE TITLE
Add package to Ubuntu 16.04 release channel

### ISSUE THREAD

**Issue by i2000s** [qutip/qutip#472]
There doesn't seem to be the package released under Ubuntu 16.04 channel. After I added the Ubuntu PPA for QuTiP, I got the following error/warning:

```
qxd@ubuntu1604$: sudo apt-get update
...
W: The repository 'http://ppa.launchpad.net/jrjohansson/qutip-releases/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/jrjohansson/qutip-releases/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/jrjohansson/qutip-releases/ubuntu/dists/xenial/main/binary-i386/Packages  404  Not Found
```

Thanks for maintaining it :)

**Comment by ajgpitch** [comment]
We have decided not to continue to maintain the Ubuntu channel. Please
install from source to using qutip 3.2.
Alternatively you can use the conda-forge channel if you are able to work
with qutip 3.1

**Comment by i2000s** [comment]
@ajgpitch Do you have any detailed instructions on using the 3.2 develop branch in Jupyter notebook? I posted a thread in the [email list](https://groups.google.com/forum/#!topic/qutip/oh1t7xJg5x8) while having trouble to compile the examples in using Stochastic equation solvers. I have tried to compile the source and to call from Conda-forge virtual environment, but always fail despite all tests have been passed. Let me know if those examples are outdated. Thanks.

**Comment by ajgpitch** [comment]
Yes, the development notebooks can become outdated. Sometimes they are used to test specific new features. 

Please remind me here specifically which notebook you have found a problem with and I will raise an issue for it.

**Comment by cgranade** [comment]
As per @ajgpitch's comment above, since the Ubuntu channel is no longer maintained, I think it makes sense to close the issue now as a wontfix.
