### ISSUE TITLE
Install problem with fortran monte-carlo option

### ISSUE THREAD

**Issue by colinbann** [qutip/qutip#491]
I am trying to install qutip with the fortran monte-carlo solver.  I'm installing over a version of qutip which did not have this option, so my installation command is:

pip install --upgrade --no-deps --force-reinstall qutip --install-option=--with-f90mc

The build fails as below.  It is looking for libraries which do not exist in the MKL distribution I am using. Perhaps they existed in an earlier version ?  Can anyone advise how to achieve a succesful build - I think I need to modify the link line. 

Any suggestions gratefully received.
Colin

   /cm/shared/apps/gcc/4.8.1/bin/gfortran -Wall -g -Wall -g -shared build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/qutip/fortran/qutraj_runmodule.o build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/fortranobject.o build/temp.linux-x86_64-2.7/qutip/fortran/qutraj_precision.o build/temp.linux-x86_64-2.7/qutip/fortran/mt19937.o build/temp.linux-x86_64-2.7/qutip/fortran/linked_list.o build/temp.linux-x86_64-2.7/qutip/fortran/qutraj_general.o build/temp.linux-x86_64-2.7/qutip/fortran/qutraj_hilbert.o build/temp.linux-x86_64-2.7/qutip/fortran/qutraj_evolve.o build/temp.linux-x86_64-2.7/qutip/fortran/qutraj_linalg.o build/temp.linux-x86_64-2.7/qutip/fortran/qutraj_run.o build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/qutip/fortran/qutraj_run-f2pywrappers2.o -L/cm/shared/apps/intel/composer_xe/2013_sp1.3.174/mkl/lib/intel64 -L/cm/shared/apps/python/2.7.9/lib -Lbuild/temp.linux-x86_64-2.7 -lzvode -lmkl_lapack32 -lmkl_lapack64 -lmkl_rt -lpthread -lmkl_lapack32 -lmkl_lapack64 -lmkl_rt -lpthread -lpython2.7 -lgfortran -o build/lib.linux-x86_64-2.7/qutip/fortran/qutraj_run.so
    /usr/bin/ld: cannot find -lmkl_lapack32
    collect2: error: ld returned 1 exit status

**Comment by nonhermitian** [comment]
You are probably installing with the Anaconda Python package. It points to a location that does not exist for the mkl blas libraries, which it doesnt ship with. 

The fortran solver is somewhat dated, and the Python solver is now close in performance. You should probably use the latter one.

**Comment by colinbann** [comment]
Thanks - I'm doing an install on behalf of one of our researchers - I'll pass comment back.
