### ISSUE TITLE
Exponentiating a zero matrix doesn't work properly

### ISSUE THREAD

**Issue by Wuggins** [qutip/qutip#501]
Exponentiating a zero matrix yields a zero matrix in the latest version of qutip.

**Comment by nonhermitian** [comment]
Did you try the development release? Seems to work just fine.

**Comment by Wuggins** [comment]
Yes. Perhaps it is a problem with my scipy installation or something. I'll do some more poking around and try to figure it out.

- Bill

**Comment by nonhermitian** [comment]
This works as far as I can tell. Closing for lack of response.
