### ISSUE TITLE
Question about _mc_alg_evolve in the source code of mcsolve: 

### ISSUE THREAD

**Issue by kwyip** [qutip/qutip#503]
Looking into the function `_mc_alg_evolve` in the source code of mcsolve, I have two questions in mind:

1. Why do you divide the interval into each `tlist[k]` (`while ODE.t < tlist[k]:`) and run the ode internal step `ODE.integrate(tlist[k], step=1)` one at a time and evaluate `if norm2_psi <= rand_vals[0]:`?
Alternatively, can I run the ode `ODE.integrate(tlist, step=n)` without collapse until `norm2_psi <= rand_vals[0]`? It seems to be faster if `ODE.integrate(tlist, step=n)` can store the state. In this way I ignore `tlist[k]` totally.

2. After `if norm2_psi <= rand_vals[0]:`, you find the collapse time to within specified tolerance. Can I just take the collapse time as the time immediately after `ODE.integrate(tlist[k], step=1)`? Since the step in the `ODE` should be small enough, would it make a lot difference by ignoring the steps of finding the collapse time to within specified tolerance?

Thank you very much.

**Comment by nonhermitian** [comment]
1. You would not get the correct jump statistics.

2. If you dont jump at the correct time, then you introduce another source of error. Then the next jump time will be affected and so on.

**Comment by kwyip** [comment]
Thanks. I also wonder that is the difference between `ODE.y` and `ODE._y`. For example, in 
```
            t_prev = ODE.t
            y_prev = ODE.y
            norm2_prev = dznrm2(ODE._y) ** 2
```
Also, is the ODE from scipy?

**Comment by nonhermitian** [comment]
It is just a way to get at the internal data without going through extra checks. It is specific to the ode solver interface.
