### ISSUE TITLE
question about semiclassical equations of motion

### ISSUE THREAD

**Issue by farzane92** [qutip/qutip#504]
Hello, I read the '
Lecture 7 - Symbolic quantum mechanics using SymPsi - Semiclassical equations of motion' and re-run it's codes but I receive error in following line:
**********************************************************************************************************************
ops, op_eqm, sc_eqm, sc_ode, ofm, oim = semi_classical_eqm(H, c_ops)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-e7aaa32c59a9> in <module>()
----> 1 ops, op_eqm, sc_eqm, sc_ode, ofm, oim = semi_classical_eqm(H, c_ops)

ValueError: too many values to unpack

 **************************************************************************************************************************
what is this error?

**Comment by nonhermitian** [comment]
This should be posted at the sympsi page not here.
