### ISSUE TITLE
optomechanics

### ISSUE THREAD

**Issue by farzane92** [qutip/qutip#507]
Hello, I want to solve  problems in optomechanics with QuTip  but I don't know which packages(mathmp, sympy,sympsi,..) must be used. please guide me about writing QuTip programs for optomechanical systems. also, I want to know in steady state, how I can plot a quantity(like variance) versus variables other than time.

**Comment by nonhermitian** [comment]
The correct place to ask this type of question is the help group:

https://groups.google.com/d/forum/qutip

However, see the example here:

https://github.com/qutip/qutip-notebooks/blob/master/examples/example-optomechanical-steadystate.ipynb
