### ISSUE TITLE
expm() fails on simple Qobjs

### ISSUE THREAD

**Issue by Wuggins** [qutip/qutip#508]
Here is a screenshot that demonstrates the problem:

<img width="731" alt="screen shot 2016-08-03 at 11 34 33 am" src="https://cloud.githubusercontent.com/assets/5287712/17377535/f9b522a6-596e-11e6-9973-accf32c2bdba.png">

(running on Linux, built from source this morning)

**Comment by nonhermitian** [comment]
Did you grab the latest version from git?  I cant seem to reproduce the error. Perhaps something has changed in diags since scipy 0.15

**Comment by nonhermitian** [comment]
The git version matches the latest, so I am a bit confused. We have unit tests for expm that work fine and I pulled the latest version here at work and everything works. I also couldnt find any changes to diags in the scipy changelog. 

Maybe remove the old qutip in the sitepackages dir and reinstall.

**Comment by Wuggins** [comment]
I'll give that a shot. Are there any other hidden dependencies that could be at fault?

**Comment by Wuggins** [comment]
It's worth noting that this does not occur on the same system with QuTiP 3.1.0

**Comment by nonhermitian** [comment]
Have you tried running the qutip tests? Do those fail?  Again, I cannot reproduce the issue.

**Comment by nonhermitian** [comment]
Closing this now since no response.
