### ISSUE TITLE
In mesolve, what is the reason that Liouvillian is preferred even when the size is too large?

### ISSUE THREAD

**Issue by kwyip** [qutip/qutip#531]
Hi,
In the source code of `mesolve`, the derivative are defined via `L * rho` where L is Liouvillian. But when the size is too large, `L` is of huge dimension. I have two questions:

1. What tricks have you made so that the derivative is still defined via `L` instead of collapse operators, which is relatively smaller in dimension? Sparse in scipy was used. But if `L` is not sparse at all, how can we avoid memory problem?

2. What is the general advantage of using Liouvillian `L` to define derivative instead of `C` the collapse operators? It seems that using `L` requires only 1 multiplication, but when I tested and try to define in `C`, it seems that it is still faster for relatively small hilbert space dimension. Is speed the main reason?

**Comment by nonhermitian** [comment]
I am not sure what you mean by too large. The dimensions are not really the issue. It is the number of nonzero elements that matter.

I am also puzzled by evolution using only collapse operators. Anytime you evolve a system you need the Hamiltonian. The Liouvillian has both coherent and dissipative terms in a single operator.

**Comment by kwyip** [comment]
Hi Paul,
Sorry let me clarify. 
1. If the number of nonzero elements is very large, is Liouvillian still preferred to defining derivatives from Hamiltonian and collapse operators (Eq.(3) in the link below)?
2. By constructing Liouvillian from Hamiltonian and collapse operators and defining the derivative as L*rho, is it computationally faster than Eq.(3) in http://qutip.org/docs/3.1.0/guide/dynamics/dynamics-master.html

Thank you.

**Comment by nonhermitian** [comment]
The Liouvillian is defined via equation #3.  I think your asking is it better to make a single operator, or take each term in equation #3 separately.  If that is your question then the answer is yes, building the Liouvillian is much better.

**Comment by kwyip** [comment]
Hi Paul,
It seems by direct multiplication is faster than defining the Liouvillian in small problem size. They give the same result. I do not know if this is the case in general for small problem size.
