### ISSUE TITLE
Use axis equal in plot_wigner

### ISSUE THREAD

**Issue by Phyks** [qutip/qutip#539]
Hi,

Is there a reason for not using aspect ratio "equal" for the resulting plot of the `plot_wigner` function? Wigner plots are much more readable when using such settings, in my opinion.

Thanks

EDIT: I can make a PR for this, but would rather have some feedback before doing it :)

**Comment by Phyks** [comment]
I am willing to make a PR to fix https://github.com/qutip/qutip/issues/544 and could include a fix for this as well.

The way I am thinking I could do it right now is to put an extra `equal` parameter to `plot_wigner` which would have a default value and could be used to alternate between the two behaviors (with othonormal axes and without).

I'd like a feedback on the best default value, each one having its own advantages:
* I could use `equal=False` as a default value, to keep the actual behavior. Using `equal=True`, users could alternate between the two behaviors.
* I could use `equal=True` as a default value. As far as I know, in the literature, Wigner plots often have orthonormal axes, so that a coherent state is a circular blob. This has the disadvantage of breaking the current behavior and code that may rely on it.

Thanks

**Comment by nonhermitian** [comment]
This was done in Pull #736
