### ISSUE TITLE
mesolve with single function call back

### ISSUE THREAD

**Issue by Phyks** [qutip/qutip#542]
Hi,

I am trying to compute a single function (not an operator) on every states returned by mesolve call.

Typically, I am doing this:
``` python
def populationCount(alpha):
    """
    Return the population count to be plotted.
    """
    alpha_tensor_state = lambda alpha: qutip.tensor(qutip.coherent(N, alpha), qutip.qeye(2))
    return lambda t, rho: (
        (
            alpha_tensor_state(alpha).dag() * rho * alpha_tensor_state(alpha) -
            alpha_tensor_state(-alpha).dag() * rho * alpha_tensor_state(-alpha)
        ).tr() / 
        (
            alpha_tensor_state(alpha).dag() * rho * alpha_tensor_state(alpha) +
            alpha_tensor_state(-alpha).dag() * rho * alpha_tensor_state(-alpha)
        ).tr()
    )

qutip.mesolve(H, rho_0, times, C_ops, populationCount(alpha) progress_bar=True)
```

which should be correct, as far as I understand the doc.

However, I get a traceback which I can't understand:
```python
AttributeError: 'numpy.ndarray' object has no attribute 'nnz'
```

Am I doing something wrong or is it a bug with handling of single function callback? Thanks!

**Comment by nonhermitian** [comment]
What version of qutip are you using?

**Comment by Phyks** [comment]
I'm using qutip 3.1.0.

**Comment by nonhermitian** [comment]
You need the latest dev version

**Comment by nonhermitian** [comment]
This has been fixed in 4.0

**Comment by Phyks** [comment]
Oh ok. I'll wait for the next update to be pushed on pip then I think. I can workaround this in the meantime.

**Comment by nonhermitian** [comment]
You might be waiting a while. You can install the github master via pip fairly easily.

**Comment by Phyks** [comment]
OK, I'll have a look at it. Is there any specific reason for not making more frequent (and with less features) releases?

I'm closing the issue as it should be fixed in latest dev branch. I will reopen if I still experience the issue after updating.

**Comment by nonhermitian** [comment]
The main reason is time. I only have an occasional hour or two to put in. In addition, there are many holes in the docs and examples that need to be closed before a release. We are trying to take care of all of this before next years APS meeting.
