### ISSUE TITLE
Serialization of Qobj objects

### ISSUE THREAD

**Issue by Phyks** [qutip/qutip#543]
Hi,

I may have missed something but cannot find references to the proper way to serialize Qobj objects. We can `pickle` them, I think, but it is not always the most practical way to deal with them.

Typically, a `json.dumps` call on a `Qobj` object fails due to the fact that Numpy array are not JSON-serializable.

It may be useful to have some methods to easily import / export `Qobj` objects (that would ideally work even if the user is to deal with list or dicts of `Qobj` in a similar manner), or add some documentation about the proper way to do it if it is already doable.

**Comment by nonhermitian** [comment]
We do have the qsave and qload functions in the fileio module.

**Comment by Phyks** [comment]
Thanks, I missed this one. Looks perfect!
