### ISSUE TITLE
Animating Wigner plots

### ISSUE THREAD

**Issue by Phyks** [qutip/qutip#544]
Hi,

I recently had to animate a Wigner plot, to show the evolution of the Wigner function in time. It looks like QuTip does not any specific methods to ease this, at least when doing it in a Jupyter notebook.

Typically, the `qutip.plot_wigner` method is really handy to plot Wigner functions, as it deals with everything, from the Wigner generation to the correct plotting. However, using it in an animation function callback from `matplotlib.animation.FuncAnimation` is not doable if you want it to be plotted live in the notebook. And to use `qutip.wigner.wigner` you have to manually reproduce lots of code from `qutip.plot_wigner`.

I can think about two solutions to this issue:
1. Enhancing `qutip.plot_wigner` so that it supports the first parameter to be a list of ket / density matrices, and in such a case it would render an animation rather than a single plot.
2. Splitting `qutip.plot_wigner` in different methods that could be called independently. Typically, a first method to initialize the Wigner plot (that is set the correct colormap, labels for axis and so on), another one to compute a wigner function to render and a last one to perform the plot itself which would call all the other methods and have the same behavior as the current `qutip.plot_wigner` method. This way, if one wishes to render an animation of a Wigner function time evolution, he can call the first method to setup the matplotlib figure accordingly, then precomputes all the wigner arrays to plot on the animation and handle the animation part on his own, typically with a `FuncAnimation` animation.

Thanks!

**Comment by nonhermitian** [comment]
This seems like a reasonable thing to implement.  However, I am backlogged with other things, so you may want to try to create a Pull yourself.  Or, perhaps on of the other devs can tackle it sooner.

**Comment by Phyks** [comment]
Ok. I was just throwing the idea with this issue. Sure, if I need it again in the future and have some time to work on it, I'll try to make a PR to the repo!

**Comment by Phyks** [comment]
Not sure this issue is closed as is, I think it would be if the notebook mentionned above was emphasized in the docs or anywhere.
