### ISSUE TITLE
msolve with nonzero starting times

### ISSUE THREAD

**Issue by asafpm** [qutip/qutip#561]
Solving time-dependent Hamiltonian problems, where the time array provided to mesolve doesn't have t[0]=0, gives unexpected results. This happens both for the list callback format and for the list array 
format.

Example [here](https://gist.github.com/asafpm/a86cd9f33f9ec7e5e360c348c1b0506e).

Using qutip 3.1.0 and python 2.7

**Comment by nonhermitian** [comment]
What exactly is the problem?  The example here:

https://github.com/qutip/qutip-notebooks/blob/master/examples/example-landau-zener.ipynb

works fine even though the start time is at t=-20.

**Comment by nonhermitian** [comment]
I am guessing this is closed.
