### ISSUE TITLE
Charge states basis

### ISSUE THREAD

**Issue by Phyks** [qutip/qutip#562]
Hi,

Sometimes it is useful to write an hamiltonian in a charge state basis. This requires the basis to be able to run through integers from minus infinity to plus infinity. This is typically the case in [this Qutip example notebook](https://nbviewer.jupyter.org/github/jrjohansson/qutip-lectures/blob/master/Lecture-11-Charge-Qubits.ipynb).

In this notebook, the author manually creates a numpy object and cast it to a `Qobj`. What about offering an analog to `qutip.basis` for such states?

Thanks

**Comment by nonhermitian** [comment]
We do have the charge operator.

**Comment by Phyks** [comment]
Indeed, it is [in the code](https://github.com/qutip/qutip/blob/2aa51b92df57f995778940815d20d293f00f8a9d/qutip/operators.py#L888-L948).

However, I cannot find any reference to them in [the documentation](http://qutip.org/docs/3.1.0/search.html?q=charge&check_keywords=yes&area=default).
