### ISSUE TITLE
Gitter integration for QuTiP

### ISSUE THREAD

**Issue by sahmed95** [qutip/qutip#564]
[Gitter](https://gitter.im) is a networking platform with tight integration to Github. Its shows the latest activity (commits, PR, comments on issues) and can be a place for people to quickly connect with other QuTiP users and find solutions. For example, the gitter channel for Dipy is pretty active and helpful. (https://gitter.im/nipy/dipy)

Has QuTiP considered [integrating](https://github.com/integrations/gitter) gitter with the repository ?

**Comment by nonhermitian** [comment]
I have not heard of this service before.  I have added QuTiP as a community:

https://gitter.im/qutip/Lobby 

If it doesn't take off then we can always just close it.

**Comment by sahmed95** [comment]
Thanks for adding. I hope this becomes an active place for discussions in the community. Adding a link on the qutip website and the README on github might help.
