### ISSUE TITLE
Switch from distutils to setuptools

### ISSUE THREAD

**Issue by ajgpitch** [qutip/qutip#593]
We have some problems with some of the conda-forge builds. It could be that there are conflicts with setuptools versions. Reading:
http://stackoverflow.com/questions/25337706/setuptools-vs-distutils-why-is-distutils-still-a-thing
Suggests that we should be able to all we need with setuptools. The general view is that it is 'better'.
Might be a bit of a fiddle, but could be worth the effort - maybe?

**Comment by nonhermitian** [comment]
This will take a bit of work.  Especially since the docs are not so easy to read.  Just changing the setup import does not work as we use numpy.distutils for the configuration.

**Comment by ajgpitch** [comment]
It seems that the work done #489 covers what we need. As in we use enough of setuptools already.
setuptools now included in conda-forge packages and building fine.
