### ISSUE TITLE
Method to add Gate instance directly to `add_gate()`

### ISSUE THREAD

**Issue by sahmed95** [qutip/qutip#610]
Currently, the method to add a new gate to a quantum circuit is the following:
```
import numpy as np
from qutip import QubitCircuit
from qutip.qip.circuit import Gate

qcircuit = QubitCircuit(4)
qcircuit.add_gate("CNOT", targets=[2], controls=[0])

# This is a valid gate addition.
qcircuit.add_gate("test_gate", targets=[0], controls=[1], arg_label=r"\pi/12",
	                       arg_value="np.pi/12")
for gate in qcircuit.gates:
	print(gate)


```

There is no way to add a gate directly. For instance:

```
test_gate = Gate("test_gate", targets=[0], controls=[1], arg_label=r"\pi/12",
	                       arg_value="np.pi/12")
# This leads to an invalid gate addition.
qcircuit.add_gate(test_gate)
```
which leads to 

```
Gate(Gate(test_gate, targets=[0], controls=[1]), targets=None, controls=None)
```

Can we add a check to see if the input to `add_gate` is a Gate object and unpack it to add a new gate ? Or, have some kind of a sanity check if the given input is in a correct gate input format. (name, targets, controls).

**Comment by ajgpitch** [comment]
Sounds like a good idea to me.
You mean check if the first arg is a Gate, if so then no need to create one, just add it to the circuit

**Comment by sahmed95** [comment]
Yes. That makes it simpler to add a new gate again and again if you have it
defined somewhere in your code. Instead of writing all the keyword
arguments.

**Comment by ajgpitch** [comment]
I guess you have to make a deep copy of it? Otherwise strange things might
happen. I get caught out by this one all the time!

**Comment by sahmed95** [comment]
Well, deepcopy is one option but since the `add_gate` function asks for a limited set of input arguments, a naive way to do this is to check if supplied `gate` is an instance of `Gate` class and unpack the parameters. Minimal change in the existing code can be something like:

```
def add_gate(self, gate, targets=None, controls=None, arg_value=None,
             arg_label=None):
    """
    Adds a gate with specified parameters to the circuit.

    Parameters
    ----------
    gate: String
        Gate name. If `gate` is an instance of Gate, it will be unpacked
        and added.
    targets: List
        Gate targets.
    controls: List
        Gate controls.
    arg_value: Float
        Argument value(phi).
    arg_label: String
        Label for gate representation.
    """
    if isinstance(gate, Gate):
        name = gate.name
        targets = gate.targets
        controls = gate.controls
        arg_value = gate.arg_value
        arg_label = gate.arg_label
        
    self.gates.append(Gate(name, targets=targets, controls=controls,
                           arg_value=arg_value, arg_label=arg_label))
```

@ajgpitch What do you think of this approach ? If this seems fine then I will open a PR.

**Comment by sahmed95** [comment]
The change will be made here : https://github.com/qutip/qutip/blob/master/qutip/qip/circuit.py#L175

**Comment by ajgpitch** [comment]
Yes, that looks like a good method.
