### ISSUE TITLE
Qobj data stored in COOrdinate format will crash sesolve

### ISSUE THREAD

**Issue by ollie1400** [qutip/qutip#613]
When calling `sesolve` on a Qobj `H` representing a Hamiltonian with data stored in COOrdinate format e.g.
`H.data` gives `<..... sparse matrix of type '<type 'numpy.complex128'> ..... elements in COOrdinate format>`

`_sesolve_const` in sesolve.py throws `AttributeError: indices not found` on line 286, because `L.data.indices` does not exist.   (Nor does `L.data.indptr` for that matter).

**Comment by nonhermitian** [comment]
Sure, because it is not the correct csr format.  In addition, if you use that format, your matvec multiplication would be slow.

**Comment by ollie1400** [comment]
Thanks!  I wasn't sure if this was something which should have been caught or dealt with in qutip (rather than thrown in scipy) since the exception doesn't **immediately** tell one the underlying cause.
