### ISSUE TITLE
Insert gates at arbitrary positions in the circuit

### ISSUE THREAD

**Issue by quantshah** [qutip/qutip#615]
Currently `QubitCircuit.add_gate()` appends a gate to the end of the circuit. If we wish to insert some gate in the middle of the circuit, we have to do a `QubitCircuit.gates.insert(index=idx, gate)`. We can also add this functionality to `add_gate` by specifying a keyword argument `index` with default value as `None`. If `index` is specified, we could insert the gate at that position. For example, right now I would do : 

```
from qutip import QubitCircuit
qcirc = QubitCircuit(5, reverse_states=False)
qcirc.add_gate("TOFFOLI", controls=[0, 1], targets=[2])
qcirc.add_gate("SNOT", targets=[3])
qcirc.add_gate("SNOT", targets=[3])

# Insert a gate after the first two gates (TOFFOLI, SNOT)

qcirc.gates.insert(2, Gate("test_gate", targets=[2]))
```

Instead of that, we could do something like:

```
qcirc.add_gate(Gate("test_gate", targets=[2]), index = [2])
``` 

Further, if you wish to add the same gate at multiple positions you could just have more entries in the `index` list. Not a very big difference from using `list.insert()` but enables `add gates` to insert gates at arbitary positions in the circuit.

**Comment by ajgpitch** [comment]
Sounds like a good idea
