### ISSUE TITLE
4.0.1 Dependencies are incorrect.

### ISSUE THREAD

**Issue by Acebulf** [qutip/qutip#616]
The latest version of QuTIP uploaded to PyPI (4.0.1 uploaded on 2016-12-29) has scipy (>=0.15) listed as a dependency. However, the file fastsparse.py imports `get_sum_dtype` from scipy.sparse.sputils, which is only available in scipy 0.18 and newer. I believe that the function was not actually used, and the import was removed in commit #596. 

I am not certain that the current version still requires scipy(>=0.18), but the version currently available on PyPI (and thus auto-installed with pip) does require it. If the user has an earlier version of scipy, qutip will fail on import (ImportError).

**Comment by nonhermitian** [comment]
I would try 4.0.2.  The requirements txt file still lists 0.15 so not sure what the issue is.

**Comment by ajgpitch** [comment]
Yes, 4.0.1 has this issue. Hence the main motivation for 4.0.2. 
4.0.1 only really exists on PyPI right now. Website and conda-forge are now 4.0.2. I will be uploading 4.0.2 to PyPI today.

I don't know if 4.0.2 will work with scipy 0.15. It only gets built and tested (import qutip) on conda-forge against numpy 1.10 / scipy 0.17 and numpy 1.11 / scipy 0.18 as far as I know. Our Travis (full) tests only test numpy 1.11 / scipy 0.18.

@nonhermitian do you think we should bump the requirements up to numpy 1.10 / scipy 0.17?

**Comment by ajgpitch** [comment]
4.0.2 is now the latest release on PyPI. 
I can't see why anyone would be installing 4.0.1 now, except from some old package they had downloaded.

**Comment by nonhermitian** [comment]
I would just leave it the way it is. That way we stay more compatible with
systems where the user may not be able to install newer versions.

-P

**Comment by ajgpitch** [comment]
Ok, we will continue to claim we are compatible with scipy 0.15 until proven different.
