### ISSUE TITLE
typo for `dims` check in `_check_ket_dims`?

### ISSUE THREAD

**Issue by lucainnocenti** [qutip/qutip#617]
To generate a random ket and have it be in the tensor product space of 3 qubits I would use

    ket = qutip.rand_ket(8, dims=[[2, 2, 2], [1, 1, 1]])
so to have the `dims` form I would get by actually taking the tensor product of three 1-qubit kets.
However this will fail due to the check performed of [L652](https://github.com/qutip/qutip/blob/master/qutip/random_objects.py#L652) of `random_objects.py`:

    if not isinstance(dims, list) or isinstance(dims[0], list):
Did I understood wrong how the `dims` parameter of `rand_ket` is supposed to work? or is there a simple typo in the above line and it was instead supposed to be something like:

    if not (isinstance(dims, list) or isinstance(dims[0], list)):
?

**Comment by nonhermitian** [comment]
This should be fixed in #632.
