### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by 17643015** [qutip/qutip#637]
Does anyone know how to fix the following error, or even how to interpret it?

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-d4205f385795> in <module>()
----> 1 from qutip import*

/home/jan/.local/lib/python2.7/site-packages/qutip/__init__.pyc in <module>()
    203 
    204 # core
--> 205 from qutip.qobj import *
    206 from qutip.states import *
    207 from qutip.operators import *

/home/jan/.local/lib/python2.7/site-packages/qutip/qobj.py in <module>()
     58 import qutip.settings as settings
     59 from qutip import __version__
---> 60 from qutip.fastsparse import fast_csr_matrix, fast_identity
     61 from qutip.ptrace import _ptrace
     62 from qutip.permute import _permute

/home/jan/.local/lib/python2.7/site-packages/qutip/fastsparse.py in <module>()
    403 #Need to do some trailing imports here
    404 #-------------------------------------
--> 405 from qutip.cy.spmath import (zcsr_transpose, zcsr_adjoint)

/home/jan/.local/lib/python2.7/site-packages/qutip/cy/__init__.py in <module>()
----> 1 from qutip.cy.spmatfuncs import *

ImportError: /home/jan/.local/lib/python2.7/site-packages/qutip/cy/spmatfuncs.so: undefined symbol: PyUnicodeUCS2_FromStringAndSize

**Comment by 17643015** [comment]
If I try to import qutip a second time, I get the following error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-d4205f385795> in <module>()
----> 1 from qutip import*

/home/jan/.local/lib/python2.7/site-packages/qutip/__init__.pyc in <module>()
     60     qutip.settings.ipython = True
     61 except:
---> 62     qutip.settings.ipython = False
     63 
     64 # -----------------------------------------------------------------------------

AttributeError: 'module' object has no attribute 'settings'

Also I am running ubuntu 16.10

**Comment by nonhermitian** [comment]
You may be trying to run QuTiP from the same directory you installed it
from.

**Comment by ajgpitch** [comment]
This is the kind of question that people would normally post on the help group
