### ISSUE TITLE
Installation failure on linux (solus 64 bit)

### ISSUE THREAD

**Issue by jakeargent** [qutip/qutip#639]
I'm using [solus](https://solus-project.com) 64-bit, and anaconda for my python.

anaconda cannot find any qutip package, so I tried to install with pip. It gives the following error:

`Command "/home/jakeargent/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-n7ekqm4y/qutip/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-lnsaamvm-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-n7ekqm4y/qutip/
`

Then I tried easy_install, which gave me:

`Processing qutip
Writing /home/jakeargent/qutip/setup.cfg
Running setup.py -q bdist_egg --dist-dir /home/jakeargent/qutip/egg-dist-tmp-9_egnp34
Installing without the fortran mcsolver.
In file included from /usr/lib64/gcc/x86_64-solus-linux/6.3.0/include-fixed/syslimits.h:7:0,
                 from /usr/lib64/gcc/x86_64-solus-linux/6.3.0/include-fixed/limits.h:34,
                 from /home/jakeargent/anaconda3/include/python3.5m/Python.h:11,
                 from qutip/cy/spmatfuncs.c:27:
/usr/lib64/gcc/x86_64-solus-linux/6.3.0/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
 #include_next <limits.h>  /* recurse down to the real one */
                                                             ^
compilation terminated.
In file included from /usr/lib64/gcc/x86_64-solus-linux/6.3.0/include-fixed/syslimits.h:7:0,
                 from /usr/lib64/gcc/x86_64-solus-linux/6.3.0/include-fixed/limits.h:34,
                 from /home/jakeargent/anaconda3/include/python3.5m/Python.h:11,
                 from qutip/cy/spmatfuncs.c:27:
/usr/lib64/gcc/x86_64-solus-linux/6.3.0/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
 #include_next <limits.h>  /* recurse down to the real one */
                                                             ^
compilation terminated.
error: Setup script exited with error: Command "gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -mtune=generic -march=x86-64 -ftree-vectorize -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -fno-omit-frame-pointer -fstack-protector-strong --param ssp-buffer-size=4 -fexceptions -D_FORTIFY_SOURCE=2 -feliminate-unused-debug-types -Wno-error -Wp,-D_REENTRANT -fPIC -I/home/jakeargent/anaconda3/lib/python3.5/site-packages/numpy/core/include -I/home/jakeargent/anaconda3/lib/python3.5/site-packages/numpy/core/include -I/home/jakeargent/anaconda3/lib/python3.5/site-packages/numpy/core/include -I/home/jakeargent/anaconda3/include/python3.5m -c qutip/cy/spmatfuncs.c -o build/temp.linux-x86_64-3.5/qutip/cy/spmatfuncs.o -w -ffast-math -O3 -march=native -funroll-loops" failed with exit status 1
`

Then, I cloned the qutip/qutip repository, and tried to build a wheel with `python setup.py bdist_wheel` under the qutip directory. Which gave me the following log:

`running bdist_wheel
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building py_modules sources
building extension "qutip.cy.spmatfuncs" sources
building extension "qutip.cy.stochastic" sources
building extension "qutip.cy.sparse_utils" sources
building extension "qutip.cy.graph_utils" sources
building extension "qutip.cy.interpolate" sources
building extension "qutip.cy.spmath" sources
building extension "qutip.cy.heom" sources
building extension "qutip.cy.math" sources
building extension "qutip.cy.spconvert" sources
building extension "qutip.cy.ptrace" sources
building extension "qutip.control.cy_grape" sources
building data_files sources
build_src: building npy-pkg config files
running build_py
copying qutip/version.py -> build/lib.linux-x86_64-3.5/qutip
copying build/src.linux-x86_64-3.5/qutip/__config__.py -> build/lib.linux-x86_64-3.5/qutip
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
building 'qutip.cy.spmatfuncs' extension
compiling C sources
C compiler: gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -mtune=generic -march=x86-64 -ftree-vectorize -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -fno-omit-frame-pointer -fstack-protector-strong --param ssp-buffer-size=4 -fexceptions -D_FORTIFY_SOURCE=2 -feliminate-unused-debug-types -Wno-error -Wp,-D_REENTRANT -fPIC

compile options: '-I/home/jakeargent/anaconda3/lib/python3.5/site-packages/numpy/core/include -I/home/jakeargent/anaconda3/lib/python3.5/site-packages/numpy/core/include -I/home/jakeargent/anaconda3/lib/python3.5/site-packages/numpy/core/include -I/home/jakeargent/anaconda3/include/python3.5m -c'
extra options: '-w -ffast-math -O3 -march=native -funroll-loops'
gcc: qutip/cy/src/zspmv.c
qutip/cy/src/zspmv.c:2:21: fatal error: complex.h: No such file or directory
 #include <complex.h>
                     ^
compilation terminated.
qutip/cy/src/zspmv.c:2:21: fatal error: complex.h: No such file or directory
 #include <complex.h>
                     ^
compilation terminated.
error: Command "gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -mtune=generic -march=x86-64 -ftree-vectorize -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -fno-omit-frame-pointer -fstack-protector-strong --param ssp-buffer-size=4 -fexceptions -D_FORTIFY_SOURCE=2 -feliminate-unused-debug-types -Wno-error -Wp,-D_REENTRANT -fPIC -I/home/jakeargent/anaconda3/lib/python3.5/site-packages/numpy/core/include -I/home/jakeargent/anaconda3/lib/python3.5/site-packages/numpy/core/include -I/home/jakeargent/anaconda3/lib/python3.5/site-packages/numpy/core/include -I/home/jakeargent/anaconda3/include/python3.5m -c qutip/cy/src/zspmv.c -o build/temp.linux-x86_64-3.5/qutip/cy/src/zspmv.o -w -ffast-math -O3 -march=native -funroll-loops" failed with exit status 1`

Well, all of them seem to fail with a similar issue. Whatever is exit status 1. ([This](http://stackoverflow.com/questions/35991403/python-pip-install-gives-command-python-setup-py-egg-info-failed-with-error-c) is the SO solution I followed, it claims that error code is related to operation not permitted or setuptools not being installed. I upgraded the setuptools, pip doesn't work with sudo (I'm guessing it shouldn't))

How can I install qutip?

**Comment by nonhermitian** [comment]
I found this thread,

https://solus-project.com/forums/viewtopic.php?t=2938

which tells one to try:

sudo eopkg install -c system.devel

-P

jakeargent wrote:

**Comment by jakeargent** [comment]
Thanks mr unobservable, that indeed solved it. For some reason it hadn't occurred to me to check the solus forums.

**Comment by vinimmelo** [comment]
Thanks for the answer, help me a lot...
