### ISSUE TITLE
Compile extensions using C++ ?

### ISSUE THREAD

**Issue by ajgpitch** [qutip/qutip#647]
Is there any performance reason why we should not compile the extensions using C++ ?

We are having issues with the conda forge packages:
conda-forge/qutip-feedstock#16
I am sure than this problem would not occur if we were compiling using MS compilers.
We are receiving lots of support requests on the Google group for help installing on Windows
We do not have a solution for python>=3.5 on Windows.

I posted a question on the Cython help group asking about accessing complex functions on Windows. One suggestion was to try C++, importing functions from `complex` rather than `complex.h`. I made a small test project that imported `conj` and it compiled using MS compilers and worked on Windows 10 with both Python 2.7 and 3.5.

We only have one small C source file. I guess it could be rewritten in C++ quite easily.
I can do further tests to check performance if we consider C++ compilation is an option for qutip.

**Comment by nonhermitian** [comment]
I dont think that there would be a performance issue. If everything builds​ fine, then that is what we should do.

**Comment by nonhermitian** [comment]
It seems that most of what we need is predefined in cython libcpp

**Comment by ajgpitch** [comment]
Ok, great news. I think we have a solution.
It's only really the spmv.c file that I am not exactly sure what to do about, as I have little or no actual C/C++ experience.

**Comment by nonhermitian** [comment]
It is actually a bit more complicated than that, but I will look into it. Many extern statements will likely need changing.

**Comment by ajgpitch** [comment]
Yes, I could not get the functions in libcpp.complex to work with something simple like:
```
cimport cython
from libcpp.complex cimport conj

def myconj(double complex a):
    cdef double complex b

    b = conj(a)
    return b
```

however this did work:
```
cimport cython
cdef extern from "complex":
    double complex conj(double complex x)

def myconj(double complex a):
    cdef double complex b

    b = conj(a)
    return b
```

Might be something to do with the type conversion mentioned in:
http://stackoverflow.com/questions/36732779/complex-conversion-to-python-complex

**Comment by nonhermitian** [comment]
Try for example

cdef extern from "<complex>" namespace "std":
    double complex exp(double complex z)

def test(double complex z):
    return exp(z)



Should work.

**Comment by nonhermitian** [comment]
There is an incompatibility between OSX clang and gcc libstdc++ binaries.  As such, we could not do parallel spmv on OSX if we move to C++ and use homebrew's GCC.  I will try to see if the homebrew llvm will work.

**Comment by ajgpitch** [comment]
I assume that parallel spmv does not work on Windows anyway?
I could look into making the compile language conditional, i.e. use C++ on Windows, otherwise C

**Comment by nonhermitian** [comment]
My suggestion is to leave this as it is, at least for now.  Best to get paper stuff done first.

**Comment by ajgpitch** [comment]
Ok, sure. We will park this for now

**Comment by nonhermitian** [comment]
I think that this is the correct solution though, so big bonus points for hunting this down!  At work, we have no use for OSX, and would love py3 on win, so I can fiddle around to get something working.  Having two separate sources may be the route we need to go.  It wouldn't be the end of the world, but should be avoided unless absolutely necessary.

**Comment by ajgpitch** [comment]
Yes, I agree, it would be much better to avoid separate sources. It is just the spmv.c that does the parallel spmv work is it?

**Comment by nonhermitian** [comment]
Actually, it seems that the sparse_struct stuff segfaults when run under cpp mode.  Compiles fine, but crashes.  So cpp seems like a no go.

**Comment by nonhermitian** [comment]
Nevermind, still got it to work.  Seems like we are still in business.

**Comment by nonhermitian** [comment]
I think i got everything to work.  Even on osx.

**Comment by nonhermitian** [comment]
This is done.
