### ISSUE TITLE
Are we ready for v4.1?

### ISSUE THREAD

**Issue by ajgpitch** [qutip/qutip#649]
Once pull #648 is merged I am keen to get a v4.1 released.
The conda-forge packages for Windows currently do work. I am very keen to resolve this. 
Also very keen to get a solution for qutip on MS Windows with Python >= 3.5 out there.
I am happy to do the admin work for the release.

The installation documentation will need updating, I am happy to this.
Is there anything else we would like to finish off, that can be done quickly, that we would like to get into a release of 4.1?

**Comment by nonhermitian** [comment]
Let me do one more minor thing tonight and then go for it.  I will also add some more to the docs tonight.

**Comment by nonhermitian** [comment]
Ready.

**Comment by ajgpitch** [comment]
Ok, great thanks.
I will start work on the release.

**Comment by nonhermitian** [comment]
When are you thinking or branching a 4.1 release?

**Comment by ajgpitch** [comment]
Was planning to do it today. Probably in about 4 hours from now.
I assume I am including all your recent pulls

**Comment by ajgpitch** [comment]
So far:
I have created the 4.1.x branch
Created the gztar and zip via sdist
(there was a problem with missing hpp files, now fixed)
I have uploaded the packages to the website and updated the links.
I have updated the conda-forge recipe. I am waiting to see how the packages work out before going any further. The Windows ones take about 24 before they get processed in the queue

**Comment by nonhermitian** [comment]
I have released the 4.1 branch and uploaded new docs with the needed updates.

**Comment by nonhermitian** [comment]
For some reason my docs do not load on git. They work fine if loaded directly from my computer though.  Seems some css files are not being found.  A brief google search pulled up a variety of things.  You seem to have had success with the 4.0.2 docs, so perhaps you can take a shot at uploading.

**Comment by nonhermitian** [comment]
Nevermind.  Forgot about the underscore issue with jekyll.

**Comment by ajgpitch** [comment]
Thanks Paul, I forgot to make the actual release!

Did you find my little script in qutip-doc for stripping the underscores?

**Comment by ajgpitch** [comment]
@nonhermitian Hopefully you will see I pinged up on conda-forge/qutip-feedstock#18. There is a problem with the OSX build of QuTiP on the conda-forge

**Comment by nonhermitian** [comment]
@ajgpitch I am trying to fix this will Pull #660.  I do not see this on any other compiler, so it is hard to peg down.  Hopefully, switching to a vector from a pointer does the trick.  The strange thing is that Apple's own clang compiler does not abort with this error, but somehow XCODE does.

**Comment by ajgpitch** [comment]
Finished.
Finally
