### ISSUE TITLE
Reminders for users to cite qutip

### ISSUE THREAD

**Issue by ajgpitch** [qutip/qutip#664]
There is some concern that some users are forgetting to cite qutip when using it in their work. This thread is for ideas of how to add reminders into the library.

**Comment by ajgpitch** [comment]
One idea was to randomly print a message on `import qutip`. I am not sure on whether this would go against established etiquette. Anyone have a view on this?

**Comment by ajgpitch** [comment]
Adding a reminder in `qutip.about()` would seem to be a good idea, but not sure how often it would be seen

**Comment by ajgpitch** [comment]
Having reminder in the repr of the Result object would seem appropriate.
"If this result is interesting, please cite QuTiP in your publication"

**Comment by sahmed95** [comment]
Something to also make citing easier such as a bib tex generator? A
qutip.cite() call within the result class that makes a .bib file where the
plots are saved or code is run. That way it will surely come to the users
notice when he checks out the saved plots / code.

**Comment by ajgpitch** [comment]
@sahmed95 Yes, very nice idea. Making life easier for people is always a good idea. We could have something on the website as well that generates bibtex for the qutip papers and the Zenodo DOI that people can copy direct into their bib files, like on the Zenodo site.

**Comment by sahmed95** [comment]
I use doi2bib.org. Using the Qutip 2 doi we get this :

http://www.doi2bib.org/#/doi/10.1016/j.cpc.2012.11.019

@article{Johansson2013,
  doi = {10.1016/j.cpc.2012.11.019},
  url = {https://doi.org/10.1016%2Fj.cpc.2012.11.019},
  year  = {2013},
  month = {apr},
  publisher = {Elsevier {BV}},
  volume = {184},
  number = {4},
  pages = {1234--1240},
  author = {J.R. Johansson and P.D. Nation and Franco Nori},
  title = {{QuTiP} 2: A Python framework for the dynamics of open
quantum systems},
  journal = {Computer Physics Communications}
}

**Comment by Phyks** [comment]
My two cents on this but if providing an easy citation formatting function, I think it would be relevant to have the QuTiP version mentionned in the citation. Many QuTiP citations I see in papers just mention something like "Thanks to QuTiP developpers, all simulations were made under QuTiP", without any explicit mention of version. Having a versionned citation might help track the impact of potential bugs in QuTiP code on results.

**Comment by ajgpitch** [comment]
@Phyks I agree that it would help having a version specific citation, for the repeatability reasons you mention. We do have a Zenodo DOI
https://zenodo.org/record/835881#.WlzkEum6_0o
Some others are worried though that if we offer this, then users may not cite the papers. Paper citations are very important

**Comment by sahmed95** [comment]
Closing this issue via https://github.com/qutip/qutip/pull/752
