### ISSUE TITLE
Cannot use mayavi when using python3.4

### ISSUE THREAD

**Issue by kwyip** [qutip/qutip#671]
Error message:
```
../anaconda/lib/python3.4/site-packages/qutip/bloch3d.py", line 115, in __init__
    raise Exception("This function requires the mayavi module.")
```
It seems that we cannot use python3 and mayavi at the same time. Anyone has similar issues?

**Comment by ajgpitch** [comment]
I have heard of others having issues with mayavi.
Support for Python 3.4 is gone now. Could you try in Python 3.5+ with the latest qutip (v4.1.0) to see if the problem persists

**Comment by Farquhar13** [comment]
I am getting the same error using Python 3.6 and qutip 4.1

**Comment by sjgriffiths** [comment]
I also got this problem with Python 3.7.3 and qutip 4.4.0. The exception arises from a syntactically-broken install of apptools on Windows (namely problems in `state_pickler.py`). Reinstalling apptools seems to fix it easily enough:

`
pip uninstall apptools
pip install -U apptools
`

**Comment by YuanyuanSunSarah** [comment]
Hey,  I had the same problem for ages. Are you using it on Jupiter Notebook? If so you need to add Jupiter notebook support manually.

As mentioned in  https://docs.enthought.com/mayavi/mayavi/installation.html
