### ISSUE TITLE
Conda installation of qutip crashes on import

### ISSUE THREAD

**Issue by goerz** [qutip/qutip#674]
Installing qutip via the conda package and then importing it produces a crash for me:

    goerz@mlhpc2:~> conda create -y -c conda-forge -m -n qutiptest python=3.5  qutip
    Using Anaconda Cloud api site https://api.anaconda.org
    Fetching package metadata: ........
    Solving package specifications: .........

    Package plan for installation in environment /home/goerz/.conda/envs/qutiptest:

    The following NEW packages will be INSTALLED:

        certifi:     2017.1.23-py35_0
        cython:      0.25.2-py35_1
        libgfortran: 3.0.0-1
        mkl:         2017.0.1-0
        ncurses:     5.9-10                                                                                                                                                            numpy:       1.12.1-py35_0
        openssl:     1.0.2k-1
        pip:         9.0.1-py35_1
        python:      3.5.3-1
        qutip:       4.1.0-np112py35_1
        readline:    6.2-2              (soft-link)
        scipy:       0.19.0-np112py35_0
        setuptools:  33.1.1-py35_0
        sqlite:      3.13.0-1
        tk:          8.5.19-1
        wheel:       0.29.0-py35_0
        xz:          5.2.2-1
        zlib:        1.2.11-0

    Linking packages ...
    [      COMPLETE      ]|##########################| 100%
    #
    # To activate this environment, use:
    # $ source activate qutiptest
    #
    # To deactivate this environment, use:
    # $ source deactivate
    #
    goerz@mlhpc2:~> source activate qutiptest
    discarding /home/goerz/.conda/envs/default/bin from PATH
    prepending /home/goerz/.conda/envs/qutiptest/bin to PATH
    (qutiptest)goerz@mlhpc2:~> python
    Python 3.5.3 | packaged by conda-forge | (default, Feb  9 2017, 14:37:12)
    [GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import qutip
    /home/goerz/.conda/envs/qutiptest/lib/python3.5/site-packages/qutip/__init__.py:161: UserWarning: matplotlib not found: Graphics will not work.
    warnings.warn("matplotlib not found: Graphics will not work.")
    Illegal instruction (core dumped)
    (qutiptest)goerz@mlhpc2:~>

Let me know if you need further information on my setup in order to reproduce this

**Comment by goerz** [comment]
This still happens if I also install matplotlib into the environment (without the "matplotlib not found" warning)

**Comment by goerz** [comment]
It does work on other workstations, so it must be something platform specific. Any ideas on what I could do to debug this further?

**Comment by goerz** [comment]
Installation via pip or from source seems to work. Oh, and I'm also pretty sure that the conda installation *used* to work on this machine (a few weeks ago)

**Comment by nonhermitian** [comment]
Well, it seems that it gets through the init file till it hits the import statements.  So one would likely have to start by importing the various modules by hand till something breaks, and then check from there.

What are the difference s between machines where it works, and the one where it doesn't?

**Comment by goerz** [comment]
Good question. I'm not sure what the *relevant* differences between the machines are. Both are Ubuntu workstations (one 14.04, the other 16.04). The versions of `conda` a different (4.0.5 vs 4.3.11, but I may not easily be able to upgrade). They both have quite different compilers installed.

I stepped through the import statement with `ipdb`. The crash happens in the following location:

    __init__.py (171): from qutip.obj import *
        qobj.py (60): from qutip.fastsparse import fast_csr_matrix, fast_identity
             fastparse.py (406): from qutip.cy.spmath import (zcsr_transpose, zcsr_adjoint, zcsr_mult)

When I continue to step into the last statement (line 406 in `fastparse.py`), I only see `importlib` internals, and the last output before it crashes  is

    > <frozen importlib._bootstrap>(222)_call_with_frames_removed()

**Comment by nonhermitian** [comment]
Should gcc be reporting redhat 4.8.2 when running​ on ubuntu?

**Comment by goerz** [comment]
Since it's the python from the conda package, I'm assuming that's because Continuum created the linux package on a Redhat system. GCC is identified like that on both of the workstations. But yeah, my guess would be that there is some shared library that's compiled in a way that's incompatible with the rest of the system. Is there any linux utility that would allow to determine which library is being accessed at the moment of the crash? Some invocation of `ldd`?

**Comment by nonhermitian** [comment]
Oh sorry, I thought you were reporting the sys gcc, not the conda one.

Conda-forge and QuTiP are tested heavily against Ubuntu 14.04, so if any
platform works, it should be that one.

As I originally suspected, the problem comes from the Cython code.
Specifically for the sparse matrix math.  The fact that you can build it
yourself suggests a binary incompatibility.  However, again, we test
against 14.04, so I am hard pressed to think about what the issue could be.
 gdb might be able to hunt down where the dump occurs.

On Mar 25, 2017 18:27, "Michael Goerz" <notifications@github.com> wrote:

Since it's the python from the conda package, I'm assuming that's because
Continuum created the linux package on a Redhat system. GCC is identified
like that on both of the workstations. But yeah, my guess would be that
there is some shared library that's compiled in a way that's incompatible
with the rest of the system. Is there any linux utility that would allow to
determine which library is being accessed at the moment of the crash? Some
invocation of ldd?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/qutip/qutip/issues/674#issuecomment-289249308>, or mute
the thread

**Comment by ajgpitch** [comment]
Not really much to add, except that if it were possible to try a fresh
install of anaconda, and maybe python 3.6, but that is just guessing.
Probably an install from source is better on linux any way.
The conda packages were mainly developed for users with issues compiling
(i.e. on Windows). Though things have moved on so much since we started
trying that as a solution.

**Comment by goerz** [comment]
`conda install libgcc` seems to solve the problem for now

**Comment by dcbradley** [comment]
We ran into the "Illegal Instruction" problem too when using the conda qutip package (4.2.0-np113py36_2).  Building qutip from source within the same conda environment produced a working qutip.

Details of the processor on which the failure was observed:

model name	: Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 xsave lahf_lm dtherm tpr_shadow vnmi flexpriority

$ uname -a
Linux plantain 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux

**Comment by nonhermitian** [comment]
I wonder if it has to do with the low level c++ code used in the sparse matrix operations.

**Comment by nonhermitian** [comment]
I am guessing that that us indeed the case, although it does appear that sse2 is there.  Conda may have to disable sse2 extensions.

**Comment by nonhermitian** [comment]
Verified working on my workstation (ubuntu 14.04, Xeon E5-2630).

**Comment by AElton363** [comment]
Hi, I am facing the same problem (Installion of qutip 4.2 with conda, python 3.6). What do you mean by disabeling the sse2 extensions?

**Comment by ajgpitch** [comment]
@AElton363  What OS are you trying on? and what version of conda?

**Comment by nonhermitian** [comment]
Installing from source is probably the way to go.

**Comment by m-kosik** [comment]
Today I encountered the same problem when installing qutip 4.3.1 from conda-forge channel on Ubuntu 18.04. I have Anaconda 2018.12  with Python 3.7. Installing via pip in the system python didn't work either. The solution was in fact to install from source in anaconda which I did in the following manner:
1. download the qutip source file from webpage, in my case it was: qutip-4.3.1.tar.gz
2. write in terminal: "whereis pip"
3. choose the anaconda pip location, something like: /home/miriam/anaconda3/bin/pip 
4. go to the directory where you downloaded the source file and type: sudo <here goes the pip location from previous step>  install qutip-4.3.1.tar.gz
5. it finally works for me.

**Comment by thangleiter** [comment]
I am now also encountering this issue when installing qutip 4.3.1 on a docker image (built from Windows). qutip 4.3.0 works without problems. Minimal docker file where qutip fails to import:

```dockerfile
FROM continuumio/miniconda3

RUN conda config --append channels conda-forge && conda update -y --quiet conda && conda install -y --quiet qutip=4.3.1
```

**Comment by nathanshammah** [comment]
@thangleiter can you try with the dependencies (cython numpy scipy nose matplotlib)? What Python are you using and what OS?

**Comment by thangleiter** [comment]
> 
> 
> @thangleiter can you try with the dependencies (cython numpy scipy nose matplotlib)? What Python are you using and what OS?

I am building (and running) the Docker image from Windows 10 1803 Education. The image itself is based on Alpine Linux (see [https://github.com/ContinuumIO/docker-images/tree/master/miniconda3](url)) and runs Python 3.7.1 (or lower, depending on the qutip version's requirements).

Explicitly installing the dependencies also results in an `Illegal Instruction`. The dockerfile for reference:
```dockerfile
FROM continuumio/miniconda3

RUN conda config --append channels conda-forge && conda update -y --quiet conda && conda install -y --quiet qutip cython numpy scipy nose matplotlib
```

**Comment by nathanshammah** [comment]
@thangleiter try to put qutip last: conda install cython numpy scipy qutip. Also check now with 4.4.0 release.

**Comment by thangleiter** [comment]
> 
> 
> @thangleiter try to put qutip last: conda install cython numpy scipy qutip. Also check now with 4.4.0 release.

Seems like it works with qutip 4.4.0 👍. The position in the conda install command doesn't seem to have any effect.
