### ISSUE TITLE
Reverse Circuit doesn't work

### ISSUE THREAD

**Issue by mrcalixe** [qutip/qutip#682]
Whenever i try to reverse some Circuit it throws an exception telling that temp does not have append method implemented.
I checked the source code and i think that instead o append the developers meant add_gate.

**Comment by sahmed95** [comment]
Could you please post the code snippet and the traceback of the error message ? Thank you.

**Comment by sahmed95** [comment]
Ok. I wrote a test for it. The error message can be seen below. I will open a PR to resolve this. Thank you very much for raising the issue.
```
qc = QubitCircuit(3)
qc.add_gate("CNOT", targets=[1], controls=[0])
test_gate = Gate("RZ", targets=[1], arg_value = 1.570796,
                             arg_label="P")
qc.add_gate(test_gate)
qc.reverse_circuit()
```

```
ERROR: Reverse a circuit
----------------------------------------------------------------------
Traceback (most recent call last):
dev/qutip/qutip/qip/circuit.py", line 371, in reverse_circuit
    temp.append(self.gates[self.N - i - 1])
AttributeError: 'QubitCircuit' object has no attribute 'append'
```

**Comment by mrcalixe** [comment]
It is a simple fix. Just replace "append" with "add_gate" in "temp.append(self.gates[self.N - i - 1])". I tested myself and it works like a charm now.
You are welcome. I love QuTip and it is an honor to help the developers.

**Comment by sahmed95** [comment]
Hi @mrcalixe, this fix has been implemented in the PR -  https://github.com/qutip/qutip/pull/684. After review, it should be merged and ready for use. Thank you very much for contributing and raising this issue. Enjoy working with QuTiP.  :)
