### ISSUE TITLE
spectrum_correlation_fft() assumes linearly spaced taulist

### ISSUE THREAD

**Issue by joniram** [qutip/qutip#689]
The function `spectrum_correlation_fft(taulist, y)` accepts all kinds of (non-linspace) taulists with corresponding correlation values `y`.
However, `y` is passed to `scipy.fftpack.fft(y)`, which assumes the values to be linearly spaced in time. If 'taulist' is not a linspace, the result of `spectrum_correlation_fft(taulist, y)` will seem realistic, but in fact be totally off.
This behaviour is especially critical, because it is often advantageous to use non-linear taulists for the calculation of correlation values.

I guess this limitation is indicated by the fact that it uses a fast fourier transform, but I think it should be indicated more clearly, at least in the docstring.

P.S: Thanks for the great module! I quite enjoy working with qutip.

**Comment by nonhermitian** [comment]
Indeed, that should be checked.  Will do soon.

**Comment by nonhermitian** [comment]
Addressed in #696.
