### ISSUE TITLE
Error multiplication of Qobjs

### ISSUE THREAD

**Issue by CareF** [qutip/qutip#690]
I can reproduce the problem by the following codes: 

    from qutip import *
    
    N = 10
    v = rand_ket(N)
    p1 = v * v.dag()
    p2 = Qobj([[ v[n,0]*v[m,0].conj() for m in range(0,v.shape[0])] 
        for n in range(0,v.shape[0])])
    print(p1-p2)

where p1 is not giving correct result. Everything is correct using smaller N. The code also works fine on my server, so it seems to be environment dependent. 

I am working on Arch Linux, Python3.6.1 with latest version of qutip from AUR (4.1.0-1). 

Any suggestion of what I can try? 
Thank you!

**Comment by CareF** [comment]
I am trying to track where the bug come from and find that it's the problem of scipy.sparse: 
the multiplication of v.data is also not working correctly.. 

Should I close this issue?

**Comment by nonhermitian** [comment]
This is the same error as #681.  It is an issue with the Arch linux package.  You should install another way.

**Comment by CareF** [comment]
@nonhermitian 
Thank you for checking this. 
FYI, I was tracking on what's wrong and it turns out qutip.cy.spmath.zcsr_mult is not working properly on my local machine. I don't have much knowledge on cython, preventing me from going further.

**Comment by CareF** [comment]
Just found that installing through pip gave the same problem.

**Comment by CareF** [comment]
Tried to build using gcc5, but it doesn't solve the problem.

**Comment by CareF** [comment]
It works on Anaconda, but Anaconda doesn't work well with my other tools. 

Thank you for your help anyway. I can live with that, and I am just updating my attempts for people who will have similar problem.
