### ISSUE TITLE
Builder Pattern for defining control problems

### ISSUE THREAD

**Issue by MichalKononenko** [qutip/qutip#692]
The [``optimize_pulse`` API](http://qutip.org/docs/4.1/apidoc/functions.html#qutip.control.pulseoptim.optimize_pulse) takes in a lot of optional arguments. Wouldn't it make more sense to use a builder pattern to define a control problem in a ``ControlProblem`` class?

**Comment by nonhermitian** [comment]
@ajgpitch Any thoughts on this one?

**Comment by sahmed95** [comment]
Hi, I was reading about builder patterns and came across this [discussion](https://stackoverflow.com/questions/11977279/builder-pattern-equivalent-in-python) which seems to suggest that builder patterns are not necessarily needed in Python. Instead, all the functions could probably be bundled into a single ```PulseOptimizer``` class and whatever the wrapper functions are doing right now can be methods of this class. The input arguments can be initialised in the __init__ of this class. This you could have something like

```
from qutip.control.pulseoptim import PulseOptimizer

optimizer = PulseOptimizer(drift="", ctlr="", ....)
crab = optimizer.opt_pulse_crab(args, ...)
unitary_crab = optimizer.opt_pulse_crab_unitary(args,...)
```

@MichalKononenko - if you are suggesting something like [this](https://sourcemaking.com/design_patterns/builder/python/1) then perhaps it is that same as what I suggested on top.

**Comment by chaithumcn3** [comment]
I would agree with what @quantshah had said. Builder patterns are useful in those languages like Java, where named parameters is not in-built. All functions bundled into a single class would be better alternative. This would help when adding new methods that differs in optimization algorithm to the class.

**Comment by jakelishman** [comment]
Closing this now due to inactivity.
