### ISSUE TITLE
Cannot import qutip after update!

### ISSUE THREAD

**Issue by caidish** [qutip/qutip#694]
I see that qutip announced a new version, but after my update,It breaks down:
`from qutip import *`
the error occurs:   undefined symbol: _ZTINSt8ios_base7failureB5cxx11E
After google the error,I find a possible solution :` pip install qutip`
Then the error changes to : 
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/home/caidish1234/anaconda3/lib/python3.6/site-packages/qutip/__init__.py in <module>()
     46     __IPYTHON__
---> 47     qutip.settings.ipython = True
     48 except:

AttributeError: module 'qutip' has no attribute 'settings'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-3-0a5c3f9bc976> in <module>()
      3 import matplotlib.pyplot as plt
      4 from tqdm import tnrange,tqdm_notebook
----> 5 from qutip import *

/home/caidish1234/anaconda3/lib/python3.6/site-packages/qutip/__init__.py in <module>()
     47     qutip.settings.ipython = True
     48 except:
---> 49     qutip.settings.ipython = False
     50 
     51 # -----------------------------------------------------------------------------

AttributeError: module 'qutip' has no attribute 'settings'`

PS:I'm using Google Computing platform. The system is Ubuntu .However,it works fine on my mac...........

**Comment by nonhermitian** [comment]
Are you running it from the installation directory?

**Comment by caidish** [comment]
@nonhermitian🤗🤗🤗I just halted the notebook and started agian..it works well now!BTW:can I use numba @jit to accelerate the program?

**Comment by nonhermitian** [comment]
Nope, your not likely to see much, if any, improvement.
