### ISSUE TITLE
Can't find qcirc.png

### ISSUE THREAD

**Issue by hellmersjl3ds** [qutip/qutip#702]
Hello, I posted this issue on the QuTiP Tutorials GitHub repo, but it doesn't look like anyone is monitoring it.

I've tried googling, but I only find stuff about making sure Imagemagick and Ghostscript are installed and they both are.

I also made sure texlive was installed.

When I try to generate a circuit diagram as follows:

> %matplotlib inline
> from qutip import *
> from qutip.qip.models.circuitprocessor import *
> from qutip.qip.models.spinchain import *
> 
> N = 3
> qc = QubitCircuit(N)
> 
> qc.add_gate("CNOT", targets=[0], controls=[2])
> 
> qc.png
> 

I get a stack trace

> FileNotFoundError                         Traceback (most recent call last)
> <ipython-input-2-4489e338191c> in <module>()
>       4 qc.add_gate("CNOT", targets=[0], controls=[2])
>       5 
> ----> 6 qc.png
> 
> /home/jhellmers/anaconda3/lib/python3.6/site-packages/qutip/qip/circuit.py in png(self)
>    1012     def png(self):
>    1013         from IPython.display import Image
> -> 1014         return Image(self._repr_png_(), embed=True)
>    1015 
>    1016     @property
> 
> /home/jhellmers/anaconda3/lib/python3.6/site-packages/qutip/qip/circuit.py in _repr_png_(self)
>    1004 
>    1005     def _repr_png_(self):
> -> 1006         return _latex_compile(self.latex_code(), format="png")
>    1007 
>    1008     def _repr_svg_(self):
> 
> /home/jhellmers/anaconda3/lib/python3.6/site-packages/qutip/qip/circuit_latex.py in _latex_compile(code, filename, format)
>      60         os.system("convert -density %s %s.pdf %s.png" % (100, filename,
>      61                                                          filename))
> ---> 62         with open("%s.png" % filename, "rb") as f:
>      63             result = f.read()
>      64     else:
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'qcirc.png'
> 

I'm using.  My configuration information is as follows:

> Software	Version
> QuTiP	4.1.0
> Numpy	1.11.3
> SciPy	0.18.1
> matplotlib	2.0.0
> Cython	0.25.2
> Number of CPUs	4
> BLAS Info	INTEL MKL
> IPython	5.1.0
> Python	3.6.0 |Anaconda 4.3.1 (64-bit)| (default, Dec 23 2016, 12:22:00) [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
> OS	posix [linux]
>

**Comment by sahmed95** [comment]
Hi, I was facing the same issue but it was resolved after I installed some of the additional LaTeX packages. The issue could be that your LaTeX file is not getting compiled as you may be missing some required packages : pdflatex, pdfcrop, pdf2svg, imagemagick (convert)

Also you may be missing

\usepackage{xy}
\xyoption{matrix}
\xyoption{frame}
\xyoption{arrow}
\xyoption{arc}
\usepackage{ifpdf}

Let me help you resolve this step by step. Could you try to see what is the result of the following snippet which tries to generate the LaTeX file and display the Image.

```
%matplotlib inline
from qutip import *
from qutip.qip.circuit_latex import _latex_compile
N = 3
qc = QubitCircuit(N)

qc.add_gate("CNOT", targets=[0], controls=[2])

latex_code = qc.latex_code()
print(latex_code)

compiled_latex = _latex_compile(latex_code)
print(compiled_latex)

from IPython.display import Image
Image(compiled_latex, embed=True)
```

**Comment by hellmersjl3ds** [comment]
I installed the "full" version of texlive (sudo apt-get install texlive-full on Ubuntu), and now it is working wonderfully.

Thanks.

**Comment by liyaochong** [comment]
&  &  \ctrl{2}  & \qw \\ 
 &  &  \qw  & \qw \\ 
 &  &  \targ  & \qw \\ 

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-52-c2a400b5ecd1> in <module>()
      9 print(latex_code)
     10 
---> 11 compiled_latex = _latex_compile(latex_code)
     12 print(compiled_latex)
     13 

C:\ProgramData\Anaconda3\lib\site-packages\qutip\qip\circuit_latex.py in _latex_compile(code, filename, format)
     60         os.system("convert -density %s %s.pdf %s.png" % (100, filename,
     61                                                          filename))
---> 62         with open("%s.png" % filename, "rb") as f:
     63             result = f.read()
     64     else:

FileNotFoundError: [Errno 2] No such file or directory: 'qcirc.png'

**Comment by JackXu1993** [comment]
On mac os, try brew install imagemagick

**Comment by Nillmer** [comment]
How do I fix this error on win64 conda?

**Comment by nchattra** [comment]
For Windows 10, I solved this issue by adding path to the folder that contains gswin32c.exe (e.g. C:\texlive\2019\tlpkg\tlgs\bin) to system variables.   [See https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/]

**Comment by SilverYar** [comment]
I'm using. My configuration information is as follows:

Software	Version
QuTiP	4.5.2
Numpy	1.18.5
SciPy	1.5.0
matplotlib	3.2.2
Cython	0.29.21
Number of CPUs	6
BLAS Info	INTEL MKL
IPython	7.16.1
Python	3.8.3 (default, Jul 2 2020, 11:26:31) [Clang 10.0.0 ]
OS	posix [darwin]
Fri Sep 18 02:42:59 2020 MSK


For Mac OS: FileNotFoundError: [Errno 2] No such file or directory: 'qcirc.png'.\

When I try to generate a circuit diagram as follows:

%matplotlib inline
from IPython.display import Image
from numpy import pi
import numpy as np
from qutip import *
from qutip.qip.operations import *
from qutip.qip.circuit import QubitCircuit, Gate

cphase(pi/2)
q = QubitCircuit(2, reverse_states=False)
q.add_gate("CSIGN", controls=[0], targets=[1])
q.png

Log Error:

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-14-a760fe8d2360> in <module>
      1 q = QubitCircuit(2, reverse_states=False)
      2 q.add_gate("CSIGN", controls=[0], targets=[1])
----> 3 q.png

~/opt/anaconda3/lib/python3.8/site-packages/qutip/qip/circuit.py in png(self)
   1122     def png(self):
   1123         from IPython.display import Image
-> 1124         return Image(self._repr_png_(), embed=True)
   1125 
   1126     @property

~/opt/anaconda3/lib/python3.8/site-packages/qutip/qip/circuit.py in _repr_png_(self)
   1114 
   1115     def _repr_png_(self):
-> 1116         return _latex_compile(self.latex_code(), format="png")
   1117 
   1118     def _repr_svg_(self):

~/opt/anaconda3/lib/python3.8/site-packages/qutip/qip/circuit_latex.py in _latex_compile(code, filename, format)
     60         os.system("convert -density %s %s.pdf %s.png" % (100, filename,
     61                                                          filename))
---> 62         with open("%s.png" % filename, "rb") as f:
     63             result = f.read()
     64     else:

FileNotFoundError: [Errno 2] No such file or directory: 'qcirc.png'

How do I fix this error on Mac?

**Comment by BoxiLi** [comment]
Hi @SilverYar 

Did you install ImageMagick? This tutorial might be helpful: https://nbviewer.jupyter.org/github/qutip/qutip-notebooks/blob/master/examples/quantum-gates.ipynb
