### ISSUE TITLE
Time dependent SMEsolver

### ISSUE THREAD

**Issue by Vutshi** [qutip/qutip#738]
Hi all,
currently we are working on a time depended version of the SME solver. There is a strategic decision to be made. At the moment, the stochastic.py file is the second largest file in qutip due to variety of methods involved. So it is a kind of mess. We think it makes sense to create stochastic_td.py to contain all the related time depended cases for solvers etc. Should we do it or is it better to keep enlarging the stochastic.py file?

**Comment by nonhermitian** [comment]
I believe that there are others working on similar things.  We have a relatively new guy named Eric, who works with @arnelg , who mentioned working on this.  I dont have his GitHub name at the moment, but I mentioned your issue to him.

**Comment by nonhermitian** [comment]
Another thought would be that it might be good for you to be part of the QuTiP slack group.  Since you contribute fairly regularly, it would be good to be in the loop of things.

**Comment by Vutshi** [comment]
What is QuTiP slack group?

**Comment by nonhermitian** [comment]
A chat app for devs that integrates nicely with github.  It us how we discuss things.

**Comment by Vutshi** [comment]
So, how can I join the chat?

**Comment by nonhermitian** [comment]
Send me your email to my private address, nonhermitian at Gmail, and I will add you.  You will also need to get the Slack app for your phone and/ or computer.

**Comment by Ericgig** [comment]
The new version is merged and will be released soon.
