### ISSUE TITLE
Error Pip Install

### ISSUE THREAD

**Issue by Phenix00** [qutip/qutip#739]
Hello Dear community, 
i'm trying to install qutip  using the " pip install qutip " command on ubuntu 16.04 , however at each time i get this error "Command python setup.py egg_info failed with error code 1 in /tmp/pip_build" 
i have tried  many versions of ubuntu ( 14, 15 ...) and many tricks in the net ( upgrading pip; upgrading python... )  trying to bypass this problem however all my tries failed..
i'll appreciate any help dear community...
sincerly yours
Amine Ch

**Comment by sahmed95** [comment]
Hi @Phenix00, I could reproduce the issue and this looks like an issue of pip messing up the dependencies in the requirements for QuTiP. The workaround is to install numpy, cython and scipy manually before running pip install qutip.

Please let me know if this works. Also, I am assuming the complete error message that you got was something like the error message below and thank you for bringing this to notice.
```
(qtest) air:qtest shahnawaz$ pip install qutip
Collecting qutip
  Downloading qutip-4.1.0.tar.gz (1.9MB)
    100% |████████████████████████████████| 1.9MB 523kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/yp/zkfwkv252nl6jtzqy2_tt88m0000gn/T/pip-build-7Mg7bn/qutip/setup.py", line 54, in <module>
        from Cython.Build import cythonize
    ImportError: No module named Cython.Build

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/yp/zkfwkv252nl6jtzqy2_tt88m0000gn/T/pip-build-7Mg7bn/qutip/
```
@ajgpitch 
I am looking into why this is happening and how it can be resolved. Relevant issues - https://github.com/h5py/h5py/issues/535, https://github.com/bayespy/bayespy/issues/14, https://github.com/pypa/pip/issues/988

**Comment by RavagerXLL** [comment]
Hi @Phenix00 ,

I don't know if you already managed to do the pip install, but I got the same errors as you and sahmed95 mentioned before. In my case, as I run my programs on a cluster in a Linux environment, where I don't have admin rights (e.g. I cannot use sudo commands), I had to use the --user option. 
So "pip install --user qutip" worked for me when the mentioned requirements have been installed met.

**Comment by kazukisona** [comment]
Hi, I got the same error but I could successfully install qutip after upgrading Scipy because the previous version of Scipy seems not to have a specific Cython package for building qutip. 

It's on Mac but try this

pip3 install scipy --upgrade
pip3 install qutip

**Comment by sahmed95** [comment]
@ajgpitch This could be closed now
