### ISSUE TITLE
QubitCircuit doesn't find png (or svg)

### ISSUE THREAD

**Issue by orome** [qutip/qutip#754]
`QubitCircuit` doesn't find `png` (or `svg`) as expected. Using a simple example right out of [one of the demo notebooks](http://nbviewer.jupyter.org/github/qutip/qutip-notebooks/blob/master/examples/quantum-gates.ipynb)

```python
qc3 = QubitCircuit(3)
qc3.add_gate("CNOT", 1, 0)
qc3.add_gate("RX", 0, None, np.pi/2, r"\pi/2")
qc3.add_gate("RY", 1, None, np.pi/2, r"\pi/2")
qc3.add_gate("RZ", 2, None, np.pi/2, r"\pi/2")
qc3.add_gate("ISWAP", [1, 2])
qc3.svg
```
I get

```
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-17-90c37b42f323> in <module>()
      5 qc3.add_gate("RZ", 2, None, np.pi/2, r"\pi/2")
      6 qc3.add_gate("ISWAP", [1, 2])
----> 7 qc3.svg
      8 dir(qc3)

/usr/local/lib/python2.7/site-packages/qutip/qip/circuit.pyc in svg(self)
   1049     def svg(self):
   1050         from IPython.display import SVG
-> 1051         return SVG(self._repr_svg_())
   1052 
   1053     def qasm(self):

/usr/local/lib/python2.7/site-packages/qutip/qip/circuit.pyc in _repr_svg_(self)
   1039 
   1040     def _repr_svg_(self):
-> 1041         return _latex_compile(self.latex_code(), format="svg")
   1042 
   1043     @property

/usr/local/lib/python2.7/site-packages/qutip/qip/circuit_latex.pyc in _latex_compile(code, filename, format)
     64     else:
     65         os.system("pdf2svg %s.pdf %s.svg" % (filename, filename))
---> 66         with open("%s.svg" % filename) as f:
     67             result = f.read()
     68 

IOError: [Errno 2] No such file or directory: 'qcirc.svg'
```
with

> uTiP | 4.2.0
> Numpy | 1.13.1
> SciPy | 0.19.1
> matplotlib | 2.0.2
> Cython | 0.27
> Number of CPUs | 2
> BLAS Info | OPENBLAS
> IPython | 5.5.0
> Python | 2.7.13 (default, Jul 18 2017, 09:17:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
> OS | posix [darwin]

**Comment by sahmed95** [comment]
Hi, this was discussed before in https://github.com/qutip/qutip/issues/702

You may be missing some LateX packages or other dependencies:
 pdflatex, pdfcrop, pdf2svg, imagemagick (convert)

Also you may be missing the following latex packages:

\usepackage{xy}
\xyoption{matrix}
\xyoption{frame}
\xyoption{arrow}
\xyoption{arc}
\usepackage{ifpdf}

**Comment by sahmed95** [comment]
@nonhermitian This could be closed now.
