### ISSUE TITLE
qutip.simdiag: update to python 3.6 and numerical issues

### ISSUE THREAD

**Issue by kevinsung** [qutip/qutip#756]
I have two matrices `A` and `B`. I run

    eigvals, eigvecs = simdiag([A, B])
and get

    AttributeError                            Traceback (most recent call last)
    <ipython-input-8-966464195054> in <module>()
    ----> 1 eigvals, eigvecs = simdiag([A, B])
    /usr/lib/python3.6/site-packages/qutip/simdiag.py in simdiag(ops, evals)
     82     eigvals, eigvecs = la.eig(A.full())
     83     zipped = zip(-eigvals, range(len(eigvals)))
    ---> 84     zipped.sort()
     85     ds, perm = zip(*zipped)
     86     ds = -np.real(np.array(ds))
    AttributeError: 'zip' object has no attribute 'sort'

The solution is to change the lines

    zipped.sort()
in `simdiag` and the private function `degen` to

    zipped = sorted(zipped)
I did this and it works.

However, I'm also wondering if there are plans to rewrite `simdiag` to be more numerically stable (if possible). I've found that the eigenvalues returned and the accuracy of the eigenvectors depends significantly on the order that they are passed. For instance, I know that `A` has integer eigenvalues, and when I run

    eigvals, eigvecs = simuldiag([A, B])
    eigvals[0]

I get

    array([ 8.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  6.,  6.,  6.,  6.,
        6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,
        6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  5.,  5.,
        5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
        5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
        5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
        5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
        5.,  5.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,
        4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,
        4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,
        4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,
        4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,
        4.,  4.,  4.,  4.,  4.,  4.,  4.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.])
as expected. But when I run

    eigvals, eigvecs = simuldiag([B, A])
    eigvals[1]
one of the eigenvalues listed is `19.897093031573782` even though it should return a list of the same numbers (the largest should be 8.0). Many of the other values listed are also not close to integers.

**Comment by nonhermitian** [comment]
simdiag is not a well used function.  In fact, I know of no one whom has used it until now.  It is not unit tested, and was written nearly eight years ago, for compatibility with the Matlab quantum optics toolbox.  As such, it is not really a priority at the moment, and it might take some time to get around to fixing it.

**Comment by nathanshammah** [comment]
Thank you @kevinsung. Closing this as the bug has been fixed by @jevonlongdell in #879. If you wish, please open a PR for the stability enhancement of `simuldiag`.
