### ISSUE TITLE
Segmentation fault in sesolve

### ISSUE THREAD

**Issue by Phyks** [qutip/qutip#761]
Hi,

I was trying to run some simulations with [Floquet formalism in Qutip](http://qutip.org/docs/4.1/guide/dynamics/dynamics-floquet.html) in a Jupyter notebook, when I ran into a "The kernel appears to died unexpectedly, it will restart" error message.

I tried to understand what is happening, and it seems it is due to a segmentation fault. It happens also when run in CPython 3.5.2. `gdb` was not super useful, and I could not get it to output any interesting backtrace.

Manually tracking the issue down, it seems that `qutip.floquet.floquet_modes` call `qutip.propagator.propagator` which itself calls `sesolve`. As far as I could track the error down for the moment, it seems to happen in [this call](https://github.com/qutip/qutip/blob/master/qutip/propagator.py#L159-L160).

My code is quite lengthy, and I did not yet manage to isolate a small snippet to reproduce the error :/ Not sure what is the best way to debug this either :/

```python
>>> qutip.about()

QuTiP: Quantum Toolbox in Python
Copyright (c) 2011 and later.
A. J. Pitchford, P. D. Nation, R. J. Johansson, A. Grimsmo, and C. Granade

QuTiP Version:      4.2.0
Numpy Version:      1.13.3
Scipy Version:      0.19.1
Cython Version:     0.27.1
Matplotlib Version: 2.0.0
Python Version:     3.5.2
Number of CPUs:     2
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Darwin (x86_64)
Installation path:  /Users/phyks/.local/share/virtualenvs/physique/lib/python3.5/site-packages/qutip
```

Thanks!

**Comment by Phyks** [comment]
Sorry for the noise, I got what was wrong, it was basically a mistake from my part.

I was using a time-dependent hamiltonian written with strings, such as

```python
H = [H_0, [H_1, 'sin(t)']
```

and `H_0` and `H_1` had incompatible shapes… :/ Maybe it would be worth adding an extra check on this, to ease debugging? Thanks!

**Comment by nonhermitian** [comment]
It checks to make.sure.the dims are compatible.  It is gard to see how the dims can be correct, but the shapes wrong?

**Comment by Phyks** [comment]
In my case,

```python
> H_0.dims
[[3, 11], [3, 11]]
> H_1.dims
[[3, 6], [3, 6]]
```
and I don't get any error when running

```python
> H = [H0, [H_1, 'sin(t)']]; qutip.propagator(H, T, [], args)
```
apart from the `Segmentation fault`.

I think this is due to `sesolve` being called with `_safe_mode=False` [here](https://github.com/qutip/qutip/blob/master/qutip/propagator.py#L160) as running
```python
> qutip.sesolve(H, psi0, tlist, [], args, options, _safe_mode=False)
``` 
gets me a `Segmentation fault` without any other error, but running
```python
> qutip.sesolve(H, psi0, tlist, [], args, options)
```
gives
```python
Exception: Input operator and ket do not share same structure.
```

**Comment by nonhermitian** [comment]
Ahh, it is because I forgot to add the safety check to the propagator function.
