### ISSUE TITLE
floquet_master_equation_steadystate docstring is not really helpful

### ISSUE THREAD

**Issue by Phyks** [qutip/qutip#768]
Hi,

I have been trying to use `qutip.floquet.floquet_master_equation_steadystate` method to get the steadystate of my system, but the docstring is not super useful.

From the docstring, I guess I should call it as `qutip.floquet.floquet_master_equation_steadystate(H, A)` where

* `H` is my (time-dependent) hamiltonian, similar as the one used in http://qutip.org/docs/latest/guide/dynamics/dynamics-floquet.html#floquet-formalism-in-qutip.
* `A` is the [`A` matrix output](https://github.com/qutip/qutip/blob/master/qutip/floquet.py#L587-L588) from `floquet_master_equation_rates` call.

I think I missed something as I am getting an error
```
TypeError: Solving for steady states requires Liouvillian (super) operators
```
from https://github.com/qutip/qutip/blob/master/qutip/steadystate.py#L224.

Additionnally, I think there is a much easier way to find the steadystate of such a system, using something like (not really well written nor optimised):

```python
def floquet_master_equation_steadystate2(A):
    """
    TODO

    Parameters
    ----------

    A : TODO
        A matrix used to build the master equation.
    """
    B = np.zeros_like(A)
    N = A.shape[0]
    for a in range(N):
        for b in range(N):
            # Convergence of off-diagonal terms in density matrix to 0
            assert(-0.5 * np.sum(A[:, a] + A[:, b]) < 0)
            # Diagonal terms of density matrix
            if a != b:
                B[a, b] = A[a, b]
            else:
                B[a, b] = -1.0 * np.sum([
                    A[nu, a] for nu in range(N) if nu != a]
                )
    eigval, eigvec = Qobj(B).eigenstates()
    assert(np.isclose(eigval[-1], 0, atol=1e-15))
    return eigvec[-1] * eigvec[-1].dag()
```

which basically looks for the eigenvector associated with 0 eigenvalue of a matrix derived from `A`, which is basically coming directly from equation 251 of [Gri98](http://qutip.org/docs/latest/biblio.html#gri98).

**Comment by nathanshammah** [comment]
Thank you, I will try to pass the word to users using Floquet.

**Comment by hodgestar** [comment]
The Floquet solver was heavily rewritten in QuTiP 5, so closing this for now.
