### ISSUE TITLE
Trouble creating type='super'

### ISSUE THREAD

**Issue by ihincks** [qutip/qutip#769]
I am trying to create a `Qobj` of type `'super'` with a matrix of my choosing. My understanding is that this should work (based on the [API doc](http://qutip.org/docs/4.0.2/apidoc/classes.html#qobj) for the `type` keyword: `str – Type of quantum object: ‘bra’, ‘ket’, ‘oper’, ‘operator-ket’, ‘operator-bra’, or ‘super’.`):

    import numpy as np
    import qutip as qu
    x = qu.Qobj(np.ones((4,4)), type='super')

However, `x` gets type `'oper'` with input-output dimensions 4:

```
    [Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True, 
Qobj data =
 [[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]]
```

 Am I misunderstanding something, or is this a bug?

Aside: I have this work-around for now:

    x = qu.to_super(qu.sigmax())
    x.data = qu.Qobj(np.ones((4,4))).data

**Comment by sahmed95** [comment]
Hi, sorry for the late response, you need to specify dimensions when you create a super operator.

Try the following code:

```
>> Qobj(np.ones((4,4)), dims=[[[2], [2]], [[2], [2]]], type='super')
Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = (4, 4), type = super, isherm = True
```

**Comment by nonhermitian** [comment]
I am looking at this right now, and while I agree with @sahmed95, it should also be possible to make the correct dims internally if `type='super'` and no dims are passed.  This would only be valid for unipartite inputs, but is probably sufficient.  Will do soon.

**Comment by ihincks** [comment]
Thank you for the helpful replies and the quick patch. I agree that defaulting to a unipartite system is what most users would expect.
