### ISSUE TITLE
Floquet mesolve not working as expected

### ISSUE THREAD

**Issue by Phyks** [qutip/qutip#772]
Hi,

It seems there are some errors in the Floquet `mesolve`-equivalent function, which are not seen when considering a simple qubit.

Consider for instance an harmonic oscillator with a drive, which should converge towards a coherent state:

```python
%matplotlib notebook

import numpy as np
from qutip import (basis, destroy, expect, fsesolve, sigmax, sigmaz, rand_ket, num,
                   mesolve)
from qutip.floquet import (floquet_modes, floquet_modes_table,
                     floquet_modes_t_lookup, fmmesolve)

# Parameters
wc = 1.0 * 2 * np.pi
wp = 1.5 * 2 * np.pi
T = 2 * np.pi / wp
N = 20
epsilon_p = np.sqrt(2) * np.sqrt(8) * (wp - wc)

psi0 = basis(N,0)
a = destroy(N)
H = [
    wc * a.dag() * a,
    [1.0j * epsilon_p * (a.dag() - a), 'cos(wp * t)']
]

args = {
    'wp': wp
}

# noise power spectrum
gamma1 = 0.05
def noise_spectrum(omega):
    return 0.5 * gamma1 * omega / (2 * np.pi)

tlist = np.linspace(0, 5 / gamma1, 100)

# find the floquet modes for the time-dependent hamiltonian
f_modes_0, f_energies = floquet_modes(H, T, args)

# precalculate mode table
f_modes_table_t = floquet_modes_table(f_modes_0, f_energies,
                                      np.linspace(0, T, 500 + 1),
                                      H, T, args)

# solve the floquet-markov master equation
output = fmmesolve(H, psi0, tlist,
                   [a], [], [noise_spectrum], T, args)

# For reference: calculate the same thing with mesolve
output_ref = mesolve(H, psi0, tlist, [np.sqrt(gamma1) * a],
                     [], args)
```

`output_ref.states[-1]` is a coherent state as expected.

![image png 1200 x 1200 pixels - redimensionnee 79](https://user-images.githubusercontent.com/3856586/31828448-433fd44a-b588-11e7-9305-e44f88ed8c1b.png)

But `output.states[-1]` is far from being a coherent state.

![image png 1200 x 1200 pixels](https://user-images.githubusercontent.com/3856586/31828469-56631e42-b588-11e7-8950-0ca04ce3c70c.png)

I tried to debug it, without real success for now :/

EDIT: Might be partially related to #624.

**Comment by Phyks** [comment]
Got it to work as expected after a few changes:

* First, it seems there is an error in [Gri98] and `A` should be transposed. This can be seen as equation 251 from [Gri98] differs from equation 52 from [PRA44]. There might be another issue with a `k` factor instead of a `-k` factor, but it should not matter as long as thermal population is 0. For some unknown reason, using `A` or its transpose does not change anything on qubits systems.
* Second, `c_ops` should not be dissipation operators but operators coupling to the environment bath. Then, one should not use `a` but `a + a.dag()`. This seems to be different than the standard `mesolve` and might deserve an emphasis in the doc.

[Gri98] 

[Gri98] | Grifoni, P. Hänggi, Driven quantum tunneling, Physics Reports 304, 299 (1998). doi:10.1016/S0370-1573(98)00022-2.
[PRA44] | 
R. Blümel, A. Buchleitner, R. Graham, L. Sirko, U. Smilansky, H. Walther, Phys. Rev. A 44 (1991) 4521.

**Comment by nonhermitian** [comment]
Many thanks for taking all the time to look into the Floquet solver.  I have no time of my own to devote to it at the moment, so feel free to modify and change as you see best.

**Comment by Phyks** [comment]
Sure, I'll try to keep my PR up to date with my latest checks. For anyone who might be using qutip for Floquet simulations, would be cool to have some reviews on my PR :)

**Comment by usmanmacer** [comment]
qutip.floquet does this floquet formalism supports any hamiltonian or just it works for two level systems? Also the code uploaded is not working, how to plot this wigner function? as an initial learning point. Floquet formalism is totally not working fro me. plz help

**Comment by Phyks** [comment]
> does this floquet formalism supports any hamiltonian or just it works for two level systems?

It should support any hamiltonian. I have simulations test cases with harmonic oscillators for instance. However, you should have a look at the code from #766 since the code currently in QuTiP repository seems to have been tested only with two-level systems and contains some bugs.


> Also the code uploaded is not working, how to plot this wigner function?

I'm sorry, I have no idea what you are talking about.


> Floquet formalism is totally not working fro me. plz help

I think you should first try to make it work with simple two-level systems. See http://qutip.org/docs/latest/guide/dynamics/dynamics-floquet.html and https://gitlab.inria.fr/lverney/qutip_floquet_example/blob/master/Example.ipynb. Note that there are some bugs in the current QuTiP code which are fixed by #766 but this one is not yet merged.

**Comment by chong-w** [comment]
I have tried the simple two-level systems in http://qutip.org/docs/latest/guide/dynamics/dynamics-floquet.html and found an unexpected error, could you help to solve this problem #854 ?

**Comment by Phyks** [comment]
Following the closing of #766 and for anyone having issues with the current Floquet codes (which has some bugs, there are open issues about it), here is a gist containing a working version of the Floquet code in qutip, to study Hamiltonian and steady-state behavior of any time-periodic system: https://gist.github.com/Phyks/20bfb5107cbc595f9e54ff92fccd6fb5.

Main differences with qutip code is:
* It reworks a bit the code from qutip, to make it more efficient.
* It fixes some known bugs.
* It introduces a function to get the steady-state density matrix without having to do a full time evolution (following a method presented in Grifoni 98).

Hope this helps,

**Comment by nathanshammah** [comment]
Thank you @Phyks. Could you open a PR about it? @Ericgig, I saw that the new solvers PR relative to QobjEvo, #990, `sesolve` is [called instead of `mesolve`](https://github.com/qutip/qutip/pull/990/files#diff-57e108dd2e7a7051e92275a95d220992R224). Probably these changes here are independent on this.

**Comment by nathanshammah** [comment]
Hi @jakelishman, given your expertise, it may be very useful if you could have a look at the `floquet` module. There are a lot of [issues](https://github.com/qutip/qutip/search?q=floquet&type=Issues) connected to it, and many users are really eager to see their solutions. This would be a milestone for QuTiP future releases, later in 2020. If interesting, there could even be projects that could be proposed as part of Google Summer of Code 2020.

**Comment by jakelishman** [comment]
I'll try and have a look in the coming weeks - hopefully it's not too urgent or someone else could take it.  I suspect looking over the whole module will require quite a lot of work, and it's been quite some time since I was last working with Floquet theory, but I'd certainly be interested in having a go.

**Comment by nathanshammah** [comment]
They’ve been on a dead track for months if not years, so there is no rush. Probably your experience is more than enough. Given that a thorough overhaul may be demanding, I mentioned the Google Summer of Code option: applying with a project and being chosen is a way to get well paid for a couple of involvement. This applies also to other modules, we will post our project ideas on the wiki page, a look at last year project proposals is here. Having good candidates get in touch early allows them to craft a strong proposal and may prompt the mentors to provide a specific project idea, which they would not otherwise bring up: https://github.com/qutip/qutip/wiki/Google-Summer-of-Code-2019.

**Comment by jakelishman** [comment]
See #1248 that implements the correct `A`.  I'm not certain about the comment about `c_ops` - I'll need to look into it more before we merge #1248.

**Comment by hodgestar** [comment]
The Floquet solver was heavily rewritten in QuTiP 5, so closing this for now.
