### ISSUE TITLE
plot_energy_levels() and division by 2\pi

### ISSUE THREAD

**Issue by petergthatsme** [qutip/qutip#782]
This is minor, but I would recommend to get rid of the division of terms in H by 2\pi in the function `visualization.plot_energy_levels()`.
Depending on the units that one uses, such a division may not be desired, and is currently a little confusing (as right now it's not explicitly mentioned in the function's doc, so one has to check the code to see what's going on).

**Comment by nonhermitian** [comment]
I think you are right.
