### ISSUE TITLE
ani.save doesn't expect clear_temp arg anymore

### ISSUE THREAD

**Issue by tilek** [qutip/qutip#798]
I am trying to use code from User Guide's [Directly Generating an Animation section](http://qutip.org/docs/4.1/guide/guide-bloch.html?highlight=funcanimation#directly-generating-an-animation):

```
ani.save('bloch_sphere.mp4', fps=20, clear_temp=True)
```

I get the following error:
```
Traceback (most recent call last):
  File "bloch_test.py", line 59, in <module>
    ani.save('bloch_sphere.mp4', fps=20, clear_temp=True)
TypeError: save() got an unexpected keyword argument 'clear_temp'
```

It looks like OpenDrift may have had the same or similar issue:
https://github.com/OpenDrift/opendrift/issues/9

My hypothesis is that QuTip needs to be adapted to the newer version of Matplotlib.
According to 
```
from qutip import *
about()
```
I use Matplotlib version: 2.1.1.

**Comment by nathanshammah** [comment]
Thank you @tilek, closing as it is addressed by PR 77 in qutip-doc.

**Comment by Nov05** [comment]
https://github.com/Nov05/JSAnimation?tab=readme-ov-file#-changed-by-nov05   

```
!git clone https://github.com/Nov05/JSAnimation.git
!pip install git+file:///content/JSAnimation ## <- change file path accordingly
!rm -r ./JSAnimation
```
