### ISSUE TITLE
Exception: Input operator and ket do not share same structure. error

### ISSUE THREAD

**Issue by questionmarkmark** [qutip/qutip#802]
from qutip import *
import numpy as np
import matplotlib.pyplot as plt
import qutip.testing as qt

Here is the part of the code that has error:

H = tensor(sigmaz(),sigmaz(),identity(2)) + tensor(identity(2),sigmaz(),sigmaz()) + 0.05 * tensor(sigmax(), sigmax(),sigmax())
psi0 = basis(8, 0)
times = np.linspace(0.0, 10.0, 20.0)
result = mesolve(H, psi0, times, [], [sigmaz()])

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-26-752e3e5ccdb6> in <module>()
      4 psi0 = basis(8, 0)
      5 times = np.linspace(0.0, 10.0, 20.0)
----> 6 result = mesolve(H, psi0, times, [], [sigmaz()])

/Users/lib/python2.7/site-packages/qutip/mesolve.pyc in mesolve(H, rho0, tlist, c_ops, e_ops, args, options, progress_bar, _safe_mode)
    223 
    224     if _safe_mode:
--> 225         _solver_safety_check(H, rho0, c_ops, e_ops, args)
    226 
    227     if progress_bar is None:

/Users/lib/python2.7/site-packages/qutip/solver.pyc in _solver_safety_check(H, state, c_ops, e_ops, args)
    795         Hdims = H.dims
    796         Htype = H.type
--> 797         _structure_check(Hdims, Htype, state)
    798     # Input H is function
    799     elif isinstance(H, (FunctionType, BuiltinFunctionType)):

/Users/lib/python2.7/site-packages/qutip/solver.pyc in _structure_check(Hdims, Htype, state)
    870         if Htype == 'oper':
    871             if Hdims[1] != state.dims[0]:
--> 872                 raise Exception('Input operator and ket do not share same structure.')
    873         # Input is super and state is ket
    874         elif Htype == 'super':

Exception: Input operator and ket do not share same structure.

**Comment by nonhermitian** [comment]
Your expectation operator needs to be tensored up.  Also psi0 needs to be the tensor of three two level subsystems, or the dims changed by hand.

**Comment by questionmarkmark** [comment]
Now that I changed psi0 structure from basis(8,0) to tensor(basis(2,0),basis(2,0),basis(2,0), then I still don't get the right structure. What ways that you recommend to make the dimension of psi0 to match the operator dimension? Thank you. 

Also, when you say the expectation operator to be tensored up, do you mean to tensor(sigmaz(),sigmaz(),sigmaz())? Thanks.

Here is the code and error.

H = tensor(sigmaz(),sigmaz(),identity(2)) + tensor(identity(2),sigmaz(),sigmaz()) + 0.05 * tensor(sigmax(), sigmax(),sigmax())
psi0=tensor(basis(2, 0),basis(2, 0),basis(2, 0))
times = np.linspace(0.0, 10.0, 20.0)
result = mesolve(H, gpy, times, [], [sigmaz()])

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-12-21d4d1054904> in <module>()
      6 
      7 
----> 8 result = mesolve(H, gpy, times, [], [sigmaz()])

/Users/lib/python2.7/site-packages/qutip/mesolve.pyc in mesolve(H, rho0, tlist, c_ops, e_ops, args, options, progress_bar, _safe_mode)
    223 
    224     if _safe_mode:
--> 225         _solver_safety_check(H, rho0, c_ops, e_ops, args)
    226 
    227     if progress_bar is None:

/Users//lib/python2.7/site-packages/qutip/solver.pyc in _solver_safety_check(H, state, c_ops, e_ops, args)
    858             else:
    859                 raise Exception('Invalid td-list element.')
--> 860             _structure_check(Hdims,Htype,_temp_state)
    861     elif isinstance(e_ops, FunctionType):
    862         pass

/Users/lib/python2.7/site-packages/qutip/solver.pyc in _structure_check(Hdims, Htype, state)
    882         if Htype == 'oper':
    883             if Hdims[1] != state.dims[0]:
--> 884                 raise Exception('Input operators do not share same structure.')
    885         # Input is super op. and state is density matrix
    886         elif Htype == 'super':

Exception: Input operators do not share same structure.
