### ISSUE TITLE
mesolve(H, rho0, tlist, c_ops, expt_ops, args={}, options=None) "expt_cps" problem.

### ISSUE THREAD

**Issue by questionmarkmark** [qutip/qutip#803]
Here is what you have in the instruction:

An instance of the class qutip.odedata, which contains either an array of expectation values for the times specified by tlist, or an array or **state vectors or density matrices corresponding to the times in tlist** [if expt_ops is an empty list], or nothing if a callback function was given inplace of operators for which to calculate the expectation values.

I wonder how to output the state vector that corresponding to the times in tlist? I have tried inputing rho() into expt_ops, but I don't think it works. it gives me an array with weird dimensions.

----------------------------
Here is the code:
H = ...
psi0=tensor(basis(2, 0),basis(2, 0),basis(2, 0),basis(2, 0),basis(2, 0),basis(2, 0))
times = np.linspace(0.0, 100.0, 100.0)
result = mesolve(H, psi0, times, [], [psi0])

result
Out[13]:
Result object with sesolve data.
--------------------------------
expect = True
num_expect = 1, num_collapse = 0
In [14]:

result.expect
result.expect
Out[14]:
[array([1.00000000e+00+0.j, 1.39934003e-01+0.j, 3.31589430e-01+0.j,
        8.25294179e-01+0.j, 5.86597077e-02+0.j, 5.84659111e-01+0.j,
        4.77021203e-01+0.j, 5.62476257e-02+0.j, 7.08785271e-01+0.j,
        2.10614966e-01+0.j, 1.18105171e-01+0.j, 5.94526471e-01+0.j,
        7.39148727e-02+0.j, 2.05242981e-01+0.j, 3.77092769e-01+0.j,
        1.34130556e-02+0.j, 2.39744019e-01+0.j, 2.23951275e-01+0.j,
        1.87656818e-04+0.j, 2.05728972e-01+0.j, 1.63835434e-01+0.j,
        7.22365902e-03+0.j, 1.70039734e-01+0.j, 1.60417861e-01+0.j,
        1.38527989e-02+0.j, 1.91747276e-01+0.j, 1.61137961e-01+0.j,
        3.47890583e-02+0.j, 2.94899823e-01+0.j, 1.17031515e-01+0.j,
        9.02925009e-02+0.j, 4.48835410e-01+0.j, 5.47500437e-02+0.j,
        2.03809669e-01+0.j, 5.29184180e-01+0.j, 4.40353918e-02+0.j,
        3.97709908e-01+0.j, 4.32688836e-01+0.j, 1.08459238e-01+0.j,
        6.07517096e-01+0.j, 2.40534348e-01+0.j, 2.55052061e-01+0.j,
        6.78548097e-01+0.j, 1.12543531e-01+0.j, 4.58315338e-01+0.j,
        5.37416505e-01+0.j, 1.03650403e-01+0.j, 5.97796042e-01+0.j,
        3.02900518e-01+0.j, 2.02901377e-01+0.j, 5.62931688e-01+0.j,
        1.28559898e-01+0.j, 3.49755444e-01+0.j, 3.89790782e-01+0.j,
        4.73802625e-02+0.j, 4.17700667e-01+0.j, 2.10948454e-01+0.j,
        4.23325182e-02+0.j, 3.52775955e-01+0.j, 1.00413292e-01+0.j,
        8.37597980e-02+0.j, 2.35655365e-01+0.j, 4.56616145e-02+0.j,
        1.13754136e-01+0.j, 1.60831464e-01+0.j, 2.40298341e-02+0.j,
        1.17206030e-01+0.j, 1.54587942e-01+0.j, 1.43523690e-02+0.j,
        1.33882551e-01+0.j, 1.99871371e-01+0.j, 4.23252882e-03+0.j,
        2.03278674e-01+0.j, 2.43212358e-01+0.j, 1.64454754e-02+0.j,
        3.55381353e-01+0.j, 2.20077896e-01+0.j, 8.04379910e-02+0.j,
        5.56333364e-01+0.j, 1.39182946e-01+0.j, 2.27584593e-01+0.j,
        6.50928359e-01+0.j, 7.21879762e-02+0.j, 5.03875229e-01+0.j,
        5.33488689e-01+0.j, 6.76542041e-02+0.j, 8.33868561e-01+0.j,
        3.08492362e-01+0.j, 1.52587505e-01+0.j, 9.57503355e-01+0.j,
        1.34999025e-01+0.j, 3.61271786e-01+0.j, 7.52225661e-01+0.j,
        5.53907804e-02+0.j, 6.24641090e-01+0.j, 4.20634456e-01+0.j,
        4.87936190e-02+0.j, 7.29634035e-01+0.j, 1.83836578e-01+0.j,
        1.10824917e-01+0.j])]

**Comment by nonhermitian** [comment]
As the docs specify, just dont pass any expectation operators, and the states are in the 'results.states' attribute
