### ISSUE TITLE
expect() function ,(TypeError: Arguments must be quantum objects or eseries

### ISSUE THREAD

**Issue by questionmarkmark** [qutip/qutip#805]
I am trying to calculate the expectation value of Mx. It is the order parameter of a hamiltonian, and I want to calculate the phase transition of it later on. I used commend expect(Mx, H.groundstate() while I have input a hamiltonian.

Here is the code and I have error as the following:

----------------------------------------
H.groundstate()

Out[193]:
(-21.1393191156312,
 Quantum object: dims = [[2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], shape = (1024, 1), type = ket
 Qobj data =
 [[-0.00980414]
  [ 0.01225526]
  [ 0.01570169]
  ...
  [ 0.01570169]
  [ 0.01225526]
  [-0.00980414]])

**## expect(Mx, H.groundstate())**

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-194-8e60f2d2c48d> in <module>()
----> 1 expect(Mx, H.groundstate())

/Users/lib/python2.7/site-packages/qutip/expect.pyc in expect(oper, state)
     95                             dtype=complex)
     96     else:
---> 97         raise TypeError('Arguments must be quantum objects or eseries')
     98 
     99 

**TypeError: Arguments must be quantum objects or eseries**

**Comment by nonhermitian** [comment]
You should really read the documentation.  It will address all the issues you have posted.

**Comment by questionmarkmark** [comment]
I have read over the documentation, and I did not see why  H.groundstate() is not a  quantum objects or eseries...

**Comment by nonhermitian** [comment]
http://qutip.org/docs/latest/apidoc/classes.html?highlight=groundstate#qutip.Qobj.groundstate

**Comment by questionmarkmark** [comment]
I have read that, but as what the output from H.groundstate(), it is showing it's a quantum object. So I don't understand why the error occurs

**Comment by nonhermitian** [comment]
There are two return values, as indicated.  Ground state energy and ground state itself.

**Comment by questionmarkmark** [comment]
Thank you so much. I want extract only the ground state eigenvector part which is the just one of the return values. I did not find a way to do that, what will you recommend doing? Thanks a lot!

**Comment by nonhermitian** [comment]
H.groundstate()[1]
