### ISSUE TITLE
unusual behavior of  phase transition of magnetization of a transverse Ising model

### ISSUE THREAD

**Issue by questionmarkmark** [qutip/qutip#811]
I was trying to see the phase transition of magnetization of a transverse Ising model, and I have the following graph. The magnetization changes unusually rapidly under the change of magnetic field and, I don't have this problem using my own library. Since the code I wrote is extremely simple and there is no error message, I wonder do you possibly have encountered the similar issues and have some suggestions on what it happens.

Here is the code, and the graph.

----------------------------------------------------------
harray = np.zeros(11)
for i in range(11):
        harray[i] = 0.0001 * i
    
#print harray
        
marray4 = np.zeros(11)

Mx = tensor(sigmaz(),identity(2),identity(2),identity(2))\
    + tensor(identity(2),sigmaz(),identity(2),identity(2))\
    + tensor(identity(2),identity(2),sigmaz(),identity(2))\
    + tensor(identity(2),identity(2),identity(2),sigmaz())

earray4 = np.zeros(11)
  
for ii in range(0, 11):
    
    H = -(tensor(sigmaz(),sigmaz(),identity(2),identity(2)) \
        + tensor(identity(2),sigmaz(),sigmaz(),identity(2)) \
        + tensor(identity(2),identity(2),sigmaz(),sigmaz()) \
        + tensor(sigmaz(),identity(2),identity(2),sigmaz())) \
        - harray[ii]*(tensor(sigmax(),identity(2),identity(2),identity(2))\
        + tensor(identity(2),sigmax(),identity(2),identity(2))\
        + tensor(identity(2),identity(2),sigmax(),identity(2))\
        + tensor(identity(2),identity(2),identity(2),sigmax()))
        

    marray4[ii] = expect(Mx, H.eigenstates()[1][0])
    
plt.plot(harray, marray4, 'o-')
plt.show()

![screen shot 2018-02-05 at 11 59 45 am](https://user-images.githubusercontent.com/35711575/35817669-17d7afe2-0a6c-11e8-859f-6ae1d686a7fe.png)

**Comment by nonhermitian** [comment]
Please do not raise issues when asking for help.  Please go to the QuTiP help group.

http://groups.google.com/group/qutip

**Comment by questionmarkmark** [comment]
Thanks. I did just now.
