### ISSUE TITLE
mesolve wrong results without collapse ops

### ISSUE THREAD

**Issue by shiMusa** [qutip/qutip#813]
Hi all,

I have a simple toy model of a 2-dim Hamiltonian. When I use
`mesolve(H, c_states[prepare], t, [Qobj([[0,0],[0,0]])], args={'tau': tau})`
I get the right result - however, if I try
`mesolve(H, c_states[prepare], t, [], args={'tau': tau})` or
`mesolve(H, c_states[prepare], t, c_ops=[], args={'tau': tau})`
the result is most definitely wrong.

Any ideas?

**Comment by nonhermitian** [comment]
You may want to give a more complete example.

**Comment by shiMusa** [comment]
Ok, my mistake. I thought mesolve would return density matrices, but it returned states...
My bad, sorry.

**Comment by nonhermitian** [comment]
It reverts to the sesolve function for no collapse.
