### ISSUE TITLE
Defining the Mølmer–Sørensen gate

### ISSUE THREAD

**Issue by omarshehab** [qutip/qutip#819]
I know the mathematical definition of the Mølmer–Sørensen gate. How can I define it as a gate in qutip to use in a circuit? Thanks.

**Comment by IIAOPSW** [comment]
I looked up Mølmer–Sørensen but I'm unsure of the definition.  

The definition on the wikipedia article must be wrong because it is not unitary.  

Anyway you should be able to define it exactly the same as all the other gates are defined in qip/gates.py. I've copied and pasted the definition of CNOT. Just change the matrix and function name to fit your usecase.  

def cnot(N=None, control=0, target=1):
    if (control == 1 and target == 0) and N is None:
        N = 2

    if N is not None:
        return gate_expand_2toN(cnot(), N, control, target)
    else:
        return Qobj([[1, 0, 0, 0],
                     [0, 1, 0, 0],
                     [0, 0, 0, 1],
                     [0, 0, 1, 0]],
                    dims=[[2, 2], [2, 2]])

**Comment by ajgpitch** [comment]
@sahmed95 Can a user defined gate be used in the qutip QIP?

**Comment by omarshehab** [comment]
@IIAOPSW : Thanks for the suggestion. I will try that. Nevertheless, it would be nice to have it in the official version of qutip.

You can use the following definition from Maslov, Dmitri, and Yunseong Nam. "Use of global interactions in efficient quantum circuit constructions." New Journal of Physics (2017).

![image](https://user-images.githubusercontent.com/4205827/36633263-2beff2a2-1960-11e8-83cd-2df60fb8e4da.png)

If I may, I would also suggest to add single qubit arbitrary rotation.

![image](https://user-images.githubusercontent.com/4205827/36633286-9c05c65c-1960-11e8-91f7-32c0990eee81.png)

In that case we will be able to write complete physical representation of any quantum circuit for trapped ion quantum computer.

**Comment by nathanshammah** [comment]
This is a good, apparently simple issue to address within the upcoming GSOC project on `qip`.

**Comment by nathanshammah** [comment]
This might be of interest in the future months to you @BoxiLi.

**Comment by BoxiLi** [comment]
This sounds good, I'll work on it.

**Comment by nathanshammah** [comment]
Cc @BoxiLi @quantshah.
