### ISSUE TITLE
enr_fock is broken

### ISSUE THREAD

**Issue by yanayyar** [qutip/qutip#820]
enr_fock is incompatible with enr_destroy.

Minimal code:
```
x = enr_destroy([3,3],2)
y = enr_fock([3,3],2,[1,1])
x[0]*y
```
returns an error.

I believe the problem is that the problem is that y has dim = [[3, 3], 1] instead of dim = [[3, 3], [1,1]].

**Comment by ajgpitch** [comment]
I am still trying to understand the error:
Perhaps the pending notebook
https://github.com/qutip/qutip-notebooks/pull/51
could help you

**Comment by yanayyar** [comment]
As I said, I think this is about the dims property. If you try,
```
x = enr_destroy([3,3],2)
z = x[0].eigenstates()[1][0]
y = enr_fock([3,3],2,[1,1])
print(z.dims)
print(y.dims)
```
you see they are incompatible:
```
[[3, 3], [1, 1]]
[[3, 3], 1]
```

Meanwhile, if you adjust dims, the multiplication works out ok:
```
y.dims[1] = [1,1]
x[0]*y
```
yields the correct result.

**Comment by IIAOPSW** [comment]
yanayyar is right. I fixed it in my branch.

**Comment by ajgpitch** [comment]
@IIAOPSW this does seem like a sensible fix. Can you create a branch and raise a PR with the fix. Call the branch something descriptive like 'fix_enr_fock_dims'. Thanks

**Comment by ajgpitch** [comment]
@IIAOPSW are you going to do the fix PR for this?

**Comment by IIAOPSW** [comment]
@ajgpitch yeah I'm on it!

**Comment by IIAOPSW** [comment]
done 
https://github.com/qutip/qutip/pull/837
