### ISSUE TITLE
Qutip on Microsoft Windows

### ISSUE THREAD

**Issue by Bilal092** [qutip/qutip#826]
I am using Anaconda on windows 10 and installed qutip from conda-forge package, I don't  have VS-15 on my system, Is it possible that that I could run qutip with VS-15 runtime liberaries instead of complete installation of visual studio. If it is possible please guide me.

**Comment by sahmed95** [comment]
Hi, if you look at the conda instructions for VS, you will find some alternatives 
https://conda.io/docs/user-guide/tutorials/build-windows.html

There is a VS community edition which might be smaller. 

Alternatively, on Windows 10, you can install a Linux subsystem (supported officially by Windows) and then I am hoping that you don't need to deal with a complete VS installation. Please find the instructions to get a native Linux subsystem in Windows 10 below:
https://docs.microsoft.com/en-us/windows/wsl/install-win10

Let me know if you need any help or encounter issues.

**Comment by Bilal092** [comment]
Thanks for suggesting Linux subsystem, but it is not good enough to run simulations, it is slower for even day to day file manipulations, so from your comment and documentation you shared I come to conclusion that there is no alternative of VS to run Qutip in windows 10.

**Comment by ajgpitch** [comment]
Hi Bilal,

The conda-forge qutip package should install without VS-15. Most of qutip
functions should still work. This was certainly the intention when we
worked on it. I can't remember now though how well we tested without VS-15,
as the main focus was getting it to work with VS-15.

The string type time-dependence needs a C++ compiler, so those functions
won't work.  This means a lot of tests will fail.

So, give it a go and let us know how you get on.

Alex

**Comment by ajgpitch** [comment]
I have asked some of the team if they can check into this too. That's why I reopened.

**Comment by Bilal092** [comment]
Actually I used conda forge channel for installation of qutip, after that I ran following jupyter notebook notebook [http://nbviewer.jupyter.org/github/qutip/qutip-notebooks/blob/master/examples/control-grape-cnot.ipynb]

**Comment by Bilal092** [comment]
I installed using  conda-forge channel and installation worked without any problems, but when i run following jupyter notebook from example code on documentation: (http://nbviewer.jupyter.org/github/qutip/qutip-notebooks/blob/master/examples/control-grape-cnot.ipynb) 
it gives following error
![grape](https://user-images.githubusercontent.com/34689025/36730450-652e8d18-1c02-11e8-83a8-8741d69f24d6.JPG)

**Comment by ajgpitch** [comment]
What happens if you try one of the control pulseoptim notebooks? e.g.:
http://nbviewer.jupyter.org/github/qutip/qutip-notebooks/blob/master/examples/control-pulseoptim-QFT.ipynb

They do not have any cython components.

**Comment by Bilal092** [comment]
This code works fine, without any problems on my machine.

**Comment by ajgpitch** [comment]
Ok, that's good news. Thanks for trying. Hopefully you can do what you want with the pulseoptim functions?

I guess the grape-cnot notebook must use some runtime compile components. If you want to use those, then you will need the VS-15 compiler.

**Comment by waseemrehar** [comment]
> I am using Anaconda on windows 10 and installed qutip from conda-forge package, I don't have VS-15 on my system, Is it possible that that I could run qutip with VS-15 runtime liberaries instead of complete installation of visual studio. If it is possible please guide me.

Dear Bilal I am quite new to use python and qutip.... some how i am not able installed qutip from conda-forge package on window 10..... can you please let us know the step wise installation. (waseem)

**Comment by Bilal092** [comment]
I installed visual studio 2015 from https://visualstudio.microsoft.com/vs/older-downloads/ , after that I simply followed instructions of qutip documentation.
