### ISSUE TITLE
Bloch sphere animation error

### ISSUE THREAD

**Issue by laserroger** [qutip/qutip#836]
When I follow the example to generate animation for bloch sphere plotting, i.e., page 120-122 from [this doc](http://qutip.org/downloads/4.2.0/QuTiP_4.2.pdf), I faced 
`'Axes3D' object is not iterable`
problem, which happens for the `save` function

> .../matplotlib/animation.py in save(self, filename, writer, fps, dpi, codec, bitrate, extra_args, metadata, extra_anim, savefig_kwargs)
   1192                 for anim in all_anim:
   1193                     # Clear the initial frame
-> 1194                     anim._init_draw()
   1195                 for data in zip(*[a.new_saved_frame_seq() for a in all_anim]):
   1196                     for anim, d in zip(all_anim, data):

> .../matplotlib/animation.py in _init_draw(self)
   1755                     raise RuntimeError('The init_func must return a '
   1756                                        'sequence of Artist objects.')
-> 1757                 for a in self._drawn_artists:
   1758                     a.set_animated(self._blit)
   1759         self._save_seq = []

>TypeError: 'Axes3D' object is not iterable

My environment:

QuTiP: Quantum Toolbox in Python
Copyright (c) 2011 and later.
A. J. Pitchford, P. D. Nation, R. J. Johansson, A. Grimsmo, and C. Granade

QuTiP Version:      4.2.0
Numpy Version:      1.14.1
Scipy Version:      1.0.0
Cython Version:     0.27.3
Matplotlib Version: 2.2.0
Python Version:     3.5.2
Number of CPUs:     2
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Darwin (x86_64)

**Comment by TheIdealis** [comment]
Someone asked this question on [stackexchange](https://stackoverflow.com/questions/42178706/python-animation-funcanimation-error-object-is-not-iterable). You just have to set `blit=False` in the `FuncAnimation` call.

**Comment by laserroger** [comment]
@TheIdealis thank you, this solves the problem.
