### ISSUE TITLE
Python in windows, AttributeError: module 'qutip' has no attribute 'states'

### ISSUE THREAD

**Issue by tom9358** [qutip/qutip#839]
Hello everyone, I tried to install qutip via pip on windows 10. I got an error stating that building the wheel failed because I didn't have Virtual Studio. I don't want to install that, so I just downloaded the wheel from this site: https://www.lfd.uci.edu/~gohlke/pythonlibs/#qutip
It installed fine, I thought.

If I start a python interpreter in the command line, I can import qutip, and its functions work fine as far as I can tell.

Now the problem: when I try to run a .py script, I get the error `AttributeError: module 'qutip' has no attribute 'states'`.

So for some reason, python can't always locate the package correctly. Other packages work fine though. Does anyone know how to solve this?

**Comment by tom9358** [comment]
Nevermind, I'm such a dumbass! I named my .py file "qutip.py". Huge facepalm.

**Comment by ajgpitch** [comment]
glad you worked that out yourself. Could have been a fun one :)
