### ISSUE TITLE
Sesolve and essolve when using intitial state vector

### ISSUE THREAD

**Issue by ComplexTranspose** [qutip/qutip#841]
There seems to be a bug when trying to solve the Schrödinger equation with the sesolve and essolve functions using an initial state vector. The following code reproduces the error:
```python
### import dependencies
%matplotlib inline
from qutip import *
import numpy as np
import matplotlib.pyplot as plt

### define spin operators at each site 
N = 3 # Number of spins
def sz(i):
    if i==N:
        i=0
    l = [qeye(2) for j in range(0,i)] + [sigmaz()] + [qeye(2) for j in range(i+1,N)]
    return tensor(l)
def sp(i):
    if i==N:
        i=0
    l = [qeye(2) for j in range(0,i)] + [sigmap()] + [qeye(2) for j in range(i+1,N)]
    return tensor(l)
def sm(i):
    if i==N:
        i=0
    l = [qeye(2) for j in range(0,i)] + [sigmam()] + [qeye(2) for j in range(i+1,N)]
    return tensor(l)

### Hamiltonian with on-site field and XX-type coupling between spins 0&1 and spins 0&2
delta = 1
V1 = 0.1
V2 = 0.1 
H0 = -0.5*delta*(sz(0) + sz(1) + sz(2)) + V1*(sp(0)*sm(1) + sm(0)*sp(1)) + V2*(sp(0)*sm(2) + sm(0)*sp(2))       

### no collapse operaters; e_op is total magnetization in z-direction 
c_ops = []
e_ops = [sz(0)+sz(1)+sz(2)]

### initial state: each spin polarized in x-y-plane
psi0 = tensor([(basis(2,0) + (1j)**i *basis(2,1)).unit() for i in range(0,N)])
rho0 = psi0*psi0.dag()

### compute time evolution with different solvers
t_list = np.linspace(0, 50, 500)
output0 = mesolve(H0, rho0, t_list, c_ops, e_ops)
output1 = essolve(H0, rho0, t_list, c_ops, e_ops)
output2 = sesolve(H0, psi0, t_list, e_ops)

### plot result
plt.plot(t_list, output0.expect[0], label='mesolve')
plt.plot(t_list, output1.expect[0], label='essolve')
plt.plot(t_list, output2.expect[0], label='sesolve')
plt.legend()

### time evolution with essolve, use state vector --> Exception raised
output3 = essolve(H0, psi0, t_list, c_ops, e_ops)
plt.plot(t_list, output0.expect[0], label='essolve, state vector')
plt.legend()
```
The Hamiltonian commutes with the operator for which the expectation value is computed as is easily checked. Therefore the expectation value should be time-independent. Using sesolve one obtains a wrong result. There seems to be an error when using state vectors instead of density matrices, as is seen by using the mesolve function instead. 

I was not able to pinpoint the error in the code, but I checked the result with essolve and using an initial state vector. This raises an exception: 
> Exception: Operator and state do not have same tensor structure: [2, 2, 2] and [2]

essolve works as intended by using a density matrix instead, which should again indicate that there is some bug when using state vectors.

Note however that the essolve bug might not be directly related to the sesolve bug, since essolve seems to work correctly when using a different initial state:
`psi0 = tensor([(basis(2,0) + 0.5*(-1j)**i *basis(2,1)).unit() for i in range(0,N)])`

I am using the newest versions of the necessary libraries: 

> QuTiP Version:      4.2.0
> Numpy Version:      1.11.3
> Scipy Version:      1.0.0
> Cython Version:     0.27.3
> Matplotlib Version: 2.0.2
> Python Version:     3.6.4
> Number of CPUs:     4
> BLAS Info:          OPENBLAS
> OPENMP Installed:   False
> INTEL MKL Ext:      False
> Platform Info:      Linux (x86_64)

**Comment by Ericgig** [comment]
No longer relevant with v5.
`essolve` was removed.
`sesolve` still has a small drift due to numerical error, but easily solver by changing `rtol` and `atol`.
