### ISSUE TITLE
ptrace MemoryError

### ISSUE THREAD

**Issue by quser40** [qutip/qutip#842]
I get a MemoryError computing a ptrace, although the output object would be smaller than the input object.

Minimum working example:
`tensor(fock(2,0), fock(100,0), fock(100,0)).ptrace(0)
`

The problem might be that internally the full density matrix is created before summation. This requires more RAM than is eventually available. Mathematically the operation should be possible without excessive RAM usage, as long as the input, as in this case, is a pure state vector.

(related to [issue #828](https://github.com/qutip/qutip/issues/828 ) but not the same.)

**Comment by nonhermitian** [comment]
I have a better version in the works.  Should be done in the next day or two.

**Comment by jakelishman** [comment]
Fixed by #970.
