### ISSUE TITLE
Propagator "batch" mode: fail to modify the options for ODE solver

### ISSUE THREAD

**Issue by kobe88885** [qutip/qutip#843]
I noticed that while operating in the batch mode of function propagator, it is not possible to use a user-defined options for the ODE solver. After inspecting the source code of propagator, I noticed that the options variable is redefined by the sentence "options=Options(normalize_output=False))" inside the function at line 183. I think it means that whatever options we input to the function, it will be restored to the default options because of this sentence.

**Comment by nathanshammah** [comment]
Seems taken care of by now. Re-open if not.
