### ISSUE TITLE
Adding a seed option to random Qobj generators

### ISSUE THREAD

**Issue by BassemSafieldeen** [qutip/qutip#856]
It would useful to have the option of generating a random Qobj (like rand_unitary) using a [seed](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.random.RandomState.html#numpy.random.RandomState), so that one is able to vary other parameters in the code and see the effect for a specific random Qobj.

**Comment by nonhermitian** [comment]
This is probably a good idea.  Feel free to make a Pull request
implementing this.

-Paul

**Comment by marekyggdrasil** [comment]
I think this is a great idea. It makes results of an experiment easily reproducible and there is no need to log literally all data, all we need to keep is the initial seed.

**Comment by marekyggdrasil** [comment]
I believe the pull request is ready to be merged.
