### ISSUE TITLE
mesolve and sesolve tidy up

### ISSUE THREAD

**Issue by ajgpitch** [qutip/qutip#867]
I have been spending quite a bit of time in sesolve.py and mesolve.py recently. I have noticed a few things that could potentially be tidied up.

1. There are deprecated functions for `list` type time dependence. Can these be deleted now.
2. The order of the internal functions is slightly different. Confuses me a lot. Suggest changing both to (as this seems like some kind of valid hierarchy):
- const
- func
- list_func
- list_str
- generic_ode

3. The parameters in the ode func are `L_list_and_args` in sesolve and `L_list, args` in mesolve. I can't see any reason for the difference.
4. The ode functions (for const and list_func) could be considered internal. Should they have a leading underscore?

**Comment by ajgpitch** [comment]
Sorry if this seems like Nero fiddling while Rome burns. Just recording this as a todo mainly.
I will try to look at the bigger issues very soon

**Comment by nathanshammah** [comment]
Checking if this got already solved by @Ericgig refactoring of stochastic solvers and `sesolve`.

**Comment by jakelishman** [comment]
Everything mentioned in this PR looks solved with the merging of `QobjEvo`, and a few other bits and bobs changes to `sesolve` and `mesolve`.  At any rate, anything that _isn't_ covered is obsoleted by #1461 and #1462 (and one further PR based on #1409).
