### ISSUE TITLE
qutip to drop support for Python 2.7

### ISSUE THREAD

**Issue by ajgpitch** [qutip/qutip#882]
We are planning to drop support for Python 2.7 in qutip version 5
Hence the next version, 4.3, will be the last support Python 2.7.

There are many reasons for this. 
It is is in line with what Numpy are planning as well, which is one of the main ones.

Please feel free to discuss here.

**Comment by hugovk** [comment]
👍 

By the way, here's the pip installs for qutip from PyPI for June 2018, showing Python 2.7 is already dropping off:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 3.6            |  51.53% |            118 |
| 2.7            |  33.19% |             76 |
| 3.5            |  13.97% |             32 |
| 3.4            |   0.87% |              2 |
| 3.7            |   0.44% |              1 |
| Total          |         |            229 |

Source: `pypinfo --start-date 2018-06-01 --end-date 2018-06-30 --percent --markdown qutip pyversion`

**Comment by nathanshammah** [comment]
Version 4.4.1 does not support Python 2 any more.
