### ISSUE TITLE
Time local and time convultion master equation

### ISSUE THREAD

**Issue by gharib85** [qutip/qutip#887]
I wish if qutip 
Could Handel memory kernel In master equation 
,A trial have been done in python 
https://www.google.com.eg/url?sa=t&source=web&rct=j&url=https://www.duo.uio.no/bitstream/handle/10852/37168/MasterMuslandLars.pdf%3Fsequence%3D1&ved=2ahUKEwiU-NyAvP_bAhXMY1AKHWGtAWoQFjAAegQIAhAB&usg=AOvVaw1lG1Ir8R7dzvmdwBMMCjUV
But importing memory equation was unclear and incomplete

**Comment by nathanshammah** [comment]
There is ongoing development for the hierarchy equation of motion.

**Comment by nathanshammah** [comment]
Please contribute with a pull request or provide more information if you think that someone else might do it.

**Comment by gharib85** [comment]
https://arxiv.org/abs/1904.06982

**Comment by gharib85** [comment]
https://github.com/berkelbach-group/pyrho/blob/master/redfield/redfield.py

**Comment by gharib85** [comment]
https://github.com/berkelbach-group/pyrho/blob/master/integrate/integrate.py
