### ISSUE TITLE
TypeError: Incompatible Qobj shapes with tensor product

### ISSUE THREAD

**Issue by AbdallaEssamAli** [qutip/qutip#888]
I am trying to perform this simple operation <a href="https://www.codecogs.com/eqnedit.php?latex=(H^{\otimes&space;2}&space;\otimes&space;I^{\otimes&space;2}&space;)&space;\times&space;\psi" target="_blank"><img src="https://latex.codecogs.com/gif.latex?(H^{\otimes&space;2}&space;\otimes&space;I^{\otimes&space;2}&space;)&space;\times&space;\psi" title="(H^{\otimes 2} \otimes I^{\otimes 2} ) \times \psi" /></a>
where 
<a href="https://www.codecogs.com/eqnedit.php?latex=H&space;=&space;\frac{1}{\sqrt{2}}&space;\times&space;\begin{bmatrix}&space;1&space;&&space;1\\&space;1&space;&&space;-1&space;\end{bmatrix}&space;,&space;I&space;=&space;\begin{bmatrix}&space;1&space;&&space;0&space;\\&space;0&space;&&space;1&space;\end{bmatrix}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?H&space;=&space;\frac{1}{\sqrt{2}}&space;\times&space;\begin{bmatrix}&space;1&space;&&space;1\\&space;1&space;&&space;-1&space;\end{bmatrix}&space;,&space;I&space;=&space;\begin{bmatrix}&space;1&space;&&space;0&space;\\&space;0&space;&&space;1&space;\end{bmatrix}" title="H = \frac{1}{\sqrt{2}} \times \begin{bmatrix} 1 & 1\\ 1 & -1 \end{bmatrix} , I = \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}" /></a>
and 
<a href="https://www.codecogs.com/eqnedit.php?latex=\psi&space;=&space;\left|0\right\rangle^{\otimes&space;4}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\psi&space;=&space;\left|0\right\rangle^{\otimes&space;4}" title="\psi = \left|0\right\rangle^{\otimes 4}" /></a>
I do that as follow: 
```python
tensor(hadamard_transform(1), hadamard_transform(1), identity(2), identity(2)) * basis(16,1)
```
and i got the following : 

```python
tensor(hadamard_transform(1), hadamard_transform(1), identity(2), identity(2)) * basis(16,1)
Traceback (most recent call last):

  File "<ipython-input-160-ae66af2f799c>", line 1, in <module>
    tensor(hadamard_transform(1), hadamard_transform(1), identity(2), identity(2)) * basis(16,1)

  File "/home/user/anaconda2/envs/Quantum/lib/python2.7/site-packages/qutip/qobj.py", line 515, in __mul__
    raise TypeError("Incompatible Qobj shapes")

TypeError: Incompatible Qobj shap
```

but when i do each part separately as follow I notice that the shapes are compatible:
```python
tensor(hadamard_transform(1), hadamard_transform(1), identity(2), identity(2))
Out[161]: 
Quantum object: dims = [[2, 2, 2, 2], [2, 2, 2, 2]], shape = (16, 16), type = oper, isherm = True
```
```python
basis(16,1)
Out[162]: 
Quantum object: dims = [[16], [1]], shape = (16, 1), type = ket
Qobj data =
```
The first has shape = (16, 16) and the second has shape = (16, 1), there shouldn't be any problems in performing matrix multiplication.
**Why I got this error and how to solve it.**

My environment is as follow:
```
~$ conda info

     active environment : Quantum
    active env location : /home/user/anaconda2/envs/Quantum
            shell level : 1
       user config file : /home/user/.condarc
 populated config files : /home/user/.condarc
          conda version : 4.5.4
    conda-build version : 3.10.5
         python version : 2.7.15.final.0
       base environment : /home/user/anaconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/user/anaconda2/pkgs
                          /home/user/.conda/pkgs
       envs directories : /home/user/anaconda2/envs
                          /home/user/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/2.7.15 Linux/3.13.0-141-generic ubuntu/14.04 glibc/2.19
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```

```
>>> from qutip import *
>>> about()

QuTiP: Quantum Toolbox in Python
Copyright (c) 2011 and later.
A. J. Pitchford, P. D. Nation, R. J. Johansson, A. Grimsmo, and C. Granade

QuTiP Version:      4.2.0
Numpy Version:      1.13.3
Scipy Version:      1.1.0
Cython Version:     0.28.3
Matplotlib Version: 2.2.2
Python Version:     2.7.15
Number of CPUs:     2
BLAS Info:          INTEL MKL
OPENMP Installed:   False
INTEL MKL Ext:      True
Platform Info:      Linux (x86_64)
Installation path:  /home/user/anaconda2/envs/Quantum/lib/python2.7/site-packages/qutip

```

**Comment by IIAOPSW** [comment]
It is giving an error because your operator and your state are in two different spaces. 

tensor(hadamard_transform(1), hadamard_transform(1), identity(2), identity(2))  is 4 single qubit operators acting on 4 single qubit subsystems.  

basis(16, 1) is a single quantum object with 16 distinguishable states and no subsystems. You cannot make a single qubit operators act on this object (since it is not a qubit) and there are no subspaces for the remaining 3 operators to act on.  

The state that you actually want (a system of 4 qubit subsystems) can be constructed as 
tensor(basis(2),basis(2),basis(2),basis(2))


Try this
>>> tensor(hadamard_transform(1), hadamard_transform(1), identity(2), identity(2)) * tensor(basis(2),basis(2),basis(2),basis(2))

Or for clarity
>>> H = hadamard_transform(1)
>>> I = identity(2)
>>> ket0 = basis(2)
>>> HHII = tensor(H,H,I,I)
>>> psi = tensor(ket0, ket0, ket0, ket0)
>>> HHII * psi

Hope this helps.
