### ISSUE TITLE
matplotlib is missing from requirements in setup.py

### ISSUE THREAD

**Issue by yurivict** [qutip/qutip#892]

**Comment by sahmed95** [comment]
Yes, that is to keep the installation light. Matplolib is surely used for the visualization but most runtime modules can do without it.

**Comment by yurivict** [comment]
> Matplolib is surely used for the visualization but most runtime modules can do without it.

There is syntax for optional dependencies in ```setup.py```, you should consider using it.

**Comment by nathanshammah** [comment]
Closing as it is addressed by @abhisekupadhyaya PR #967.
