### ISSUE TITLE
INSTALL_REQUIRES cython?

### ISSUE THREAD

**Issue by yurivict** [qutip/qutip#893]
Normally, cython shouldn't be required in the run time.

**Comment by sahmed95** [comment]
I think there are some optimized Cython routines which for some of the solvers which need cython in run-time. Not completely sure about it. Let me check.

**Comment by yurivict** [comment]
Once built, binaries aren't linked with anything related to cython.

**Comment by ajgpitch** [comment]
The string type time-dependent solvers generate pyx files and compile them in runtime. Much of qutip will run without Cython. But not the string type time-dependent solvers, which are one of the main features of qutip.
@yurivict you could try removing Cython from your Python env and then run the tests - see how many fail

**Comment by yurivict** [comment]
Ok, thanks. I believe you. -)
