### ISSUE TITLE
sdist does not copy .pyx files after MANIFEST.in is included

### ISSUE THREAD

**Issue by sahmed95** [qutip/qutip#894]
I am generating a new source distribution and run into an issue of copying the .pyx files. For all the files in `qutip.cy` we want both the `.cpp` files and `.pyx` files to be copied in the source. But currently only the `.cpp` files are being copied. 

Did we face this issue before? I think the addition of the `MANIFEST.in` file in 4.3 overrides the package_include that setup uses.

This issue https://github.com/statsmodels/statsmodels/issues/1606/ seems to suggest that they should be added the MANIFEST.in file. 

@ajgpitch @Ericgig @nonhermitian

**Comment by sahmed95** [comment]
Numpy seems to add it this way - https://github.com/numpy/numpy/blob/master/MANIFEST.in

If it is okay then I can change the MANIFEST files and continue the 4.3 release.

**Comment by ajgpitch** [comment]
I did come across this before. You might find an old qutip issue on the
same.
But if it works for numpy, then good enough for us

**Comment by sahmed95** [comment]
Resolved.
