### ISSUE TITLE
mesolve seems to give inconsistent results with and without dissipation (which mcsolve does not reproduce)

### ISSUE THREAD

**Issue by OliverLunt** [qutip/qutip#898]
(Apologies: this is a repost from the QuTiP Google group, but since this seems to be a possible bug with mesolve, I figured it was more appropriate to post it here. See the Google post [here](https://groups.google.com/forum/#!topic/qutip/KKqHcZxiAmg) for some images documenting this issue.)

Hello,

I'm trying to simulate a system of qubits with a two-pulse periodic Hamiltonian and some dissipation using QuTiP's mesolve function. As a consistency check, I compared the results of setting c_ops = [], and setting c_ops as the zero matrix. These should give the same results, yet for certain basis states, setting c_ops as the zero matrix seems to give the wrong result.

Here is a minimum working example that reproduces the effect:

```
import numpy as np
from qutip import sigmax, sigmaz, mesolve, basis
from scipy import signal, optimize

### Function definitions

def on_off_signal(t):
 """
 Generate a periodic signal that is +1 for half a period and 0 for the other half.
 """

 return (1 + signal.square(2 * np.pi * t))/2

def off_on_signal(t):
 """
 Generate a periodic signal that is 0 for half a period and +1 for the other half.
 """

 return (1 - signal.square(2 * np.pi * t))/2


### Define Hamiltonian

H1 = sigmaz()
H2 = np.pi * sigmax() # H2 applied for time 0.5 results in a full spin flip
H = [[H1, on_off_signal],
     [H2, off_on_signal]]


### Start in a Z basis state

psi0 = basis(2,0)


### Set the collapse operator as the zero matrix (since 1/T_dephasing = 0)

T_dephasing = np.inf
c_ops = (1/T_dephasing) * sigmaz()


### Run simulation

tlist = np.linspace(0, 2, 10000)
e_ops = [sigmaz()]
output = mesolve(H, psi0, tlist, c_ops = c_ops, e_ops = e_ops)
Z_expectation = output.expect[0]
```

### Notes on system:

- The Hamiltonian is periodic and formed of two-pulses.
- H2 applies a full spin flip when applied for time 0.5, so if we start in a Z basis state then Z_expectation should change from +1 to -1 or vice versa.

### Problem:

- When I set c_ops = [], I get the expected behaviour of Z_expectation.
- When I set c_ops to be the zero matrix as in the code above, Z_expectation remains constant, even though this should give exactly the same result as setting c_ops = [].
- This effect seems to depend on the choice of initial state. For a random pure state, setting c_ops to be the zero matrix seems to give the correct result, but for a Z basis state I get the inconsistency.
- This effect is not reproduced by the Monte Carlo based solver, mcsolve. However, I would like to use mesolve if possible because it is much faster for the systems I am considering.

### Some further notes:

- I think this is something to do with the fact that the Hamiltonian is time-dependent. 
    - If I just simulate H2, then Z_expectation oscillates as expected. 
    - Additionally, if I swap the order of H1 and H2 in the Hamiltonian, then I get the correct result.
- Setting c_ops as the zero matrix results in a much quicker simulation time than setting c_ops = []. This seems somewhat counter-intuitive, since I thought setting c_ops as the zero matrix would force the program to simulate the evolution of the density matrix rather than the state vector.
    - Given this, I wonder if mesolve is making an approximation to speed up the calculation which is not valid here.

I would very much appreciate any insights into where this inconsistency comes from, and how to fix it. Since mcsolve does not reproduce it, I think this might be an issue with mesolve.

Many thanks,

Oliver

**Comment by sahmed95** [comment]
Thanks for opening this issue @OliverLunt. It sure looks like some bug that should definitely be resolved. I would like to take a look as soon as I can and discuss how to fix this.

@IIAOPSW can also help perhaps.

**Comment by Ericgig** [comment]
@OliverLunt, 
The problem lies in the adaptative step of the ode solver. Since nothing happen at first, the step become so long that it jump over the change in the on_off signal...
You can do:
```
opt = qt.Options()
opt.max_step = 0.5
output = mesolve(H, psi0, tlist, c_ops=c_ops, e_ops=e_ops, options=opt)
```
To limit the step size and it will work as expected. 

I am not sure why sesolve (used when no c_ops are given) have smaller step size. It seems to be something in the scipy solver.
