### ISSUE TITLE
Numpy requirements too low for v4.3

### ISSUE THREAD

**Issue by ajgpitch** [qutip/qutip#905]
The version requirements need increasing.

This was posted on the help group.
Please update the requirements, for the new features (PIQS and photon scattering) to work Numpy = 1.12.0+ is required as numpy.flip() and numpy.geomspace are used.

**Comment by sahmed95** [comment]
I am on it. Does this mean we do a 4.3.2 micro release?

**Comment by ajgpitch** [comment]
I think a micro release would be the right thing to do.
We could wait a week and see if anything else get reported though

**Comment by piyushchauhan** [comment]
Is this issue still open? If open can I work on it?

**Comment by ajgpitch** [comment]
@piyushchauhan This is still open. 
However, any PR for this would conflict with #961. @agarwal1998 has not answered the questions on there though, so if you create a PR that solves #892 and this issue, then we will close #961
