### ISSUE TITLE
Cannot use mayavi for python version 3.6.5

### ISSUE THREAD

**Issue by akhil21** [qutip/qutip#908]
I am starting to use qutip and would like to draw 3D bloch spheres but cannot import Bloch3d() because of mayavi. I installe dmayavi from anaconda but now there;s some issue with "vtk"
My qutip version is - 4.2.0

**Comment by nathanshammah** [comment]
Did you sort this out?

**Comment by nathanshammah** [comment]
If you need more help for this, please ask in the help [group](https://groups.google.com/forum/#!forum/qutip).
