### ISSUE TITLE
QubitCircuit images

### ISSUE THREAD

**Issue by Wheest** [qutip/qutip#913]
I'm quite new to the package, so please forgive me if this is obvious.  Haven't been able to find anything in docs or previous issues. I'm looking to get images of quantum circuits saved.  My quirks of setup means that I'm not using notebooks.  Therefore the normal `qc.png` command isn't compatible. 

In `qutip/qip/circuit.py`, the properties `png()` and `svg()` directly display in a notebook the compiled LaTeX figure of the cicuit.  I would rather be able to access the compiled image directly.

I've been looking around the codebase to see if there is native functionality for this.  We can get Bloch spheres using the kind of workflow I'm imagining:

```
from qutip import *    

b = Bloch()

b.show()

bb = b.fig
bb.savefig('Bloch.png')
bb.savefig('Bloch.pdf')
```

Does anyone have any suggestions?  

I think that `_latex_compile()` returns a bytes object, which can be interpreted as an image, but I haven't had a chance to play around with it yet.

**Comment by nathanshammah** [comment]
Reference to #441.

**Comment by nathanshammah** [comment]
Dear @Wheest this is more a [help group](https://groups.google.com/forum/#!forum/qutip) question. 
In any case, @quantshah do you know the answer to this?
