### ISSUE TITLE
Eigenvalues of Hamiltonian

### ISSUE THREAD

**Issue by devendergarg14** [qutip/qutip#918]
How to find eigenvalues of Hamiltonian from eigenenergies( ) command.For Hamiltonian it gives error 'list' object has no attribute 'eigenenergies''
 I am using Hamiltonian 
H = wc * a.dag() * a + wm * bv.dag() * bv+ wv * bm.dag() * bm + g * (a.dag() * bv + bv.dag()* a)-g * (a.dag() * bm + bm .dag()*a) 
command is like    H.eigenenergies( )

**Comment by Ericgig** [comment]
The eigenenergies method is defined for Qobj. Try calling "type(H)", if you don't get "Qobj" then the Hamiltonian is not in the right format. 
Some solvers (sesolve, mesolve, ...) accept time dependent Hamiltonian in list format, eigenenergies does not.
