### ISSUE TITLE
macOS 10.14 compilation problem

### ISSUE THREAD

**Issue by Vutshi** [qutip/qutip#919]
It seems the new macOS can not compile QuTiP, it can not find `<complex>`. The headers do present in `/usr/include` (however it required a header package installation on the new macOS)

**Comment by Vutshi** [comment]
If the QuTiP is already installed then there is no problem after the update, it works.

**Comment by nonhermitian** [comment]
I will submit a patch to the installer later today.  Basically you need to add `'-mmacosx-version-min=10.9'` to the `_compiler_flags` and `extra_link_args`.
