### ISSUE TITLE
Optimization flags in setup.py should be completely avoided

### ISSUE THREAD

**Issue by slavoutich** [qutip/qutip#920]
Hard-coding compiler flag `-march=native` in setup.py completely destroys possibility to set up Qutip on heterogeneous cluster. In general, it brings a lot of problems for people that don't have a good experience in debugging "illegal instruction" errors, that often happen, if you compile the module on different machine than you use.

If you are sure you need optimized build for localhost, you might use
```
export CFLAGS="-O3 -march=native"
export CXXFLAGS="$CFLAGS"
pip install qutip
```
instead or provide separate option for setup.py script.

**Comment by goerz** [comment]
Might this be the cause of https://github.com/qutip/qutip/issues/674?

**Comment by slavoutich** [comment]
I am almost certain that this is the reason.
