### ISSUE TITLE
Second order optical coherence function with zero time delay(g^2(0))

### ISSUE THREAD

**Issue by devendergarg14** [qutip/qutip#921]
How to find second order coherence function with zero time delay in qutip(g^2(0))? The qutip inbuilt function "correlation_3op_1t()" has "**taus**" argument which is zero in this case.

**Comment by nathanshammah** [comment]
You can use the four-operator correlation function, `correlation_4op_1t`.  In this specific case you can use  taking tau= 0 result. [`correlation.coherence_function_g2`](http://qutip.org/docs/latest/guide/guide-correlation.html#example-second-order-optical-coherence-function).
