### ISSUE TITLE
dW_factors in smesolve

### ISSUE THREAD

**Issue by nnkt** [qutip/qutip#926]
Simulating the stochastic master equation, I got confused since `dW_factors` are used to
compute the measured value, e.g. `_smesolve_single_trajectory` in stochastic.py,
but not in the update of density matrix, e.g. `_rhs_rho_euler_maruyama` in stochastic.py.

If it is not a bug, how shall I set the value?
Shall I understand as a fixed quantity as in this [tutorial](http://nbviewer.jupyter.org/github/qutip/qutip-notebooks/blob/master/examples/smesolve-heterodyne.ipynb), 
or is it a free parameter?

Thanks in advance!

**Comment by Ericgig** [comment]
dW_factors only affect measurement and nothing else. You should leave them at the default value. As I understand it, it is mostly there if you want to use another method than provided ones (homodyne, heterodyne or photocurrent) and manually provide d1,d2 and rhs.
