### ISSUE TITLE
Two level atom with a drive term

### ISSUE THREAD

**Issue by akhil21** [qutip/qutip#928]
This may be very fundamental but I tried implementing it by using online resources before posting the question here.
I want to plot the dynamics of an atom in the vacuum first, where it's revolving around z-axis on the Bloch sphere.
And then plot the dynamics with a driving term and see the orientation of the atom in the Bloch sphere.

**Comment by matpompili** [comment]
Maybe this is helpful. You will just need to change the Hamiltonian.

https://nbviewer.jupyter.org/github/qutip/qutip-notebooks/blob/master/examples/bloch-sphere-animation.ipynb
