### ISSUE TITLE
Cannot use arrays for time-dependent control fields

### ISSUE THREAD

**Issue by goerz** [qutip/qutip#932]
Code to reproduce:

~~~
import qutip
import numpy as np
import scipy

def transmon_ham_and_states(Ec=0.386, EjEc=45, nstates=8, ng=0.0, T=10.0):
    """Transmon Hamiltonian"""
    Ej = EjEc * Ec
    n = np.arange(-nstates, nstates+1)
    up = np.diag(np.ones(2*nstates),k=-1)
    do = up.T
    H0 = qutip.Qobj(np.diag(4*Ec*(n - ng)**2) - Ej*(up+do)/2.0)
    H1 = qutip.Qobj(-2*np.diag(n))

    eigenvals, eigenvecs = scipy.linalg.eig(H0.full())
    ndx = np.argsort(eigenvals.real)
    E = eigenvals[ndx].real
    V = eigenvecs[:,ndx]
    w01 = E[1]-E[0] # Transition energy between states

    psi0 = qutip.Qobj(V[:, 0])
    psi1 = qutip.Qobj(V[:, 1])    

    profile = lambda t: np.exp(-40.0*(t/T - 0.5)**2)
    eps0 = lambda t, args: 0.5 * profile(t) * np.cos(8*np.pi*w01*t)
    return ([H0, [H1, eps0]], psi0, psi1)

H, psi0, psi1 = transmon_ham_and_states()

tlist = np.linspace(0, 10, 1000)

# convert function to array
H[1][1] = np.array([H[1][1](t, None) for t in tlist])

result = qutip.mesolve(H, psi0, tlist=tlist)
~~~

This crashes with a `CompileError: command 'gcc' failed with exit status 1` on Python 3.6 or `CompileError: command '/usr/bin/clang' failed with exit status 1` on Python 3.5. It works fine if I don't to the conversion from the function to the array.

The Cython program that is being generated and that fails to compile is this:
~~~
# This file is generated automatically by QuTiP.
# (C) 2011 and later, QuSTaR

import numpy as np
cimport numpy as np
cimport cython
np.import_array()
cdef extern from "numpy/arrayobject.h" nogil:
    void PyDataMem_NEW_ZEROED(size_t size, size_t elsize)
    void PyArray_ENABLEFLAGS(np.ndarray arr, int flags)

from qutip.cy.spmatfuncs cimport spmvpy
from qutip.cy.interpolate cimport interp, zinterp
from qutip.cy.math cimport erf
cdef double pi = 3.14159265358979323

include '/Users/goerz/Documents/Programming/github/krotov/.venv/py36/lib/python3.6/site-packages/qutip/cy/complex_math.pxi'

@cython.cdivision(True)
@cython.boundscheck(False)
@cython.wraparound(False)
def cy_td_ode_rhs(
        double t,
        complex[::1] vec,
        complex[::1] data0,int[::1] idx0,int[::1] ptr0,
        complex[::1] data1,int[::1] idx1,int[::1] ptr1,
        np.ndarray[np.float64_t, ndim=1] _td_array_0):
    
    cdef size_t row
    cdef unsigned int num_rows = vec.shape[0]
    cdef double complex * out = <complex *>PyDataMem_NEW_ZEROED(num_rows,sizeof(complex))
     
    spmvpy(&data0[0], &idx0[0], &ptr0[0], &vec[0], 1.0, out, num_rows)
    spmvpy(&data1[0], &idx1[0], &ptr1[0], &vec[0], (0 if (t > 10.000000) else _td_array_0[int(round(999 * (t/10.000000)))]), out, num_rows)
    cdef np.npy_intp dims = num_rows
    cdef np.ndarray[complex, ndim=1, mode='c'] arr_out = np.PyArray_SimpleNewFromData(1, &dims, np.NPY_COMPLEX128, out)
    PyArray_ENABLEFLAGS(arr_out, np.NPY_OWNDATA)
    return arr_out  
~~~

Program versions are
~~~
CPython 3.6.7
IPython 7.1.1

qutip 4.3.1
numpy 1.15.4
scipy 1.1.0
cython 0.29

compiler   : GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)
system     : Darwin
release    : 18.0.0
machine    : x86_64
processor  : i386
CPU cores  : 4
interpreter: 64bit
~~~
I also tried this with Python 3.5  and qutip 4.2

**Comment by goerz** [comment]
Actually, this seems to be a platform-specific problem. I just ran this on a Linux server, and there it seems to work fine (at least it runs through)

Package versions are exactly the same as above, and the platform info is this:
~~~
compiler   : GCC 7.3.0
system     : Linux
release    : 4.4.0-124-generic
machine    : x86_64
processor  : x86_64
CPU cores  : 80
interpreter: 64bit
~~~

**Comment by goerz** [comment]
Oh, I just noticed that if I do this in a jupyter notebook, I get a somewhat useful error message from the server: 
~~~
/Users/goerz/.pyxbld/temp.macosx-10.6-x86_64-3.5/pyrex/rhs72670.cpp:541:10: fatal error: 'complex' file not found
#include <complex>
~~~

**Comment by goerz** [comment]
I see this was already mentioned on the mailing list...
https://groups.google.com/d/msg/qutip/Z-5o4HHYRv4/50-nw-J-BQAJ

**Comment by goerz** [comment]
`xcode-select --install` does not fix the problem

**Comment by goerz** [comment]
I'm also seeing this on Windows, with a fresh installation of Anaconda on a virtual machine (the Win11/Edge one) from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by goerz** [comment]
Cell 18 in https://github.com/qucontrol/krotov/blob/9e6b7cf45a3e3ddbdb9192d2c9824b8a7e1f9fa2/docs/notebooks/01_example_simple_state_to_state.ipynb
is an example for a failing propagation on Windows. The `mesolve` method that is being called there maps very directly to QuTiP's `mesolve`: https://github.com/qucontrol/krotov/blob/9e6b7cf45a3e3ddbdb9192d2c9824b8a7e1f9fa2/src/krotov/objectives.py#L199

**Comment by ajgpitch** [comment]
The error reported here
```
/Users/goerz/.pyxbld/temp.macosx-10.6-x86_64-3.5/pyrex/rhs72670.cpp:541:10: fatal error: 'complex' file not found
#include <complex>
```
Suggests that any string format time-dependence would fail to compile. @goerz Could you try to reproduce with simple example, e.g.
```
H = [[sigmaz(), "sin(t)"]]
```
?

**Comment by goerz** [comment]
Yes, that also fails, with the same error (on Windows):

`Building module rhs44481 failed: ['distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat\n']`

I just realized that this particular problem is probably just that this Windows VM doesn't  have Visual Studio installed (maybe I should try again with the 20GB developer's VM that Microsoft has).

So as a user on Windows, having installed QuTiP through Anaconda, I can't do any time propagation? Somehow, I would have thought that having Cython though Anaconda would also come with some compiler like gcc (which is what it seems to be doing on the Mac). Otherwise, that seems like a very limiting factor to any Windows user. There's no way to run QuTiP while preventing it to cythonize time-dependencies, right? That is, aside from workarounds like the one I did here: https://github.com/qucontrol/krotov/blob/247d4066c83ee4923769b934486da9dae95f6879/src/krotov/objectives.py#L175

Anyway, this is likely not really the same issue as the original problem on the Mac.

**Comment by goerz** [comment]
`H = [[sigmaz(), "sin(t)"]]` also fails on the Mac, with the same `'complex' file not found`

**Comment by nathanshammah** [comment]
I don't know if it is relevant, but I copy-pasted the block in the first [post](https://github.com/qutip/qutip/issues/932#issue-378533309) of the thread and I do not get an error message by running it on OS High Sierra 10.13.6 in a Jupyter notebook.

There is a clang warning 
```
libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
```
Other details

```
QuTiP Version:      4.3.1
Numpy Version:      1.14.2
Scipy Version:      1.1.0
Cython Version:     0.28.5
Matplotlib Version: 2.2.3
Python Version:     3.6.7
Number of CPUs:     2
BLAS Info:          INTEL MKL
OPENMP Installed:   False
INTEL MKL Ext:      True
Platform Info:      Darwin (x86_64)
```

**Comment by goerz** [comment]
@nathanshammah Is this from within an Anaconda installation?

**Comment by ajgpitch** [comment]
> So as a user on Windows, having installed QuTiP through Anaconda, I can't do any time propagation?

**Comment by ajgpitch** [comment]
As for a C++ compiler on Windows, there is supposedly a C++ SDK for Windows that is a lot lighter than VS Community edition. However, I tried at some point to get it working a failed. I just now tried again to find it, but could not. MS has this habit of moving stuff around. There a lot of conflicting info out there. I am sorry that MS makes compiling C/C++ such a complicated thing. I'll see if maybe I can make some progress this week.

**Comment by nathanshammah** [comment]
@goerz yes.

**Comment by ajgpitch** [comment]
@goerz you may find #954 helpful

**Comment by jarthurgross** [comment]
Just tried a potential solution that didn't work, so here's what I did in case someone finds the information useful:

I'm running macOS Mojave 10.14.4, and Theano was complaining about not being able to find `stdio.h`. [This comment](https://github.com/frida/frida/issues/338#issuecomment-424595668) gave a fix (apparently stuff used to be in `/usr/include` but isn't by default anymore). Since it was a similar issue to what we're facing with `qutip`, I wondered if it might fix the problem finding `complex`. It didn't.

**Comment by nathanshammah** [comment]
This ran fine on Mac Mojave with the latest conda and pip release (4.4.0). In pip, I first created a new conda environment and then ran `conda install pip`, `pip install cython numpy scipy qutip` Feel free to reopen if it is not solved on your machine.
