### ISSUE TITLE
Provide pip wheels

### ISSUE THREAD

**Issue by goerz** [qutip/qutip#933]
It seems that over the last year, nearly all packages in the scientific Python ecosystem have started to provide wheels. This is great news, as it make installation on platforms that don't have the necessary compilers installed very easy, and it's also extremely fast.

So far, `conda` has been the only realistic option to install qutip outside of Linux development workstation, and it's not without caveats (https://github.com/qutip/qutip/issues/674). Conda has also been getting extremely slow
(https://github.com/conda/conda/issues/7239), which causes problem with continuous integration services or readthedocs (together with the fact that setting up conda on these services isn't entirely trivial, and, for readthedocs, buggy: https://github.com/rtfd/readthedocs.org/issues/3925, https://github.com/rtfd/readthedocs.org/issues/3829)

If qutip were to provide wheels, this might alleviate all of these problems. Depending on how complicated the process is compared compared to a conda package, it might then even be ok to drop conda support.

**Comment by nathanshammah** [comment]
Noted. Will be discussed and will get back to you.

**Comment by ajgpitch** [comment]
I agree that supporting pip more fully using wheels is a good idea. The conda-forge advantage was / is that the build is automated. 
If we can find some way to automate the building of wheels, then we shall do it.

**Comment by goerz** [comment]
It looks like there are some wheels for QuTiP on Windows available at  https://www.lfd.uci.edu/~gohlke/pythonlibs/

Just tried them out, and they seem to work fine.

**Comment by nathanshammah** [comment]
This proved more challenging than expected for the current release, e.g., as various Linux distribution require different wheels. Still looking at it.

**Comment by jakelishman** [comment]
Fixed by #1465, to be released in QuTiP 4.6.0.
