### ISSUE TITLE
fidelity() returning <1.0 for two exactly same density matrix as arguments. 

### ISSUE THREAD

**Issue by ashsaki** [qutip/qutip#935]
I was using fidelity() function to with two density matrices as arguments. However, even if I use two exactly the same DM, the function returns <1.0 value (0.70710678 to be precise). I was hoping for two same DMs fidelity should be 1.0. 

Attached is the density matrix. 
![image](https://user-images.githubusercontent.com/44783187/48210546-86494f00-e345-11e8-98fb-ae155745d948.png)

**Comment by Vutshi** [comment]
This is a strange density. Nonhermitian.

**Comment by nonhermitian** [comment]
It says your density matrix is not hermitian
