### ISSUE TITLE
Intel MKL error breaks wigner.qfunc

### ISSUE THREAD

**Issue by dweigand** [qutip/qutip#937]
This is just FYI because I needed some time to track this one down, but I do not think it can be fixed in qutip (or scipy).

A Bug in Intel MKL causes scipy.linalg.eig to break and return zeros if the matrix is too large. This in turn breaks wigner.qfunc if the state in question is a density matrix. Possibly related are issues 
https://github.com/scipy/scipy/issues/8713 and https://github.com/scipy/scipy/issues/8205. However the fix mentioned there does not solve the problem for me, so it might be unrelated.

If you run into this error, the only workaround I know of is to link scipy and numpy to a different blas library, e.g. openblas. Note that anaconda on windows always uses MKL on intel machines, so you need to install either manually or with pip.

**Comment by nathanshammah** [comment]
Thank you for the information.

**Comment by jakelishman** [comment]
Should now be fixed by later releases of MKL; see scipy/scipy#8205.
