### ISSUE TITLE
Product of superoperator and density matrix

### ISSUE THREAD

**Issue by goerz** [qutip/qutip#939]
Consider the following example:
~~~
>>> import qutip
>>> from qutip.operators import *
>>> import numpy as np
>>> ket = (qutip.tensor(qutip.ket('0'), qutip.ket('0')) - 1j * qutip.tensor(qutip.ket('1'), qutip.ket('1')))/np.sqrt(2)
>>> rho = qutip.ket2dm(ket)
>>> H = qutip.tensor(sigmaz(), identity(2)) + qutip.tensor(identity(2), sigmaz())
>>> c_ops = [qutip.tensor(sigmam(), identity(2)), qutip.tensor(identity(2), sigmam())]
>>> L = qutip.superoperator.liouvillian(H, c_ops=c_ops)
~~~

Now, it seems very sensible to want to apply the superoperator to the density matrix via a simple product. However, this fails:
~~~
>>> L * rho
Traceback (most recent call last):
  File "<ipython-input-50-c0fe3dea3c39>", line 1, in <module>
    L * rho
  File "/Users/goerz/anaconda3/lib/python3.5/site-packages/qutip/qobj.py", line 515, in __mul__
    raise TypeError("Incompatible Qobj shapes")
TypeError: Incompatible Qobj shapes
~~~

The only way to do it seems to be:

~~~
>>> qutip.vector_to_operator(L * qutip.operator_to_vector(rho))
Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[-1.0+0.j   0.0+0.j   0.0+0.j   2.0-0.5j]
 [ 0.0+0.j   0.5+0.j   0.0+0.j   0.0+0.j ]
 [ 0.0+0.j   0.0+0.j   0.5+0.j   0.0+0.j ]
 [ 2.0+0.5j  0.0+0.j   0.0+0.j   0.0+0.j ]]
~~~

I would argue that the product `L * rho` should do this kind of conversion internally instead of throwing an exception. It seems to me the intention of `L * rho` is completely unambiguous, but maybe I'm missing something?

Having the product work out of the box means that I can write a simple propagation routine as `(A * dt).expm() * state` and it would work independent of whether (A, state) are a (Hamiltonian, vector) or a (Liouvillian, density matrix). Currently, I have to catch the different cases and handle them separately.

**Comment by Ericgig** [comment]
I do not know if `L * rho` not working is desired or an oversight. 
However you can call operator Qobj: `L(rho)` does what you expect of `L*rho`. 
Since `H(ket)` also work, you can use that form to handle both cases with the same code.

**Comment by goerz** [comment]
Oh wow! That's really nice! (and completely undocumented, as far as I can tell ;-) ). I had actually noticed at some point that `callable(qob)` returns True and wondered what that was about.

So this definitely solves my problem, and I could see the argument for the abstract "apply x to y"  being realized as`x(y)`. In that case, maybe not allowing objects with incompatible `data` shapes is ok after all. I'll leave it to the maintainers to decide whether they want to close this issue with "wont-fix".
