### ISSUE TITLE
Qobj in args are modified without proper documentation.

### ISSUE THREAD

**Issue by Ericgig** [qutip/qutip#948]
While we are at it, I have found another undocumented, untested "feature" is the solvers.
In `sesolve`, when H is a function and a Qobj is in args, it is replaced by it's data"
sesolve.py, 696:
```        
for key in args:
      if isinstance(args[key], Qobj):
            new_args[key] = args[key].data
```
`mesolve` does a similar thing: (mesolve.py:889) 
```
        for key in args:
            if isinstance(args[key], Qobj):
                if isoper(args[key]):
                    new_args[key] = (
                        -1j * (spre(args[key]) - spost(args[key])))
```
While this is probably not common, I don't see it being useful (at least without proper documentation).

**Comment by ajgpitch** [comment]
This seems somehow familiar, but its not coming to me now. Maybe @nonhermitian can illuminate?

**Comment by hodgestar** [comment]
@Ericgig Should we close this issue?
