### ISSUE TITLE
Unit testing software: nose, nose2, pytest 

### ISSUE THREAD

**Issue by nathanshammah** [qutip/qutip#958]
This is post for discussion over whether it might be beneficial to switch from `nose` to another unit testing software. 

- QuTiP is using nose for unit testing. A [disclaimer](https://nose.readthedocs.io/en/latest/) on that project homepage warns that nose might not be maintained in the future. 

- [`nose2`](https://nose2.readthedocs.io/en/latest/differences.html) is the successor to `nose`. It is actively maintained. There are some [differences](https://nose2.readthedocs.io/en/latest/differences.html).  

- [pytest](https://pytest.readthedocs.io/en/latest/) is another open-source solution. By comparing [nose2](https://github.com/nose-devs/nose2/graphs/contributors?from=2010-08-01&to=2019-02-27&type=a) and [pytest](https://github.com/pytest-dev/pytest/graphs/contributors?from=2009-04-05&to=2019-02-27&type=a) activity it seems that the latter has grown and is actively updated. 

I wonder whether it would make sense to migrate to a more popular (possibly more robust?) software and how much work this would mean. Other implications are not clear to me at this moment.

**Comment by ajgpitch** [comment]
I think we should swap, but I don't think it's necassarily high priority.

My reckoning is that nose2 could be easier to switch to than pytest. I don't think that anything we do is particularly special. It might be a case of suck it and see.

**Comment by quantshah** [comment]
I have been trying out pytest for the last couple of days and we can start by using it for the testing as it is now. We need to replace installation [lines](https://github.com/qutip/qutip/blob/master/.travis.yml#L23) like this in the .travis.yml file to install pytest:
```
conda install mkl blas=*=mkl numpy scipy pytest cython coveralls pytest-cov
```

and then change the runner script to use pytest instead of `nose` by changing:
```
nosetests --verbosity=2 --with-coverage --cover-package=qutip qutip
```
to
```
pytest --verbosity=2 --cov=qutip qutip
```

**Comment by BassemSafieldeen** [comment]
> 
> 
> I have been trying out pytest for the last couple of days and we can start by using it for the testing as it is now. We need to replace installation [lines](https://github.com/qutip/qutip/blob/master/.travis.yml#L23) like this in the .travis.yml file to install pytest:
> 
> ```
> conda install mkl blas=*=mkl numpy scipy pytest cython coveralls pytest-cov
> ```
> 
> and then change the runner script to use pytest instead of `nose` by changing:
> 
> ```
> nosetests --verbosity=2 --with-coverage --cover-package=qutip qutip
> ```
> 
> to
> 
> ```
> pytest --verbosity=1 --cov=qutip qutip
> ```

I have implemented this. See pull request #972.

**Comment by BassemSafieldeen** [comment]
> 
> 
> I have been trying out pytest for the last couple of days and we can start by using it for the testing as it is now. We need to replace installation [lines](https://github.com/qutip/qutip/blob/master/.travis.yml#L23) like this in the .travis.yml file to install pytest:
> 
> ```
> conda install mkl blas=*=mkl numpy scipy pytest cython coveralls pytest-cov
> ```
> 
> and then change the runner script to use pytest instead of `nose` by changing:
> 
> ```
> nosetests --verbosity=2 --with-coverage --cover-package=qutip qutip
> ```
> 
> to
> 
> ```
> pytest --verbosity=1 --cov=qutip qutip
> ```

I have submitted a pull request with these changes. Travis build fails with error "file not found: qutip". I suspect it is a problem with pytest, and I am investigating.

**Comment by BassemSafieldeen** [comment]
The problem has been fixed.

**Comment by goerz** [comment]
I've found `pytest` to be extremely nice to work with. One advantage is that `pytest` will also pick up and run `nose` tests, so there is no need to rewrite all of the existing tests. At the same time, new tests will be easier to write, as `pytest` has much less boilerplate code than `nose`.

**Comment by TejasAvinashShetty** [comment]
In addition one could also use [Hypothesis](https://hypothesis.works/). It has tools to directly [test](https://hypothesis.readthedocs.io/en/latest/numpy.html) numpy arrays and find out edge cases which fail.

**Comment by nathanshammah** [comment]
Pinging @tehruhn for help on this.

**Comment by nathanshammah** [comment]
Happy to close this, although the CircleCI thing may still be relevant.
