### ISSUE TITLE
Branch for next major version features

### ISSUE THREAD

**Issue by ajgpitch** [qutip/qutip#964]
We (mainly @Ericgig ) are developing some changes that would only be included in the next major release. It would make sense to merge these into one branch, but not the `master` branch, so that we can test their compatibility. Maybe `development` is a good name, although we often refer to our `master` as the 'development' branch.

I have seen some template for this in another project, but cannot remember where. If anyone has some ideas for this, then would be good if they could share here

**Comment by skyme5** [comment]
Why not create a feature branch?
