### ISSUE TITLE
Qobj dimension not consistent with shape

### ISSUE THREAD

**Issue by nathanshammah** [qutip/qutip#978]
It is possible for the user to define a Qobj whose dimensions (`dims`) do not match the shape (`shape`). An example is given below, 

```
Qobj(qeye(2).full(), dims=[1,2])
```
prints
```
Quantum object: dims = [1, 2], shape = (2, 2), type = other
 1.0 0.0
  0.0 1.0
```
If this is an expected behaviour, it might be needed to change the docstring of `Qobj`, as it does not mention `other`.  Or I am missing something. A look at issue #28 did not help. 

One might insert a check on `dims` product to match `shape`.

**Comment by quantshah** [comment]
Good catch. I think we can add a check [here](https://github.com/qutip/qutip/blob/master/qutip/qobj.py#L253) and [there](https://github.com/qutip/qutip/blob/master/qutip/qobj.py#L300) in `qutip.qobj`.

```
        elif inpt is None:
            # initialize an empty Qobj with correct dimensions and shape

            if any(dims):
                if shape:
                    check_dims(dims, shape)
                N, M = np.prod(dims[0]), np.prod(dims[1])
                self.dims = dims
                
            elif shape:
                N, M = shape
                if dims:
                    check_dims(dims, shape)
                self.dims = [[N], [M]]
```
where we can define a simple `check_dims` function for consistency checks.

But this is also really not a bug perhaps but more to do with minimizing user mistake. 
@ajgpitch

**Comment by nwlambert** [comment]
If my memory is correct forcing dims and shape to be consistent might break some stuff, like the ENR states (where it is assumed they can be different).

**Comment by nathanshammah** [comment]
Closing it for the time being, as not a bug.
