### ISSUE TITLE
Define __round__ for QObj

### ISSUE THREAD

**Issue by MichalKononenko** [qutip/qutip#982]
I'm asserting that two operators are almost equal, and implementing a __round__ method for Qobj would be useful in this regard.

**Comment by Ericgig** [comment]
Qobj equality has a tolerance option in qutip's settings:
```
>>> import qutip as qt
>>> import qutip.settings as settings
>>> settings.atol = 1
>>> qt.destroy(1) == qt.destroy(1)+0.5
True
```

**Comment by nathanshammah** [comment]
The other features of such a function might be already taken care of by `Qobj.tidyup()`, which similarly can be called with `Qobj.tidyup(atol=1)`.
