### ISSUE TITLE
python setup.py clean creates files instead of removing them

### ISSUE THREAD

**Issue by RizzerOnGitHub** [qutip/qutip#986]
`python3 setup.py clean` creates cpp files in qutip/control and qutip/cy.  This is the exact opposite of what it should do. It's supposed to clear out build files, not create new ones.

**Comment by RizzerOnGitHub** [comment]
Likewise it also creates qutip/version.py.

**Comment by nathanshammah** [comment]
May be addressed by #1037. If still persistent, please reopen.
