### ISSUE TITLE
setup.py installs rhs*.pyx test files generated during build-time tests

### ISSUE THREAD

**Issue by RizzerOnGitHub** [qutip/qutip#987]
`setup.py test` invokes test_td_formats.py, which generates rhs*.pyx files in the build subdir.

`setup.py install` installs everything in the build subdir. So that includes the rhs*pyx test files.  The test files get installed at the toplevel of the installation path, just above the qutip dir.

**Comment by RizzerOnGitHub** [comment]
The path in question is /usr/lib/python3*/dist-packages/rhs*.pyx

**Comment by nathanshammah** [comment]
Would you be able to open a Pull Request? Also for #986.

**Comment by RizzerOnGitHub** [comment]
I'm not entirely certain how to fix it inside setup.py.

I use Debian packaging tools and can add commands to debian/rules to delete these files after running the setup.py commands (clean and test). But I'm not sure how to get setup.py to clean up after itself.

**Comment by nathanshammah** [comment]
Should have been taken care in the recent conda and pip release of QuTiP, 4.4.0, #1037.

**Comment by RizzerOnGitHub** [comment]
Thanks, confirming the stray rhs*.pyx files are no longer installed in 4.4.1.
