### ISSUE TITLE
Inconsistency in conda

### ISSUE THREAD

**Issue by TejasAvinashShetty** [qutip/qutip#988]
This may not really be an issue per se, but I thought it would a good idea to post it anyway.
On updating my conda  environment which is devoted for qutip I get, 

> Collecting package metadata: done
Solving environment: \ 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:
    conda-forge/osx-64::qutip==4.2.0=np113py36_2
done
  All requested packages already installed.

Is this because qutip depends on somewhat older versions of it's dependencies  (like numpy, etc)?
MacOS 10.13.6

**Comment by nathanshammah** [comment]
I can’t tell now, will investigate. What’s strange to me in the first place is that on conda-forge, it says that for Mac’s Os, QuTiP is now at 4.3.1, https://anaconda.org/conda-forge/qutip. 

Also, it would be useful to update the windows version from 4.2 on conda forge. Cc @quantshah.

**Comment by nathanshammah** [comment]
Hi @TejasAvinashShetty, I had a try at the conda install on my machine. I had no issue:
```
conda create -n qutip-env
conda activate qutip-env
(qutip-env): conda install cython numpy scipy nose matplotlib
(qutip-env): conda install qutip
(qutip-env): python
"Python 3.7.3 (default, Mar 27 2019, 16:54:48)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin"
>>> from qutip import *
>>> qutip.about()
QuTiP Version:      4.3.1
Numpy Version:      1.16.3
Scipy Version:      1.2.1
Cython Version:     0.29.7
Matplotlib Version: 3.0.3
Python Version:     3.7.3
Number of CPUs:     2
BLAS Info:          INTEL MKL
OPENMP Installed:   False
INTEL MKL Ext:      True
Platform Info:      Darwin (x86_64)
Installation path:  /Users/nathanshammah/miniconda3/envs/qutip-env/lib/python3.7/site-packages/qutip
>>> quit()
(qutip-env): conda deactivate
conda update -n qutip-env  --all
"Collecting package metadata: done
Solving environment: done
# All requested packages already installed."
```
Can you please specify your machine configuration and what did you do to update the environment?
Does this relate to this?

I guess I am unable to reproduce the issue unless I go back to qutip 4.2. 
Googling "np113py36_2", I ended up on this QuTiP Google Group thread, https://groups.google.com/forum/#!topic/qutip/BwtoyhW60jo
maybe making sure you are not in the QuTiP folder resolves the issue. 

You can also activate your environment, uninstall qutip, update all the rest and the install qutip 
```
conda activate qutip-env 
(qutip-env): conda uninstall qutip
conda update -n qutip-env  --all
conda activate qutip-env 
(qutip-env): conda install qutip
``

Another practical suggestion, not really assessing the issue, would be to create a new environment and do a fresh install.

**Comment by TejasAvinashShetty** [comment]
I had a glance at the [https://groups.google.com/forum/#!topic/qutip/BwtoyhW60jo](url) ,. i don't think so my issue is as serious as stated in the above link. I am not in the folder of qutip.On trying to update this is what I get.

`(qutip-env) Tejass-MacBook-Pro:~ shetty$ conda update conda

PackageNotInstalledError: Package is not installed in prefix.
  prefix: /anaconda3/envs/qutip-env
  package name: conda


(qutip-env) Tejass-MacBook-Pro:~ shetty$  conda update --prefix /anaconda3/envs/qutip-env anaconda

PackageNotInstalledError: Package is not installed in prefix.
  prefix: /anaconda3/envs/qutip-env
  package name: anaconda


(qutip-env) Tejass-MacBook-Pro:~ shetty$  conda update  anaconda

PackageNotInstalledError: Package is not installed in prefix.
  prefix: /anaconda3/envs/qutip-env
  package name: anaconda


(qutip-env) Tejass-MacBook-Pro:~ shetty$ conda update -n base -c defaults conda
Collecting package metadata: done
Solving environment: - 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:
\ 
  - defaults/osx-64::anaconda==5.1.0=py36_2
| 
done

# All requested packages already installed.

(qutip-env) Tejass-MacBook-Pro:~ shetty$ `

**Comment by TejasAvinashShetty** [comment]
Reinstalling fixes the issue. though there may be better ways to go about this [for e.g.](https://stackoverflow.com/questions/55527354/the-environment-is-inconsistent-please-check-the-package-plan-carefully)
