### ISSUE TITLE
Bloch sphere (not Bloch3d) is visualised only once in jupyter notebook

### ISSUE THREAD

**Issue by ziofil** [qutip/qutip#989]
After creating a Bloch sphere object, I can add vectors and visualise it with the method `show()`. All fine so far.

This however works only the first time. If I call `show()` a second time, it doesn't output anything.

**Comment by nathanshammah** [comment]
Indeed 
```
b = Bloch()
b.show()
```
renders the Bloch sphere. Calling again `b.show()` does not work as you say. 

Interestingly, invoking just
```
b
```
 gives an error, but plots the correct sphere again. 
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/miniconda3/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

~/miniconda3/lib/python3.6/site-packages/qutip/bloch.py in _repr_svg_(self)
    298         from IPython.core.pylabtools import print_figure
    299         self.render()
--> 300         fig_data = print_figure(self.fig, 'svg').decode('utf-8')
    301         plt.close(self.fig)
    302         return fig_data

AttributeError: 'str' object has no attribute 'decode'
```
Regarding the no-show, I guess there is something to fiddle with at
https://github.com/qutip/qutip/blob/master/qutip/bloch.py#L625-L632

**Comment by wrzadkow** [comment]
I tried to solve this issue. It seems like this is known, and expected, behavior of `plt.show()`, described e.g. here https://stackoverflow.com/questions/50452455/plt-show-does-nothing-when-used-for-the-second-time/51005555

The workaround depends on the user environment. For Ipython one uses `display()` function from `IPython.display`, while in other cases using `fig.show()` instead of `plt.show(fig)` works.

This would however make the code more involved and environment-dependent, so I didn't decide to submit a PR right away, but I can do with the above fix if somebody from qutip team agrees.

**Comment by nathanshammah** [comment]
@wrzadkow thank you. It sounds good to me. Could [detect](https://stackoverflow.com/questions/5376837/how-can-i-do-an-if-run-from-ipython-test-in-python) whether the environment  is `IPython`. 
If you can write a test too for it to avoid environment-dependent errors that would be great.

**Comment by wrzadkow** [comment]
@nathanshammah thanks! Submitted a PR that seems to be fixing the issue in the above mentioned way.

Naturally I have brief tests for that, in a form of Jupyter notebook and in the form of `.py` file (the `.py` is just a copy of Jupyter but here we need to test both environments). Should I commit the `.py` file to `qutip/tests/` on this repo (add to my PR) and Jupyter test to `qutip-notebooks` or there is another standard way?

**Comment by nathanshammah** [comment]
Addressed by [#996](https://github.com/qutip/qutip/pull/996).

**Comment by nathanshammah** [comment]
@wrzadkow I now read your last comment. I found no previous test for Bloch. If you want to add one that would be great but besides checking the environment I wouldn’t know how to do it. But you’re welcome to go ahead. I don’t think that there are tests in qutip-notebooks, Travis CI only looks into qutip/qutip. Thank you for the PR.

**Comment by wrzadkow** [comment]
@nathanshammah OK, my "tests" were just creating instances of `Bloch()` with and without `plt.figure()` instance passed in the constructor and then repeatedly executing the `show()` function. Now after I had a look at `qutip/tests` my small testing snippets indeed don't fit into that. Hence at this stage I don't see the benefit from adding these trivial "tests" I did to the repo. Thank you for the review and all the guidance.
